### ISSUE TITLE
Crash when opening guidebook

### ISSUE THREAD

**Issue by Enderborn1235** [klikli-dev/occultism#1]
**Describe the bug**
See Log, happens when opening guidebook [crash-2020-05-02_05.27.28-server.txt](https://github.com/klikli-dev/occultism/files/4567495/crash-2020-05-02_05.27.28-server.txt)

When it crashed it said something about not finding something in patchouli, even though I have the latest version (version 1.2-33) installed

**To Reproduce**
Open the guidebook (Not tested with debug book)

**Expected behavior**
See a menu

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
- Minecraft Version: 1.15.2 and forge-31.1.63
- Modpack Link and Version, or list of mods: see crash log

**Comment by klikli-dev** [comment]
Thank you for the report, I will test with the latest patchouli version and get back to you

**Comment by klikli-dev** [comment]
It seems the API for opening the book changed slightly, I updated that and it's now using a hopefully more patch-resistant approach. It does not crash for me now, can you please test with the latest alpha (0.2.1, might take a bit to finish processing on their side) available on Curse and let me know if that works on your end?

**Comment by Enderborn1235** [comment]
That fixed it! Thank you!
