### ISSUE TITLE
crash when putting ore mining djinni in to dimensional mineshaft

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#10]
**Describe the bug**
crash when placing ore miner djinni lamp in dimensional mineshaft

**To Reproduce**
1. Place block 'dimensional mineshaft'
2. Right click to open menu.
3. place ore mining djinni lamp in left slot
4. See error https://pastebin.com/K2dNDE4z

**Expected behavior**
no idea, havent seen it work yet xD

unless i say otherwise, assume all bug reports from me are on latest occult version with just JEI and patchouli mods installed xD

**Comment by klikli-dev** [comment]
Fixed in v1.15.2-0.2.5
