### ISSUE TITLE
Interacting with demons deleting armor

### ISSUE THREAD

**Issue by JaceValen** [klikli-dev/occultism#1006]
**Describe the bug**
Shift-right clicking on a demon with a piece of armor in your hand, while having a piece of armor on will delete the piece in your hand

**To Reproduce**
1. have armor on
2. have armor piece in hand
3. shift-right click demon as if interacting
4. armor piece is consumed

**Expected behavior**
I would like to just interact with the demon, or just have the armor swap happen. 

- Minecraft Version: 1.20.1

**Additional context**
happened with a slow crusher demon. multiple pieces of armor were tested

**Comment by klikli-dev** [comment]
@JaceValen can you specify in more detail how to reproduce this?
I put on a diamond chestplate, then put one in my hand and shift-right-clicked a foliot crusher and nothing happened, except that the foliot inventory opened (chestplate still here).

Do I need a full suite of armor? 
Also does this reproduce with just occultism + dependencies?
Considering that the code for the crusher interaction is unchanged for years at this point it seems possible that another mod that handles entity interactions causes this

**Comment by JaceValen** [comment]
originally, i had on a full suit of diamond armor and was holding a pair of boots from a mod. when i shift clicked the foliot crusher, they disappeared as if they were consumed. the crusher was crushing something at the time. i retested by holding a pair or diamond boots which looked as tho they replaced my current pair, but picking up the pair i had on caused them to revert to my regular pair, and the test pair was gone

**Comment by klikli-dev** [comment]
I tried now with a full suite of diamond armor, and a crusher crushing iron ore.
I had additional diamond boots in my hand and shift-right-clicked the spirit, and once again it just opened the spirit UI (where I could take out the iron ore ... ) 

Can you try this in an occultism only scenario?
If we can reproduce it it might be an occultism issue that we can fix, but it does sound more like some sort of mod interaction
