### ISSUE TITLE
Storage search Engine should search by term

### ISSUE THREAD

**Issue by JaceValen** [klikli-dev/occultism#1007]
The storage actuator search bar does not search by term, only by item name. It would be nice to be able to search for a word that is in any part of an item. Copious amounts of enchanted books can be hard to search through.

**Comment by klikli-dev** [comment]
@JaceValen Any part as in the item description? 

The search already covers multiple areas but to make it more precise you need to specify with a prefix were to search, like in JEI:

- no prefix: item name
- @: mod name 
- #: tooltip/item description
- $: tag

**Comment by JaceValen** [comment]
> @JaceValen Any part as in the item description?
> 
> The search already covers multiple areas but to make it more precise you need to specify with a prefix were to search, like in JEI:
> 
> * no prefix: item name
> * @: mod name
> * #: tooltip/item description
> * $: tag

Holy hell, I had no idea that I could search like that. I should have said description, that is my bad. The # was exactly what I was looking for. Thank you so much.
