### ISSUE TITLE
Item description for otherworld ashes and spirit attuned gem missing

### ISSUE THREAD

**Issue by Nervy3926** [klikli-dev/occultism#1009]
Hi there,
i dont know if this is just on this version, but on FTB Skies, the description to the two items on the title are missing and are replaced with a file name of sorts, a .text file to be exact
![image_2023-12-08_122634200](https://github.com/klikli-dev/occultism/assets/153287899/3b928a07-973b-481f-a3f4-2058b1b678b2)
![image_2023-12-08_122657022](https://github.com/klikli-dev/occultism/assets/153287899/2c232a32-066e-4819-8f80-e0551589c189)
The steps to reproduce this are simply opening the book and clicking on the spirit fire icon and going to these pages.
I expected the description to be there, but i have the wiki so this isn't massively important for me atm.
Mod Version:1.88.0
OS: Win 11
MC Version: 1.19.2
Modpack link: https://www.feed-the-beast.com/modpacks/103-ftb-skies?tab=about
Hope this can help,
Kind Regards
Nervy.

**Comment by klikli-dev** [comment]
ah there should be no text, it accidentally added a translation key which then has no value. Will fix!
