### ISSUE TITLE
Stored Apotheosis items do not get retrieved properly

### ISSUE THREAD

**Issue by steventsvetkov** [klikli-dev/occultism#1010]
**Describe the bug**
Apotheosis items, stored in the dimensional storage, such as gems and armor/weapons/tools with Apotheosis modifiers, do not behave as expected when retrieving them if there are several items of the same type.

**To Reproduce**
1. Add several diamond pickaxes to the storage, some of which are normal and some have different Apotheosis rarities and modifiers.
2. Use the prompt "pickaxe" in the search.
3. When you click on a specific Apotheosis pickaxe to get, it retrieves a different pickaxe, which could be with modifiers or it could be normal.

This occurs even if you are very specific in the search prompt and only one item is shown. It happens both when accessed directly via the actuator and via a remote.

**Expected behavior**
When the user searches for an item and click on it to grab it, the user gets the item they actually clicked on.

**Screenshots**
It happens with Apotheosis gems as well.
![Apotheosis](https://github.com/klikli-dev/occultism/assets/7537488/6b5e6e09-3ad2-4a56-9047-91fb6762365d)

**System (please complete the following information):**
- Occultism Version: 1.92.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: ATM9-0.2.25 https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4915982

**Additional context**
There is some consistency to which wrong item is provided, it's as if the storage is sorted in a different way under the hood than what is shown in the UI.

**Comment by klikli-dev** [comment]
This seems to be the same error as #989 closing this and commenting there
