### ISSUE TITLE
Line 3031 occultism:white_candle new log error since last update. Unknown registry key

### ISSUE THREAD

**Issue by Sultia** [klikli-dev/occultism#1012]
**Describe the bug**
Unknown registry key

**To Reproduce**
1. use all the mods in the log or download modpack and run game

**Expected behavior**
No line of code as after the last update this has occured

**Screenshots**
N/A

**System (please complete the following information):**
- Occultism Version: 1.89.1
- OS: [e.g. Windows] 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/orbit-cycle/files/4870317
[latest (7).log](https://github.com/klikli-dev/theurgy/files/13400789/latest.7.log)

**Additional context**

**Comment by klikli-dev** [comment]
Sorry this escaped my notice because it was posted in theurgy, not occultism.
This was fixed in #1003
