### ISSUE TITLE
Incompatibility with Farmer's Delight

### ISSUE THREAD

**Issue by FizuPop** [klikli-dev/occultism#1015]
Occultism causes an incompatibility issue with Farmer's Delight that renders the cooking pot unusable.

**To Reproduce**
1. Place campfire
2. Place cooking pot on campfire
3. Place bowl and ingredients inside cooking pot

**Expected behavior**
Cooking pot's textures and cooking features work properly

**Screenshots**
![Screenshot 2023-12-18 224932](https://github.com/klikli-dev/occultism/assets/154299966/4bc3abb6-bae3-4b7a-85c1-220b53ab616d)
![Screenshot 2023-12-18 224950](https://github.com/klikli-dev/occultism/assets/154299966/abd8cba3-12ef-4f74-aa73-935dffa28e4e)

**System (please complete the following information):**
- Occultism Version: 1.95.0
- OS: Windows 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
[ModList.log](https://github.com/klikli-dev/occultism/files/13711289/ModList.log)

**Comment by klikli-dev** [comment]
Same underlying issue as #1014 will be fixed today!
I messed up the campfire tag with a typo :s

**Comment by FizuPop** [comment]
Awesome :D
