### ISSUE TITLE
[bug] Patchouli book error

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1018]
**Describe the bug**
When trying to open the dictionary, and error appears. 

**To Reproduce**
No idea how this happened, I was playing the game and this happened.

**Expected behavior**
The book should open.

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/44974827/89bc87c2-eb09-403f-abf3-f7db7197d5e6)

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.95.2
- OS: Windows
- Minecraft Version: 1.20.1
- Patchouli: Patchouli-1.20.1-84-FORGE

**Additional context**

**Comment by klikli-dev** [comment]
@ffuentesm does this reproduce if you make a minimal install with occultism + dependencies (no theurgy)?
And in your current setup, is theurgy installed and if so which version?

I cannot reproduce this on my end, but basically it should only happen if occultism thinks that theurgy is installed, but it actually is not - or an incompatible version is - in which case I have to update something

**Comment by ffuentesm** [comment]
I am not playing with theurgy.
Just a few moments ago, I was using the preview mechanic to draw a ritual, and then after the server reloaded, the error started to show. 
I could try to just close and re-start my game to see if it works.

**Comment by klikli-dev** [comment]
That would be a good start!
Other than that - if we find out how to cause it in a new world, ideally with only occultism + dependencies then We can look into fixing it

**Comment by ffuentesm** [comment]
Just restarted the game, its working again!
