### ISSUE TITLE
skeleton heads not showing up

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#102]
skeleton heads won't show when using the patchouli vizualization tool

discovered it when trying to summon the djinn familiar parrot(purple one)

the heads not showing up
![image](https://user-images.githubusercontent.com/43792439/104636339-7f47c500-56a3-11eb-9965-87343a7a1553.png)
book 
![image](https://user-images.githubusercontent.com/43792439/104636368-8969c380-56a3-11eb-8561-852a82a365f5.png)

**System (please complete the following information):**
- Occultism Version:  version 1.0.3 for 1.16.4
- OS: [e.g. Windows] windows 10
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: 
- here is a dropbox link
- https://www.dropbox.com/sh/kb3q32kecjr7dpm/AAD6BqFo-qjrAJ02nWnaZWVua?dl=0

**Comment by daniel-eder** [comment]
This is a patchouli (the mod that enables the in game guide and block previews) issue, that in turn seems to be due to some vanilla rendering weirdness - sadly it seems they cannot fix it currently.

**Comment by klikli-dev** [comment]
This is a patchouli (the mod that enables the in game guide and block previews) issue, that in turn seems to be due to some vanilla rendering weirdness - sadly it seems they cannot fix it currently.

**Comment by najlitarvan** [comment]
ok better to report still
