### ISSUE TITLE
Configurable Options for Stable Wormholes

### ISSUE THREAD

**Issue by aszecsei** [klikli-dev/occultism#1023]
**Is your feature request related to a problem? Please describe.**
I'm attempting to make on-the-go storage a bit more difficult in my modpack while also separating the functionality of the stable wormhole and storage accessor. As-is, it's entirely possible to get most of the functionality of the storage accessor by repeatedly placing & destroying a stable wormhole (if a little tedious). I'd like to find a way to disincentivize this "solution."

**Describe the solution you'd like**
I'd like a config option to unlink the stable wormhole from the actuator when the wormhole is destroyed (or perhaps after a certain number of times it's destroyed?).

**Additional context**
N/A

**Comment by klikli-dev** [comment]
Counting the times it has been destroyed is to be honest a bit too specific a use case for me, but I will add a config to delete link on destruction.
If you need the counting on top of that (maybe as a second setting with a default of "unlink after ... 1")  I am open for a PR
