### ISSUE TITLE
Crusher Max tier

### ISSUE THREAD

**Issue by Eqis-Edu** [klikli-dev/occultism#1024]
Since there can have min tier, why not a max tier too?
In addition to obviously being used to demand "weak" spirits, it can be used to alter the result of the same input based on spirit level (to use a specified tier min = x and max =x, maybe a "extact tier" option to simplify in this case).

**Comment by klikli-dev** [comment]
I had not considered that before but it makes sense, we should do that. Helps with giving the tiers meaning I would say!

**Comment by klikli-dev** [comment]
Finally got around to tackling this!
