### ISSUE TITLE
Crash on end of Aviar ritual 

### ISSUE THREAD

**Issue by uhloin** [klikli-dev/occultism#1029]
**Describe the bug**
Final step of Aviar ritual crashes Minecraft

**To Reproduce**
1. Start Aviar rutial
2. Wait until all ores disappeared, crash when there is time for book 

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.104.0.jar 
- OS: [e.g. Windows] Win 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
theurgy-1.20.1-1.11.0.jar 
modonomicon-1.20.1-forge-1.54.4.jar 
geckolib-forge-1.20.1-4.4.jar 
curios-forge-5.4.7+1.20.1.jar
SmartBrainLib-forge-1.20.1-1.13.jar
[crash-2024-01-14_21.43.11-server.txt](https://github.com/klikli-dev/occultism/files/13932534/crash-2024-01-14_21.43.11-server.txt)

**Comment by klikli-dev** [comment]
@uhloin Please try to downgrade smartbrainlib to 1.11 (Forge version!)
The crash is coming from smartbrainlib (which occultism uses for entities), when an entity with such a smart brain spawns it crashes.

On SBL 1.11 this does not happen for me. You can also consider getting in touch with smartbrainlib to see if 1.13 can be used somehow (or of occultism needs to change anything for it to work)

EDIT: As seen below and in the linked SBL issue it was a case of the Forge Version of SBL being used on Neo. SBL is working as intended - please use SBL 1.13 for Neo!

**Comment by uhloin** [comment]
Thank you, 1.11 works fine. I created Issue for SmartBrainLib with link here

**Comment by Tslat** [comment]
1.13 works fine - you're using the wrong loader version here

See: https://github.com/Tslat/SmartBrainLib/issues/57#issuecomment-1891803412

**Comment by uhloin** [comment]
Ritual is finished, but Foliot Crusher demon has a tiny visualization issue. If I give him End Stone, he crushed it but a stone stays in his arms. After that I gave an Obsidian, he crushed it too and dropped obsidian dust, but he is still holding End Stone in the arms. If I restart game, End Stone disappears.

**Comment by uhloin** [comment]
I can confirm, this combination works fine:

modonomicon-1.20.1-forge-1.54.4.jar
SmartBrainLib-neoforge-1.20.1-1.13.jar 
geckolib-neoforge-1.20.1-4.4.jar
occultism-1.20.1-1.104.0.jar
theurgy-1.20.1-1.11.0.jar 

But if somebody like me used wrong set before, it's possible even after download all of them additional crashes or freezes. If so, I recommend clear .minecraft/config, this helped me.
