### ISSUE TITLE
FPS lag when using the storage controller to open the storage itself

### ISSUE THREAD

**Issue by SaikoTSP** [klikli-dev/occultism#1038]
Describe the bug:
FPS lag when using the storage controller to open the storage itself.

Not really sure how to reproduce it. I tried in an instance with just occultism and dependencies and since there's nothing in the actuator it doesn't happen. It started to happen roughly when I got to 600/700 items in the storage.
I don't have to much yet in my world, this is in a modpack I created for me and 3 friends and I only have 749 slots used as you'll see in the video below.

Expected behavior:
To not have fps lag when using the controller.

Screenshots:
You can see the fps drop in left corner. I go from 80/90 to 16.
https://streamable.com/doo7oz

System:
-Occultism Version: 1.104.1
-OS: Windows 11
-Minecraft Version: 1.20.1
-Modpack Link and Version, or list of mods:
[Mouse Tweaks](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Cloth Config API (Fabric/Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Architectury API (Fabric/Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Bookshelf](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Searchables](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)
[AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Curios API (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Nature's Compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Iceberg [Forge]](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Advancement Plaques [Forge]](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Citadel](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Allomancy](https://www.curseforge.com/minecraft/mc-mods/allomancy)
[Apothic Attributes (AttributesLib)](https://www.curseforge.com/minecraft/mc-mods/apothic-attributes)
[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Obscure API (Forge)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
[Aquamirae (Forge)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
[playerAnimator](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Aqua Combat](https://www.curseforge.com/minecraft/mc-mods/aqua-combat)
[Ars Nouveau](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Modonomicon](https://www.curseforge.com/minecraft/mc-mods/modonomicon)
[SmartBrainLib (Forge/Fabric/Quilt)](https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)
[Ars Ocultas](https://www.curseforge.com/minecraft/mc-mods/ars-ocultas)
[AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Auudio [Forge]](https://www.curseforge.com/minecraft/mc-mods/auudio-forge)
[Balm (Forge Edition)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Better Third Person](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Better Combat [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Big Swords R](https://www.curseforge.com/minecraft/mc-mods/big-swords-r)
[TerraBlender (Forge)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Biomes O' Plenty](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Blood Magic](https://www.curseforge.com/minecraft/mc-mods/blood-magic)
[Tome of Blood: Rebirth](https://www.curseforge.com/minecraft/mc-mods/tome-of-blood-rebirth)
[CorgiLib](https://www.curseforge.com/minecraft/mc-mods/corgilib)
[Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons](https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials)
[Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Bountiful (Forge)](https://www.curseforge.com/minecraft/mc-mods/bountiful)
[Cupboard](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Brutal Bosses - Custom Bosses[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)
[Caelus API (Forge/NeoForge)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Canary](https://www.curseforge.com/minecraft/mc-mods/canary)
[Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[L_Ender 's Cataclysm](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Combat Roll [Fabric & Forge]](https://www.curseforge.com/minecraft/mc-mods/combat-roll)
[Cataclysmic Combat](https://www.curseforge.com/minecraft/mc-mods/cataclysmic-combat)
[Cave Dweller Evolved](https://www.curseforge.com/minecraft/mc-mods/cave-dweller-evolved)
[Collective](https://www.curseforge.com/minecraft/mc-mods/collective)
[Colorful Hearts](https://www.curseforge.com/minecraft/mc-mods/colorful-hearts)
[Comforts (Fabric/Forge/Quilt)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Consecration (Fabric/Forge/Quilt)](https://www.curseforge.com/minecraft/mc-mods/consecration)
[Corail Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[CraterLib](https://www.curseforge.com/minecraft/mc-mods/craterlib)
[Create](https://www.curseforge.com/minecraft/mc-mods/create)
[CreativeCore](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Cyclops Core](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[DarkBlades - End Game Weapons, Armor & Tools (Fabric/Forge)](https://www.curseforge.com/minecraft/mc-mods/darkblades-end-game-weapons)
[Deeper and Darker](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Divine Weaponry - Better Combat](https://www.curseforge.com/minecraft/mc-mods/divine-weaponry)
[Domum Ornamentum](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Dragon Mounts: Legacy](https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy)
[Structure Essentials[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Dungeons and Taverns](https://www.curseforge.com/minecraft/mc-mods/dungeon-and-taverns)
[Structure Gel API](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Dungeons Enhanced](https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced)
[Durability101 Forge/Fabric 1.12-1.20](https://www.curseforge.com/minecraft/mc-mods/durability101)
[Easy Villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
[Elytra Slot (Fabric/Forge/Quilt)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[TexTrue's Embeddium Options](https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)
[Embeddium++](https://www.curseforge.com/minecraft/mc-mods/embeddiumplus)
[bad packets](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[Puzzles Lib [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Enchanting Infuser [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[Ender Trigon](https://www.curseforge.com/minecraft/mc-mods/ender-trigon)
[EnhancedVisuals](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Entity Culling](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[EvilCraft](https://www.curseforge.com/minecraft/mc-mods/evilcraft)
[Explorer's Compass](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Explorify – Dungeons & Structures](https://www.curseforge.com/minecraft/mc-mods/explorify)
[Eyes in the Darkness](https://www.curseforge.com/minecraft/mc-mods/eyes-in-the-darkness)
[Falling Leaves (Forge)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[FastWorkbench](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[FerriteCore (Forge)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Framework](https://www.curseforge.com/minecraft/mc-mods/framework)
[FTB Library (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[FTB Teams (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[FTB Chunks (Forge)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Iris/Oculus & GeckoLib Compat](https://www.curseforge.com/minecraft/mc-mods/geckoanimfix)
[Goblin Traders](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[The Graveyard (FORGE)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[HammerLib](https://www.curseforge.com/minecraft/mc-mods/hammer-lib)
[Resourceful Lib](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Handcrafted](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Harder Spawners](https://www.curseforge.com/minecraft/mc-mods/harder-spawners)
[ImmediatelyFast](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Immersive Aircraft [Fabric/Forge]](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Immersive Armors [Fabric/Forge]](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Improvable Skills 3](https://www.curseforge.com/minecraft/mc-mods/improvable-skills)
[AtomicStryker's Infernal Mobs](https://www.curseforge.com/minecraft/mc-mods/atomicstrykers-infernal-mobs)
[Inventory HUD+](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[Iron Chests](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Iron's Spells 'n Spellbooks](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Item Filters](https://www.curseforge.com/minecraft/mc-mods/item-filters)
[Jade 🔍](https://www.curseforge.com/minecraft/mc-mods/jade)
[Just Enough Items (JEI)](https://www.curseforge.com/minecraft/mc-mods/jei)
[JEI Integration](https://www.curseforge.com/minecraft/mc-mods/jei-integration)
[Kambrik](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Konkrete [Forge]](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[Prism [Forge]](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Legendary Tooltips [Forge]](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
[Lootr (Forge & NeoForge)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Majrusz Library](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
[Majrusz's Progressive Difficulty](https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty)
[Max Health Fix](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[Medieval Paintings](https://www.curseforge.com/minecraft/mc-mods/medieval-paintings)
[Medieval Music[Forge/Fabric]](https://www.curseforge.com/minecraft/mc-mods/medieval-music)
[ModernFix](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[BlockUI](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Structurize](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Multi-Piston](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Mutant Monsters [Forge & Fabric]](https://www.curseforge.com/minecraft/mc-mods/mutant-monsters)
[No Chat Reports](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
[Primal Magick](https://www.curseforge.com/minecraft/mc-mods/primal-magick)
[Smooth Boot (Reloaded)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Polymorph (Fabric/Forge/Quilt)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Sound Physics Remastered](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Sophisticated Core](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[spark](https://www.curseforge.com/minecraft/mc-mods/spark)
[Starlight (Forge)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[Theurgy](https://www.curseforge.com/minecraft/mc-mods/theurgy)
[Too Fast](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[Tool Belt](https://www.curseforge.com/minecraft/mc-mods/tool-belt)
[Tool Stats](https://www.curseforge.com/minecraft/mc-mods/tool-stats)
[Tree Harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
[Vampirism - Become a vampire!](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)
[Vampires Need Umbrellas](https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas)
[Vampiric Ageing - A Vampirism Addon](https://www.curseforge.com/minecraft/mc-mods/vampiric-ageing-a-vampirism-addon)
[Vampirism Integrations](https://www.curseforge.com/minecraft/mc-mods/vampirism-integrations)
[Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Xaero's Minimap & World Map - Waystones Compatibility [Forge]](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap-world-map-waystones-compability)
[Werewolves - Become a Beast!](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast)
[When Dungeons Arise - Forge!](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Xaero's Minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Xaero's World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Inventory Sorter](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[Just Enough Resources (JER)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Gothic Medieval RPG Font](https://www.curseforge.com/minecraft/texture-packs/gothic-rpg-font)
[Mandala's GUI - Dark mode](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)
[EnhancedVisual Pixelated](https://www.curseforge.com/minecraft/texture-packs/enhancedvisual-pixelated)
[xali's Bushy Leaves](https://www.curseforge.com/minecraft/texture-packs/xalis-bushy-leaves)
[Enhanced Boss Bars](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars)
[Occultism](https://www.curseforge.com/minecraft/mc-mods/occultism)

**Comment by klikli-dev** [comment]
@SaikoTSP these types of things are sadly super hard to track because it could be something in occultism, something in one of the mods that adds items that you have in storage, or a combination of both.

Can you try to install https://www.curseforge.com/minecraft/mc-mods/spark and run it on your client? (not the server in this case).

It works roughly like this:
1. Install the mod client-side (I am not sure if the server needs it too, most likely not)
2. Enter the server (or your singleplayer world if it shows the same issue)
3. Go stand in front of your storage
4. run /spark profiler start
5. Open the storage and reproduce the issue
6. run /spark profiler stop

You should then receive a link with the performance output, please send me this link.
The link does not contain any personal information, it simply shows how long minecraft takes for each task. That may help us track the issue down

**Comment by SaikoTSP** [comment]
https://spark.lucko.me/swLPXm3DsH

**Comment by klikli-dev** [comment]
@SaikoTSP  thank you! However I must apologize, it was the wrong command - turns out spark has a specific one for the client side / GUI: /sparkclient profiler start and stop, can you run that too?

**Comment by SaikoTSP** [comment]
Sure, here it is: https://spark.lucko.me/QT6oEe5adq
I tried another thing in the mean time, I deleted my controller, picked up one in creative, bound it to my storage. My fps still lowers a bit (to 50), not to 16 tho.

**Comment by SaikoTSP** [comment]
And I've come across another issue as well. Whenever I try to take a single item from the storage, the item disappears from the storage as it gets to my mouse or inventory, as it should, but when I try to take a stack, the value in the storage won't change.
Imagine, I take a stack of iron out of 447 ingots, the value won't change in the storage, and if I take all 447 ingots, an "afterimage" will stay within the storage as well, as if I haven't pick up any of the iron.

**Comment by klikli-dev** [comment]
> Sure, here it is: https://spark.lucko.me/QT6oEe5adq I tried another thing in the mean time, I deleted my controller, picked up one in creative, bound it to my storage. My fps still lowers a bit (to 50), not to 16 tho.

It's odd there is nothing obvious. Almost all of the time spent rendering is from minecraft's builtin item renderer, the remainder is almost exclusively JEI for the sidebar. So the problem is either the amount of items drawn, or that one or more of the items takes a long time to render.

I will investigate it further but lacking an obvious culprit it might be hard to track down

**Comment by SaikoTSP** [comment]
Sure thing, another question, to use the the storage remotely, the chunk (where the storage is) needs to be loaded? And if so, the storage itself forces chunk loading?

**Comment by klikli-dev** [comment]
> Sure thing, another question, to use the the storage remotely, the chunk (where the storage is) needs to be loaded? And if so, the storage itself forces chunk loading?

That is correct it needs to be loaded. The storage does not chunk load itself - please use a chunk loading mod, e.g. the chunk management from FTB is useful.

The reason is simply to avoid players abusing occultism chunkloading to bypass server limits

**Comment by SaikoTSP** [comment]
Thank you so much for the support :)

**Comment by klikli-dev** [comment]
This patch may not solve the issue, but it optimizes the item rendering on my end. 
All further item rendering is done by minecraft so I have limited (= no) influence on what happens, so I hope this helps at least a little
