### ISSUE TITLE
Spirit Campfire Provides Light When Extinguished

### ISSUE THREAD

**Issue by ImAislen** [klikli-dev/occultism#1040]
**Describe the bug**
Minor bug, but the spirit campfire provides light while extinguished. Same light level as when lit.

**To Reproduce**
1. Place a soul campfire in a dark room
2. Extinguish with a shovel
3. See the light level doesn't change

**Expected behavior**
When extinguished, the soul campfire shouldn't provide any light

**Screenshots**

![Soulcampfiredarkroom](https://github.com/klikli-dev/occultism/assets/131167396/d2358d62-90da-4990-831b-df0aaec05f14)

![Soulcampfirelit](https://github.com/klikli-dev/occultism/assets/131167396/8db2a4f8-ed6d-477b-8138-9e682d4b5618)

![Soulcampfireext](https://github.com/klikli-dev/occultism/assets/131167396/300ce2f7-e4ba-44e0-984f-65a0d507c6cd)

**System (please complete the following information):**
- Occultism Version: 1.112.0 Neoforge
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: Occultism, SmartBrainLib, Modonomicon, GeckoLib 4

**Comment by klikli-dev** [comment]
It's ... uh ... a magic campfire?

Will be fixed presently!
