### ISSUE TITLE
Issue summoning the possessed elder guardian

### ISSUE THREAD

**Issue by Kevin-Marsh** [klikli-dev/occultism#1042]
The ritual for summoning the possessed elder guardian isn't accepting any fish that I could find. Cod, Salmon, Tropical Fish were attempted. Modifying the ritual with a datapack from forge:fish to forge:chicken allowed the ritual to complete just fine. It seems to be an issue with fish.

**System (please complete the following information):**
- Occultism Version:  occultism-1.20.1-1.109.0
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: [Allthemods 9](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5055211) and [Allthemods 9 no frills](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-no-frills/files/5055887)

**Additional context**
Atm9 implemented custom ritual designs but that is not the cause of this. I also tested it without the modifications to rule it out.

**Comment by klikli-dev** [comment]
Closed in #1043
