### ISSUE TITLE
Djinni hitbox

### ISSUE THREAD

**Issue by Eqis-Edu** [klikli-dev/occultism#1044]
Increase the hitbox of djinni to match the model

![2024-01-24_21 42 57](https://github.com/klikli-dev/occultism/assets/117950663/eaf66603-825f-4916-949c-b3e2b5778516)

**Comment by klikli-dev** [comment]
@Eqis-Edu how did you summon the djinni?
The djinni resizes based on the job he has, but currently the default size is to fit the foliots, from which his machine manager model is borrowed.

What I mean to say is, if you summon the djinni via the ritual as crusher (currently his only in-game form that has the big model) the collider should fit; only if summoned without a job he falls back to the default size (and there should currently not be an in-game way to do that)
