### ISSUE TITLE
neoforge 20.4, crash on launch

### ISSUE THREAD

**Issue by Abalieno** [klikli-dev/occultism#1045]
Stopped running under latest betas:
NullPointerException: Trying to access unbound value: ResourceKey[minecraft:attribute / neoforge:step_height]
at com.klikli_dev.occultism.registry.OccultismEffects.lambda$static$4(OccultismEffects.java:49) ~[occultism-1.20.4-neoforge-1.113.0.jar%23230!/:1.113.0] {re:classloading}

I think any recent betas, currently testing 142.

**Comment by klikli-dev** [comment]
This is a crash caused by neo (or rather, an underlying vanilla issue). Neo will add a workaround - so far it seems the only option is to use an older neo version
