### ISSUE TITLE
Storage bugs from Occultism (Accidentally posted on Theurgy page)

### ISSUE THREAD

**Issue by Neenes47** [klikli-dev/occultism#1046]
Describe the bug
Mostly to do with the Occultism Storage interface, I am using this mod in ATM9 so that might be a bug with the modpack I still haven’t tested it on the standalone mod but here are the issues I encountered.
1- The most annoying thing is on the interface when you are typing to find an item, it conflicts with other hotkeys from other mods, this bug is weird because it doesn’t happen with any other storage mod that has that search bar. For example: when typing “pot” or any word with P it opens the Players menu from minecraft. Or when typing anything with G it opens baubles inventory. The workaround I found for this was to link the search with JEI and search on JEI’s search bar. But that sometimes also bugs with the mod and it double taps the key I’m typing so when typing “torch” it types “ttoorrcchh”.
2- the other bug is visual but does confuse me a lot, the items count in the storage interface doesn’t instantly update. For example I had to craft some otherworld stone slabs and I needed 12, I crafted it and stored in the system but it wasn’t showing up so I thought it bugged and I crafted again. I closed the interface and opened again and I had crafted 24 without knowing.
3- this one is conflict with other mods but for example when crafting items that has the same recipe there is no button to change the item I want to craft in the interface like other mods do. For example I wanted to craft the occultism candle but it is the same recipe as vanilla candles and I couldn’t switch to the occultism one so I had to use a regular crafting table.

System (please complete the following information):

Occultism Version: occultism-1.20.1-1.113.0
OS: Windows 11
Minecraft Version: 1.20.1
Modpack Link and Version, or list of mods: All the Mods 9 on Curseforge (9-0.2.40)
Additional context
I am playing in a server I created but I don’t know if that is related to the issue.

**Comment by klikli-dev** [comment]
I created separate issues for the problems you mentioned.

For #3, as far as I know this cannot be implemented on my end without creating a whole new feature myself.
Usually people use polymorph to get this functionality, but it does not yet support occultism, see https://github.com/illusivesoulworks/polymorph/issues/229

I am closing this issue as the remaining other two are now separate
