### ISSUE TITLE
crash just after summoning a Foliot

### ISSUE THREAD

**Issue by PCThrow** [klikli-dev/occultism#1050]
**Describe the bug**
Complete babies first summoning, there is a brief message that the spirit is summoned, and then it crashes.

**To Reproduce**
1. set up the ritual Aviar's Circle, with all the metal ores and everything
2. activate with the bound book
3. wait for ritual to finish

**Expected behavior**

**Screenshots**
have a slow crusher

**System (please complete the following information):**
- Occultism Version: 1.113.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.20.1
- Forge version? 47.1.3
- modpack? personal

mods: 
- Additional Structures 4.2.1
- AlmostUnified 1.20.1-0.7.2
- Architectury 9.1.12
- Ars Artifice 1.20.1-2.0.3
- Ars Creo 4.0.1
- Ars Elemental 1.20.1-0.6.4.1
- Ars Instrumentum 4.0.0
- Ars Nouveau 4.9.0
- Ars Nouveau Scaling Compats 1.20.1-1.10.1-alpha
- Ars Nouveau Trinkets1.20.1-2.2.0
- Ars Ocultas 1.2.1
- Awesome dungeon 3.2.0
- Awesome dungeon edition ocean 3.3.0
- Awesome dungeon nether 3.1.1
- Awesome dungeon the end 3.1.1
- Bad Packets 0.4.3
- BetterDays 1.20.1-3.1.0.3-FORGE
- Bookshelf 20.0.5
- Carry On 2.1.2.5
- Chunk Loaders 1.2.8
- Cloth Config v10 API 11.1.106
- Collective6.66
- Comforts 6.3.4+1.20.1
- Create 0.5.1.E
- Cristel Lib 1.1.5
- Curios API 5.3.5+1.20.1
- Delightful3.4.2
- Dungeon Crawl 2.3.14
- Dungeons and Taverns 3.0.2
- Embeddium 0.2.2+MC1.20.1
- EnchantmentDescriptions 17.0.8
- Farmer's Delight 1.20.1-1.2.3
- GeckoLib 4 4.4.2
- Geophilic 2.0.0-mc1.20u1.20.2
- Homeostatic 1.20.1-2.9.5.0
- Just Zoom 1.0.2
- Konkrete 1.6.1
- Library ferret 4.0.0
- Modonomicon 1.57.0
- Nature's Compass 1.20.1-1.11.2-forge
- Not Enough Glyphs 1.20.1-3.2.0.2
- Occultism 1.113.0
- Oculus 1.6.9
- Patchouli 1.20.1-81-forge   (can't use newer, why Forge is still at 47.1.3)
- PMMO Farmers Delight Compat 1.20.1-1.0.4
- Project MMO 1.2.9
- REI Plugin Compatibilities 12.0.88
- Replanting Crops 5.1
- Repurposed Structures 7.1.11+1.20.1-forge
- Roughly Enough Items (REI) 12.0.665
- SmartBrainLib 1.13
- Sophisticated Backpacks 3.18.59.909
- Sophisticated Core 0.5.89.425
- Starbunclemania 1.20.1-1.2.0.7
- Storage Drawers 12.0.2
- Structure Compass Mod 2.0.6
- SuperMartijn642's Config Library 1.1.8
- SuperMartijn642's Core Lib 1.1.15
- TerraBlender 3.0.0.169
- TexTrue's Embeddium Options 0.1.2+mc1.20.1
- Theurgy 1.14.1
- Too Many Glyphs 2.3.2.12345
- Towns and Towers 1.11.1
- Tree Harvester 8.2
- wthit 8.4.0
- Xaero's Minimap 23.9.7
- Xaero's World Map 1.37.7

**Additional context**
[crash-2023-10-18_11.56.51-client.txt](https://github.com/klikli-dev/occultism/files/14155602/crash-2023-10-18_11.56.51-client.txt)
[latest.log](https://github.com/klikli-dev/occultism/files/14155605/latest.log)

**Comment by klikli-dev** [comment]
A crash after the first summoning is likely a problem with the wrong smartbrainlib version installed - see here: https://github.com/Tslat/SmartBrainLib/issues/57#issuecomment-1891803412

The crash log you posted, however, has nothing to do with occultism, it seems to be caused by or affecting REI
