### ISSUE TITLE
Crusher name in description in dictionary of spirit

### ISSUE THREAD

**Issue by Loriannas** [klikli-dev/occultism#1053]
**Describe the bug**
te name in the description of marid crisher is wrong

**To Reproduce**
1. open dictionary of spirit book
2. find marid crusher
3. read description

**Expected behavior**
read : The marid crusher is... instead the afrit crusher is...

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/157993656/1d879825-28d8-4df1-97f2-6c57394b296e)

**System (please complete the following information):**
- Occultism Version: 1.84.0
- OS: [e.g. Windows]
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: Ragnamod VII

**Additional context**

**Comment by klikli-dev** [comment]
Thank you for the report - this has been fixed in later versions, but 1.18.2 is not being updated any more, that is why it remains
