### ISSUE TITLE
[1.20.1] Dictonary error when trying to short cut to ritual circle

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1054]
**Describe the bug**
Dictionary glitches when trying to access the ritual circle shortcut

**To Reproduce**
Open the dictionary to the lv 2 crusher
Click on the ophyx calling ritual shortcut on the crusher page
See error

**Expected behavior**
It should open to the ophyx calling ritual page

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/44974827/38ed73cb-ff8d-468b-8e6a-c9269c193220)

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.114.0
- OS:  Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
[Mod_list.txt](https://github.com/klikli-dev/occultism/files/14234791/Mod_list.txt)

**Comment by klikli-dev** [comment]
@ffuentesm does this happen for all circles or only for a specific one? 

Edit: I just randomly tried a few and they all work, so more information is needed.
Further, please try if this happens with just occultism + dependencies - if not it is probably another mod or a datapack interfering

**Comment by ffuentesm** [comment]
Strange. 
I just launched again and tried a non-ophyx calling ritual shortcut. and it worked normally. Then I tried the ophyx calling ritual and worked again. 
Not sure what is happening but the glitch is not happening.
