### ISSUE TITLE
[1.20.1] Crash when summoning an entity

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1055]
**Describe the bug**
I tried to summon a djinn crusher, and the Neruina mod killed the ticking entity that would have crashed the game, then I tried to manually summon it using the ritual item from creative to check it. That caused the game to crash.

**To Reproduce**
Try to summon a Djinn

**Expected behavior**
The Mob should have appeared

**System (please complete the following information):**
Occultism Version: occultism-1.20.1-1.114.0
OS: Windows
Minecraft Version: 1.20.1
Modpack Link and Version, or list of mods:
[Mod_list.txt](https://github.com/klikli-dev/occultism/files/14251153/Mod_list.txt)

**Additional context**
[crash-2024-02-12_16.29.43-server.txt](https://github.com/klikli-dev/occultism/files/14251135/crash-2024-02-12_16.29.43-server.txt)

**Comment by klikli-dev** [comment]
Duplicate of #1029 
See https://github.com/Tslat/SmartBrainLib/issues/57#issuecomment-1891803412 for solution - use the right variant of smart brain lib
