### ISSUE TITLE
Making Familiar's stronger

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1056]
**Is your feature request related to a problem? Please describe.**
Combat familiars die pretty easily and are relatively weak. Putting a single mummy against even 2 zombies will have it dead in very short order. 

**Describe the solution you'd like**
The change to allow them to drop a Familiar Soul Shard is great. This will allow them to be brought back very quickly in the field as the materials required are easy to carry around. 

Letting them be a little stronger, however, wouldn't be detrimental, I think. In Enigmatica 9, we buffed some of them substantially and they seemed to perform well. Now, understand our mobs were also generally buffed in many cases, so this may be a little extreme, but I don't really think it's that far off for defaults. 

You can see the values we gave them here, however: https://github.com/EnigmaticaModpacks/Enigmatica9/blob/30ba12dd79be5b155f6538fb69e76b589463d8f9/kubejs/server_scripts/base/recipes/apotheosis/minibosses/occultism.js#L195

This covers the Mummy, Dragon, Shub Niggurath, and Beholder. My options were rather limited since I could only tweak them through standard attributes. So, the Beholders couldn't do any extra damage, for example, much as I would have liked to turn it into a laser gatling gun. 

Still, they were all brought up to approximately player health and the equivalent of diamond armor. The Mummy and Dragon both also got the equivalent of a diamond sword's damage bonus. They could still die this way, even against unbuffed mobs,, but they were far more likely to make it through a combat. 

If similar damage buffs could be applied to the ranged guys, like beholder, that'd be wonderful. They're also very slow to fire. Doubling their attack rate wouldn't be out of line, I think. 

**Additional context**
This is referring back to our discussion in Discord here: https://discord.com/channels/688406873392676924/1194638517708533760/1199606209817358387

**Comment by klikli-dev** [comment]
Thank you! It is good to have concrete numbers, will update their stats accordingly!

**Comment by klikli-dev** [comment]
One note: The beholder respects the damage boost mob effect for the ray so you can buff it that way :) But I will increase the default damage & rate

**Comment by MuteTiefling** [comment]
Woop! Nice :D
