### ISSUE TITLE
Familiar Ring is not storing familiars

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1057]
**Describe the bug**
Right clicking a familiar with the ring simply removes the familiar. It isn't stored in the ring and cannot be released. 

**To Reproduce**
1. Summon a Mummy
2. Right Click with a Familiar Ring

**Expected behavior**
The Familiar should be stored in the ring

**System (please complete the following information):**
- Occultism Version: occultism-1.20.4-neoforge-1.114.1
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods:

**Comment by klikli-dev** [comment]
That sounds like another victim of the capability rework - will check it out!

**Comment by klikli-dev** [comment]
Next patch will introduce a potential fix - feedback will be appreciated as I am not sure if it works 100%.
 Note that it cannot restore familiars captured before at he issue is related to saving - but familiars captured after should work

**Comment by TheBedrockMaster** [comment]
This issue seems to be related https://github.com/AllTheMods/ATM-10/issues/142

**Comment by MuteTiefling** [comment]
Just tested in 1.161.0 and these guys are working fine. Can put a deer in a familiar ring and get it back out again.
