### ISSUE TITLE
Sinytra Connector and Geckolib Fabric

### ISSUE THREAD

**Issue by ChapperNi** [klikli-dev/occultism#1058]
Hey, I'm not sure how applicable this is--but I'm using Sinytra connector with fabric mods, and some of those fabric mods require the fabric version of geckolib, but this mod won't recognize the fabric version of Geckolib. Is there anything that can be done?

**Comment by klikli-dev** [comment]
@ChapperNi you can ask Geckolib if they have a way to handle this (or maybe Sinytra connector) - on my end I just require "geckolib" of version 4.4 minimum as far as the "formal" requirements go- 

However I suspect this is a technical limitation, I am pretty sure my multiplatform mod modonomicon would have the same issue if both a fabric and forge mod needed it.
