### ISSUE TITLE
Soul campfire shouldn’t deal damage

### ISSUE THREAD

**Issue by blockgoblin31** [klikli-dev/occultism#1059]
**Is your feature request related to a problem? Please describe.**
My modpack uses lychee to copy the soul fire recipes over to the soul campfire and id prefer if it didn’t damage players, like soul fire
**Describe the solution you'd like**
I’d like the soul campfire to not deal damage when standing on it
**Additional context**
My pack is on 1.19.2 but I fully understand if that version’s no longer supported, I feel like it’s a good consistency change either way.

**Comment by klikli-dev** [comment]
1.19.2 will not get this update as I don't have it set up on my machine any more, but 1.20.1+ will :) Thanks for reporting

**Comment by klikli-dev** [comment]
For newer versions fixed in 3e10b6bc33eec9db0222760e839c4e9c262ff51f
