### ISSUE TITLE
Instruction for opening Config screen for Books of Calling is incorrect

### ISSUE THREAD

**Issue by Samrel556** [klikli-dev/occultism#1060]
**Describe the bug**
In guide book the instruction for opening the configuration screen for Books of Calling states "Right-Click the air to open configuration screen"

**To Reproduce**
1. Read Guide book entry on Books of Calling
2. Hold a Bound Book of Calling
3. Right-Click the air
4. Notice nothing happens
5. Right-Click ground opens Configuration screen

**Expected behavior**
Behavior should match written instructions

**System (please complete the following information):**
- Occultism Version: 1.116.0
- OS: Arch Linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: JEI + Occultism and required dependencies

**Comment by klikli-dev** [comment]
I only now got around to testing this and it does not reproduce for me.
I am closing it (assuming that some patch inbetween has fixed it). If it still remains, please ping me here to reopen
