### ISSUE TITLE
Crash preventing world from running on server.

### ISSUE THREAD

**Issue by GentlemanCheesy** [klikli-dev/occultism#1061]
**Describe the bug**
Server is crashing and freezing up when occultism is present.

**To Reproduce**
Unsure what is causing it directly as it happens when nobody is online or maybe at server restarting? I cannot tell.

**Expected behavior**
No crashes if possible.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.114.0
- OS: [e.g. Windows] Server Environment, not sure what os it would be.
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: Neoforge
[SwissSocietyV5.2.txt](https://github.com/klikli-dev/occultism/files/14365592/SwissSocietyV5.2.txt)

**Additional context**
Crash Report:
[crash-2024-02-20_23.01.11-fml.txt](https://github.com/klikli-dev/occultism/files/14365565/crash-2024-02-20_23.01.11-fml.txt)

**Comment by klikli-dev** [comment]
I'm asking in the neoforge discord about this, because it (it being registering compostables) worked before without issues, maybe they changed something.

You can try using an older neo version, or forge 47.1.3
