### ISSUE TITLE
candles recognized as bedrock

### ISSUE THREAD

**Issue by NekoTy** [klikli-dev/occultism#1062]
tried to use the pentacles to summon a foliot transporter, it said the pentacle was not recognized. after looking in the spirit dictionary it showed all the candles as bedrock.

**To Reproduce**
1. open spirit dictionary
2. look at pentacle diagram
3. see bedrock in place of candles

**Expected behavior**
i expected the pentacle to require candles like it has before and not bedrock in the pentacle.

**Screenshots**
![2024-02-21_17 32 16](https://github.com/klikli-dev/occultism/assets/100053827/691aab2f-f6be-4515-9bd0-a654bbad2c45)
![2024-02-21_17 32 20](https://github.com/klikli-dev/occultism/assets/100053827/30a728e7-7305-4ca7-a469-5d992b9d7ea7)
![2024-02-21_17 32 22](https://github.com/klikli-dev/occultism/assets/100053827/9d70e7d7-3ed0-4043-8870-01d52e7edf62)
![2024-02-21_17 32 23](https://github.com/klikli-dev/occultism/assets/100053827/35afe392-15bc-4a14-84c0-0aab45f7dd7a)
![2024-02-21_17 32 24](https://github.com/klikli-dev/occultism/assets/100053827/a788c14c-57d6-4c0e-8eee-28bb38d01972)
![2024-02-21_17 32 26](https://github.com/klikli-dev/occultism/assets/100053827/e2f3d81d-7fc6-430a-a7e7-66dae1d84de3)
![2024-02-21_17 32 28](https://github.com/klikli-dev/occultism/assets/100053827/eb226e2d-8a29-4091-a317-d8275f773bbc)
![2024-02-21_17 32 29](https://github.com/klikli-dev/occultism/assets/100053827/424d4b4e-26bd-4f6a-88c9-37a2f7897ace)
![2024-02-21_17 32 30](https://github.com/klikli-dev/occultism/assets/100053827/f0125245-d7c3-4ebc-8678-0880e181c2f0)
![2024-02-21_17 32 32](https://github.com/klikli-dev/occultism/assets/100053827/0029aca2-44a5-4622-bf88-b820d24a4ae8)
![2024-02-21_17 32 34](https://github.com/klikli-dev/occultism/assets/100053827/5faff054-58bf-4f88-8153-51d0872c0480)
![2024-02-21_17 32 35](https://github.com/klikli-dev/occultism/assets/100053827/26323866-9c0e-4052-a748-3daa02c776ad)
![2024-02-21_17 32 37](https://github.com/klikli-dev/occultism/assets/100053827/33088a08-29a8-41e5-a74b-3e43debe8d35)
![2024-02-21_17 32 48](https://github.com/klikli-dev/occultism/assets/100053827/c353a149-3b13-4a55-9e5d-0fd8bd09db73)

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.116.0.jar
- OS: [e.g. Windows] windows 11
- Minecraft Version: 1.20,1
- Modpack Link and Version, or list of mods: [NekoTy Occultism.zip](https://github.com/klikli-dev/occultism/files/14367211/NekoTy.Occultism.zip)

that is the modpack with the problem hope its fine to give it like that (im not very good at tech sorry)

**Comment by klikli-dev** [comment]
Please provide a log - this looks like something went wrong with loading - or another mod messed with the candles.
Out of the box they definitely work

**Comment by NekoTy** [comment]
[latest.log](https://github.com/klikli-dev/occultism/files/14380707/latest.log)

this is the latest log it should include the issue

**Comment by GaeaKat** [comment]
This part of the log looks intresting: 
`[15:27:07] [Server thread/ERROR]: Failed to parse Tag and BlockState properties from json member "tag" for TagMatcher: {0}. Will use empty property map as fallback, Exception: {1}
com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block tag 'minecraft:candles' at position 0: <--[HERE]`

**Comment by GaeaKat** [comment]
One of the mods you have added has removed the minecraft:candle blocktag
From your pack: 

![CleanShot 2024-02-23 at 01 22 02@2x](https://github.com/klikli-dev/occultism/assets/690546/45591184-3879-4ab1-ba84-0d9d66d2b2ab)
![CleanShot 2024-02-23 at 01 27 51@2x](https://github.com/klikli-dev/occultism/assets/690546/eb326c2b-1521-4fc1-8e4f-ef006a06439a)

**Comment by GaeaKat** [comment]
Vanilla: 
![CleanShot 2024-02-23 at 01 27 11@2x](https://github.com/klikli-dev/occultism/assets/690546/c06c3f8e-437f-4041-a81b-a8554046a4a2)

**Comment by NekoTy** [comment]
there was one mod i added before the problem occurred, probably should've thought that might be the problem. there's an update for that mod ill try that if it doesn't fix ill remove the mod and report back

**Comment by GaeaKat** [comment]
Did a quick binary search (removinghalf. testing, and so on) ... it is supplementaries that is removing the minecraft:candles tag

**Comment by GaeaKat** [comment]
https://github.com/MehVahdJukaar/Supplementaries/issues/949 here is the relevent issue, Supplementeries has fixed it as of  the latest version.

**Comment by NekoTy** [comment]
awesome updated it now thanks for the help
