### ISSUE TITLE
ATM9 no frills beholder familiar ritual not working

### ISSUE THREAD

**Issue by Eragon-Brisinger** [klikli-dev/occultism#1063]
**Describe the bug**
I am playing ATM9 no frills modpack on my multiplayer server and i am trying to summon the beholder familiar and it does not seem to allow me to start the ritual stating that make sure its set up correctly but i used the ihagans enthrallment circle for something else and it worked

**To Reproduce**
1. Create Ihagans Enthrallment pentacle 
2. place ingredients for beholder familiar ritual
3. use book of binding on golden sacrificial bowl

**Expected behavior**
For the book of binding to be placed in center  bowl and show its waiting for spider sacrifice 

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.116.0.jar 
- OS: windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: All the mods no frills https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-no-frills 0.1.8

**Additional context**

**Comment by klikli-dev** [comment]
Have you talked to the ATM team?
They changed the pentacles which may be related to the issue

**Comment by klikli-dev** [comment]
Just tested with "pure" occultism - it works. Most likely you need to re-create your pentacle based on the ATM changes.
Please ping me here if the ATM team says its an occultism thing after all
