### ISSUE TITLE
Chinese characters fail to show up in the guidebook

### ISSUE THREAD

**Issue by Noaaan** [klikli-dev/occultism#1067]
**Describe the bug**
Same as title

**To Reproduce**
1. Set your language to simplified chinese
2. Open any save file
3. Open any entry

**Expected behavior**
Text should be readable

**Screenshots**
![2024-02-29_22 07 37](https://github.com/klikli-dev/occultism/assets/4163353/755ae72a-3f6f-4672-9251-2ab546d0ced8)

**System (please complete the following information):**
- Occultism Version: 1.117.0 (NeoForge)
- OS: Linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: N/A, only Occultism with its dependencies

**Comment by klikli-dev** [comment]
@Noaaan can you check in your config folder if the ModonomiconClient.toml file has an entry "fontFallbackLocales" and what that entry contains? 
Also do you happen to know the ISO code of your language settings? zh_cn (simplified chinese for mainland china) should be in the setting by default, but other simplified chinese variants are not yet in there

**Comment by Noaaan** [comment]
I am using zh_cn. The other languages do not have any translations with Occultism as far as I can see. The config file includes the following:
`fontFallbackLocales = ["zh_cn", "ja_jp", "ko_kr"]`

**Comment by klikli-dev** [comment]
Thanks! I managed to reproduce it, it looks like something went wrong sinced we fixed that

**Comment by klikli-dev** [comment]
@Noaaan it looks like the problem occurs only when changing language from en -> cn after starting, is this also your experience?

**Comment by klikli-dev** [comment]
When updating modonomicon to 1.61.1 it should work :)
