### ISSUE TITLE
Reloading the guidebook makes it unusable

### ISSUE THREAD

**Issue by Noaaan** [klikli-dev/occultism#1068]
**Describe the bug**
There is something wrong with one of the entries that makes the guidebook unusable after reloading the game. The log states the following error: 
```java
BookErrorManager.error() called for book: occultism:dictionary_of_spirits with error: BookErrorInfo{ 
errorMessage='Failed to load entry 'occultism:dictionary_of_spirits/entries/getting_started/theurgy_divination_rod'', 
context='Page Index: 0', 
exception='com.google.gson.JsonSyntaxException: Unknown item 'theurgy:divination_rod_t1''
}
```
I assume this is something related to a load condition with Theurgy, which fails to apply when reloading. 

**To Reproduce**
1. Open the guidebook
2. Close it
3. Run `/reload`
4. Open the guidebook again
There is now a missing entry

**Expected behavior**
Expected the book to still be usable

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/4163353/9d904031-09a0-438c-b4b6-c6d2d3ae8c09)

**System (please complete the following information):**

-   Occultism Version: 1.117.0 (NeoForge)
-   OS: Linux
-   Minecraft Version: 1.20.1
-   Modpack Link and Version, or list of mods: N/A, only Occultism with its dependencies

**Comment by klikli-dev** [comment]
Just to clarify, theurgy is not installed, correct?
I ask because it is an occultism dependency, but optional ..

**Comment by Noaaan** [comment]
I have not installed it

**Comment by klikli-dev** [comment]
Thanks! Managed to reproduce it and will look into it

**Comment by klikli-dev** [comment]
@Noaaan if you update to modonomicon 1.60.1 (as soon as it is available, will be a few minutes / hours) it should work
