### ISSUE TITLE
mods aren't compatible with  the server 

### ISSUE THREAD

**Issue by Seacub1Playz** [klikli-dev/occultism#1069]
i have been playing on this server for atleast a week now but when going to log on today its saying that two mods arent on the server and to remove them from the mod pack but when i did do that it wouldnt let me on the server at all the two mods that are not working are the werewolves mod and the female gender mod.

**Comment by klikli-dev** [comment]
@Seacub1Playz I fear you are wrong here, we are not running a server :) I am just developing the occultism mod

**Comment by Seacub1Playz** [comment]
> @Seacub1Playz I fear you are wrong here, we are not running a server :) I am just developing the occultism mod

ive been on the server with the modpack and the server advitises ur discord server as the one to go to for help???

**Comment by GaeaKat** [comment]
> > @Seacub1Playz I fear you are wrong here, we are not running a server :) I am just developing the occultism mod
> 
> ive been on the server with the modpack and the server advitises ur discord server as the one to go to for help???

Only for help with the Occultism, modonomicon. or Theurgy  mods I would imagine, not for a random modpack @klikli-dev  had no hand in making.
