### ISSUE TITLE
Transporter cannot take from Barrel [1.20.1]

### ISSUE THREAD

**Issue by Johannason** [klikli-dev/occultism#1072]
**Describe the bug**
Foliot Transporter cannot extract from barrel

**To Reproduce**
That's the whole report, really.
I had an input barrel, a transporter, a crusher, a janitor, and an output barrel.
The transporter cannot extract from the barrel, whether top face or side face.
On replacing the barrel with a chest, transporter had no problems.
(Janitor can deposit in barrel just fine)

**Expected behavior**
A barrel is just another type of inventory block, I don't know why a transporter wouldn't be able to take from it.

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.116.1
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 57 mods in total, none of which should alter barrels or chests.
- https://www.mediafire.com/file/yxkvudmlyqkqqtj/1.20.1_MNA.zip/file

**Comment by klikli-dev** [comment]
Can you re-test this? @GaeaKat tried to reproduce the issue and for her it could add and remove items

**Comment by GaeaKat** [comment]
Tested with vanilla barrel and chipped barrel varients added using the modfiles provided. Either way the transporter was able to access the contents, though it is worth noting it didn't animate the barrel opening

**Comment by Johannason** [comment]
Bug re-tested and still extant. Maybe something about the placement of chalk mark or sign causes him to assume the barrel is blocked?
Testing that... and confirmed. For some reason an adjacent chalk mark prevents access to the barrel on that side.

https://imgur.com/a/u6xGJ77

**Comment by GaeaKat** [comment]
I am afraid I am still having difficulty reproducing - 
![image](https://github.com/klikli-dev/occultism/assets/690546/0f1bf451-456f-4ebf-8ec5-5506e3fa37f0)
With this setup the spirit is still able to access the barrel

**Comment by GaeaKat** [comment]
I am afraid I am still having trouble reproducing, with this setup 
![image](https://github.com/klikli-dev/occultism/assets/690546/48879164-fb22-4fa5-9eff-0909ad624ba1)
It still can access the barrel fine. I tried making a reproductioin of that corner of your room shown in the screenshots, to see if I could

**Comment by GaeaKat** [comment]
What version of forge is in use?

**Comment by Johannason** [comment]
forge-1.20.1-47.2.20

Am conducting more tests with extraction face and direction with interesting results, will add when completed.

**Comment by Johannason** [comment]
Transporters can extract from a Barrel surrounded by Chalk if they are approaching from the North or West side.
If they are approaching from the East or South, a Chalk Mark on that side prevents them from accessing the barrel.

https://imgur.com/a/novyg2z

In my main world, the Chalk Mark is blocking the South side.

**Comment by GaeaKat** [comment]
Ok Now I can reproduce the error also! This feels like it is going to be a weird one.

**Comment by GaeaKat** [comment]
I have located the bug as within https://github.com/klikli-dev/occultism/blob/version/1.20.1/src/main/java/com/klikli_dev/occultism/common/entity/ai/goal/ExtractItemsGoal.java#L162-L177 this function.
