### ISSUE TITLE
pentacles with bedrock instead of candle

### ISSUE THREAD

**Issue by zeze427** [klikli-dev/occultism#1075]
when im trying to do a ritual its say its false and when i'm openning the book it says to place bedrock instead of candle

step 1: i went to dictiobary of spirit
step 2: open Pentacles
step 3:i watched all the pentacles we're needed a bedrock instead of candles

I wanted to have the candle instead

![Capture d’écran (626)](https://github.com/klikli-dev/occultism/assets/162836034/c0ff4826-d965-4189-96cc-e83ac48a91f4)

- Occultism Version:1.120.0.jar 
- Minecraft Version:1.20.1
- Modpack Link and Version, or list of mods:
alexscaves-1.0.9.jar
balm-forge-1.20.1-7.2.1.jar
blockui-1.20.1-0.0.101-ALPHA.jar
citadel-2.4.9-1.20.1.jar
domum_ornamentum-1.20-1.0.150-BETA-universal.jar
essential_1-3-0-6_forge_1-20-1.jar
iceandfire-2.1.13-1.20.1-beta-2.jar 
journeymap-1.20.1-5.9.18-forge.jar
minecolonies-1.20.1-1.1.452-RELEASE.jar
modonomicon-1.20.1-forge-1.60.0.jar
moonlight-1.20-2.10.0-forge.jar
octolib-1.20.1-0.2.jar
relics-1.20.1-0.5.3.jar
sophisticatedbackpacks-1.20.1-3.20.1.1012.jar
Sophisticated Core
storagedrawers-1.20.1-12.0.2.jar
structurize-1.20.1-1.0.662-BETA.jar
supplementaries-1.20-2.8.0.jar
the_bumblezone-7.2.5+1.20.1-forge.jar
Vampirism-1.20.1-1.10.6.jar
Werewolves-1.20.1-1.2.0.1.jar
ars_elemental-1.20.1-0.6.4.1.jar
ars_nouveau-1.20.1-4.9.0-all.jar
ars_ocultas-1.20.1-1.2.1-all.jar
BetterAdvancements-1.20.1-0.3.2.162.jar
Botania-1.20.1-443-FORGE.jar
Botarium
carryon-forge-1.20.1-2.1.2.7.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.f.jar
createoreexcavation-1.20-1.4.2.jar
create-new-age-forge-1.20.1-1.1.2.jar
cristellib-1.1.5-forge.jar
curios-forge-5.7.0+1.20.1.jar (Forge/NeoForge)
fabledweaponry-1.20.1-1.0.7.1.jar
FerriteCore ((Neo)Forge)
geckolib-forge-1.20.1-4.4.2.jar
Guide-API-VP-1.20.1-2.2.6.jar
jei-1.20.1-forge-15.3.0.4.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
more_music_discs_blossom.jar
multipiston-1.20-1.2.31-ALPHA.jar
occultism-1.20.1-1.120.0.jar
oreexcavation-1.13.170.jar
Patchouli-1.20.1-84-FORGE.jar
SmartBrainLib-forge-1.20.1-1.13.jar (Forge/Fabric/Quilt)
ToroHealth-Unofficial-Forge-1.20.1-1.0.0.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
Waystones

i cant do the ritual because its say the pentacle is wrong

**Comment by GaeaKat** [comment]
You need to update supplementaries. The version you have accidentally deleted the candles tag, hence the weird behaviour of any mod using that tag, including occultism.

**Comment by zeze427** [comment]
> You need to update supplementaries. The version you have accidentally deleted the candles tag, hence the weird behaviour of any mod using that tag, including occultism.

thx  for the help i will try
