### ISSUE TITLE
Dictionary of Spirits doesnt open

### ISSUE THREAD

**Issue by ImCassandra** [klikli-dev/occultism#1076]
**Describe the bug**
Is very simple, i have the dictionary on my left hand and when i click it doesnt open, only do a little animation like a sword

**To Reproduce**
1. Get the dictionary (craft with book and seed)
2. Grab it and right click to open it
3. Nothing happen, only a little animation but without open

**Expected behavior**
I expect to open the book

**Screenshots**
The screenshot is not necessary i think, its simply not open

**System (please complete the following information):**
- Occultism Version: 1.20.4
- OS: [e.g. Windows] if i understand correctly the question, i have windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: I dont know what i need to write..

**Additional context**
I dont think i need to write something else. If you need something different please tell me

**Comment by GaeaKat** [comment]
seems if you /give a book or craft the book, the NBT tag is not added to it.
log -
```
[13:35:09] [Render thread/ERROR] [Modonomicon/]: ModonomiconItem: ItemStack has no tag!
```

**Comment by ImCassandra** [comment]
So what i need to do?

**Comment by GaeaKat** [comment]
> So what i need to do?

nothing can do, unless you can get a dictionary from the creative menu, this is a bug that needs to be fixed and a new version uploaded

**Comment by ImCassandra** [comment]
I give to myself from creative. You right, if you craft it it doesn open

**Comment by ImCassandra** [comment]
Thanks buddy, you saved me!!!
