### ISSUE TITLE
Crash when rendering enchantment text on a Master Miner Marid

### ISSUE THREAD

**Issue by loving2** [klikli-dev/occultism#1078]
**Describe the bug**
Evilcraft's Blood Chest will repair an item with durability but has a chance of adding a negative enchantment. Apotheosis adds text to enchantments to describe them. When a miner has one of Evilcraft's enchantments on it, it appears to crash the client when trying to render the text from hovering the mouse over the miner.

**To Reproduce**
1. Use a Miner
2. Repair it in an Evilcraft Blood Chest until it has negative enchantments (not sure which enchantment causes the issue)
3. Mouse over the Miner
4. Crash

**Expected behavior**
The client renders the text and doesn't crash.

**System (please complete the following information):**
- Occultism Version: 1.116.0
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: [ATM9 v0.2.51](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5125809)

**Additional context**
I uploaded the crash report along with it, not sure if this belongs with Apotheosis or here or with Evilcraft even, but if this is the wrong spot let me know and I'll make an issue elsewhere!
[crash-2024-03-12_17.00.58-client.txt](https://github.com/klikli-dev/occultism/files/14578788/crash-2024-03-12_17.00.58-client.txt)

**Comment by klikli-dev** [comment]
@loving2 thanks for reporting. Could you possibly also report that with Apotheosis?
The crash happens in "apoth_enchTooltipRewrite" which seems to be something they added via mixin.

Feel free to link to this issue so they an yell at me if I did something wrong and need to change something ;)
At least at first glance it looks like it goes through occultism and vanilla code without issues, but I am not an expert on tooltips at all.

**Comment by loving2** [comment]
Thanks, will do! I wasn't sure where exactly it was crashing, but it certainly seems to be something with the tooltip

**Comment by loving2** [comment]
Looks like it was something they were aware of and already fixing, thanks again!
