### ISSUE TITLE
I don't get the Third Eye Effect

### ISSUE THREAD

**Issue by zeroporcento1** [klikli-dev/occultism#1079]
I'm making a modpack on 1.16.5, on CurseForge, and I was testing the mod but the demon dream's fruit isn't activating the Third Eye's effect. Instead, it gives me the Conduit Power effect. My friend ate the fruit and the same thing happened, but I could see he had the effect when I put my aim on him with a mod that makes me able to see other entities effects. I don't know what is causing this. I also put the Otherworld Goggles but didn't find any otherworld trees or stone.

**Comment by zeroporcento1** [comment]
It has some conflict with vampirism that it changes it for blindness

**Comment by zeroporcento1** [comment]
Ok I removed vampirism along with ars noveau and forbidden & arcanus and it worked but i activated those except for vampirsm and now the effect is Haste II. It was Conduit II, then Blindness II and now it's Haste II.

**Comment by zeroporcento1** [comment]
Artifacts (by ochotonida)
Mutant Villager! (by pixelgeist666)
Corail Tombstone (by Corail_31)
Rubidium (by Asek3)
The Abyss II - The Other Side (by y4z0n)
Industrial Agriculture (by ArrowsendGaming)
Wavey Capes (by tr7zw)
Eating Animation [Forge] (by matyrobbrt)
Forbidden and Arcanus (by cesar_zorak)
Nature's Compass (by Chaosyr)
Supplementaries (by MehVahdJukaar)
Majrusz's Progressive Difficulty (by Majrusz17)
GeckoLib (by Gecko)
Ars Nouveau (by baileyholl2)
Ender Storage 1.8.+ (by covers1624)
FerriteCore ((Neo)Forge) (by malte0811)
Lootr (Forge & NeoForge) (by Noobanidus)
Cucumber Library (by BlakeBr0)
Macaw's Paintings (by sketch_macaw)
Back Tools (by iChun)
Harder Branch Mining (by MacTso)
Clumps (by Jaredlll08)
HT's TreeChop (by hammertater)
Curios API (Forge/NeoForge) (by TheIllusiveC4)
Occultism (by kli_kli)
BountifulBaubles (by Cursed1nferno)
Villager Names (by Serilum)
Mutant Wolf (by TrueRealCursed_Warrior)
EvilCraft (by kroeser)
Witchery: Rewitched (by hero3112)
Macaw's Lights and Lamps (by sketch_macaw)
Kotlin for Forge (by thedarkcolour)
FPS Boost (by The_TCT)
Upgrade Aquatic (by TeamAbnormals)
Majrusz Library (by Majrusz17)
FastSuite (by Shadows_of_Fire)
Mouse Tweaks (by YaLTeR)
Ding (Forge) (by iChun)
Falling Leaves (Forge) (by Cheaterpaul)
Better Fps - Render Distance[Forge] (by someaddon)
iChunUtil (by iChun)
Equipable Twilight Forest Charms (TFC) (by MemeMan)
Tome of Blood (by AshLuna)
SuperMartijn642's Core Lib (by SuperMartijn642)
ReAuth (by TechnicianLP)
Structure Gel API (by ModdingLegacy)
BetterEnd (Forge) (by Beethoven92)
Astral Sorcery (by HellFirePvP)
Nyf's Spiders (by Nyfaria)
InsaneLib (by Insane96)
Gateways to Eternity (by Shadows_of_Fire)
The Arcaneum (by totalblacksmith)
Sons Of Sins (by Furti_Two)
Advancement Plaques [Forge] (by Grend_G)
ModernFix (by embeddedt)
Moonlight Lib (by MehVahdJukaar)
Better Compatibility Checker (by Gaz_)
Nature's Starlight (by Ellpeck)
Item Highlighter [Forge] (by Grend_G)
Eidolon's Sanguine Arsenal (by alexandr_0031)
Mantle (by mDiyo)
Macaw's Roofs (by sketch_macaw)
Twilight Forest: The Lost Blocks (by Kitteh6660)
ExpandAbility (by florensie)
Eidolon's Hexblades (by Alexth99)
Nature's Aura (by Ellpeck)
Ensorcellation (by TeamCoFH)
Enchanted: Witchcraft (by Favouriteless)
Jade 🔍 (by Snownee)
Placebo (by Shadows_of_Fire)
Iceberg [Forge] (by Grend_G)
Progressive Bosses (by Insane96)
Dark Caverns (by Freerangerstudios)
ShetiPhianCore (by ShetiPhian)
Morpheus (by Quetzi)
CodeChicken Lib 1.8.+ (by covers1624)
Ars Mage Fight (by Cycro54)
Harder Spawners (by MacTso)
Sophisticated Backpacks (by P3pp3rF1y)
Macaw's Bridges (by sketch_macaw)
Vampirism Integrations (by maxanier)
Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)
Born in Chaos (by mongoose_artist)
Inventory Sorter (by cpw)
Blood And Madness (A Bloodborne Inspired Mod) (by Nitespring)
Lapis Reserve (by sfort__)
Farmer's Delight (by vectorwing)
Spice of Life: Carrot Edition (by lordcazsius)
EnderTanks (by ShetiPhian)
MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)
TenshiLib (Forge) (by flemmli97)
Prism [Forge] (by Grend_G)
Macaw's Fences and Walls (by sketch_macaw)
End's Delight (by foggyhillside)
Fusion (Connected Textures) (by SuperMartijn642)
Architectury API (Fabric/Forge/NeoForge) (by shedaniel)
Macaw's Windows (by sketch_macaw)
Macaw's Doors (by sketch_macaw)
Infinite Abyss (by dreamcritting)
AI Improvements (by QueenOfMissiles)
XP Tome (by bl4ckscor3)
Legendary Tooltips [Forge] (by Grend_G)
InvMove (by PieKing1215)
ObserverLib (by HellFirePvP)
Valhelsia Core (by ValhelsiaTeam)
Nether's Delight (by lumpazl)
Paragliders (by Tictim)
Eidolon (by elucent_)
Damage Tilt (by Charles445)
Blood Magic (by WayofTime)
IAP [Botania] (by ArrowsendGaming)
Mystical Agradditions (by BlakeBr0)
Fast Async World Save[Forge/Fabric] (by someaddon)
FPS Reducer (by bre2el)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Improved Mobs (Forge) (by flemmli97)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Just Enough Items (JEI) (by mezz)
Ice and Fire: Dragons (by sbom_xela)
Blueprint (by TeamAbnormals)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Xaero's Minimap (by xaero96)
Common Capabilities (by kroeser)
TRansliterationLib (by tr7zw)
Quickstack (by tfarecnim)
The Conjurer (by ModdingLegacy)
Entity Collision FPS Fix (by Corgi_Taco)
Mana and Artifice (by AWildCanadianEh)
Citadel (by sbom_xela)
Abnormals Delight (by TeamAbnormals)
DataPack Anvil (by Sirttas)
Apotheosis (by Shadows_of_Fire)
Macaw's Trapdoors (by sketch_macaw)
Mutant Beasts (by Chumbanotz)
Theurgy (by kli_kli)
Macaw's Paths and Pavings (by sketch_macaw)
Mahou Tsukai (by stepcros)
Stalwart Dungeons (by Furti_Two)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
SuperMartijn642's Config Lib (by SuperMartijn642)
Skin Layers 3D (Fabric/Forge) (by tr7zw)
Oculus (by Asek3)
Bookshelf (by DarkhaxDev)
Fast Leaf Decay (by olafskiii)
Elemental Craft (by Sirttas)
Macaw's Furniture (by sketch_macaw)
AutoRegLib (by Vazkii)
Mystical Agriculture (by BlakeBr0)
ESSENTIAL Mod (by SparkUniverse_)
Botania (by Vazkii)
Vampirism - Become a vampire! (by maxanier)
Botania Additions (by ToMe250)
Enchantment Descriptions (by DarkhaxDev)
Chisels & Bits - For Forge (by AlgorithmX2)
AttributeFix (by DarkhaxDev)
FastFurnace (by Shadows_of_Fire)
Obscure API (Forge) (by Obscuria)
Patchouli (by Vazkii)
Caelus API (Forge/NeoForge) (by TheIllusiveC4)
Runelic (by DarkhaxDev)
When Dungeons Arise - Forge! (by Aureljz)
Ice and Fire: Dragonseeker (by syrikalis)
Goblin Traders (by MrCrayfish)
Cosmetic Armor Reworked (by LainMI)
Not Enough Animations (by tr7zw)
CoFH Core (by TeamCoFH)
AppleSkin (by squeek502)
Ars EnderStorage (by Moonwolf2872)
The Twilight Forest (by Benimatic)
FastWorkbench (by Shadows_of_Fire)
Cyclops Core (by kroeser)
AIOT Botania (by MelanX)
Better Third Person (by Socolio)
Advent of Ascension (Nevermine) (by Scimiguy)
Observable (by tasgon)
Collective (by Serilum)

This is the modlist

**Comment by klikli-dev** [comment]
This has happened in the past, but it does not seem like something occultism can fix.
The third eye effect uses just base game / forge features to add a new food effect, and it seems some other mod switches how effects work in some scenarios. 

I would recommend to continue the mod remove/add until you know exactly which mod causes the effect to switch from third eye to something else and then inquire with the author if they know what is going on.

If they know and occultism needs to change anything feel free to ping me here or open a new issue!
