### ISSUE TITLE
Unoptainable Datura Seeds 

### ISSUE THREAD

**Issue by Dinocraft1515YT** [klikli-dev/occultism#1080]
**Describe the bug**
Breaking small_grass and fern don't give you the datura_seeds

**To Reproduce**
1. Brake some small_grass or fern
2. See error

**Expected behavior**
Those 2 blocks should give you the seeds

**System (please complete the following information):**
- Occultism Version: 1.20.4-neoforge-1.121.1
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: https://drive.google.com/file/d/1GamW_usSe45IvZjkr-XaRO-JXSE0VBUl/view?usp=drivesdk

**Additional context**
I've made a datapack to fix it temporaly until new version

**Comment by GaeaKat** [comment]
Can reproduce, tried a stack of bone meal, broke all the grass it produced, no seeds

**Comment by klikli-dev** [comment]
Fixed in cca0437bf3878bd21d5ac3acdcdf453fa29debe7 thanks to @GaeaKat! 
Will be released as release/v1.20.4-1.121.2
