### ISSUE TITLE
AMD Graphics Card suspected of preventing Iesnium ore rendering.

### ISSUE THREAD

**Issue by silvernirvash** [klikli-dev/occultism#1082]
**Describe the bug**
So I'm playing a modpack with a group of friends. I'm the only one using an AMD RX 7600XT in my PC everyone else is using Nvidia graphics cards. I'm going through the Occultism mod right now in the modpack and everything is working fine however no matter what I do I can't make Iesnium Ore reveal itself. I tested this out with one of my friends who was able to see the ore get highlighted when using the Divination Rod and can even see the ore when wearing the goggles but I can't even when looking at the exact same block.

**To Reproduce**
1: have an AMD graphics card installed on your PC
2: run any modpack with Occultism in the pack or just install the Occultism mod
3: go to the nether with the appropriate tools needed to find Iesnium ore
4. Get no visual highlighting a block nor any revealed Iesnium ore revealing itself when mining to it.

**Expected behavior**
I expect no visual reveal of the iesnium ore nor a white outline of the block when looking for it with the divination rod

**Screenshots**

**System (please complete the following information):**
- Occultism Version:  1.19.2-1.90.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/stacia-2-expert

**Additional context**

**Comment by klikli-dev** [comment]
This is a known issue with AMD cards. Open occultism-client.toml in your instance's /config folder and set `useAlternativeDivinationRodRenderer = true` 
I am not sure if this alternative renderer is set up on 1.19.2, but it should be.
