### ISSUE TITLE
Storage system crash

### ISSUE THREAD

**Issue by Yargo0** [klikli-dev/occultism#1088]
So when i add a craft with JEI with the storage accesor it doesn't put all the item and if i try to move an item from one slot to another in the crafting interface of the storage accesor it crashes 

To reproduce
1. have JEI and craft anything by using the plus (when you click for the reciepe of an item on JEI)
2. if there aren't all the item in the craft try to drag one to another slot
3. crashe

occultisme 1.18.2 latest version
windows 11
Minecraft 1.18.2
modpack : 1.18.2 https://www.curseforge.com/minecraft/modpacks/ragnamod-vii

**Comment by klikli-dev** [comment]
Please provide your crash log

That said, 1.18.2 is no longer supported, so Occultism will likely not get a patch, unless a community member provides it.
However, as no such crash has been reported in the months/years 1.18.2 has been out, it may be a mod compatibility problem, so if you provide the log we may be able to get a step further

**Comment by Yargo0** [comment]
[crash-2024-03-16_12.43.55-client.txt](https://github.com/klikli-dev/occultism/files/14623643/crash-2024-03-16_12.43.55-client.txt)
here it is, but I don't have any clue what mod may be causing this

> Please provide your crash log
> 
> That said, 1.18.2 is no longer supported, so Occultism will likely not get a patch, unless a community member provides it. However, as no such crash has been reported in the months/years 1.18.2 has been out, it may be a mod compatibility problem, so if you provide the log we may be able to get a step further

**Comment by GaeaKat** [comment]
fastutil seems to be having issues in that crash log

**Comment by Yargo0** [comment]
i don't know how to read a crash log but i had my suspicion on polymorph even if i wasn't sure at all, i had a friend that had problem with it and after removing it it seems that the prroblem is solved even though it still drop my framerate when i move the item but at least it doesn't crash anymore
