### ISSUE TITLE
[1.20.4][Neoforge] Spirit campfire don't campfire properly

### ISSUE THREAD

**Issue by Lucksinia** [klikli-dev/occultism#1097]
**Describe the bug**
While trying to use spirit campfire it just stores food and not cooks it.

**To Reproduce**
1. Place block Spirit campfire
2. right-click a raw food source on it.
3. Observe how it's stuck there forever, until you break the block.

**Expected behavior**
Raw food should be cooked after designated time. As vanilla campfires do. or something like that.

**Screenshots**
<img src="https://github.com/klikli-dev/occultism/assets/63837173/3edc9a2d-3448-4218-920d-87dd8d711f96" width="25%" height="25%">

**System (please complete the following information):**
- Occultism Version: 1.123.0
- OS: Windows 11
- Minecraft Version: 1.20.4/NeoForge 20.4.208
- List of mods: Jade + JEI + all Mekanism + Occultism + Modonomicon

**Additional context**
As can be seen on screenshot, campfire added food into it's internal  inventory, started some process... but then just stuck.

**Comment by klikli-dev** [comment]
Hmm I have to check what the underlying functionality is.
I am just using the vanilla campfire block, I suspect it somewhere checks for the _specific_ vanilla campfire variants
