### ISSUE TITLE
[1.20.1] Crashing when Configuring Janitor/Transporter

### ISSUE THREAD

**Issue by revan2811** [klikli-dev/occultism#1098]
**Describe the bug**
Only tried with Janitor or Transporter. When I open the configure book to set the mode my Minecraft freezes and crashes to desktop.
The Janitors work area can be changed no problem.

**To Reproduce**
1. Open the book
2. Left click on the "Mode" button
3. Freeze and Crash

**Expected behavior**
Changing the Mode to set the drop off container

**Screenshots**
Changing Janitors Work area works fine
![2024-03-20_14 19 13](https://github.com/klikli-dev/occultism/assets/15685269/adc44a51-0a43-447b-8c10-83bcba49bd16)

**System (please complete the following information):**
- Occultism Version: 1.123.0
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 

  [✔️] almostunified-forge-1.20.1-0.8.1.jar
  [✔️] appleskin-forge-mc1.20.1-2.5.1.jar
  [✔️] architectury-9.2.14-forge.jar
  [✔️] ars_creo-1.20.1-4.1.0.jar
  [✔️] ars_nouveau-1.20.1-4.9.0-all.jar
  [✔️] ars_ocultas-1.20.1-1.2.2-all.jar
  [✔️] ash_api-forge-3.0.2+1.20.1.jar
  [✔️] balm-forge-1.20.1-7.2.2.jar
  [✔️] BarteringStation-v8.0.0-1.20.1-Forge.jar
  [✔️] bendy-lib-forge-4.0.0.jar
  [✔️] betterbeaconplacement-1.20.1-3.3.jar
  [✔️] betterspawnercontrol-1.20.1-4.4.jar
  [✔️] Bookshelf-Forge-1.20.1-20.1.9.jar
  [✔️] BotanyPots-Forge-1.20.1-13.0.25.jar
  [✔️] BotanyPotsTiers-Forge-1.20.1-6.0.1.jar
  [✔️] BotanyTrees-Forge-1.20.1-9.0.11.jar
  [✔️] Bountiful-6.0.3+1.20.1-forge.jar
  [✔️] caelus-forge-3.1.0+1.20.jar
  [✔️] chunkloaders-1.2.8a-forge-mc1.20.1.jar
  [✔️] cloth-config-11.1.118-forge.jar
  [✔️] Clumps-forge-1.20.1-12.0.0.3.jar
  [✔️] cofh_core-1.20.1-11.0.0.51.jar
  [✔️] Cognition-v2.0.3-1.20.1.jar
  [✔️] collective-1.20.1-7.36.jar
  [✔️] Companion-1.20.1-forge-5.0.1.jar
  [✔️] Controlling-forge-1.20.1-12.0.2.jar
  [✔️] convenientcurioscontainer-1.13-forge-1.20.1.jar
  [✔️] cookingforblockheads-forge-1.20.1-16.0.3.jar
  [✔️] corail_woodcutter-1.20.1-3.0.4.jar
  [✔️] craftingtweaks-forge-1.20.1-18.2.3.jar
  [✔️] create_connected-0.7.3-mc1.20.1-all.jar
  [✔️] create_wizardry-1.20.1-0.1.2.jar
  [✔️] create-1.20.1-0.5.1.f.jar
  [✔️] curios-forge-5.7.0+1.20.1.jar
  [✔️] cyclepaintings-1.20.1-3.5.jar
  [✔️] deepslategenerator-1.1.0.jar
  [✔️] DiagonalFences-v8.1.3-1.20.1-Forge.jar
  [✔️] DiagonalWalls-v8.0.2-1.20.1-Forge.jar
  [✔️] DiagonalWindows-v8.1.3-1.20.1-Forge.jar
  [✔️] easy-villagers-forge-1.20.1-1.1.4.jar
  [✔️] eccentrictome-1.20.1-1.10.2.jar
  [✔️] EdivadLib-1.20.1-2.0.1.jar
  [✔️] elytraslot-forge-6.3.0+1.20.1.jar
  [✔️] EnchantingInfuser-v8.0.2-1.20.1-Forge.jar
  [✔️] enderchests-forge-1.20.1-1.2.jar
  [✔️] ensorcellation-1.20.1-5.0.0.21.jar
  [✔️] entity_model_features_forge_1.20.1-1.3.jar
  [✔️] entity_texture_features_forge_1.20.1-5.2.3.jar
  [✔️] entityculling-forge-1.6.2-mc1.20.1.jar
  [✔️] ExtraStorage-1.20.1-4.0.7.jar
  [✔️] extremesoundmuffler-3.41-forge-1.20.jar
  [✔️] farmingforblockheads-forge-1.20.1-14.0.2.jar
  [✔️] fixedanvilrepaircost-1.20.1-3.3.jar
  [✔️] flib-1.20.1-0.0.11.jar
  [✔️] flourish-forge-3.0.0+1.20.1.jar
  [✔️] ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
  [✔️] ftb-chunks-forge-2001.2.5.jar
  [✔️] ftb-library-forge-2001.1.5.jar
  [✔️] ftb-teams-forge-2001.1.4.jar
  [✔️] functionalstorage-1.20.1-1.2.9.jar
  [✔️] geckolib-forge-1.20.1-4.4.4.jar
  [✔️] grindstonesharpertools-1.20.1-3.4.jar
  [✔️] harvestwithease-1.20.1-8.0.1.0-forge.jar
  [✔️] HorseExpert-v8.1.1-1.20.1-Forge.jar
  [✔️] infinitetrading-1.20.1-4.3.jar
  [✔️] inventorysorter-1.20.1-23.0.1.jar
  [✔️] inventorytotem-1.20.1-3.2.jar
  [✔️] ironchest-1.20.1-14.4.4.jar
  [✔️] ironfurnaces-1.20.1-4.1.6.jar
  [✔️] irons_spellbooks-1.20.1-3.0.1.jar
  [✔️] itemcollectors-1.1.9-forge-mc1.20.jar
  [✔️] Jade-1.20.1-forge-11.8.0.jar
  [✔️] JadeAddons-1.20.1-forge-5.2.2.jar
  [✔️] jearchaeology-1.20.1-1.0.3.jar
  [✔️] jei-1.20.1-forge-15.3.0.4.jar
  [✔️] jmi-forge-1.20.1-0.14-47.jar
  [✔️] journeymap-1.20.1-5.9.18p1-forge.jar
  [✔️] Kambrik-6.1.1+1.20.1-forge.jar
  [✔️] Kiwi-1.20.1-forge-11.5.5.jar
  [✔️] kotlinforforge-4.10.0-all.jar
  [✔️] laserio-1.6.8.jar
  [✔️] LeavesBeGone-v8.0.0-1.20.1-Forge.jar
  [✔️] light-overlay-8.0.0-forge.jar
  [✔️] majrusz-library-forge-1.20.1-7.0.5.jar
  [✔️] majruszs-enchantments-forge-1.20.1-1.10.7.jar
  [✔️] mineralchance-1.20.1-3.4.jar
  [✔️] modonomicon-1.20.1-forge-1.62.0.jar
  [✔️] moonlight-1.20-2.11.0-forge.jar
  [✔️] MoreMobGriefingOptions-1.20.1-2.0.4.jar
  [✔️] MouseTweaks-forge-mc1.20-2.25.jar
  [✔️] occultism-1.20.1-1.123.0.jar
  [✔️] Paintings-forge-1.20.1-11.0.0.0.jar
  [✔️] pamhc2foodcore-1.20.4-1.0.5.jar
  [✔️] passiveendermen-1.20.1-4.6.jar
  [✔️] passiveshield-1.20.1-3.4.jar
  [✔️] Patchouli-1.20.1-84-FORGE.jar
  [✔️] player-animation-lib-forge-1.0.2-rc1+1.20.jar
  [✔️] polymorph-forge-0.49.2+1.20.1.jar
  [✔️] Powah-5.0.5.jar
  [✔️] ProjectE_Integration-1.20.1-7.2.1.jar
  [✔️] ProjectE-1.20.1-PE1.0.1.jar
  [✔️] ProjectExpansion-1.20.1-1.0.0.jar
  [✔️] ProjectExtended-1.20.1-1.5.0.jar
  [✔️] PuzzlesLib-v8.1.18-1.20.1-Forge.jar
  [✔️] reactive-1.20.1-8a.jar
  [✔️] refinedcooking-4.0.0.jar
  [✔️] refinedstorage-1.12.4.jar
  [✔️] refinedstorageaddons-0.10.0.jar
  [✔️] RSInfinityBooster-1.20.1-1.0+32.jar
  [✔️] scaffoldingdropsnearby-1.20.1-3.2.jar
  [✔️] Searchables-forge-1.20.1-1.0.2.jar
  [✔️] sebastrnlib-4.0.0.jar
  [✔️] shetiphiancore-forge-1.20.1-1.2.jar
  [✔️] shulkerdropstwo-1.20.1-3.3.jar
  [✔️] SmartBrainLib-forge-1.20.1-1.13.jar
  [✔️] sophisticatedbackpacks-1.20.1-3.20.2.1022.jar
  [✔️] sophisticatedcore-1.20.1-0.6.8.567.jar
  [✔️] sophisticatedstorage-1.20.1-0.10.7.750.jar
  [✔️] supermartijn642configlib-1.1.8-forge-mc1.20.jar
  [✔️] supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
  [✔️] supplementaries-1.20-2.8.6.jar
  [✔️] theurgy-1.20.1-1.17.1.jar
  [✔️] titanium-1.20.1-3.8.27.jar
  [✔️] toomanyglyphs-1.20.1-2.3.2.12345.jar
  [✔️] transparent-forge-8.0.1+1.20.1.jar
  [✔️] trashcans-1.0.18b-forge-mc1.20.jar
  [✔️] UniversalEnchants-v8.0.0-1.20.1-Forge.jar
  [✔️] universalgrid-1.20.1-1.1.jar
  [✔️] veinmining-forge-1.3.1+1.20.1.jar
  [✔️] waystones-forge-1.20-14.1.3.jar
  [✔️] zombieproofdoors-1.20.1-3.2.jar

**Additional context**

I tried a few things to recreate this problem in another world (created a new world, but with same mods) and just used creative to create a ritual to summon a janitor. I could change the mode without a problem. If you could help me figure out why I crash I would apreciate it. I dont neccessary want to start over.

**Comment by GaeaKat** [comment]
Are you able to attach a crash log?

**Comment by revan2811** [comment]
Here

[2024-03-20-1.log](https://github.com/klikli-dev/occultism/files/14668360/2024-03-20-1.log)

**Comment by klikli-dev** [comment]
The log does not contain a crash, but I suspect its the same as https://github.com/klikli-dev/occultism/issues/1103
I will close here and continue over in https://github.com/klikli-dev/occultism/issues/1103 as we have a log there
