### ISSUE TITLE
Book of Calling: Foliot Janitor Crash

### ISSUE THREAD

**Issue by includeFukari** [klikli-dev/occultism#1103]
**Describe the bug**
Book of Calling: Foliot Janitor UI is crashing the game.

**To Reproduce**
1. Right click Book of Calling: Foliot Janitor in the air in order to open the menu
2. Click mode button
3. Click area button
4. Game crashes

**Expected behavior**
I have never used the Janitor feature so I expect it to not crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.123.0
- OS: Windows 10
- Minecraft Version: 1.20.1 [forge: 1.20.1-47.2.0]
- Modpack Link and Version, or list of mods: 
automobility-0.4.2+1.20.1-forge.jar
blur-forge-3.1.1.jar
constructionwand-1.20.1-2.11.jar
curios-forge-5.7.2+1.20.1.jar
CuriosQuarkOBP-1.20.1-1.2.5.jar
embeddium-0.3.11+mc1.20.1.jar
FarmersDelight-1.20.1-1.2.4.jar
geckolib-forge-1.20.1-4.4.4.jar
Jade-1.20.1-forge-11.8.0.jar
jei-1.20.1-forge-15.3.0.4.jar
modonomicon-1.20.1-forge-1.62.0.jar
moonlight-1.20-2.11.9-forge.jar
musketmod-1.20.1-forge-1.4.8.jar
occultism-1.20.1-1.123.0.jar
oculus-mc1.20.1-1.6.15a.jar
Quark-4.0-439.jar
QuarkOddities-1.20.1.jar
SmartBrainLib-forge-1.20.1-1.13.jar
supplementaries-1.20-2.8.7.jar
tectonic-mod-1.19.3-v2.2.1.jar
Terralith_1.20.4_v2.4.11.jar
voicechat-forge-1.20.1-2.5.10.jar
XaerosWorldMap_1.38.1_Forge_1.20.jar
Xaeros_Minimap_24.0.3_Forge_1.20.jar
Zeta-1.0-14.jar

**Additional context**
none

**Comment by GaeaKat** [comment]
Are you able to supply a crash log?

**Comment by includeFukari** [comment]
Certainly, here is the log:
[latest.log](https://github.com/klikli-dev/occultism/files/14813274/latest.log)

**Comment by GaeaKat** [comment]
Is this server or single player? Sorry having difficulty reproducing the crash

**Comment by includeFukari** [comment]
Singleplayer

**Comment by klikli-dev** [comment]
@includeFukari 1.124.0 has a possible fix for this, please let me know if it persists.
Further, please let me know if you experience any other errors, the crash is caused by an edge case that minecraft to my knowledge should not allow ( the "handheld item" at least as reported to occultism differs from the book while the book is open ) in most scenarios. This could cause other issues with the book not working properly even if it does not crash

**Comment by includeFukari** [comment]
Updated to 1.124.0 but now it crashes after clicking the "Mode" button.

[latest.log](https://github.com/klikli-dev/occultism/files/14815954/latest.log)

**Comment by klikli-dev** [comment]
@includeFukari Thank you that actually confirms the real issue, will fix it in the next few minutes!
