### ISSUE TITLE
Dimensional mineshafts don't allow Djinni miners

### ISSUE THREAD

**Issue by theCalcaholic** [klikli-dev/occultism#1107]
**Describe the bug**
So if I understand how they *should* work, dimensional mineshafts are broken for me in two ways:

1. They don't produce ores. The progress bar will complete multiple times, but they won't output anything. Similar to #892 but without the broken recipes in JEI/REI (and on the latest version of Occultism). Also the durability of the ore miner doesn't reduce.
2. I cannot input the ore miners by hand, only with a hopper. When I drag a lamp into the slot, it won't allow me to drop it there, but putting a hopper on top of the mineshaft and inserting ore miners through that works.

**To Reproduce**
1. Place dimensional mineshaft
3. Right click and fail to insert ore miner by hand
4. Add hopper on top and insert ore miner through that
5. Observer no ores getting produced.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.124.3
- OS: Linux (Fedora, Server: debian)
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods:  [Valhelsia 6](https://www.curseforge.com/minecraft/modpacks/valhelsia-6) with a few manually added mods (among them occultism) - [full modlist](https://pastebin.com/2QwMYsRY)

**Additional context**

**EDIT:** I just noticed, that this behavior does only apply to Djinni miners for some reason - which are the only ones I had tried so far. Foliots, Afrits and Marids do work as expected. Am I missing something?

**Comment by klikli-dev** [comment]
The behaviour your describe indicates a recipe issue (I think hoppers bypass the "insert only if valid recipe" check).
Do you see any recipes for djinni miners?

**Comment by theCalcaholic** [comment]
@klikli-dev Interesting, I just noticed, that, according to REI, the Djinni ore miner has no tags, which sounds like it could be the issue - any idea what might cause this?

I suppose the mineshaft isn't accepting it, because it's missing the `#occultism:miners/ores` tag.

**Comment by GaeaKat** [comment]
Looked into this, it looks like it may have been missed when I added data-gen for tags
