### ISSUE TITLE
[1.20.4] [Neoforge] Were Ritual recipes removed from JEI screen?

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1113]
**Describe the bug**
I can't see the Ritual recipe on the JEI/EMI menu

**To Reproduce**
1. Left Click on a Ritual (Crushing ritual)

**Expected behavior**
When L-clicking on a Ritual icon on the JEI menu, it should open the menu to the bowl items and output screen. 
Like in 1.20.1 version

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/44974827/de8b024e-d8e6-410a-a399-92d70d7c7986)

**System (please complete the following information):**
- Occultism Version: occultism-1.20.4-neoforge-1.125.0
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: 
jei-1.20.4-neoforge-17.3.0.49
emi-1.1.4+1.20.4+neoforge
ImmersiveEngineering-1.20.4-11.1.0-172

**Additional context**
I recall that this used to work on 1.20.1

**Comment by klikli-dev** [comment]
@GaeaKat can you comment on the "happy path" of how that should work with EMI present?

Without EMI jei should show the rituals still (but haven't tested, may be bugged!)

**Comment by GaeaKat** [comment]
> @GaeaKat can you comment on the "happy path" of how that should work with EMI present?
> 
> Without EMI jei should show the rituals still (but haven't tested, may be bugged!)

I think I see the difference between EMI and JEI here, and I am currently working on fixing it

**Comment by ffuentesm** [comment]
> @GaeaKat can you comment on the "happy path" of how that should work with EMI present?
> 
> Without EMI jei should show the rituals still (but haven't tested, may be bugged!)


Updated and did not change anything. 
Well, is more that I can find the rituals on EMI, but the Ritual icons on the item list does not send me to the ritual page. 
 Video: https://github.com/klikli-dev/occultism/assets/44974827/7dbc3a38-6aeb-4c90-ba24-023a4bb6386f
