### ISSUE TITLE
Small QoL additions (Tags and Crafting recipes)

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1114]
First, I would suggest adding the #minecraft:bookshelve_books tag to the books added by Occultism (Tomes, Spirit Dictionary, etc) 
This would allow them to be added to the bookshelves, it would be great for map-making to hide these mod books to structures, that are not inside chests. 

Second, I noticed that a few updates ago, 3 new ways to get the third eye were added, Demon Seed, Demon Essence, and Otherworld Essence. Really nice, especially how you can get the luck effect from it. 
I just find it a bit convoluted that you can use either seed or fruit to make the demon essence. Why that? Just so you can use the surplus? 
![image](https://github.com/klikli-dev/occultism/assets/44974827/2fb040cb-8340-4753-b9d2-2fc302ca8113)

Maybe you could add the forge:seeds/datura to the Demon seed (only the fruit has the seed/datura tag), and make the Demon essence recipe using the tag: forge:seeds/datura instead of both items, this way you can use both the seed and the fruit to make the essence, they already do both and this form you can use the other if you have 1 fewer of the item to craft.
![image](https://github.com/klikli-dev/occultism/assets/44974827/cce258bf-4fe6-4dcb-bcc4-91a928b2b108)

Either that, or remove the 9xDemon Fruit-> Demon Essence, and make Demon Fruit -> Demon Seed

**Comment by klikli-dev** [comment]
Agreed on the shelves!

The demon fruit being in the seeds tag is a copy paste error, they should not be.
I think it is fine to have two separate recipes for fruit vs seeds instead of making a tag to create on recipe. 
The idea is indeed to use the seed surplus
