### ISSUE TITLE
(Modrinth Only) but the mod logo on a black png

### ISSUE THREAD

**Issue by OminousDiscovery** [klikli-dev/occultism#1118]
**Is your feature request related to a problem? Please describe.**
it looks bad on a gray background

**Describe the solution you'd like**
put the logo on a black background

**Additional context**

![image](https://github.com/klikli-dev/occultism/assets/150559423/ed40d301-20ce-4b6d-b909-6986ec0dbfbb)

**Comment by klikli-dev** [comment]
Looks like modrinth sets the background based on light/dark mode, on light mode it looks ok. 
I set a background manually
