### ISSUE TITLE
Ismenium is not highlighted.

### ISSUE THREAD

**Issue by Sokratis2233** [klikli-dev/occultism#1120]
**Describe the bug**

 I am currently playing the occultism mod and I believe I have ran into an issue while searching for Iesnium Ore in the nether. I have done everything the book tells me to along with the glasses and the infused pickaxe along with the rod which spots the ore however it does not seem to highlight the Iesnium. The rod goes full purple yet does nothing else after leading me to finding it the hard way possible by digging all the area around carefully.

**Expected behavior**
A clear and concise description of what you expected to happen

I was expecting that after the rod goes full purple for the ismenium to highlight itself yet it doesnt highlight anywhere. I waited for the animation to finish and before that I shift right clicked and marked ismenium ore in the rod successfuly. All the rituals seem to work fine and provide me the necesary materials.

**Screenshots**

I do not have any for the game doesnt seem to have any other additional errors rather than the lack of highlighting after the rod goes full

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.126.0
- OS: [e.g. Windows]: Windows 10
- Minecraft Version: 1.20
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/theboysmc

**Additional context**
-

**Comment by klikli-dev** [comment]
Excerpt from the discord FAQ: 

```
If theurgy is installed: The rod will shoot a particle effect towards the target block, instead of highlighting anything.

Otherwise, that may be an Nvidia vs AMD issue. Open occultism-client.toml in your instance's /config folder and set useAlternativeDivinationRodRenderer = true
```

In summary, try the setting or try theurgy (theurgy is pretty much guaranteed to work).
If issues remain please ping me in discord to discuss or here to reopen the issue
