### ISSUE TITLE
Help/Bug

### ISSUE THREAD

**Issue by Reaviik** [klikli-dev/occultism#1121]
**Describe the bug**
The bug consists of duplicating the Storage Actuator with the items inside

**To Reproduce**
1. Try placing the Storage Actuator next to a plot protected by the RedProtect Plugin (usually 2 edge blocks).
2. Note that it will drop 2 identical Storage Actuators

**Expected behavior**

**Screenshots**
[Video](https://www.youtube.com/watch?v=YRzCG80ANd8)
**System (please complete the following information):**
- Occultism Version: 1.125.0
- OS: Linux Host
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: [Curse](https://www.curseforge.com/minecraft/modpacks/infinity-nexus-reborn)

**Additional context**
This is a bit confusing, I don't know if the “error” is on the part of the mod or the plugin but I've contacted both, they're working on my server .-

**Comment by klikli-dev** [comment]
I am not familiar with how well plugins deal with block drops, but I suspect it may be due to the storage actuator not using loot tables. I will look into changing that!

**Comment by klikli-dev** [comment]
I will soon push a fix that will close this issue. If the problem remains, please ping me here to reopen it
