### ISSUE TITLE
Uphyxes Inverted Tower missing skull in visualisation

### ISSUE THREAD

**Issue by Sirfirelord1** [klikli-dev/occultism#1124]
**Describe the bug**
The ritual visualisation in-world is missing elements seemingly randomly based on how you move the mouse

**To Reproduce**
1. Select the ritual from the book
2. Select Visualisation mode
3. Anchor it
4. Fill in exactly as shown
5. See error when activating any ritual

**Expected behavior**
it should be correct

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/115722472/62baaee2-02bf-4399-b6e7-62d918be9581)
![image](https://github.com/klikli-dev/occultism/assets/115722472/2592d754-2eae-478e-aa49-d03c5b5d0544)
![image](https://github.com/klikli-dev/occultism/assets/115722472/90765f6a-50f0-4dff-8e65-9206442980a9)

**System (please complete the following information):**
- Occultism Version: 1.130.0
- OS: Windows 10
- Minecraft Version: 1.20.1, Forge 47.2.0
- Modpack Link and Version, or list of mods: 

**Additional Context**
from testing it seems like this happens with other rituals also

**Comment by klikli-dev** [comment]
That is a headscratcher, it does not reproduce for me:
![image](https://github.com/klikli-dev/occultism/assets/60774993/b0e56e47-ee39-42e3-838a-fc746f3ac3c6)

**Comment by klikli-dev** [comment]
Does this reproduce for you in:
1. a fresh world
2. with just occultism + required/optional dependencies?

**Comment by klikli-dev** [comment]
Closing this for now as not reproducible, please open a new issue or ping me here to reopen if it remains
