### ISSUE TITLE
Dimensional Mineshaft could produce minecraft:barrier items

### ISSUE THREAD

**Issue by YocyCraft** [klikli-dev/occultism#1129]
**Describe the bug**
As the title

**To Reproduce**
1. Place block 'Dimensional Mineshaft'
2. Put a Miner in it
3. It will produce barrier item occasionally

**Expected behavior**
Dimensional Mineshaft should not produce minecraft:barrier items

**Screenshots**
![2024-06-20_02 59 25](https://github.com/klikli-dev/occultism/assets/80801884/21b4518e-b8dc-412d-9e63-a5b5dcf98962)
![2024-06-20_02 59 31](https://github.com/klikli-dev/occultism/assets/80801884/2ed64387-50f9-48ad-bd54-eb48ac464590)

**System (please complete the following information):**
- Occultism Version: 1.133.0
- OS: Windows
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: [Enigmatica 10 (v1.0.1)](https://www.curseforge.com/minecraft/modpacks/enigmatica10/files/5441909)

**Additional context**

**Comment by ffuentesm** [comment]
Oh, I think that is because it is generating an item from a tag that does not exist, so it defaults to the barrier block.

In the image's case, it was generating an Aluminium Ore, but since there is no aluminum ore mod, it outputs the barrier.

**Comment by klikli-dev** [comment]
This is a known issue related to kubejs and occultism interactions, but it seems it cannot be fixed. 
You can prevent it by running /reload 
If you join discord the FAQ channel has a small kubejs script to automatically fix this on each world load

**Comment by YocyCraft** [comment]
> This is a known issue related to kubejs and occultism interactions, but it seems it cannot be fixed. You can prevent it by running /reload If you join discord the FAQ channel has a small kubejs script to automatically fix this on each world load

But kubejs is not in the modpack

**Comment by ffuentesm** [comment]
@YocyCraft is there any mod that adds blocks with those Ores tags? My understanding is that the Mineshaft is trying to generate that block, but since it's not available, it outputs a barrier. [More Metals II](https://www.curseforge.com/minecraft/mc-mods/more-metals-ii) adds aluminum, so I believe it would patch that problem at least.

**Comment by klikli-dev** [comment]
> > This is a known issue related to kubejs and occultism interactions, but it seems it cannot be fixed. You can prevent it by running /reload If you join discord the FAQ channel has a small kubejs script to automatically fix this on each world load
> 
> But kubejs is not in the modpack

That is a very important piece of info. So far we've only seen that with kubejs.

I have to investigate, it might be related to recipe conditions (namely, it's loading a recipe for an empty tag that it shouldn't.) I'll check!

**Comment by klikli-dev** [comment]
Recipe conditions were the culprit, should all be fixed now :)
