### ISSUE TITLE
[1.21] [Neoforge] Crash when trying to right-click raw ores on JEI/EMI.

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1130]
**Describe the bug**
When I right-click a raw ore/raw ore block/ore block item, instead of opening the crusher JEI/EMI tab, it crashes the game

**To Reproduce**
1. right-click on a ore item

**Expected behavior**
Should open the crusher JEI tab

**System (please complete the following information):**
- Occultism Version:  1.133.1
- OS: Windows
- Minecraft Version: 1.21

**Additional context**
[https://pastebin.com/DKACqHZP](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fDKACqHZP)

**Comment by klikli-dev** [comment]
Seems this same crash can happen for multiple reasons, see also https://github.com/EnigmaticaModpacks/Enigmatica10/issues/7#issuecomment-2183521580

I will look into this, probably some rendering update I missed
