### ISSUE TITLE
[1.21] [Neoforge] Missing Crusher recipe Blazerod 

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1131]
**Describe the bug**
The Blazerod to Blaze powder using a crusher daemon is missing 

**Expected behavior**
There should be a recipe output instead of a barrier block

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/44974827/28b4052a-12e7-4c67-a46e-b0b092d0a5c7)

**System (please complete the following information):**
Occultism Version: 1.133.2
OS: Windows
Minecraft Version: 1.21

**Comment by klikli-dev** [comment]
Hmm that indicates that the recipe exists but that blaze dust is not tagged as a dust. Maybe it is safe to just make the recipe output the item here, I'll check!
