### ISSUE TITLE
Tweaking the Demon Dream Essence recipe for better QoL 

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1133]
**Is your feature request related to a problem? Please describe.**
Fuse both fruit and seed recipes for the dream essence
![image](https://github.com/klikli-dev/occultism/assets/44974827/ed5ca1e1-0c34-4326-bfac-bdeb823f0254)

**Describe the solution you'd like**
This is the code for the new QoL recipe, you can make a list instead of two different recipes now in code. 
```
{
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "pattern": [
    "ppp",
    "ppp",
    "ppp"
  ],
  "key": {
    "p": [
      {
        "tag": "c:crops/datura"
      },
      {
        "tag": "c:seeds/datura"
      }
    ]
  },
  "result": {
    "id": "occultism:demons_dream_essence",
    "count": 1
  }
}
```

**Additional context**
This way you do not need to wait to grow more fruit if you are just one or two items shy from crafting. You can now use your surplus interchangeably. 
So is either this or a fruit-to-seed recipe to convert your fruit surplus into seeds.

**Comment by klikli-dev** [comment]
Oh that is a beautiful solution, thank you! Will add that ASAP
