### ISSUE TITLE
[1.20.1] Crusher spirit gives up barriers

### ISSUE THREAD

**Issue by sanik** [klikli-dev/occultism#1135]
**Describe the bug**
Crusher spirit gives up barriers when crushing various materials such as gold

**To Reproduce**
Video: https://centurymine.net/6627053996697.mp4

**Expected behavior**
Obviously from the video above

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.131.1.jar
- OS: Windows 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
Inside mods: (3) -> [minecraft, forge, mohist]
Client-only mods: (2) -> [textrues_embeddium_options, mythicbotany]
Server-only mods: (0) -> []
All mods: (78) -> [smartbrainlib, cyclopscore, rhino, blue_skies, geckolib, sophisticatedstorage, productivelib, cmfixed, sophisticatedcore, cmcore, waystones, structory, placebo, citadel, naturescompass, artifacts, evilcraft, evilcraftcompat, cmsync, libx, cmworld, mixinextras, sophisticatedbackpacks, apotheosis, iceandfire, balm, cmbukkit, cloth_config, forge, mohist, twilightforest, structure_gel, mythicbotany, minecraft, voicechat, terrablender, biomesoplenty, jade, structurecompass, timeout_fixes, cmhelper, forbidden_arcanus, spectrelib, botania, roughlyenoughitems, cmapi, curios, ars_nouveau, patchouli, polymorph, ars_elemental, attributeslib, modonomicon, constructionwand, architectury, kubejs, ftblibrary, itemfilters, ftbteams, ftbquests, ftbxmodcompat, vampirism, teamlapenlib, vampirism_integrations, vampiresneedumbrellas, werewolves, godly_vampirism, lootr, occultism, ars_ocultas, productivebees, cmmisc, textrues_embeddium_options, reeses_sodium_options, t_and_t, expandability, valhelsia_core, cristellib]

**Comment by klikli-dev** [comment]
@sanik 

This is a common issue with certain kubejs setups. Can you try to run /reload to see if it fixes it?

If so, please join discord, the FAQ channel has a kubejs script to automate this for you on each load.

**Comment by sanik** [comment]
@klikli-dev It worked in the logs and showed this: https://pastes.dev/4GHoKcpjF1 but everything worked! You can send a link to the message in the Discord to automate the fix and also ping when and if there is a normal solution!

**Comment by klikli-dev** [comment]
https://discord.com/channels/688406873392676924/809433052233203713/1193462194541711390

A permanent fix is not expected currently as we've been unable to trace down the exact reason and it doesn't reproduce in the dev environment. But the fix is without any big side effects :)

**Comment by shobu13** [comment]
Hello, can you provide a snippet of this script or update your discord invitation link please ?
 cheers :)
