### ISSUE TITLE
Crushing recipes appear to be missing entries

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1140]
**Describe the bug**
Noticed that there's no gold dust recipe, for example, so I went to look at what the Crusher can do and this is it:

![image](https://github.com/klikli-dev/occultism/assets/9543430/97bb5fa1-c26d-4b5d-a30b-44c558f91ea4)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.134.4
- OS: Windows
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: Enigmatica 10 in-dev

**Additional context**
Latest log: https://gist.github.com/MuteTiefling/1228fb547f8db4358b380a0e8ff9c18d

**Comment by ffuentesm** [comment]
I think that is your Modpack changing the recipes, since on my game I can see the crushed Gold 
![image](https://github.com/klikli-dev/occultism/assets/44974827/e2f1baf5-d7d4-4370-b77f-1b17def1aa34)

**Comment by MuteTiefling** [comment]
We haven't implemented any recipe changes to the crusher.

**Comment by klikli-dev** [comment]
This seems to be the same problem as https://github.com/klikli-dev/theurgy/issues/193, which is a kubeJS issue that should be fixed in latest. Please ping me to reopen if that is not the case
