### ISSUE TITLE
[1.21] [Neoforge] Left click on Pentacle does not open Ritual Tab on EMI

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1141]
**Describe the bug**
Left clicking on a pentacle on EMI should open the ritual tab that creates that Pentacle. Showing the sacrificial items and type of circle it requires. 

**To Reproduce**
1. Left Click on a Pentacle on EMI menu.

**Expected behavior**
Left click should open the Ritual recipe tab for the Pentacle. Right click should open a tab if that pentacle has a function (e.i. Crushers)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.134.4
- OS: Windows
- Minecraft Version: 1.21

**Comment by MuteTiefling** [comment]
Noticing the same here. Makes it hard to get to any of the rituals that only summon an entity, like the Crushers.

**Comment by MuteTiefling** [comment]
Might be related, but EMI is also showing the wrong ritual dummy associated with some rituals. 

Infused Pickaxe is showing this, for example: 
![image](https://github.com/klikli-dev/occultism/assets/9543430/710bf8a3-cf59-427c-8bc9-6a13cd3194ac)
