### ISSUE TITLE
Server crash when inserting items into storage container

### ISSUE THREAD

**Issue by ImAK9** [klikli-dev/occultism#1143]
**Describe the bug**
Crashing server when in this case, inserting golden swords and axes into the storage container.

**Expected behavior**
I guess not to crash.

**System (please complete the following information):**
- Occultism Version:  **1.134.6**
- OS: **Linux**
- Minecraft Version: **1.21**
- Modpack Link: **[Craftoria](https://legacy.curseforge.com/minecraft/modpacks/craftoria/files/5505036)**

**Additional context**
This may as well be a modpack issue itself, I havent had the time to test this myself as it was reported by a user but I should be able to later this weekend if needing further investigasion.

**Comment by klikli-dev** [comment]
@ImAK9 can you please provide a crash log? 

EDIT: All good, I managed to reproduce it. I just needed an item with a data component / nbt.
