### ISSUE TITLE
[1.21 NeoForge] Duplicating items in Dimensional Storage

### ISSUE THREAD

**Issue by ptlthg** [klikli-dev/occultism#1144]
**Describe the bug**
Shift clicking items out of the crafting GUI in dimensional storage gives you the resulting craft, but doesn't cost any items and leaves them in the table.

**To Reproduce**
1. Put a crafting recipe in the dimensional storage grid
2. Shift click the resulting item out to craft it
3. Observe that no items were consumed

**Expected behavior**
Crafting things should cost items

**Screenshots**

https://github.com/klikli-dev/occultism/assets/24925519/93a250ea-90ee-4ac2-b289-827c989cd844

**System (please complete the following information):**
- Occultism Version: 1.134.6
- OS: Linux
- Minecraft Version: 1.21
- Modpack Link: [Craftoria](https://legacy.curseforge.com/minecraft/modpacks/craftoria/files/5505036)

**Comment by klikli-dev** [comment]
@ptlthg thank you, good find! It seems it only works in certain conditions (e.g. I tried it with crafting wooden planks and it did not "work"), let's see what is going on here ...
