### ISSUE TITLE
Divination Rod doesn't display the white box around the Iesnium ore when bound to it. (AMD Graphics Card)

### ISSUE THREAD

**Issue by Pilpoh** [klikli-dev/occultism#1149]
**Describe the bug**
Divination Rod doesn't display the white box around the Iesnium ore when bound to it. The divination rod is bound to netherrack and can be charged but when charged it doesn't display the white box wall hacks around the ore.

**To Reproduce**
1. Create a Divination Rod.
2. Shift + Right click some Netherrack.
3. Hold right click on the Divination Rod.
4. No white box appears.

**Expected behavior**
When a Divination Rod is bound to iesnium ore and is charged, it should show a white box around the nearest iesnium ore.

**Screenshots**
![CrimsonDawn](https://github.com/klikli-dev/occultism/assets/9051878/093af6b3-238c-4cdf-9bd9-36903a252e2a)
This is what it should show but it doesn't for me!

**System (please complete the following information):**
- Occultism Version: 1.135.0.jar
- OS: Windows
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: ATM 10 (v 0.9)

**Additional context**
I have an AMD graphics card (AMD Radeon RX 6700 XT)

**Comment by klikli-dev** [comment]
This is sadly expected behaviour on amd cards.
The config file in your modpack, occultism-client.toml, contains a setting to use the alternative renderer which works on amd.

Alternatively you can install theurgy alongside, in which case a particle effect will shoot towards the target block.

**Comment by Pilpoh** [comment]
Cracking! Thanks KliKli! I'll probably go change the render :) Thanks for the quick response!

**Comment by Moot-a** [comment]
This doesn't exist in the 1.18.2-1.84.0 version of the mod, I'm stuck in my progression in Ragnamod VII because of this.
