### ISSUE TITLE
Add empty book of calling recipe

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#115]
**Is your feature request related to a problem? Please describe.**
currently if you accidentally delete or lose your book of calling, you have no way to make a replacement other than summoning a new spirit and taking its book

**Describe the solution you'd like**
Add a recipe for an empty book of calling

**Comment by theboo** [comment]
took me this long to finally test it, but the book of calling we can craft doesnt seem to work... i shift right click to bind, it says it bound, but then it just tells me to shift right click to bind again.. 

screenshots:
https://i.imgur.com/wzeMbUt.png
https://i.imgur.com/oR3VYrd.png

**Comment by klikli-dev** [comment]
Will address this in https://github.com/klikli-dev/occultism/issues/148 for proper changelog generation
