### ISSUE TITLE
Are the seeds suppose to work this way?

### ISSUE THREAD

**Issue by Zurain21** [klikli-dev/occultism#1150]
Not sure if intended but you can eat demon dream seeds as if it was the fruit. Can also replace all the demon dream fruit in the Demon Essence recipe

Would not expect not to be able to eat the seeds.

- Occultism Version: 1.135.0
- OS: Windows 11
- Minecraft Version:1.21
- Modpack Link and Version, or list of mods: All The Mods 10, Also All the Mods 9

**Comment by ffuentesm** [comment]
I also would not expect to eat the seeds, but the seeds and fruits are interchangeable in the Demon Essence recipe so you can spend your surplus on both items.

**Comment by klikli-dev** [comment]
yeah they should not be edible, but the recipe is intentional.
I probably messed something up when updating to 1.21
