### ISSUE TITLE
Incompatibility with Resourceful Chickens Mod

### ISSUE THREAD

**Issue by Echoframe** [klikli-dev/occultism#1151]
**Describe the bug**
The mod Resourceful Chickens forces all chickens to become resource chickens instead, making them no longer recognized as chickens (why this happens, i have no clue). The result is that the resource chickens are not a valid sacrifice for the rituals. **Only chickens are affected.**

**To Reproduce**
1. Have Resource Chickens Mod along Occultism
2. Start any ritual using forge:chickens
3. Sacrifice won't recognize the dead mob

**Expected behavior**
The ritual progresses and summons whatever it should summon.

**Screenshots**
Wouldn't make sense.

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.132.1
- OS: Win11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: (Curseforge) TNP Limitless 7 *+ Resource Chickens-1.20.1-2.6beta1*

**Additional context**
I changed the recipies to use cows instead as a workaround.

**Comment by klikli-dev** [comment]
@Echoframe thanks for reporting!
The reason for this is that resource chickens likely do not have the chicken tag, or occultism and RC use different chicken tags (there was some discussion about using "wrong" plurals such as "c:chickens" to enforce plural tags to end with s).

Can you open an issue with resource chickens to inquire about their tags and link here? 
It seems the mod is not open source, so I cannot look myself
