### ISSUE TITLE
Familiar ring

### ISSUE THREAD

**Issue by L0wki3** [klikli-dev/occultism#1153]
The familiar doesn’t show in the JEI and once crafted won’t let the familiar go in it.

- Occultism Version: 1.21

- Minecraft Version: 1.21

**Comment by klikli-dev** [comment]
This is currently expected behaviour until there is a clear successor for Curios, the mod that powered the familiar ring.
At this point there are a few competing standards, and implementing one may lead to compatibility problems in packs that already has the other
