### ISSUE TITLE
Chimera Familiar Model prevents player from seeing things. 

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1157]
**Is your feature request related to a problem? Please describe.**
Unlike a house or camel mount, the model of the chimera blocks the player's view
![image](https://github.com/user-attachments/assets/bbaf22b0-b8db-4a51-b60d-6d75a9f925d6)

**Describe the solution you'd like**
Either change the model so it does not obstruct the player's view.
Make the part of the model that is blocking the player invisible. 
Or prevent first person when the player is mounted.

**Comment by klikli-dev** [comment]
Ok that is odd .. do you know if that happened < 1.21 as well and nobody reported it, or if it is new?

**Comment by klikli-dev** [comment]
Ohhh I see the scale got messed up I think it did not used to be so big
