### ISSUE TITLE
[1.21][neoforge] Chimera phase into half of a block when sitting preventing any interaction

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1158]
**Describe the bug**
It seems that the collision of the chimera when sitting is not working properly. So it stays halfway inside the block where it should be sitting. 
I tried removing the blocks underneath, but it fell and stopped half inside the next block below it. 

**To Reproduce**
1. summon a chimera
2. Right click to have it sit it

**Expected behavior**
The chimera should be on the block, not inside the block. 

**Screenshots**
![image](https://github.com/user-attachments/assets/df6f94f5-25fa-4fe9-9b4b-82c9e330de63)
![image](https://github.com/user-attachments/assets/22ed3ad6-d765-413f-a5c4-9bb972277919)

**System (please complete the following information):**
- Occultism Version: 1.136.5
- OS: Windows
- Minecraft Version: 1.21

**Comment by klikli-dev** [comment]
uhh .. I have to look into that more. I think in 1.21 minecraft incorporates scale into entities (before it mostly ignored it) which seems to cause all these issues
