### ISSUE TITLE
[Mod Compatibility] Apotheosis weird behavior with soul gem

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#116]
**Describe the bug**
After picking up named mobs from Apotheosis, when you place the mob back down it teleports to its original location. Tested with IF mob imprisonment tool right after and it picks up/places as expected

**To Reproduce**
1. pick up apo boss mob
2. go somewhere
3.place it back down
4. watch it yeet away

**Expected behavior**
it should either place where intended or not be able to pick them up at all

**Screenshots**
https://gyazo.com/82d1e6fbfde4ddd19ebb5b2c79c9f6d3

**System (please complete the following information):**
- Occultism Version: 1.0.5
- OS: [e.g. Windows] windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: enigmatica 6 dev build

**Comment by klikli-dev** [comment]
Hello darkness my old friend :D
That's a returning bug, in 1.15 it was fixed by removing position from the entity nbt before spawning - seems 1.16 changed this a bit, but I think I know how to properly work around it
