### ISSUE TITLE
Cannot summon the possessed elder guardian in ATM10 0.14

### ISSUE THREAD

**Issue by Sage027** [klikli-dev/occultism#1160]
Cannot summon the possessed elder guardian in ATM10 0.14

the sacrifice is not the elder guardian instead of a normal elder guardian so i can't summon him. the name of the sacrifice now is (see the image) or ritual.occultism.sacrifice.elder_guardian

![image](https://github.com/user-attachments/assets/add6b8b8-fcc5-4519-b3f0-dcf49a567f89)

**Comment by ffuentesm** [comment]
You need to update to the newest version. 
![image](https://github.com/user-attachments/assets/5821865a-9d4c-4155-91af-1eb54a8682a3)
![image](https://github.com/user-attachments/assets/8fd299c2-4269-46e7-a50e-15756c787476)
