### ISSUE TITLE
Foliots teleport to me when I use waystones

### ISSUE THREAD

**Issue by F7albert-tech** [klikli-dev/occultism#1162]
**Describe the bug**
I have three Foliots workin in my base a crusher, a janitor and a transporter. When I teleport using a waystone they teleport where I go.

**To Reproduce**
1. Place foliots in my base and give them a job.
2. Use a waystone to teleport to other place

**Expected behavior**
The foliot stay where I leave them

**Screenshots**
![2024-07-20_11 31 59](https://github.com/user-attachments/assets/29b74b98-4993-4797-a195-c7c36a69bc3d)
![2024-07-20_11 32 35](https://github.com/user-attachments/assets/f6aca28a-95fb-4441-b1cc-cb31fe132872)

**System (please complete the following information):**
- Occultism Version: 1.136.5
- OS: Windows 11
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: All the mods 10-0.16

**Additional context**
👯‍♂️

**Comment by klikli-dev** [comment]
I think that is because they are based on tamed animals .. I have to check if that can be disabled. 
Does this also happen when you teleport using an in-game command? @F7albert-tech

**Comment by F7albert-tech** [comment]
No, I don´t have that issue. It apear only with overworld waystones.

**Comment by ffuentesm** [comment]
The only thing that teleport to me are familiars and Demonic partner. Which is what I expect to happen .
