### ISSUE TITLE
Storage Controller being wiped.

### ISSUE THREAD

**Issue by WhitePhant0m** [klikli-dev/occultism#1163]
**Describe the bug**
Storage Controllers lose all their contents if an item they had stored in them no longer exists.

**To Reproduce**
1. Add items into a storage controller from some mod, and some vanilla items as well
2. Remove said mod
3. Notice how storage controller is completely empty

**Expected behavior**
Storage controller not wiping when the item ceases to exist.

**System (please complete the following information):**
- Occultism Version: 1.136.5
- OS: [e.g. Windows] Win11
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: [Craftoria](https://www.curseforge.com/minecraft/modpacks/craftoria) 0.4.0
I replicated this by putting vanilla items in, and some hammers from Just Hammers, and removing the mod.

**Additional context**

[Error from logs](https://mclo.gs/eIiYp3r#L1323).

**Comment by klikli-dev** [comment]
Oh crap .. I am using the codecs to serialize the entire inventory .. I suppose they do not have handling for missing items. I'll have to ask the neo people if they add something for that
