### ISSUE TITLE
[1.21][Neoforge] Demonic Partner not working

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1165]
**Describe the bug**
I am right clicking on her with a stack of raw chicken and nothing happens 

**Expected behavior**
It should cook the chicken

**Screenshots**
 
![image](https://github.com/user-attachments/assets/43a04f36-d821-4d2e-9d4b-dc4cb2ad85b9)

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.136.5
- OS:  Windows 
- Minecraft Version: 1.21

**Comment by klikli-dev** [comment]
@ffuentesm thanks for reporting!
Turns out its another one of the recipe datagen errors (the spirit spawns, but is not tamed).
After the fix is pushed a new one will have to be summoned (or maybe there is a command to tame a target entity?)
