### ISSUE TITLE
Chimera Familiar Bug

### ISSUE THREAD

**Issue by GiornoGiovanna01** [klikli-dev/occultism#1178]
**Describe the bug**
Chimera familiar does not pathfind to enemies.
**To Reproduce**
1. Spawn in the Chimera Familiar.
2. Hit or get hit by a mob.
3. Chimera does not pathfind correctly and walks sideways until it hits something
**Expected behavior**
The chimera should pathfind to mobs.
**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.132.2
- OS: [e.g. Windows] Windows 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: SmartBrainLib, Patchouli, Occultism, Modonomicon, GeckoLib and Curios API, all of them are updated to the latest version as of writing this.

**Additional context**
https://medal.tv/games/minecraft/clips/io47VIecYALVZjRmG/d13379rAImE8?invite=cr-MSxQQW8sMTk2Mzg3Njc4LA
Video that demonstrates the bug.

**Comment by klikli-dev** [comment]
@GiornoGiovanna01 I think you found something broken pretty badly in the Chimera's AI. Apparently MC updates changed how certain things work .. I need to investigate. Thank you for reporting!
