### ISSUE TITLE
[1.21][Neoforge] Shift Click on crafting result gets a unnamed bound book

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1179]
Neoforge: 21.0.148 
occultism-1.21-neoforge-1.143.1

If I shift and click when binding a book. I get a "Not yet Know" result
![image](https://github.com/user-attachments/assets/5d1e6f99-63de-454d-a601-83042c333733)
![image](https://github.com/user-attachments/assets/de2a805f-6235-4a73-80db-089915622793)

**Comment by klikli-dev** [comment]
@ffuentesm apparently (according to neo discord) this is a vanilla bug (that onCraftedBy is not called when quick crafting). There seems to be a mod that fixes it - someone suggested that fastworkbench does that, although I believe you already tried with that installed, right?

**Comment by klikli-dev** [comment]
I *think* I found a way to work around it without causing the EMI/JEI issues.
Will push it soon, please let me know if it causes other issues with the names
