### ISSUE TITLE
possibility on how to make rituals datapack-able

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#118]
the ritual would consist of 2 parts:
a separate files would be able to describe the pattern of marking and items, similar to how the vnilla crafting shaped does it but on a much bigger scale, which would allow for other mod items to be used too. 
This would then be assigned an id in the botttom.

and that id could be used with ritual type recipe in a recipe.json
then there would the ability to have the ability to sacrifice an entity, since the item use would be harde but possibly flint and steel could be built into it as true/false.
where items  that are required will be added and the output would be an item or entity, possibly both

would allow for flexibility and potencial infitity of new patterns

**Comment by klikli-dev** [comment]
Note for anyone passing by: While rituals are not fully datapack-able currently, you can modify ritual ingredients via the https://github.com/klikli-dev/occultism/tree/master/src/main/resources/data/occultism/recipes/ritual_ingredients recipes. 
You should adjust the corresponding guide book pages in https://github.com/klikli-dev/occultism/tree/master/src/main/resources/data/occultism/patchouli_books/dictionary_of_spirits/en_us/entries/rituals.

**Comment by klikli-dev** [comment]
Closed in favor of omnibus ticket: https://github.com/klikli-dev/occultism/issues/319
