### ISSUE TITLE
ATM9 to the sky THE MARID CRUSHER Achievement Bug

### ISSUE THREAD

**Issue by olaquiensoy** [klikli-dev/occultism#1181]
In ATM9 to the Sky i am following the questbook of All the Mods 9 for Occultism and one Achievement is "The Marid Crusher" which i successfully did (the demon spawned). But after successfully summoning the Demon i saw that i didnt get the Achievement in the ATM9 book, which prevents me from goint further with the mod. I Summoned it again but still no success with the Achievement.

**To Reproduce**
1. Create Block of Iesnium
2. Create Book of Binding: Marid (Bound) "can be used to summon the marid Holmurkyr" (i'ts the green book)
3. Create Block of Diamond
4. Create Emerald Block
5. Create the Ritual "Fatmas's Incentivized Attraction" by using the right colours of chalk, candles and mob heads like in the discription
6. Placing Iesnium Block, Diamond Block, Emerald Block and ghast tear in the Sacrificial Bowls
7. Placing Book of Binding: Marid (Bound) in the Golden Sacrificial Bowls
8. Waiting for Demon to Spawn

**Expected behavior**
Demon Spawned successfully which can crush ores and giving me 6x the dust. But not getting the achievement in ATM9 

**Screenshots**
![Occultism](https://github.com/user-attachments/assets/54390284-76be-4bdc-b74f-3eda45f5cd81)

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.132.2
- OS: Windows
- Minecraft Version: Minecraft Forge 1.20.1
- Forge Version: 47.2.20
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky

I think The Problem is that the Book that i should be using says below "Can be used to summon the marid Aldmyld" But when i look for the same green book it only shows me the one that says below " Can be used to summon the marid Lukrondthyre" See pictures below:
![image](https://github.com/user-attachments/assets/35dd8292-8221-40af-94c9-65f4af6329c5)
![image](https://github.com/user-attachments/assets/5dbdffc2-0dcc-4dbc-85ef-356964cb72fb)

**Comment by klikli-dev** [comment]
@olaquiensoy I just tested, the advancement for marid miners exists (albeit hidden to the player) and gets unlocked.

Have you reported this to the ATM team? Maybe there is a typo in the quest and it is listening to the wrong advancement?
If not please report this as a bug on their end and maybe ping me in the issue so I can talk with them in case it is something on my end after all.

The name of the marid is not relevant, that is just "eye candy" and not counted in the advancement

**Comment by klikli-dev** [comment]
Closed as stale
