### ISSUE TITLE
A duplication glitch

### ISSUE THREAD

**Issue by DemonGal6** [klikli-dev/occultism#1184]
The other day someone in my community reported a duplication glitch in the mod by having 2 flames next to each other.

https://www.curseforge.com/minecraft/modpacks/demons-tech-magic-and-superheroes

That is a link to my modpack, unfortunately I can’t give more information about the glitch as of right now due to the one finding the glitch being either busy or asleep. I will provide more information once they are online and I can get the specifics out of them.

**Comment by klikli-dev** [comment]
@DemonGal6 thank you, good find! I managed to reproduce and fix it!

**Comment by DemonGal6** [comment]
That’s good, I’m glad we could help.

**Comment by klikli-dev** [comment]
Closed in 981943b39a16b3054903e2f0986b0263bc8e1a48 and 3b879e430b415f7ed952614b2b36ae286d7d7465
