### ISSUE TITLE
Marid Crusher pentacle inconsistency 

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#1189]
**Describe the bug**
The dictionary of spirits tells you to use fatma's pentacle to summon the marid crusher, the recipe viewers say to use abras open conjure. Fatma's does not work, abras does.

**To Reproduce**
1. Look at marid recipe in book
2. Look at marid recipe in recipe viewer
**Expected behavior**
Both sources should be the same and correct 

**System (please complete the following information):**
- Occultism Version: 1.1.0
- OS: [e.g. Windows]
- Minecraft Version:1.21
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/enigmatica10/files/5608507

**Comment by klikli-dev** [comment]
@theboo that is so spooky, I just checked in my dev setup and there both show abras conjure:

![image](https://github.com/user-attachments/assets/9463e805-be96-411a-8a34-d8d73d649f65)

I will download E10 and compare

**Comment by klikli-dev** [comment]
@theboo can you verify if this issue persists for you?
I just downloaded E10 in curse (1.8.0) and I do not have the issue:

![image](https://github.com/user-attachments/assets/11d551c3-bb78-4851-9d61-175909f4a4ef)

**Comment by theboo** [comment]
Shenanigans are afoot! The reason I didn't make an issue at first and asked if anyone was available to test is cuz I never tested it myself personally haha, was reported in our discord... I might get a chance this weekend to load up a world, been wanting to anyway.

**Comment by klikli-dev** [comment]
@theboo all good! It seems the issue was that the wrong pentacle was in the recipe (afrit instead of marid pentacle). Not sure where the person reporting it got a discrepancy in displays from, but they may just have remembered the right one.

https://github.com/klikli-dev/occultism/pull/1190 fixes this
