### ISSUE TITLE
EMI Rendering crash when looking up recipe uses for resources [Neoforge 1.20.1]  

### ISSUE THREAD

**Issue by novaisadumbass** [klikli-dev/occultism#1191]
**Describe the bug**
When looking up recipes in EMI involving resources such as iron ingots, ores, game crashes.

Install occultism + pedendencies as well as EMI on latest neoforge 1.20.1
Press U on an iron ingot in creative inventory

**Expected behavior**
Recipes load correctly.

- Occultism Version:  latest
- OS: Windows 11

**Additional context**
From the crash logs it appears to be a rendering issue regarding spirit miners, logs are attached. 
[crash-2024-08-16_18.26.04-client.txt](https://github.com/user-attachments/files/16639355/crash-2024-08-16_18.26.04-client.txt)

**Comment by klikli-dev** [comment]
@novaisadumbass Please install the correct version of SmartBrainLib. As you say you are on Neo, you likely have the Forge version installed (Curseforge Launcher sometimes chooses the wrong one). If you remove it and place the right one you will no longer crash.

**Comment by novaisadumbass** [comment]
That indeed was the issue! Thank you for the help :)
