### ISSUE TITLE
Crash or Freeze upon first foliot ore crusher summoning

### ISSUE THREAD

**Issue by koboldDelegate** [klikli-dev/occultism#1194]
**Describe the bug**
When summoning the first foliot ore crusher as described in the book, game either crashes or freezes.

**To Reproduce**
1. Set up summoning on top of ice, with planks under the candles (unsure if the material is influencing anything)
2. Place the 4 ores
3. Ores are consumed
4. Text "Summoned foliot ore crusher successfully" appears
5. Game either crashes or freezes

**Screenshots**
![image](https://github.com/user-attachments/assets/86dac76f-c826-4f27-a6a6-b8d67412d928)

**System:**
- Occultism Version: 1.136.1
- OS: Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
- Ars Nouveau [4.12.4]
Just Enough Professions (JEP) [3.0.1]
Patchouli [1.20.1-84-FORGE]
GeckoLib 4 [4.4.7]
Ars Creo [4.1.0]
Create [0.5.1.f]
Just Enough Resources [1.4.0.247]
Architect's Palette [1.3.6.1]
Curios API [5.9.1+1.20.1]
Modonomicon [1.74.1]
Xaero's Minimap [24.2.0]
Create Crafts & Additions [1.20.1-1.2.4d]
SmartBrainLib [1.14.2]
Ars Ocultas [1.2.2]
Just Enough Items [15.12.3.54]
Create Deco [2.0.2-1.20.1-forge]
Sophisticated Core [0.6.22.611]
Xaero's World Map [1.38.8]
Sophisticated Backpacks [3.20.5.1044]
Create: Steam 'n' Rails [1.6.4+forge-mc1.20.1]
Occultism [1.136.1]

**Additional context**
Using NeoForge 47.1.106

[crash-2024-08-18_16.06.52-server.txt](https://github.com/user-attachments/files/16651907/crash-2024-08-18_16.06.52-server.txt)

**Comment by klikli-dev** [comment]
@koboldDelegate this is only indirectly related to occultism, it's actually a problem of the modpack/launcher. Please see https://github.com/klikli-dev/occultism/issues/1139#issuecomment-2199235469
