### ISSUE TITLE
[1.21.1][Neoforge] Crash when using the Ritual circle preview

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1195]
**Describe the bug**
using the circle preview causes the game to crash after a few seconds of the preview rendering 

**To Reproduce**
1. open a ritual circle preview on the spirit dictionary

**Expected behavior**
the game should not crash

**System (please complete the following information):**
- Occultism Version: occultism-1.21.1-neoforge-1.152.0.jar 
- OS: Windows
- Minecraft Version: 1.21.1

**Additional context**
Log: https://hastebin.com/share/tiqezirera.php

**Comment by klikli-dev** [comment]
Fixed in [dafd1cf94c93182da7be795541c6ec879040c14d](https://github.com/klikli-dev/modonomicon/commit/dafd1cf94c93182da7be795541c6ec879040c14d)
