### ISSUE TITLE
Crash when viewing pentacle preview

### ISSUE THREAD

**Issue by Leonxilofin** [klikli-dev/occultism#1196]
**Describe the bug**
When trying to view the pentacle preview for Ophyx' Calling the game crashes

**To Reproduce**
1. Open Dictionary of Spirits
2. Navigate to the pentacles
3. Go to Ophyx' Calling
4. Press the preview ritual eye

**Expected behavior**
No crash

**Screenshots**
N/A

**System (please complete the following information):**
- Occultism Version: occultism-1.21-neoforge-1.148.0
- OS: Windows 11
- Minecraft Version: Neoforge 1.21.1
- Modpack Link and Version, or list of mods:  https://www.curseforge.com/minecraft/modpacks/craftoria Ver. 0.8.0

**Additional context**
If I had to guess...its probably all rituals that involve a skull since I've tried other rituals and they worked just fine.
[crash-2024-08-18_19.06.15-client.txt](https://github.com/user-attachments/files/16707597/crash-2024-08-18_19.06.15-client.txt)

**Comment by klikli-dev** [comment]
Please update modonomicon to v1.100.2, it fixes this crash
