### ISSUE TITLE
Spirit name still being random even after you name dictionary of spirits

### ISSUE THREAD

**Issue by oncer56** [klikli-dev/occultism#1198]
**Describe the bug**
Spirit name will remain random even after you name the dictionary of spirits in a anvil wich from my understanding should't be the case

**To Reproduce**
1. name dictionary of spirits in an avill (example:jeff)
2. combine the named dictionary of spirits in a crafting with any unbound binding book (example:book of binding foliot)
3. you will see that the crafting output to will say that the outputed bound book is spose to have a spirt name that is the same as the name of the dictionary of spirits (example:jeff)
4. craft the bound book
5. look at the spirit name it will still have been randomised

**Expected behavior**
the bound books spirit name is the same as the name of the dictionary of spirits (example:jeff)

**System (please complete the following information):**
- Occultism Version: 1.136.1
- OS: Windows
- Minecraft Version: 1.20.1
- list of mods: 
- architecture 9.2.14
- cupboard 2.7
- curios 5.9.1
- embeddium 0.3.30
- geckolib 4.4.7
- gpumemleakfix 1.8
- jei 15.12.2.51
- kubejs 2001.6.5-build.14
- memorysettings 5.5
- modonomicon 1.74.1
- occultism 1.136.1
- probejs 6.0.1
- rhino 2001.2.3-build.6
- saturn 0.1.3
- SmartBrainLib 1.15
- smoothboot(reloaded) 0.0.4

**Additional context**
needed for a modpack

**Comment by klikli-dev** [comment]
An initial test does not reproduce this (the resulting book has the same name as the renamed dictionary), I will test further to see if I can repro it.

@oncer56 is this in SP or on a server?

**Comment by klikli-dev** [comment]
I did a quick test in ATM 10 and could not reproduce the issue there either, does it still happen for you on latest occultism?

**Comment by oncer56** [comment]
its SP. 
after testing it, it works fine on the 1.21.1 version.
also tested it with just occultism and its dependecies on the 1.136.2 version of occultism and the name is still random even after i name the  dictionary of spirits so it does not look like comptibilty issue

**Comment by klikli-dev** [comment]
Mea culpa - I overlooked that the issue was on 1.20.1
Will test there!

**Comment by oncer56** [comment]
thank you for the fix
