### ISSUE TITLE
Curio support for current items and possible suggestions.

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#120]
Changing this to be a list of possible curios to keep it in one spot. If anyone has any other curio ideas, post them here and ill add them to the list.

- [ ] Unsurprisingly Large Satchel- Body slot (will need a keybind added to open the satchel.)
- [ ] Otherworld Goggles- Head slot

**Comment by klikli-dev** [comment]
That's a good idea - for now I'll icebox it, but if/when I add other curious I'll add it for the satchel as well.
