### ISSUE TITLE
Possessed Elder Guardian sacrifice not working Direwolf20 1.20

### ISSUE THREAD

**Issue by notsome1else** [klikli-dev/occultism#1203]
**Describe the bug**
Iam trying to spawn a possessed elder guarding using the ritual. I have everything set up, the gray particles start spawning and but i cant sacrifice a fish
I tried:
Putting raw cod/salmon in sacrificial bowl
drop raw cod/salmon
move tuna/guardian/elder guardian/dolphin using mob imprisonment tool into the circle and killing it 
I updated the version from 1.104 which was installed by the ftb launcher  beccause i thought it might gget fixed by #1042 or #1043 

Nothing works, maybe iam missing something, this is my first time using occultism but i could not find any information on that specific ritual

**Expected behavior**
A possessed elder guardian should spawn

**Screenshots**
![grafik](https://github.com/user-attachments/assets/0f27c95e-2fb2-49e1-ba65-7a9abc31a2dc)

**System (please complete the following information):**
- Occultism Version: 1.137.1
- OS: Win 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: Direwolf20 1.20
- https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by notsome1else** [comment]
DO NOT DOWNLOAD FROM THIS LINK!!!!

That clearly is Malware!

**Comment by klikli-dev** [comment]
Thanks for the warning!
For all: derKarlito's Message pertains to a spam message that GitHub has meanwhile removed

**Comment by klikli-dev** [comment]
@derKarlito As for the error I am almost 100% sure that people did the same ritual in ATM on 1.20.1 so it *should* work unless the pack changes the recipe, which I do not think is the case.

Can you try to remove one of the stones next to the pentacle and replace it with water, then place a e.g. a salmon (using a bucket) and killing it with a sword or other item?

Tuna *could* have worked but I suspect whatever mod adds tuna does not tag it as fish, so Occultism doesn't know that that tuna was a fish :D

**Comment by notsome1else** [comment]
Well yes, that worked xD

Thanks :D
