### ISSUE TITLE
Recipe Conditions for Rituals

### ISSUE THREAD

**Issue by Drackion** [klikli-dev/occultism#1210]
Is it possible add `Biome` & `Dimension` recipe conditions to rituals. These recipe conditions would add additional possibilities for Modpack creators such as locking a ritual to only work in the Nether or only work in a Plains biome.

**Comment by klikli-dev** [comment]
- [x] Add support for neo conditions as start conditions for ritual
- [x] Add custom conditions for biomes and dimensions
- [x] Make golden bowl check for recipes
- [x] add system to get description and failure messages from recipe conditions
- [x] add failure message printing to ritual start checks
- [x] add descriptions for recipe conditions to JEI, EMI and Modonomicon
- [x] add all failure messages
- [x] add all description message
- [x] remove demo condition from foliot crusher
- [ ] update kubejs addon
