### ISSUE TITLE
Transfer NBT when crafting Tier 2 Ritual Bag

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1212]
Would be nice if this bag kept its contents when being upgraded. :D

**Comment by klikli-dev** [comment]
oh dang

**Comment by klikli-dev** [comment]
Ok, turns out I cannot access the NBT of ingredients at the end of the ritual (where I need them).
A refactor to store all ingredient information is currently out of scope so I will change the recipe

**Comment by MuteTiefling** [comment]
Ah, I figured it wouldn't be trivial to change things to store nbt, but this works just as well. Thanks!

**Comment by MuteTiefling** [comment]
Hrm, I think there might be an issue with the recipe on this one. KubeJS is yelling at me because parts are missing. 

T2
```json
{
  "type": "occultism:ritual",
  "result": { "count": 1, "id": "occultism:ritual_satchel_t2" },
  "ritual_dummy": {
    "count": 1,
    "id": "occultism:ritual_dummy/craft_ritual_satchel_t2"
  },
  "activation_item": { "item": "occultism:book_of_binding_bound_afrit" },
  "duration": 240,
  "ingredients": [
    { "item": "minecraft:hopper" },
    { "item": "minecraft:dispenser" },
    { "tag": "minecraft:wool" },
    { "tag": "c:leathers" },
    { "tag": "c:strings" },
    { "tag": "c:ingots/silver" },
    { "item": "occultism:afrit_essence" },
    { "tag": "c:ender_pearls" },
    { "tag": "c:ender_pearls" },
    { "tag": "c:ender_pearls" },
    { "tag": "c:ender_pearls" }
  ],
  "pentacle_id": "occultism:craft_djinni",
  "ritual_type": "occultism:craft_with_spirit_name"
}
```

T1
```json
{
  "type": "occultism:ritual",  
  "entity_to_summon_settings": {},
  "result": { "count": 1, "id": "occultism:ritual_satchel_t1" },
  "ritual_dummy": {
    "count": 1,
    "id": "occultism:ritual_dummy/craft_ritual_satchel_t1"
  },
  "ritual_requirement_settings": {
    "activation_item": {
      "item": "occultism:book_of_binding_bound_djinni"
    },
    "duration": 240,
    "ingredients": [
      { "item": "minecraft:hopper" },
      { "item": "minecraft:dispenser" },
      { "tag": "minecraft:wool" },
      { "tag": "minecraft:wool" },
      { "tag": "c:leathers" },
      { "tag": "c:leathers" },
      { "tag": "c:strings" },
      { "tag": "c:ingots/silver" }
    ],
    "pentacle_id": "occultism:craft_djinni"
  },
  "ritual_start_settings": {},
  "ritual_type": "occultism:craft_with_spirit_name"
}
```

It's complaining about `ritual_requirement_settings` and `entity_to_summon_settings` missing so far. I suspect if I add those it'll complain about `ritual_start_settings` not being there as well.

**Comment by klikli-dev** [comment]
Ohh I think I messed up when merging. 
T2 uses the old format (I had to change the recipe format, because minecraft's codecs are limited in how many fields they support, and people requested additional ritual features).

Occultism loads both formats, but I think there is no way to let kubejs accept both ways

**Comment by klikli-dev** [comment]
https://github.com/klikli-dev/occultism/tree/refs/tags/release/v1.21.1-1.160.1 will update the format.

However for me it now raises the question if kubejs modifications of the rituals may run into issues after this update.

**Comment by MuteTiefling** [comment]
Yeah, I'm having to update some scripts. No big deal though. I'm just globally reducing the craft time and that script is now looking in the wrong spot for those values
