### ISSUE TITLE
Storage actuator and storage access

### ISSUE THREAD

**Issue by mumos0** [klikli-dev/occultism#1213]
Hello, I realize that with the version of occultism-1.20.1-1.139.0-release and its improvements in the Spanish language there is a type of error when tuning the storage accessor with the storage actuator, it does not save the coordinates in the control therefore the control still does not change to a green color, could it be an error for Spanish servers or I do not understand

Could you try the server at https://www.curseforge.com/minecraft/modpacks/galaxyori

![image](https://github.com/user-attachments/assets/5a51bd07-bdc5-4952-8b4e-4f176ec6fa04)

**Comment by klikli-dev** [comment]
@umos8 Does the storage remote work?
As in, is it only a visual bug, or gameplay too?

I cannot reproduce this error

**Comment by klikli-dev** [comment]
Closed as stale

**Comment by mumos0** [comment]
Hi, today it doesn't work, I don't understand why 

 mod pack https://www.curseforge.com/minecraft/modpacks/starages/files/all?page=1&pageSize=20

**Comment by mumos0** [comment]
I think it's a bad configuration with the Spanish language in mod

**Comment by mumos0** [comment]
![image](https://github.com/user-attachments/assets/1cd66de9-d184-4af1-ba01-29e12d3b3cc6)
