### ISSUE TITLE
Error with Dicitionary Of Spirits at server

### ISSUE THREAD

**Issue by Renol0236** [klikli-dev/occultism#1216]
This error only occurs on the server (single player works correctly)
1. Open Dicitionary Of Spirits
2. Right click to open book.
3. See error

![изображение](https://github.com/user-attachments/assets/09d124eb-8385-4cbd-bfe0-f72ed952575b)

- Occultism Version: 1.139.0
- OS: Windows 11
- Minecraft Version: 1.20.1 Forge 47.2.0
- Modpack Link and Version, or list of mods: 

1.  	- alexsmobs 1.22.8
2. 	- appleskin 2.5.1+mc1.20.1
3. 	- architectury 9.2.14
4. 	- athena 3.1.2
5. 	- attributefix 21.0.4
6. 	- badmobs 19.0.2
7. 	- balm 7.2.2
8. 	- betteranimationscollection 8.0.0
9. 	- betterfpsdist 1.20.1-4.3
10. 	- bettervillage 3.1.0
11. 	- bobberdetector 0.1.9.1.20.1
12. 	- bookshelf 20.1.9
13. 	- botania 1.20.1-446-FORGE
14. 	- botarium 2.3.2
15. 	- bountiful 6.0.3+1.20.1
16. 	- callablehorses 1.3.0.1
17. 	- canary 0.3.3
18. 	- chipped 3.0.4
19. 	- chunkloaders 1.2.8a
20. 	- chunksending 1.20.1-2.8
21. 	- citadel 2.5.4
22. 	- clientcrafting 1.20.1-1.8
23. 	- cloth_config 11.1.118
24. 	- clumps 12.0.0.3
25. 	- collective 7.84
26. 	- comforts 6.3.5+1.20.1
27. 	- connectivity 1.20.1-5.4
28. 	- constructionwand 1.20.1-2.11
29. 	- controlling 12.0.2
30. 	- corpse 1.20.1-1.0.12
31. 	- cosmeticarmorreworked 1.20.1-v1a
32. 	- craftingtweaks 18.2.3
33. 	- create 0.5.1.f
34. 	- create_central_kitchen 1.3.10
35. 	- create_confectionery 1.1.0
36. 	- create_crush_everything 1.0.2
37. 	- create_dragon_lib 1.3.3
38. 	- create_enchantment_industry 1.2.8
39. 	- create_new_age 1.1.2
40. 	- create_pillagers_arise 113.23.
41. 	- create_power_loader 1.4.0-mc1.20.1
42. 	- create_recipes 1.0.0
43. 	- create_sa 2.0.4.
44. 	- create_structures 0.1.1
45. 	- create_structures_arise 136.9.8
46. 	- create_tweaked_controllers 1.20.1-1.2.4
47. 	- create_ultimate_factory 1.6.0
48. 	- createarmory 0.5
49. 	- createbigcannons 5.5.1+mc.1.20.1-forge
50. 	- createchunkloading 1.6.0
51. 	- createdeco 2.0.1-1.20.1-forge
52. 	- createliquidfuel 2.1.0-1.20.1
53. 	- createoreexcavation 1.5.2
54. 	- createtrackmap 1.4
55. 	- cupboard 1.20.1-2.6
56. 	- curios 5.10.0+1.20.1
57. 	- deuf 1.20.1-1.3
58. 	- dynamiclightsreforged 1.20.1_v1.6.0
59. 	- effecttooltips 9.0.2
60. 	- embeddium 0.3.9+mc1.20.1
61. 	- embeddiumextras 2.0.0
62. 	- enchdesc 17.0.14
63. 	- entityculling 1.6.2
64. 	- farmersdelight 1.20.1-1.2.4
65. 	- fastleafdecay 31
66. 	- ferritecore 6.0.1
67. 	- flywheel 0.6.10-7
68. 	- foodeffecttooltips 1.0.0
69. 	- forge 47.2.0
70. 	- framedblocks 9.3.1
71. 	- freecam 1.2.1+1.20
72. 	- ftblibrary 2001.1.5
73. 	- ftbquests 2001.3.4
74. 	- ftbranks 2001.1.3
75. 	- ftbteams 2001.2.0
76. 	- ftbxmodcompat 2.1.0
77. 	- fusion 1.1.1
78. 	- gamemenumodoption 2.2.1
79. 	- geckolib 4.4.9
80. 	- gjeb 1.3.0.32
81. 	- gpumemleakfix 1.20.1-1.8
82. 	- guardvillagers 1.20.1-1.6.4
83. 	- hpm 2.6.5
84. 	- immediatelyfast 1.2.10+1.20.4
85. 	- immersive_paintings 0.6.7+1.20.1
86. 	- inventorysorter 23.0.1
87. 	- itemfilters 2001.1.0-build.59
88. 	- jade 11.7.1
89. 	- jadeaddons 5.2.2
90. 	- jei 15.3.0.4
91. 	- jeresources 1.4.0.247
92. 	- justenoughprofessions 3.0.1
93. 	- kambrik 6.1.1+1.20.1
94. 	- konkrete 1.8.0
95. 	- kotlinforforge 4.10.0
96. 	- krypton 0.2.3
97. 	- leaky 1.20.1-1.7
98. 	- letmedespawn 1.2.0
99. 	- libraryferret 4.0.0
100. 	- lootr 0.7.32.79
101. 	- mcwbridges 2.1.1
102. 	- mcwdoors 1.1.0
103. 	- mcwfences 1.1.1
104. 	- mcwtrpdoors 1.1.2
105. 	- minecraft 1.20.1
106. 	- mixinextras 0.2.0
107. 	- mixinsquared 0.1.1
108. 	- modernfix 5.14.0+mc1.20.1
109. 	- modonomicon 1.75.0
110. 	- mousetweaks 2.25
111. 	- musicplayer 2.7.0.267
112. 	- mutil 6.1.1
113. 	- naturescompass 1.20.1-1.11.2-forge
114. 	- neruina 1.3.0
115. 	- notenoughanimations 1.7.1
116. 	- occultism 1.139.0
117. 	- oculus 1.6.15a
118. 	- okzoomer 3.0.1
119. 	- patchouli 1.20.1-84-FORGE
120. 	- polymorph 0.49.2+1.20.1
121. 	- puzzlesaccessapi 8.0.7
122. 	- puzzlesapi 8.1.4
123. 	- puzzleslib 8.1.17
124. 	- railways 1.5.3+forge-mc1.20.1
125. 	- rechiseled 1.1.5c
126. 	- rechiseledcreate 1.0.2
127. 	- recipeessentials 1.20.1-3.2
128. 	- reeses_sodium_options 1.0.4
129. 	- resourcefullib 2.1.23
130. 	- ritchiesprojectilelib 2.0.0-dev+mc.1.20.1-forge-build.182
131. 	- rubidium 0.7.1
132. 	- searchables 1.0.2
133. 	- sliceanddice 3.2.0
134. 	- smartbrainlib 1.15
135. 	- smoothchunk 1.20.1-3.6
136. 	- sophisticatedbackpacks 3.20.3.1029
137. 	- sophisticatedcore 0.6.9.569
138. 	- sound_physics_remastered 1.20.1-1.1.2
139. 	- spectrelib 0.13.15+1.20.1
140. 	- storagedrawers 12.0.3
141. 	- strawstatues 8.0.2
142. 	- structureessentials 1.20.1-3.3
143. 	- supermartijn642configlib 1.1.8
144. 	- supermartijn642corelib 1.1.17
145. 	- tetra 6.4.0
146. 	- textrues_embeddium_options 0.1.5+mc1.20.1
147. 	- tfmg 0.9.2-1.20.1
148. 	- tlskincape 1.32
149. 	- torchmaster 20.1.5
150. 	- treeharvester 9.1
151. 	- uteamcore 5.1.4.312
152. 	- villagernames 7.3
153. 	- voicechat 1.20.1-2.5.20
154. 	- waystones 14.1.3
155. 	- workers 1.7.8
156. 	- worldedit 7.2.15+6463-5ca4dff
157. 	- xaerominimap 23.9.7
158. 	- xaeroplus 2.1
159. 	- xaeroworldmap 1.37.8

**Comment by klikli-dev** [comment]
This is due to the russian translation containing 1.21 content. It is community maintained, so it is hard for everyone to get everything right.

Please update modonomicon to the latest version, I added some special handling that should fix this
