### ISSUE TITLE
My server members are unable to log onto the server after months with no issues

### ISSUE THREAD

**Issue by GwenFelicis** [klikli-dev/occultism#1218]
Server kicks members with no other movement or anything, they are just refused access to the server with an error string.

**To Reproduce**
1. Log onto the server
2. Get kicked off immediately

**Expected behavior**
Logging on to play the game with no issues other than the occasional lag

**Screenshots**

![image_2024-09-27_184320990](https://github.com/user-attachments/assets/ca388500-06ae-4f30-b3d7-ac4f4908117c)

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.136.1
- OS: Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/shenanigans-smp-modpack

**Additional context**
Members of the server had no previous issues with logging onto the server and have been kicked repeatedly for the only reason of the book while other members remain able to log onto the server still without issue.

**Comment by klikli-dev** [comment]
@GwenFelicis please provide a log from the server and from one of the people being disconnected. 

Generally this looks like some sort of data corruption
Some ideas: 
- Try to re-install latest occultism on the server, in case the jar file got damaged somehow
- Did anything change with the mod installed? 
- Are any of the people using a non-english language?

**Comment by klikli-dev** [comment]
Closing this in favour of #1221 as we are collecting more data on the same issue there
