### ISSUE TITLE
Unbound Afrit does not attack

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#122]
**Describe the bug**
im summoning the unbound afrit and it just stands there looking uncomfortably horrendous(separate issue that rid is now on top of lmaoo)... but it does not attack,, im also told it is supposed to summon with blazes? that doesnt seem to happen either

**To Reproduce**
1. summon afrit
2. watch it look at u with dead empty eyes in dismay and bask in the horror of it's face while it does absolutely nothing

**Expected behavior**
should try to murder me

**Screenshots**
https://gyazo.com/7195307f0215aa4ba4dbdd31400481f0
**System (please complete the following information):**
- Occultism Version: 1.0.6
- OS: [e.g. Windows] windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: enigmatica 6 dev build

**Additional context**

**Comment by theboo** [comment]
I should mention it was summoned properly, I didn't use an egg... It just wandered far away from the pentacle before I started recording

**Comment by klikli-dev** [comment]
That was a true kli kli genius moment. The Afrit is being tamed after spawn .. 
Will fix that :)
