### ISSUE TITLE
Crash previewing pentacle

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1220]
**Describe the bug**
Seems something isn't liking the bumblezone's candles in the dictionary preview. Game crashed as soon as it cycled around to them. 

**To Reproduce**
1. Have Bumblezone 
2. Preview a pentacle with candles in it

**Expected behavior**
No crash :D

**Screenshots**
N/A

**System (please complete the following information):**
- Occultism Version: 1.161.0
- OS: Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: Enigmatica 10 dev

**Additional context**
[Add any other context about the problem here.](https://gist.github.com/MuteTiefling/4bd19e1bd75f82a16f28b5bd227720f0)

**Comment by klikli-dev** [comment]
"Invalid block entity the_bumblezone:potion_candle // com.telepathicgrunt.the_bumblezone.blocks.blockentities.PotionCandleBlockEntity state at BlockPos{x=5, y=1, z=1}, got Block{twilightforest:skeleton_skull_candle}[candles=1,lighting=none,rotation=8]" 

uhhh 

EDIT: Ahh! Candles rotate through, and in this particular case there are two candles with block entities. Block entities, however, are cached, which causes this issue. I will check if it is possible to conditionally update the cache (dropping the cache would be no bueno for performance)

**Comment by MuteTiefling** [comment]
Thanks!
