### ISSUE TITLE
ATM9 Occultism Dictionary of Spirits blocking Server Entry

### ISSUE THREAD

**Issue by AllTheMelanie** [klikli-dev/occultism#1221]
**Describe the bug**

I cannot join my ATM9 server we JUST created because we get this error code every time. 

**To Reproduce**

1. Attempt Join ATM9 server
2. Receive error code

**Expected behavior**

I just want to be able to join the new server 

**Screenshot**

see attached 

![image_2024-10-01_115833811](https://github.com/user-attachments/assets/a53721a3-9708-4a70-93aa-edde91c76715)

**System (please complete the following information):**

- Occultism Version: 1.137.0

- OS: Windows 11

- Minecraft Version: 1.20.1

- Modpack Link and Version, or list of mods: ATM9, loaded through prism launcher/curse forge

**Additional context**
Our server is bisect hosting, so I don't know if it is a problem with that? But it’s only this occultism message I receive, so I think it might be something I need to change within the mod

**Comment by klikli-dev** [comment]
Someone else reported this issue, but I could not reproduce it yet. 
The error indicates something is broken in the book included with occultism, but the only recent change in that regard was the spanish translation, which I think the server does not even load.

I will investigate further.

EDIT: I re-tried with a server, and I can join just fine. I presume the issue is due to some mod combination, or datapack/kubejs. The other report was also in a bigger modpack, so maybe one of the more common mods has an adverse interaction with occultism.

Meanwhile, can you try to downgrade occultism versions on both server and client until you can join? That might allow me to narrow down at which point problems started (unless no occultism change was involved at all, which is possible too, but would be good to know as well)

**Comment by AllTheMelanie** [comment]
The occultism version on the Server was 1.137.0 so i changed the Prism Launcher version to 1.137.0 a well and it still happens. I just found the other report you mentioned and i tried changing both to the newest version, 1.139.0 and I get the same error report.

**Comment by AllTheMelanie** [comment]
I can join a single player world just fine, so does that mean it's definitely on the server side?

**Comment by klikli-dev** [comment]
> I can join a single player world just fine, so does that mean it's definitely on the server side?

That is hard to say. It might also be a problem with networking (the serialization and deserialization of the data), which simply does not happen in singleplayer. 

It does indicate however, that the data pack contained in the mod is fine, and that it is something else.
Can you check your modonomicon version and make sure it is on the latest version? 
Modonomicon is what handles the book for occultism, so it might also be an issue over there that only recently flared up

**Comment by AllTheMelanie** [comment]
i see that i have 1.75.0 jar for modonomicon on the server and i have both 1.75 and 1.77 on the prism launcher. i can remove the 1.77 so there is no difference in versions and let you know if it works. I had no idea modonomicon handled the book, that's pretty neat

**Comment by klikli-dev** [comment]
I just set up a local ATM9 server and joined it without issue.
I am on ATM version 0.3.2 without modifications, client installed from curseforge launcher, server downloaded from https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5682518/additional-files

Can you try with that version if you can join?
If it does not work, can you try to do it with the launcher and files I used with a local server?
(when downloading the server pack from ATM you just need to run "startserver.bat" and it does everything for you)

![image](https://github.com/user-attachments/assets/b238aebb-c5bd-42bf-96c3-ccd406b9b97e)

**Comment by klikli-dev** [comment]
It may be that something went wrong when the server was installed on bisect? I am not sure, but at least on a fresh world with latest atm9 I cannot make that error happen

**Comment by AllTheMelanie** [comment]
![image_2024-10-01_125300462](https://github.com/user-attachments/assets/3dae12fd-3aa1-4438-b637-a552a084437a)

I just changed the prism launcher version to 1.77 and now i receive this message

**Comment by AllTheMelanie** [comment]
I am not very familiar with how some of this works, I have a friend that I own the server with and he knows a lot more about what you are saying and the recommendations you have, so when he gets off work I will show him your responses and see if he can use that information to fix it and I can let you know which thing you recommended worked! I appreciate your help, thank you

**Comment by klikli-dev** [comment]
> I am not very familiar with how some of this works, I have a friend that I own the server with and he knows a lot more about what you are saying and the recommendations you have, so when he gets off work I will show him your responses and see if he can use that information to fix it and I can let you know which thing you recommended worked! I appreciate your help, thank you

Excellent! If you or your friend find any way to reproduce this without bisect (as in: Download server files, start server, start client, connect) please let me know, in that scenario I might be able to find out more

**Comment by AllTheMelanie** [comment]
sounds great! I'll be sure to get back to you, thanks a bunch!

**Comment by klikli-dev** [comment]
Closing as stale, please tag me if it pops up again.
