### ISSUE TITLE
Cannot craft in occultism crafter

### ISSUE THREAD

**Issue by bigrad1** [klikli-dev/occultism#1223]
cannot craft in occultism storage
cannot craft using emi specifically, i can drag and drop stuff normally and that still works, but not the shift click crafting

https://github.com/user-attachments/assets/185c2856-45c7-47f5-a0c9-775102467c9c

**Comment by klikli-dev** [comment]
Please provide the information the "bug report" template requires, especially the versions of minecraft and occultism, and the mod list or mod pack.

**Comment by Leonxilofin** [comment]
I'm also having this issue. 
- Occultism Version: occultism-1.21.1-neoforge-1.161.0
- OS: Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: [Craftoria](https://www.curseforge.com/minecraft/modpacks/craftoria) 1.4.1

In short, the dimensional matrix doesn't autofill recipes taken from EMI which is shown in OP's video

**Comment by klikli-dev** [comment]
thanks! Managed to reproduce it, it seems it only happens on servers

**Comment by bigrad1** [comment]
> thanks! Managed to reproduce it, it seems it only happens on servers

Yeah I play on a server with a few buddies. Just a small server I made for my friends.
