### ISSUE TITLE
Add Crushing Recipes for Allthemodium Alloy Dusts

### ISSUE THREAD

**Issue by TheBedrockMaster** [klikli-dev/occultism#1228]
**Describe the solution you'd like**

I suggest adding crushing recipes for the 3 Allthemodium Alloy Dusts from Allthemodium Alloy Ingots from Allthemodium.

**Comment by klikli-dev** [comment]
I can add them as default recipes, but wouldn't ATM add the recipes if they desired that?
Or asking the other way around: Are there other ways to crush ingots into dust that are roughly on the same gameplay tier as occultism crusher?

Then I can add them without accidentally unbalancing their pack :)

**Comment by TheBedrockMaster** [comment]
This is ATM dev Toblerone0508, these dusts are currently unobtainable and don't have uses, I'm planning on adding uses to them in the future and recipes to get them but I thought I might as well suggest that these recipes are added to Occultism itself.

**Comment by klikli-dev** [comment]
Excellent, then I'll add them :)
