### ISSUE TITLE
Minor config bug with ritualDurationMultiplier

### ISSUE THREAD

**Issue by KamiN0Baka** [klikli-dev/occultism#1231]
When editing occultism-server.toml, if you forget the zero when decreasing ritualDurationMultiplier (i.e. .25 instead of 0.25), it causes NeoForge to regenerate the entire file. I suspect it has something to do with either the way the config is processed or the variable type used, so I'm not sure it's even fixable or even really worth the trouble of fixing. I'd suggest adding to the comment line that says what ritualDurationMultiplier does that you need to have a 0 before the decimal for values below 1.

Side note, discovered this on ATM10 and spent a couple of hours combing through modpack scripts making sure there wasn't one that was defaulting out the config on purpose before I thought to try Occultism on a clean instance. Once I did, I figured out what was going on in like five minutes. I need to learn to apply Occam's razor to troubleshooting Minecraft mod issues.

**Comment by klikli-dev** [comment]
@KamiN0Baka I suspect that is how Neo's config (Nightconfig) handles floating point numbers, as I am just using their "DoubleValue" config. Indeed whenever it discovers an error it just goes nuclear ... Sadly not a lot of influence I have as a modder here, but the comment idea is great
