### ISSUE TITLE
Server crashing when loading my occultism setup

### ISSUE THREAD

**Issue by Alexo6o5** [klikli-dev/occultism#1235]
**Describe the bug**
The server crashes whenever someone loads my storage/dimensional mineshaft (in same chunk) (storage had a few hundred slots used iirc), 1.20.1
[2024-10-26-2.log.gz](https://github.com/user-attachments/files/17530700/2024-10-26-2.log.gz)

**To Reproduce**
I have no idea.  

**Expected behavior**
I expected the server not to crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.139.1
- OS: apex hosting? prob linux
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
Scorched guns 2
Curios
Occultism
Waystones
AI Improvements
Alex's mobs
Appleskin
Applied energistics 
architectury api
ars nouveau
artifacts
balm
blue skies
brandons core
citadel 
cloth config api
clumps
codechicken lib 1.8.+
comforts
create
create crafts and additions
draconic evolution
embeddium 
enchanting infuser
ferritecore
framework
freecam
ftb library
ftb ultimine
geckolib
goblin traders
gravestone mod
ice and fire: dragons
jade
jade addons
just enough items
just enough resources
mahou tsukai
modernfix
modonomicon
mrcrayfish gun mod [unofficial]
nature's compass
patchouli
puzzles lib
smartbrainlib
sophisticated backpacks
sophisticated core
structure gel api
trade cycling

or, if u just want image of mods folder:
![image](https://github.com/user-attachments/assets/5fbf027f-0cff-4c99-9ee6-c31ae7f0d410)

**Additional context**
server said something about saving a chunk in a different file bc it was too big. not sure what that was about and dont recall exact line. maybe its in the log?

**Comment by klikli-dev** [comment]
@Alexo6o5 I have not encountered that before, but the oversized file issue you mentioned may be the core reason. The actual crash just says
```
[26Oct2024 12:53:47.538] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[26Oct2024 12:53:47.539] [Server Watchdog/ERROR] [net.minecraft.server.dedicated.ServerWatchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
```

Can you run https://www.curseforge.com/minecraft/mc-mods/spark on your server and then send me the spark log?
It shows exactly which task takes how long, which helps to figure out what is going on
