### ISSUE TITLE
Possessed Witches drop Uncraftable Potions

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1239]
**Describe the bug**
Possessed Witch loot table has no components defined for potions.

**Expected behavior**
Either should drop an actual potion or just a bottle of water. 

**Screenshots**
![image](https://github.com/user-attachments/assets/cfaf2751-986f-4729-8be0-81d2bfb96c5f)

**System (please complete the following information):**
- Occultism Version: 
![image](https://github.com/user-attachments/assets/a4b77562-b312-42b2-867d-feecebd5287c)

- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: Enigmatica 10

**Comment by Eqis-Edu** [comment]
literally what is written in the dictionary
![image](https://github.com/user-attachments/assets/a5affe04-0cf0-42c4-8ccb-54695c9da4b6)

**Comment by MuteTiefling** [comment]
Why? This is nonsense. You're just throwing an item at the player that is quite literally never supposed to happen and indicates an error in every case.

May as well give them barrier blocks next.

**Comment by klikli-dev** [comment]
Yeah I think we should go with bottle of water here, "uncraftable" in the name will trigger players, especially if they don't read the book ... which are many :D

**Comment by klikli-dev** [comment]
Changed in #1246
