### ISSUE TITLE
[Minor] JEI description of Iesnium Ore is hard to read

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#124]
**Describe the bug**
JEI description of Iesnium Ore is hard to read

**Expected behavior**
More readable I guess :P

**Screenshots**
![billede](https://user-images.githubusercontent.com/21295394/105410967-0ad8cd00-5c33-11eb-8f43-500493b4057c.png)

**System (please complete the following information):**
- Occultism Version: 1.0.6
- Minecraft Version: 1.16.4

**Comment by klikli-dev** [comment]
This is somewhat weird, I encountered it a few time in my dev env as well, but not consistently. I'm using the MC formatting codes with `§6` and `§r` but sometimes `§r` does not reset the formatting - I suspect it has something todo with JEI's automatic wrapping/line breaks in text.

That said, I'll see if additional reset signs can fix this :)
