### ISSUE TITLE
Wild Illager Summon appears misnamed

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1240]
**Describe the bug**
Wild Illager ritual still listed as Possessed Evoker

**Expected behavior**
Ritual is now part of the Wild series of summons, so it would make more sense for the ritual to be renamed Summon Wild Illager Raid. 

**Screenshots**
![image](https://github.com/user-attachments/assets/89ee58b9-ab07-44d1-943a-5af4fc534417)

Spawn egg probably needs a rename too
![image](https://github.com/user-attachments/assets/362b07e1-608b-4bc6-8283-d44c22680a7a)

The Dictionary of Spirits refers to it by yet a third name altogether.
![image](https://github.com/user-attachments/assets/07c5528e-e32f-4a79-837e-279cd34ed789)

**System (please complete the following information):**
- Occultism Version: 
![image](https://github.com/user-attachments/assets/a4b77562-b312-42b2-867d-feecebd5287c)

- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: Enigmatica 10

**Comment by MuteTiefling** [comment]
Found a fourth name. Should just be consistent, whatever it's named.
![image](https://github.com/user-attachments/assets/b64d2503-cd54-4122-9cff-2bb8de075aac)

**Comment by MuteTiefling** [comment]
May be worth having a second look at all of these rituals actually. I'm seeing a lot of inconsistencies in names between the book and recipe viewer. 

Considering these are thematically no longer Possession rituals, it may also make sense to redo the possession chapter in the book to move these into their own category.

**Comment by Eqis-Edu** [comment]
"Wild" possessions is just a group possession
(and horde if all mobs are the same)

The spawn egg refer to the "main" mob, like the wild hunt wither skeleton

**Comment by MuteTiefling** [comment]
With the way categories are laid out in the book, these appear to have been fully divorced from 'possession' as those all use the yellow chalk line of pentacles and the book no longer refers to them as possession, but contact with wild spirits. 

They're wild. That's fine. It's a new category and effectively quite different from Possession. The names should consistently reflect that. It will more accurately signal to the player that these are Wild summons and different from possession.

**Comment by klikli-dev** [comment]
Closed in #1237 unless I am much mistaken
