### ISSUE TITLE
Miner's are not being deposited in the Dimensional Mineshaft's output when near breaking

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1241]
**Describe the bug**
Miner's are not being deposited in the Dimensional Mineshaft's output when near breaking

**To Reproduce**
1. put miner in mineshaft
2. wait

**Expected behavior**
Following a discord discussion, I had understood that these would be getting a change such that when they reach 1 durability, they'd be output to the Mineshaft's output slot. This was to facilitate their repair along with the new repair ritual.

**System (please complete the following information):**
- Occultism Version: 
![image](https://github.com/user-attachments/assets/0d694f7c-fe4b-487e-8739-44c9f575c644)
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: Enigmatica 10

**Comment by Eqis-Edu** [comment]
Is a server config and default is false

**Comment by MuteTiefling** [comment]
Default true would be greatly appreciated by players, I'm sure. This is very useful qol in a mod that just got very grindy...

**Comment by klikli-dev** [comment]
Changed in #1237
