### ISSUE TITLE
Butchery compatibility tallow.

### ISSUE THREAD

**Issue by hazerddex** [klikli-dev/occultism#1243]
when using butchery the animals no longer drop tallow is there a work around for this?

**Comment by ffuentesm** [comment]
Which version are you using? This was a bug a while ago. 
Its to do with the tags on the tool.

**Comment by hazerddex** [comment]
butchery 2.7.1 occultism 1.1.40.1

**Comment by klikli-dev** [comment]
@hazerddex sorry I completely missed this. 
I am closing this because a bunch of stuff changed, please ping me if this is still an open issue so I can reopen it
