### ISSUE TITLE
Crash when viewing certain rituals in guidebook

### ISSUE THREAD

**Issue by AbsorbingSafe11** [klikli-dev/occultism#1247]
**Describe the bug**
When clicking the little eye icon in the guidebook (to see how the ritual is placed in the world) the game crashes

**To Reproduce**
1. Open guidebook
2. Select a ritual (haven't yet tested with every ritual, but Hedyrin's Lure was consistently crashing)
3. Click little eye icon
4. Crash to desktop

**Expected behavior**
A ghost of the ritual would appear for me to fill out and properly setup the ritual

**Screenshots**
![2024-11-01_09 15 11](https://github.com/user-attachments/assets/e82c2dd8-1cf2-45bd-93af-ff87c7de2390)

**System (please complete the following information):**
- Occultism Version:  occultism-1.21.1-neoforge-1.166.0
- OS: Windows 11
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/tnp-limitless-8 (specifically Limitless 8 - v0.25.0)

**Additional context**
Seems like its a Placebo issue from what I saw in the crash log, but I'll post a link to that as well (also not very good at making these reports so sorry for mistakes)

**Comment by AbsorbingSafe11** [comment]
So I was unable to get the same crash again (to make sure I posted the right crash log), but  I did encounter this when looking at other rituals
![2024-11-01_09 23 42](https://github.com/user-attachments/assets/2908ab22-1ae4-4ffb-a022-57ef247f68e9)

**Comment by AbsorbingSafe11** [comment]
Then it crashed when I was paused and looking at the above screenshot, but didn't leave a crash report

**Comment by Eqis-Edu** [comment]
I place all the pentacles twice and didn't get any crashes. The skulls really look weird but probably another mod changes their rendering and that's affecting it.

**Comment by AbsorbingSafe11** [comment]
It seems to randomly happen in the pack when looking at ritual previews (what I was calling ghost blocks), but the lack of a crash report make this harder to figure out at all (also I removed rendering mods like Sodium to make sure it wasn't them and still got the crash)

**Comment by shade1822226911** [comment]
when i did the pentacles, the texture of the skulls seems to be the mahou tsukai textures in all the mods 10

**Comment by klikli-dev** [comment]
I am tentatively close this for now as recently a few modonomicon changes were made that fixed some crashes if certain other mods where involved. 

Please open a new issue if the crash appears again or ping me to reopen it
