### ISSUE TITLE
Revert Empty Magic Lamp Change

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#1249]
**Is your feature request related to a problem? Please describe.**
Crafting a magic lamp previously used an iesnium ingot. Now it needs a raw ore.

![image](https://github.com/user-attachments/assets/7a7c7df6-7ee0-4b43-bbab-3806b51521a6)

This feels like a 'gotcha' recipe.

The player is, of course, going to excitedly process up their ore as they get back from mining it. They then excitedly go to make a lamp and boom. "Gotcha!!! Go back to the nether and mine up some more!" 

Anti player intentionally antagonistic design is not fun.

**Describe the solution you'd like**
This should use an ingot. If you feel it's *really* that necessary to increase the cost, then use a block.

**Comment by Eqis-Edu** [comment]
The use of raw was to maintain the cost even with crushers, not to deceive the player, reversing this

**Comment by MuteTiefling** [comment]
Thanks

**Comment by klikli-dev** [comment]
Closed in #1246 I think?
