### ISSUE TITLE
Information about Pentacles in the Book are inconsistent / missleading

### ISSUE THREAD

**Issue by flece** [klikli-dev/occultism#1250]
**System**
- Occultism Version: occultism-1.21.1-neoforge-1.164.0

**Describe the bug**
Information in the Book are inconsistent / missleading
there is an Pentacle missing in lower right. So i was thinking that the 3 Chalks are not usefull.

**To Reproduce**
open book
go to pentacles
click the Eye top right to unlock ALL Entries

**Expected behavior**
now i should see all entries (entries gated by Advancement progress greyed out)

**Screenshots**
![2024-11-03_19 16 19](https://github.com/user-attachments/assets/b573635f-714c-46e6-8bed-1c08e970cb96)

**Comment by klikli-dev** [comment]
Closed in #1246
