### ISSUE TITLE
sapling trader 

### ISSUE THREAD

**Issue by RIExJonny** [klikli-dev/occultism#1251]
**Describe the bug**

so my sapling trader wont trade or do anything as i gave him my sappling to trade and nothing but when i tried it with the stone trader it works just fine so i know i was doing it right its just not working for the sapling trader.

**To Reproduce**
1. Place block '...'
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version:   1.21.1-neoforge-1.64.0.jar
- OS: [e.g. Windows]
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods:  ATM 10

**Additional context**

**Comment by Eqis-Edu** [comment]
It is the "oak sapling" from occultism to be traded
looking for a way to make this more visually explicit

**Comment by RIExJonny** [comment]
i fount out what i did wrong
