### ISSUE TITLE
Black chalk advancement

### ISSUE THREAD

**Issue by RIExJonny** [klikli-dev/occultism#1252]
**Describe the bug**

ok so i got the black chalk and everything but it still will not unlock the pentacle that requires advancemnet: black chalk and love the work you did to add ways to use the other colors and also im not the only one with this problem.. thank you agine for everything

**To Reproduce**
1. Place block '...'
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.21.1-neoforge-1.164.0.jar
- OS: [e.g. Windows]
- Minecraft Version: 1.21
`minecraft mod: ATM10
**Additional context**

**Comment by RIExJonny** [comment]
![Minecraft NeoForge_ 1 21 1 - Multiplayer (3rd-party Server) 11_4_2024 6_28_24 PM](https://github.com/user-attachments/assets/49faaffa-8335-44dc-8ac7-cc3b159e58ba)

**Comment by RIExJonny** [comment]
![Minecraft NeoForge_ 1 21 1 - Multiplayer (3rd-party Server) 11_4_2024 6_28_06 PM](https://github.com/user-attachments/assets/f0acdab4-565e-4362-a9ba-610078534def)

**Comment by Eqis-Edu** [comment]
It was an issue caused by the "Achievement Optimizer" mod, which was removed from ATM in version 1.16.
And #1246 will fix this so it doesn't happen again.

**Comment by RIExJonny** [comment]
thank you and i will go ahead and close this one out.. thank you agine

**Comment by RIExJonny** [comment]
![Minecraft NeoForge_ 1 21 1 - Multiplayer (3rd-party Server) 11_4_2024 9_27_47 PM](https://github.com/user-attachments/assets/9d7fb997-d77c-4adf-b798-f29d1965ed4a)
 sad to say i reponed it as it wont get past this part.. i am updated all the way. i went to the  other one #1246 but with it now closed i reopend this one

**Comment by Eqis-Edu** [comment]
the advancement has unlocked? Modonomicon is supposed to unlock even without loading the name
I tested it now in atm 1.16 and all worked correctly

**Comment by RIExJonny** [comment]
what did you do?/

**Comment by RIExJonny** [comment]
![Minecraft NeoForge_ 1 21 1 - Multiplayer (3rd-party Server) 11_4_2024 10_35_20 PM](https://github.com/user-attachments/assets/3a6aed7a-074a-47f8-b9f1-66cda700aa4c)

**Comment by RIExJonny** [comment]
![allthemods 1 16](https://github.com/user-attachments/assets/52b30468-49f9-4d5d-8bd1-c08ee0f2c65f)

**Comment by Eqis-Edu** [comment]
I just opened any test world and took the chalks, they all gave me the advancement.
I'll suggest two options
+ spawn the F key while holding the chalk, switching to offhand (old problems, old solutions)
+ Since you have the next level, use it to see where the black chalk and wither skulls should be, and place them, it will work even without unlocking it in the dictionary

**Comment by RIExJonny** [comment]
thank you that worked
