### ISSUE TITLE
Crash to Menu when configuring Djinn Machine Operator

### ISSUE THREAD

**Issue by Shadowfire86** [klikli-dev/occultism#1254]
**Describe the bug**
When I attempt to finish configuring the Djinn Machine Operator, in particular setting up the target machine, and go to close the menu either through Esc or the X button at the bottom, the background blurs and I get the following message: Internal Exception:io.netty.handler.codec.EncoderException: Failed to encode packet 'serverbound/minecraft:custom_payload'  and am sent back to the server select screen.

**To Reproduce**
1. Place down Djinn machine operator using book of calling
2. Shift+Right Click the machine to open setup menu
3. Set up machine (I used defaults except naming which I tried with and without naming)
4. Close the Menu either using Esc or the button at the bottom of this menu
5. Above Error appears and returned to menu

**Expected behavior**
Djinni machine operator now works on the configured machine handling input and output.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.21.1-neoforge-1.159.5.jar
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: Direwolf20 1.21 Modpack Version 1.3.0

**Additional context**
Already linked book to Storage Actuator which is in a different room, and yes there are the Wormhole/Mirror things nearby. I tried setting the DMO (Djinn Machine Operator) on both an Iron Furnaces Netherite Furnace, and an EnderIO Alloy Smelter with the same result.

**Comment by klikli-dev** [comment]
@Shadowfire86 Can you please provide your latest.log file, and potentially crashstack file if one was generated?

Usually these types of errors are due to negative interactions with other mods (such as performance optimization mods) and somewhat hard to track down, but in case it is an error in occultism the log file might tell us

**Comment by Shadowfire86** [comment]
[disconnect-2024-11-09_00.02.20-client.txt](https://github.com/user-attachments/files/17687068/disconnect-2024-11-09_00.02.20-client.txt)

I checked my crash log folder. Since it just booted me back to Server, nothing generated. If the location for the log you want is in another folder, I'll look for it if you tell me as much. Hopefully the attached file is what you needed? From the Debug Folder.

**Comment by itszenergy** [comment]
I also have the same issue
[disconnect-2024-11-09_15.57.19-client.txt](https://github.com/user-attachments/files/17688563/disconnect-2024-11-09_15.57.19-client.txt)

**Comment by klikli-dev** [comment]
Thank you for the info! I could not reproduce it in dev, but I have a lead, as I managed to make another error happen that might be related (sometimes dev and live behave a bit differently in how they handle errors, which leads to different symptoms in the game and logs). I will push a fix. If that does not fix it, please ping me here so I can reopen the issue!

**Comment by itszenergy** [comment]
Just updated and tried on the Craftoria modpack. Still the same issue :(
[disconnect-2024-11-09_17.06.05-client.txt](https://github.com/user-attachments/files/17688729/disconnect-2024-11-09_17.06.05-client.txt)

**Comment by klikli-dev** [comment]
@itszenergy does this happen in singleplayer or just on a server?
And can you reproduce it if you do a minimal pack on curseforge with just occultism + dependencies?

Considering that I currently do not get any errors with this process in dev it is _likely_ that it's another mod causing it, but if it is occultism after all we should find out so I can fix it

**Comment by itszenergy** [comment]
Tried Singleplayer and Server. Currently playing with friends on the Craftoria pack. Sorry I can't be of any more help.

**Comment by Shadowfire86** [comment]
Unfortunately my world is singleplayer, so I don't think I'll be much more help.

**Comment by Shadowfire86** [comment]
@klikli-dev Would you mind if I link this issue to the FTB Modpack Team to look into since it appears to be a mod interaction issue? I already checked the issues list and verified it's not already there.

**Comment by klikli-dev** [comment]
Ok making one more change to hopefully fix that!
