### ISSUE TITLE
[Suggestion] Add a list of pentacles for each chalk type in Patchouli Book

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#126]
I was just thinking it might be nice to have a list on each colored chalk entry page of what pentacles it is used in. There is a nice empty space below the chalk entries where this list could go. 
![2021-01-22_09 03 59](https://user-images.githubusercontent.com/3585761/105521710-18bd3b00-5c91-11eb-97b4-b72212d9ea07.png)

**Comment by klikli-dev** [comment]
Good idea - see my comment in #127 :)

**Comment by klikli-dev** [comment]
Thank you @najlitarvan for your help with this!
