### ISSUE TITLE
Shrink Mod Interaction with Summons reverts summons to a unusable tier (foliot, djinn, etc)

### ISSUE THREAD

**Issue by Walker395** [klikli-dev/occultism#1262]
**Describe the bug**
After summoning anything (so far tested with Foliot Crusher, Afrit Crusher and Afrit Smelter), if you use the Shrink Mod device to shrink and then store the summon in a bottle, once released from the bottle it spawns in without a role (forgets its a crusher or smelter etc.) 

**To Reproduce**

1. Shrink summon
2. Store in bottle
3. Release from bottle

**Expected behavior**
If you have the ability to shrink and move the mob, the role should also remain. 

**Screenshots**

Summon spawns in and works as intended:
![2024-12-04_13 27 59](https://github.com/user-attachments/assets/b854db3a-0cb3-4a5e-8066-17ed3bbde293)

Shrink Summon:
![2024-12-04_13 28 24](https://github.com/user-attachments/assets/982e0795-678e-428b-b737-7a2290dc5b77)

Pick up with bottle:
![2024-12-04_13 28 42](https://github.com/user-attachments/assets/d2c3df17-3495-4441-b54f-3d34dbd77338)

When released from bottle name switches to whatever level the summon in (tried on Foliot as well) and wont pick up any ores
![2024-12-04_13 28 51](https://github.com/user-attachments/assets/7542fdcf-9230-476e-9047-36118867a20f)

**System (please complete the following information):**
- Occultism Version: 1.167.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: DW20 1.21

Hope this is helpful!

**Comment by rhullah** [comment]
I'm guessing that's an issue with the shrink mod (not saving all data of the entity captured). Since you're in DW20, you can use his Creature catcher instead. I know that works which is what I use.

**Comment by Walker395** [comment]
Ah I see, that would make more sense that it would be on Shrink mods end. Thanks

________________________________

**Comment by weirdchildren** [comment]
Just in case you didn't know the occultism mod has the "soul gem" which is a great way of easily transporting mobs.
You probably know that already but just in case.

**Comment by klikli-dev** [comment]
This is indeed most likely due to the shrink mod not storing all entity data, as far as I know other mob transport tools including soul gems work
