### ISSUE TITLE
Rituals not accepting Forge Dusts

### ISSUE THREAD

**Issue by Walker395** [klikli-dev/occultism#1263]
**Describe the bug**
When trying to test another bug, I spawned in the Occultism Obsidian Dust (instead of the Mekanism Dust that the DW20 pack seems to favor). Though the ritual was setup correctly it didn't register the Occultism Obsidian dust and only worked with the Mekanism Version. This may also be the case with other dusts

**Expected behavior**
JEI says it accepts any obsidian Forgecraft dusts.

**System (please complete the following information):**
- Occultism Version: 1.167
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: DW20 1.21

**Additional context**

**Comment by weirdchildren** [comment]
This seems more likely a problem with how the recipe is setup in the pack. If DW20 favors Mekanism dust then the fact that Occultism dust doesn't work is probably from their doing. I would report this to the modpack devs if it's relevant to gameplay.

But also I don't really know what I'm talking about all that much so take this with a grain of salt.

**Comment by klikli-dev** [comment]
This is most likely due to DW20 using a resource unifier mod. By default occultism uses forge (or rather now "c"/common) tags
