### ISSUE TITLE
Otherworld wood not dropping 

### ISSUE THREAD

**Issue by SlenKen** [klikli-dev/occultism#1270]
In Minecraft 1.19.2 after planting otherworld dappling and getting third eye effect, I'm getting Minecraft oak wood instead of occultism otherworld wood.

**Comment by SlenKen** [comment]
I'm using forge 43.3.0 
Mod version: occultism-1.19.2-1.90.0

**Comment by ffuentesm** [comment]
What are you breaking the trees with? 
I recall that in the older versions, if you do not break it with an axe or by hand, it just drops normal oak

**Comment by SlenKen** [comment]
I'm breaking the tree with hand or axe, neither works

**Comment by SlenKen** [comment]
So it just started working out of blue. I started testing some things on creative, and now everything works as it should on survival.
