### ISSUE TITLE
Grove spawning issues

### ISSUE THREAD

**Issue by Jvkeh** [klikli-dev/occultism#1277]
**Describe the bug**
Groves are not fully generating correctly along chunk borders, despite recent changes. 

**To Reproduce**
1. Generate chunks (I have used both flying around as well as neoforge's generate command)
2. Come across incorrectly generated grove

**Expected behavior**
Groves should spawn as a sphere of stone, withholding a grove within.

**Screenshots**
![2024-12-30_20 47 11](https://github.com/user-attachments/assets/c4c9b731-ca5f-4244-9da8-a21b0e549f6c)
![2024-12-30_20 59 14](https://github.com/user-attachments/assets/8c81838c-ceb7-4968-8bc3-4cdcff42b9d6)
![2024-12-30_20 59 58](https://github.com/user-attachments/assets/adcf6a04-74d1-4775-a532-71b824642662)

**System (please complete the following information):**
- Occultism Version:  v1.171.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.21.1
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/craftoria

**Additional context**

**Comment by klikli-dev** [comment]
This is a known issue, see https://github.com/klikli-dev/occultism/issues/1022
Sadly I am currently unable to fix it, but I am accepting ideas / discussions / pull requests to fix it
