### ISSUE TITLE
No Results From Summoning's After The First Ritual

### ISSUE THREAD

**Issue by Zeyeo** [klikli-dev/occultism#129]
**Describe the bug**
When attempting to do the possessed Endermite ritual, And Successfully making the ritual Circle. Nothing Happens. Even After the game states that the ritual is in progress.

**To Reproduce**
1. Open The Dictionary Of Spirits and go to the page of Rituals, then click on possession rituals.
2. Traverse until you find the ritual circle needed to summon a possesed endermite(Which is the "Hedyrin's Lure") and click on the name.
3. Place down the visualized circle so that you copy it correctly
4. Navigate back to the Possessed endermite page And place down x4 sacrificial bowls. then 2 stone and 2 dirt in the placed down bowls. there should be 1 stone in 2 of them and 1 dirt in the other two.
5. Assuming that you have a Book of Binding Foliot(Bound) Place it in the middle golden sacrificial bowl.
6. See the "Possesed Endermite Ritual Has Begun" Message 
7. Wait For All Eternity.

**Expected behavior**
I expected for the ritual to begin slowly taking away the stone and dirt from the bowls and eventually summon a possessed endermite after the "Ritual has begun message" but all the items stayed and the ritual never ended.

**Screenshots**
Here Is A Video: 

https://user-images.githubusercontent.com/77851332/105524379-9000c800-5cad-11eb-92b6-23109408b999.mp4

**System (please complete the following information):**
- Occultism Version: 1.0.6
- OS: [e.g. Windows] Windows 10 
- Minecraft Version: forge-35.1.37
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/zeyeos-zooty-booty-pack
V 1.0.3
**Additional context**

**Comment by theboo** [comment]
throw an egg at the ritual... check the entry in the book it says "Use: Egg"

**Comment by theboo** [comment]
some rituals require you to use an item or sacrifice a certain mob after the ritual has started

**Comment by Zeyeo** [comment]
Well... i guess i didnt pay enough attention to that, also with the possessed skeleton sacrifice. for the possessed skeleton, does the chicken have to say in the circle? or do i need to throw a raw chicken in?

**Comment by Zeyeo** [comment]
or kill it in the circle?

**Comment by Zeyeo** [comment]
ah okay its kill it, alr sry bout the misunderstanding. I would recommend making the book a little more detailed for people like me who overthink things.

**Comment by theboo** [comment]
yes, a sacrifice means it must be killed within 8 blocks of the bowl... there is even one ritual that requires a villager or player sacfrifice

**Comment by klikli-dev** [comment]
@theboo thanks for helping out!
@Zeyeo As the creator one is sometimes a bit blind on how to explain things. If you have specific ideas on how to change a page / what new pages to add, just create an issue or pull request and I will add it to the mod
