### ISSUE TITLE
Please check the 1.16.4 box for 1.0.7 as well as future versions

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#133]
Just making a note that occultism 1.0.7 is not checked as 1.16.4 compatible making it a bit more work for pack makers still on 1.16.4 to update the mod.

Most of the modding community hasnt updated to 1.16.5 yet so it might be nice to keep the 1.16.4 checkbox checked until then xD

thanks a bunch!

**Comment by klikli-dev** [comment]
Currently a manual process - seems I missed it for 1.0.7, just added that
I'll make a note to *at some point* automate it. Please ping me in case I forget to tag another version!

**Comment by theboo** [comment]
thanks a bunch!
