### ISSUE TITLE
Items rotating sacrifiacal bowl and crystal matrix seem a bit janky

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#138]
**Describe the bug**
Watching the items rotate in the sacrificial bowls as well as watching the crystal matrix rotate seems a bit janky.

**To Reproduce**
1. place item in sacrificial/golden sacrificial bowl
2. watch the item rotate in like 15 degree increments
3. watch crystal matrix on storage actuator also move kinda janky

**Expected behavior**
i feel they could be MUCH smoother

**Screenshots**
video of bowls and matrix:
https://gyazo.com/5e2b6bd1a67a74d8960b6b7ec7db4acb
video of items on a pedestal from pedestals mod for reference of what i think it should look like:
https://gyazo.com/32970fc182b4706e57cdd71fcc526d04

**System (please complete the following information):**
- Occultism Version: 1.0.7
- OS: [e.g. Windows] windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: enigmatica 6 dev build

**Additional context**
i am not using optifine or anything like that

**Comment by klikli-dev** [comment]
@theboo When tested on my local server (with only occultism + dependencies) I cannot reproduce it.
Also checked the code: I am using partialticks to interpolate, so anim should be independent of frame rate.
Difference to pedetals mod seems to be that pedestals uses system time, where I use game time -> this indicates that a performance or similar mod is intervening - reducing game time ticks without correctly adjusting the partialtick interpolation time (as vanilla does when frames and/or ticks drop). 

I'll look into switching to system time, but that has some side effects with other parts of the code, so I'll need to investigate

**Comment by klikli-dev** [comment]
@theboo I switched one part of the rendering to system time, if any jankyness remains in the next build please just reopen this and I'll look into a full refactor
