### ISSUE TITLE
Dictionary of Spirits gets consumed when crafting a bound book of binding

### ISSUE THREAD

**Issue by Keltas** [klikli-dev/occultism#14]
**Describe the bug**
Crafting a bound book of binding consumes dictionary of spirits.

**To Reproduce**
1. Craft the book of binding (tested with Foliot) with the dictionary. To get a name bound.
2. Get just a named book of binding back without the dictionary of spirits.

**Expected behavior**
Dictionary of spirits to remain after crafting like an empty bucket after crafting using water bucket. While it doesn't cost much and can be easily remade, this is a constant annoyance, as you need to recraft it to check if you got everything for the ritual during every single ritual you perform. You need the dictionary for most parts of the mod and therefore losing it to the most common crafting mechanic in mod is an annoyance.

**System (please complete the following information):**
- Occultism Version: 2.5
- OS: Windows 10
- Minecraft Version: 1.15.2
- Mods: Tested with just Occultism, Patchouli, Journey Map and JEI.

**Comment by klikli-dev** [comment]
I agree, that would be ridiculous. It's absolutely intended to remain, but I made a recent change to the item, which I assume broke that behaviour. Will be fixed ASAP.

**Comment by klikli-dev** [comment]
Will be fixed in 0.2.6
