### ISSUE TITLE
Satchel can be put inside itself

### ISSUE THREAD

**Issue by Toonlink264** [klikli-dev/occultism#140]
**Describe the bug**
i was using the occultism satchel and accidentally put it inside itself.

**To Reproduce**
1. open occultism satchel
2. place satchel inside itself
3. See error

**Expected behavior**
i expected the satchel to not be able to be moved when open or inable to go inside it's inventory

**Screenshots**
it happened so fast i couldn't capture it

**System (please complete the following information):**
- Occultism Version: unsure
- OS: Windows
- Minecraft Version: 1.16
- Modpack Link and Version, or list of mods: Enigmatica 6

**Comment by klikli-dev** [comment]
@Toonlink264 thank you for your report!
May I ask you too look in your mod folder what the file name of occultism is to find the version?
This is a known bug that was fixed recently so I'd like to verify if it is on the buggy version or if we need to look into it again.
Thank you!

**Comment by klikli-dev** [comment]
Closed until we can get a repro.

**Comment by Toonlink264** [comment]
whoops i completely forgot about this. I'm on 1.0.9

**Comment by klikli-dev** [comment]
@Toonlink264 Can you try if you can reproduce this on the latest occultism version (1.0.12)? 
I could not reproduce it so far and want to verify if it is fixed or if I'm not doing it right :) 
Thank you!
