### ISSUE TITLE
[Bug] you can pipe items that are not the magic lamp into the dimensional mineshaft (with a pipe from other mods like i used from mekanism) and causing the game to crash

### ISSUE THREAD

**Issue by boboop143** [klikli-dev/occultism#141]

**Comment by klikli-dev** [comment]
@boboop143 please provide a crashlog to diagnose the issue. Generally speaking input will likely not be restricted, as e.g. kubejs could create new miner items. Instead I'll try to make any input compatible/not cause the crash

**Comment by boboop143** [comment]
[crash-2021-01-25_13.59.26-server.txt](https://github.com/klikli-dev/occultism/files/5867248/crash-2021-01-25_13.59.26-server.txt)

**Comment by boboop143** [comment]
i is fixed but i think i forgot to tell that the game crashed only when the bar of the shaft filled up
