### ISSUE TITLE
[mod compat] akashic tome duplicates when crafting  bound book in actuator

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#143]
**Describe the bug**
If you have the dictionary inside an akashic tome, the whole tome is duplicated if you use it to craft a bound book of binding in the storage actuator/remote tablet. This does not occur in a vanilla crafting table or in a Refined storage terminal crafting grid. In those two locations it crafts as intended. Tested in both sp and server

**To Reproduce**
1. Put dictionary in akashic tome
2. Craft bound book of binding
3. End up with 2 akashic tomes

**Expected behavior**
should work as it does when not in a tome

**Screenshots**

https://cdn.discordapp.com/attachments/802988228688609330/803415962330202172/2021-01-25_19-07-18.mp4
**System (please complete the following information):**
- Occultism Version: 1.0.7
- OS: [e.g. Windows] windows
- Minecraft Version:1.16.4
- Modpack Link and Version, or list of mods: enigmatica 6 version 0.3.9

**Additional context**

**Comment by SeaSaltStar** [comment]
After further testing this also applied to other nonstackable items. Not sure if the update target fixed the book or crafting overall. Wanted to add this note.

**Comment by klikli-dev** [comment]
At least in dev it fixed the crafting issue you mentioned and this issue - if issues remain after 1.0.9 let me know and I will look into it :)

**Comment by theboo** [comment]
this issue only occurs when shift clicking... https://gyazo.com/35b926466bbdef713145e3f4013f4dbd
