### ISSUE TITLE
Quark/Eidolon/Buzzier Bees Candle compat

### ISSUE THREAD

**Issue by Akaruz64** [klikli-dev/occultism#144]
Not an issue, just a request to overhaul the candle recipes to better match what the other mods have, also being able to use (primarily buzzier bees candles (at least for the moment, since, if i'm not mistaken, the'll remove them once 1.17 comes out) as does quark when you have both (quark candles get disabled if buzzier bees are installed, but the tallow drop doesn't)

To either be able to craft the candle using the other tallows (tried to add all of them the proper forge tag using a datapack but it's not working, no idea why) or be able to exchange one candle with another (if it's doable)

Nothing else. Thank you! and keep up the good work

**Comment by klikli-dev** [comment]
I'll look into that - craftability shouldn't be an issue, but using other candles in the ritual *may* be as I'm using another mod to handle the multiblock detection. One way or another we'll improve compat though :)
