### ISSUE TITLE
Occultism Oak Sapling doesnt exist

### ISSUE THREAD

**Issue by SaphieNyako** [klikli-dev/occultism#146]
**Describe the bug**
Occultism Oak Sapling doesn't exist (the requirement for trading with the Otherworld Sapling Trader).
I imagine the intended trade is "Unstable Otherworld Sapling" for "Stable Otherworld Sapling".
When trading you get a Unstable otherworld Sapling instead of a Stable one.
When getting it in create you also get an unstable sapling. The stable one doesnt exist. 

**To Reproduce**
1. Place block '...'
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**
Get a stable sapling

**Screenshots**
![2021-01-25_04 48 07](https://user-images.githubusercontent.com/77398437/106129243-5bcf5080-6160-11eb-99c7-7fb541f73780.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.0.5.jar
- OS: [e.g. Windows]
- Minecraft Version: forge 35.1.36
- Modpack Link and Version, or list of mods: Feywild

**Additional context**

**Comment by klikli-dev** [comment]
@SaphieNyako this may be a bug that existed in 1.0.5 without being noticed but in the latest public build, 1.0.8 the "stable" sapling (just named otherworld sapling vs "natural otherworld sapling") exists and can be traded by providing the trader with the natural version and waiting for 20 seconds.
