### ISSUE TITLE
Craftable book of calling doesn't work

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#148]
See https://github.com/klikli-dev/occultism/issues/115#issuecomment-767242026

**Comment by klikli-dev** [comment]
@theboo I can't repro this in 1.0.8 with just occultism. Do you still see this behaviour?
I tested with foliot transporter and foliot lumberjack, manually crafted the book, but used spawn eggs for the foliot.

**Comment by theboo** [comment]
so apparently this works just fine in survival... the reason i kept having the issue is i was in creative mode for testing, and u apparently cannot bind books of calling to new spirits while in creative. Switching to survival mode worked
