### ISSUE TITLE
The dimensional storage actuator deletes items

### ISSUE THREAD

**Issue by Keltas** [klikli-dev/occultism#15]
**Describe the bug**
When the stack size in atuator reaches 128, you can no longer interact with it. After exiting and reloading the world the stack is no longer present.
**To Reproduce**
1. Put 127 cobblestone into the actuator.
2. You can take out a stack by clicking on them.
3. Put 128 (or more) cobblestone  into the actuator.
4. You can no longer take out the cobblestone.
5. Exit the world.
6. Enter the world.
7. On opening the actuator the cobblestone is no longer present.

**Expected behavior**
For the actuator to not delete items.

**System (please complete the following information):**
- Occultism Version: 0.2.5
- OS: Windows 10
- Minecraft Version: 1.15.2
- Modpack Link and Version, or list of mods: Occultism, Patchouli, Journey Map, JEI.

**Additional context**

**Comment by klikli-dev** [comment]
That obviously should not happen, I'll investigate.

**Comment by klikli-dev** [comment]
Fixed in 0.2.6.
Will cause items in the actuator to be deleted on upgrade, as the underlying issue was the storage format.
