### ISSUE TITLE
Add fake display block to correctly show skeleton skulls in multiblock in-world previews

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#153]
skulls are rendered via tile entity, therefore not showing up in in-world previews. 
solve this by using:
- this.api.predicateMatcher() with custom block as display
- custom block uses minecraft's inventory model for skull

**Comment by theboo** [comment]
genius!

**Comment by klikli-dev** [comment]
Turns out MC is way ahead of me there - items are also not rendered regularly, instead they use a special item renderer. Going to shelf this again
