### ISSUE TITLE
feat: Greedy Familiar / Bound Attractor Ring(item magnet curio)

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#154]
had a thought for a magic based item magnet. Basically just a magnet like from other mods with curio support and a hotkey(this is the big thing other mods miss).

The lore could be a greedy spirit that wants to enter our plane to suck up items in to the other place for itself, but the occultist finds a way to bind it to a ring where the items are sucked up into the players inventory instead.

Would need support for botania's solegnolia demagnetizing flower and the demagnetizer mod, both of which have nice api for implementation.

**Comment by klikli-dev** [comment]
Sounds good! Iceboxed until I find time to do some new features, but I like it :)
