### ISSUE TITLE
new ritual/use for abras conjure

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#158]
a ritual where an afrit is summoned. similar to fantasy spirits it could grant a wish in the form of giving an item but since afrit'S are strong spirits they can decide to give you a bad item, should be datapack able to let makers of modpack change it to suit their needs, Note: will require balancing.

**Comment by klikli-dev** [comment]
Another good idea! Probably will also add a certain risk of the afrit escaping and attacking to add some risk beyond getting trash :) 

Iceboxed until next time I get around to add new features.

**Comment by klikli-dev** [comment]
I decided against this for the time being - this is more in line with some ideas I have for the future theurgy rework
