### ISSUE TITLE
Config to summon the parrot untamed

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#167]
so i have found a slight mod compat issue... When using the save your pets mod, you cannot sacrifice the summoned parrot for the drikwing because the pet doesnt actually die, u have 1 minecraft day to save the pet... leaving the only option for players in packs with that mod to find a wild parrot which can be easier said than done(and the defeats the purpose of this ritual i believe).

i was hoping you could add a config to allow the parrot to be summoned untamed.

**Comment by najlitarvan** [comment]
i think this would be better as a standart since it would allow other people to get the familiar without having them summoning it and the drikwing had troubles healing when summoned and not spawned from a spawn egg
