### ISSUE TITLE
idea for a new random summon with the djinni familiar summoning

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#168]
if we can get a chicken that follows us with foliot maybe we could get as a small chance with djinni to get a bat that would give night vision

**Comment by klikli-dev** [comment]
Lovely idea!
I do think I'd like to figure out first how to capture a familiar in a curio and provide the effects from the inventory, that way people can either have it out in the world, or as curio to avoid losing it thanks to bugs

**Comment by najlitarvan** [comment]
i was thinking about how to do the sit state, and maybe the bat could look for a nearest block from which it could hang down like this
![image](https://user-images.githubusercontent.com/43792439/106434837-59c40500-6472-11eb-859c-c3c558dbab7b.png)

**Comment by klikli-dev** [comment]
This has been implemented in #297, albeit in an even better way
