### ISSUE TITLE
mana and artifice cantrip

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#177]
using the latest versions of both occultism and mana and artifice
when ussing mana and artifice cantrip's flint and steel like cantrip the soul fire will not be created when burning a dream fruit

**Comment by klikli-dev** [comment]
I believe I am currently checking hardcoded for flint and steel or the tag.
This is for performance reasons, as listening to fire creation would require to check every block placement. 
I will check if there is a pre-made fire-related check, if there is not I *think* I will have to leave this unsolved - but let's not get ahead of ourselves :)

**Comment by klikli-dev** [comment]
There is currently no event for fire starting, so I will close this until such an event is available. I could listen to block change events, but the (potentially quite big) performance impact of that is - in my estimate - not worth supporting edge cases for the time being.
