### ISSUE TITLE
Storage Search Box Overlaps Clear Search Button

### ISSUE THREAD

**Issue by Brittank88** [klikli-dev/occultism#179]
**Describe the bug**
The 'click area' for the search textbox for dimensional storage overlaps with the "Clear Search" button, causing overlapping tooltips on hover.

**To Reproduce**
1. Set up a basic dimensional storage system.
2. Open it up.
3. Hover over the "Clear Search" button.
4. See overlap.

**Expected behavior**
There shouldn't be an overlap; the hover / click areas should be mutually exclusive.

**Screenshots**
![image](https://user-images.githubusercontent.com/24266948/107097329-d2ef9d80-6860-11eb-8b41-c7cac2cb6f0f.png)
![image](https://user-images.githubusercontent.com/24266948/107097336-d8e57e80-6860-11eb-9e95-0fec4bf51cb5.png)

**System (please complete the following information):**
- Occultism Version: `1.0.10`
- OS: `Windows 10`
- Minecraft Version: `1.16.5`
- Modpack Link and Version, or list of mods: [mod-list_2021-02-06_09.52.12.txt](https://github.com/klikli-dev/occultism/files/5935724/mod-list_2021-02-06_09.52.12.txt)

_P.S. Not related to this issue but the fact that this issue tracker allows for modpack dev help is just very cool so thank you, I wish more mod devs did this! <3_

**Comment by klikli-dev** [comment]
Good find, thanks a lot!
