### ISSUE TITLE
[Suggestion] Ability for textbox in dimensional actuator to lose focus for more than a moment

### ISSUE THREAD

**Issue by Keltas** [klikli-dev/occultism#18]
**Is your feature request related to a problem? Please describe.**
At the moment after clicking out of focus, the actuator gives you around a second to press a button without typing anything in after which it regains focus. This makes it hard to use the show recipes/uses functionality from JEI. Moreover, not sure if related but at the moment you cannot use the letter e in search bar of actuator as it closes the GUI instead. 
**Describe the solution you'd like**
Give the ability to click away from the textbox to disable sending keystrokes to said textbox until clicked onto it again. Also allow pressing "open/close inventory" key (default "e" but you can change it to be able to type "e") without closing GUI when said textbox is in focus.

**Additional context**

**Comment by klikli-dev** [comment]
I cannot reproduce this in the dev environment, but I made some  best-guess changes to the focus behaviour in 0.2.6, hopefully that fixes it. Please re-open the issue if it persists.
