### ISSUE TITLE
Add new crusher tiers: djinni, afrit and marid (no decay, higher output)

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#182]
i know it has been mentioned before quite a few times but might as well have an issue even if it gets iceboxed.

a djinni version of the crusher would be super cool... drop ores in world, crusher picks it up and outputs to an inventory... maybe 2-3x faster than the foliot and with a book for binding inventory and no decay. Would be very cool for automation... datapackable recipes would be nice for pack dev too, with options for bonus output similar to create crushing.

**Comment by klikli-dev** [comment]
To keep things a bit simpler, I think I will add a spirit that can pick up items, based on the transporter (using the new extended filter functionality from #185). Then the djinni crusher can be a relatively simple upgrade of the foliot. 
Recipes are already datapackable, but adding bonus output is a neat idea, so when I get around to that, I'll definitely add it

**Comment by klikli-dev** [comment]
- [ ] Create cleanup spirit with filter like transport spirit
- [ ] Add djinni crusher with higher speed, no decay and book of binding
- [ ] Add bonus output to crusher recipes. Should be feature a configurable minimum tier.
