### ISSUE TITLE
Server crash on summoning Foliot Lumberjack

### ISSUE THREAD

**Issue by Atriarch** [klikli-dev/occultism#183]
**Describe the bug**
On a server pack, any attempt to summon the Foliot Lumberjack results in a **java.lang.NullPointerException** crash.

**To Reproduce**
Activate the summoning process for the Foliot Lumberjack.

**Expected behavior**
The server does not crash.

**Screenshots**
![Crash](https://user-images.githubusercontent.com/3643143/107161126-5c7d9900-694f-11eb-8c91-ed66fa6853d3.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.0.10.jar
- OS: Bisect Hosting
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: 
- I can share via Discord if requested.

**Comment by klikli-dev** [comment]
I found a way to fix this, but out of interest, did you do anything special to obtain the book of binding?
Based on the crashlog the book had no foliot bound to it, which should not usually occur.

**Comment by Atriarch** [comment]
Nothing special with the book. Though, before I tried using the book of binding with the Foliot name, I tried to use a book of calling with a different Foliot name. Nothing happened, so I switched back to the book of binding. Once all five items were consumed (not including the book), about 6 seconds later, the server crashed.
