### ISSUE TITLE
Crash and Create contraption & Occultism storage deleted! (server)

### ISSUE THREAD

**Issue by VallenFrostweaver** [klikli-dev/occultism#184]
Minecraft 1.16.5
Forge 36.0.13
Create v0.3e
Occultism 1.0.9
This is on a server. The server crashed. Upon reconnecting the player noticed their Create mining operation was completely deleted and as well as the connected Occultism setup. The player then recounts what is missing here: 
"In the picture there should have been about 30 drills with equal number of chassis and a couple of chests that were attached to a pulley. Before the crash I was standing on the setup moving ore from the chest into my occult storage system."
![aaaaabbb](https://user-images.githubusercontent.com/13642054/107210830-9789d600-69fc-11eb-8115-9682fdeb500c.png)
NOTE: This bug report has also been filed on the Create Github issues listing here: https://github.com/Creators-of-Create/Create/issues/1056
Also, here is the crash report: https://pastebin.com/YGJPuy1V
EDIT: Player also commented: "If it helps I was using the storage actuator at the time. Not a stable wormhole, or the remote thing."

**Comment by klikli-dev** [comment]
@VallenFrostweaver thank you for the report.
Based on the crash report, something was removing blocks from the world (I am not familiar with create, but the log suggests LinearActuatorTileEntity, PulleyTileEntity being involved). It seems in this process the tile entity for the storage actuator was deleted before the block could drop it's items, which caused the crash.

I can prevent said crash by adding a check if the tile entity still exists when the block drops, however the removal of the blocks happens outside my code (presumably by something in create that moves/destroys blocks) so half of the puzzle remains
