### ISSUE TITLE
Stable wormhole and Dimensional Accessor don't have JEI "move items" button unlike Actuator

### ISSUE THREAD

**Issue by Keltas** [klikli-dev/occultism#19]
**Describe the bug**
Unlike in the actuator block, when using JEI in accessor or wormhole, you do not have the + button (move items) allowing you to instantly have crafting grid filled with required materials from the storage.

**Expected behavior**
When using the JEI recipe browser in stable wormhole/dimensional accessor, to have the plus button that allows to instantly move relevant items into the crafting area according to the recipe, as happens in the Actuator block.

**System (please complete the following information):**
- Occultism Version: 0.2.5
- OS: Windows 10
- Minecraft Version: 1.15.2
- Modpack Link and Version, or list of mods: JEI, Occultism, Patchouli, Journey Map,

**Comment by klikli-dev** [comment]
Fixed in 0.2.6
