### ISSUE TITLE
Storage Actuator Base causes texture of adjacent block faces to become see through

### ISSUE THREAD

**Issue by Crioca** [klikli-dev/occultism#196]
**Describe the bug**
When you place a Storage Actuator Base next to a block it causes the adjacent block face to stop rendering and become see-through. See Screenshot.

**To Reproduce**
Place a Storage Actuator Base (Note: not a Dimensional Storage Actuator) next to a solid block like Stone or Cobblestone.

**Expected behavior**
The texture of the adjacent block face should remain visible.

**Screenshots**
https://i.imgur.com/FbDuLNG.png

**System (please complete the following information):**
occultism-1.16.5-1.0.12
Windows 10
MC 1.16.4
Forge 35.1.36

Mods:

appliedenergistics2-8.2.0.jar
architectury-1.4.91-forge.jar
astralsorcery-1.16.4-1.13.9.jar
AutoRegLib-1.6-47.jar
BloodMagic-1.16.4-3.1.0-15.jar
Botania-1.16.4-411.jar
chiselsandbits-0.2.10-RELEASE.jar
citadel-1.5.3.jar
ClickMachine-1.16.3-4.2.2.jar
cloth-config-forge-4.1.3.jar
cofh_core-1.16.3-1.1.4.jar
cookiecore-1.16.2-3.0.2-9389769.jar
create-mc1.16.3_v0.3e.jar
curios-forge-1.16.4-4.0.3.0.jar
DoggyTalents-1.16.4-2.0.1.1.jar
Druidcraft-1.16.5-0.4.52.jar
eidolon-0.2.7.jar
essentials-1.16.4-2.10.0.jar
FarmersDelight-1.16.3-0.3.2.jar
forge-1.16.5-geckolib-3.0.3.jar
gravestone-1.16.4-1.0.7.jar
horsestatsmod-MC1.16.x-1.3.4.jar
iceandfire-2.1.5-1.16.4.jar
ironchest-1.16.4-11.2.10.jar
jei-1.16.4-7.6.1.71.jar
lanterncolors-1.16.3-2.1.1.jar
light-overlay-5.6.1.jar
Lollipop-1.16.4-3.2.4.jar
magicfeather-1.16.2-3.1.0.jar
mana-and-artifice-1.2.1.9.jar
mcw-bridges-1.0.5-mc1.16.5-4.jar
mcw-doors-1.0.2-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-trapdors-1.0.1-mc1.16.5.jar
NaturesCompass-1.16.5-1.8.6.jar
observerlib-1.16.4-1.5.1.jar
occultism-1.16.5-1.0.12.jar
Patchouli-1.16.4-48.jar
Placebo-1.16.3-4.3.3.jar
polymorph-forge-1.16.5-0.24.jar
Powah-1.16.4-2.3.9.jar
Quark-r2.4-305.jar
Shrink-1.16.4-1.0.7.jar
Statues-1.16.5-0.1.6.6.jar
supplementaries-1.16.5-0.9.25.jar
theurgy-1.16.5-1.0.6.jar
torohealth-1.16.4-forge-4.jar
dir.txt
worldedit-forge-mc1.16.3-7.2.1-dist.jar

**Comment by theboo** [comment]
are you using optifine by chance?

**Comment by Crioca** [comment]
No not using optifine or any shaders, nothing that'd really change the visuals of vanilla items.
