### ISSUE TITLE
Gold and Diorite are missing from recipe for miningshaft.

### ISSUE THREAD

**Issue by SaphieNyako** [klikli-dev/occultism#197]
Gold and Diorite are missing from recipe for miningshaft.

There are two recipes for granite and iron. 
And none for gold and diorite.
The recipe for diorite ended up in one of granite, and one of gold for the recipe of iron.
See screenshot. 

**To Reproduce**
1. Gold and Diorite dont show.
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/77398437/109414939-1fd51880-79b6-11eb-8ec8-3101ccae6e15.png)

**System (please complete the following information):**
- Occultism Version: 
- OS: [e.g. Windows]
- Minecraft Version:
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
Good find, there were copy/paste errors in those two recipes.

Note: You can add your own recipes via datapack too :)
