### ISSUE TITLE
[1.16.5] Crash when using Occultism machine operator

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#199]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1530

**Describe the bug**

> I have an occultism storage system with the tablet for accessing it via distance.  The storage base and a Mek energized smelter are in a force loaded chunk in my base and a djinni machine operator is assigned to the smelter.  While away from my base I tried putting a stack of clay that I'd picked up while out and about directly into the smelter via the machine operator slot.  Caused a hard crash of my game. Logged back in and repeated once to confirm the cause of the crash.

[crash-2021-03-04_00.03.49-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/6081204/crash-2021-03-04_00.03.49-client.txt)

**To Reproduce**
1. See main description.

**Expected behavior**
No crash.

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.0.14
- OS: Unknown
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Enigmatica 6, v0.4.2

**Comment by NillerMedDild** [comment]
I'm constantly amazed by your turnaround speed :P thanks!

**Comment by klikli-dev** [comment]
As it happens most of this stuff is relatively simple to solve, luckily :D
