### ISSUE TITLE
crash in storage actuator without JEI

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#20]
**Describe the bug**
crash when opening dimensional storage(through the storage block itself, the accessor or the wormhole)
**To Reproduce**
1.open dimensional storage without JEI installed
https://pastebin.com/eThfeW5w
**Expected behavior**
mod should recognize JEI isnt installed and act accordingly

**System (please complete the following information):**
- Occultism Version: 0.2.6
- OS: [windows]
- Minecraft Version:1.15.2
- Modpack Link and Version, or list of mods: occultism and patchouli

**Comment by theboo** [comment]
or list jei as a dependency on curse site... since apparently some people are crazy and play without jei :D

**Comment by klikli-dev** [comment]
That won't be necessary, I'll make it work without jei.
Issue was simply me overlooking that my check if jei is loaded in the background tries to load jei .. which it does not even need for the check, it's just an architectural flaw.

Will be fixed in the next build 0.2.7

**Comment by klikli-dev** [comment]
Fixed in 0.2.7
