### ISSUE TITLE
Occultism plants are not compostable

### ISSUE THREAD

**Issue by Wxrlds** [klikli-dev/occultism#200]
**Describe the bug**
Occultism plants are not compostable

**To Reproduce**
1. Place Vanilla Composter
2. Right click Datura Seed/Occultism Sapling/Occultism Leaves on Composter
3. Nothing happens

**Expected behavior**
Plants should go into the Composter

**System:**
- Occultism Version: occultism-1.16.5-1.0.15
- OS: Windows 10
- Minecraft Version: 1.16.5
- curios-forge-1.16.5-4.0.4.0
- jei-1.16.4-7.6.1.71
- Patchouli-1.16.4-50

**Additional context**
Seems that https://github.com/klikli-dev/occultism/issues/26 isn't fixed anymore

**Comment by klikli-dev** [comment]
Seems the way compostability is checked changed and my registration no longer works - will be fixed, thank you!
