### ISSUE TITLE
Missing entries in the lang file

### ISSUE THREAD

**Issue by Wxrlds** [klikli-dev/occultism#206]
**Describe the bug**
Some rituals/advancements have missing names. They're probably missing in the lang file

**To Reproduce**

Following rituals/advancements have missing names. Not sure if I've missed any:
- Advancement Summoning the Foliot Lumberjack
- Ritual Familiar Parrot (start, interrupt, finished)
- Ritual Wild Parrot (start, interrupt, finished)
- Ritual Summoning Dawn (start, interrupt, finished)
- Ritual Summoning Dust(start, interrupt, finished)
- Ritual Drikwing Familiar (start, interrupt, finished) (by the way the book says that it needs spider web instead of cobweb not sure if that's intended)
- Ritual Wild Drikwing (start, interrupt, finished) (also same thing with the cobweb)
- Ritual Soul Gem (start, interrupt, finished)
- Ritual Storage Stabilizer Tier 2 (start, interrupted. finished)
- Ritual Storage Stabilizer Tier 3 (start, interrupted, finished)
- Ritual Storage Stabilizer Tier 4 (start, interrupted, finished)

**Expected behavior**
Rituals/Advancements show correct names

**Screenshots**
![grafik](https://user-images.githubusercontent.com/42120270/110992095-bf5eb780-8375-11eb-8739-8fc29c64f617.png)
![grafik](https://user-images.githubusercontent.com/42120270/111001834-ce009b00-8384-11eb-8bd3-b1117591da4a.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.0.15
- OS: Windows 10
- Minecraft Version: 1.16.5
- Forge 36.0.54
- curios-forge-1.16.5-4.0.5.0
- Patchouli-1.16.4-50
- jei-1.16.4-7.6.1.71

**Comment by klikli-dev** [comment]
@Wxrlds advancements are currently not enabled in the mod, they are only set up hidden to use as an entry point with quests. As such if a modpack enables the advancements, it needs to provide texts for them.

**Comment by Wxrlds** [comment]
Then I suppose that the advancement is a separate bug as the only mods installed are the ones I listed. I think that this is on Occultism's side then. JEI isn't listed as dependency (unlike Patchouli and Curios) but I doubt that JEI is messing with only that one specific advancement from only your mod.
