### ISSUE TITLE
Configurable max stack sizes for storage actuator - WARNING: Do not change on an existing world - items may be lost!

### ISSUE THREAD

**Issue by HipHopHuman** [klikli-dev/occultism#208]
**Is your feature request related to a problem? Please describe.**
Being able to restrict stack counts to the vanilla defaults would help solve issues where other mods query the Actuator for the total amount of items stored more accurately.

**Describe the solution you'd like**
Allow the maximum stack size for each slot in the dimensional actuator to be configured to the same as Vanilla's defaults, (1 bucket, 16 enderpearls, 64 of generic items, etc).

**Additional context**
This suggestion is based on the discussion in #207

**Comment by klikli-dev** [comment]
@HipHopHuman I added two new options:

- `controllerStackSize`: Allows to modify the default max stack size of 1024 in the storage actuator.

- `overrideItemStackSizes`: Set to false to disable the controllerStackSize and instead use vanilla behaviour (like in chests, .. )

**Comment by HipHopHuman** [comment]
It takes a little while longer than usual for the world to load, but is working great once logged in - thanks for the effort, I appreciate it :)
