### ISSUE TITLE
Bugged Refined Storage Portable Grid causes exception when retrieved from dimensional storage (Enigmatica 6)

### ISSUE THREAD

**Issue by Mendanbar** [klikli-dev/occultism#210]
**Describe the bug**
Related to this RS bug: https://github.com/refinedmods/refinedstorage/issues/2765

Basically, after using the RS portable grid for a while, its NBT data becomes unmanageably large, causing it to become unstable.  In my world, I was able to store one of these bugged units in my occultism dimensional storage. But due to the huge NBT data load, any time I try to remove it from storage it kicks me from the server and shows the error in the screenshot.  The client is able to reconnect, and there are no errors in the server console.  But now I'm stuck with this unstable item in my otherwise perfectly working occultism storage with no way to remove. :(

99% RS problem, but I thought I'd mention it in case there is anything occultism can do to prevent large NBT problems like these.

**To Reproduce**
1. Make an RS portable grid (with any size disk), and use it for a while.
2. After a time, it will be impossible to right click open it in the air (this is a sign of the glitch)
3. Place in occultism storage
4. Observe as it can now not come out of storage... ever :(

**Expected behavior**
Some sort of protection... don't let it go in in the first place, or some way to protect/strip/compress NBT so it doesn't crash/overflow and break the game?

**Screenshots**
![Screen Shot 2021-03-21 at 4 18 07 AM](https://user-images.githubusercontent.com/10580609/111903236-730f1980-89fe-11eb-893b-4c7ff2889eec.png)

**System (please complete the following information):**
- Occultism Version: 1.0.15
- OS: MacOS
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Enigmatica 6 0.4.3 (RS version 1.9.12)

**Additional context**
none

**Comment by klikli-dev** [comment]
I'm going to look into this, but I think short of converting every item to it's byte buffer representation on insert and checking the size (which would quite possibly be harmful for performance) I don't think that can be prevented. I'll see if the forge discord has some input on that topic though.

**Comment by theboo** [comment]
You might be able to pull it out of the actuator through a wormhole using some sort of pipe with a fuzzy/non-nbt strict filter set to pull any portable grid

**Comment by klikli-dev** [comment]
Closing this for now - there seems to be no good way to do this, and it should be a rather rare occurrence. Please re-open if this becomes a frequent problem.
