### ISSUE TITLE
[1.16.5] Occultism Storage crafting eats honey bottles

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#211]
**Describe the bug**
If more than 4 honey bottles are placed in the crafting grid of the occultism storage and the output is shift-clicked rather than individually clicked, it only returns one honey block and 4 empty bottles and the remainder of the honey bottles disappear.

**To Reproduce**
1. Setup Occultism Storage
2. Craft Honey Blocks with 16 Honey Bottles by shift-clicking the Honey Block
3. Observe 12 missing bottles

**Expected behavior**
To get all bottles back.

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.0.16
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
- Enigmatica 6 v0.4.6 in-dev
Roughly matches this: https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3248233

**Comment by klikli-dev** [comment]
That shift-craft is my nemsis - I'll look into it :)

**Comment by NillerMedDild** [comment]
Thank you 😄
