### ISSUE TITLE
Inserting recipes with JEI's "+" button not working in Storage Actuator

### ISSUE THREAD

**Issue by recon88** [klikli-dev/occultism#213]
Whenever I try to "+" insert (JEI) a recipe into the Storage Actuator, it first switches to the Red Wool recipe and also keeps opening the recipe instead of closing the window.

GIF: https://imgur.com/a/pJzEJq1

Reproducable with just JEI and Occultism installed. 
Both latest versions.

For example:
- Make sure there's enough Gold Ingots in the Storage Actuator
- Hover over Gold Block in the JEI item list, press R
- Click the "+" button
- Recipe should now switch to another one. If you try inserting that one, it keeps reopening the recipe windows

**Comment by recon88** [comment]
Ok, that's a really weird one.
Did some investigation why it always is the Red Wool in my case.
It seems to be doing another left-click on it's own after clicking the "+" button.
If I hold the left mouse button after clicking "+" and move the cursor away from JEI's item list, it inserts the recipe properly and doesn't open the recipe window again. If I keep holding and move to another recipe, it opens that one's crafting windows after releasing the button.

Video for better explanation: https://www.youtube.com/watch?v=wpoYstoayqY

**Comment by klikli-dev** [comment]
I've seen this issue before, but looking at the video, my own UI is not actually interacting with this. It seems JEI does not correctly set clicks to handled, so it clicks "through". This may have to do with the size/width of my UI (other UIs may have the right size "catch" the click-through).

As the JEI recipe preview is not handled by the mods, but rather by JEI itself, I think in this case you should create a ticket in their GitHub (and possibly reference this ticket). If my UI somehow influences JEI to cause this click-through / if there is something I should be doing, I'm happy to look into it.

**Comment by klikli-dev** [comment]
Reopening the investigation on my end - will probably take a while for me to get to debug through both sides.

**Comment by klikli-dev** [comment]
This is solved in the latest JEI version, see https://github.com/mezz/JustEnoughItems/issues/2300
