### ISSUE TITLE
Otherworld saplings in botany pots

### ISSUE THREAD

**Issue by 0xicl33n** [klikli-dev/occultism#214]
**Is your feature request related to a problem? Please describe.**
This would provide automation of otherworld wood/leave in a compact way

**Describe the solution you'd like**
Support for otherworld trees in [botany pots](https://www.curseforge.com/minecraft/mc-mods/botany-pots). Currently, they cannot be placed in the botany pot

**Additional context**
Example for those who havent heard of them
![image](https://user-images.githubusercontent.com/2192160/113914109-003dc680-9792-11eb-91bf-6a66cb011ef0.png)

The time they take to grow is configurable depending on mod/modpacks

**Comment by klikli-dev** [comment]
@0xicl33n it is my understanding that botany pots are configured via json files - any modpack should be able to do that

**Comment by klikli-dev** [comment]
Closing this for now - feel free to comment in case I need to do anything to actually enable the botany pots datapacks
