### ISSUE TITLE
[1.16.5] Client-side crash with too much NBT in Occultism storage

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#217]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/2015

**Describe the bug**
>I clicked my Occultism tablet in my inventory while it was in use. I assume it got put in the Occultism system. I am locked out of >my server with a constant error message on login.
>
>Rolling back character data allows me to access the server but if I use my hand held Occultism tablet I am immediately >disconnected and cannot get back on. Server does not crash.

**To Reproduce**
1. Place a ton of items in Occultism storage
2. Bind a tablet to said storage
3. Put the tablet in the storage

**Expected behavior**
Being unable to put the tablet in the storage perhaps? Not sure how to fix this tbh, or if it can be :P

**System (please complete the following information):**
- Occultism Version: 1.0.17
- OS: [e.g. Windows] ?
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: [Enigmatica 6](https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3253093)

**Additional context**
Latest.log: https://pastebin.com/9PrvTfKN
![image](https://user-images.githubusercontent.com/37197624/115299937-667cfe80-a12d-11eb-83e8-6d7aacef3888.png)

**Comment by klikli-dev** [comment]
Thanks! Probably indeed easiest to disallow storing the tablet, going to look into that :)
