### ISSUE TITLE
Unable to override Patchouli entries for rituals

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#218]
**Is your feature request related to a problem? Please describe.**
I'm trying to create custom Ritual recipes for Enigmatica 6 Expert and I'm hitting a bit of a wall.

The pack is set up as two packs in one with a packmode switch to get to Expert. I've successfully injected altered recipes without issue, but I cannot seem to get the book to update in a way that'll work for this. 

Since it's two packs in one, I can't simply drop in a JSON override for the patchouli pages, since that would impact Normal mode too.  Instead, KubeJS has the ability to insert a JSON file through code, which I've used for other applications such as creating data overrides for Tetra. Unfortunately it doesn't appear to work here. I think it's a load order issue of some sort where your book data always ends up loading over top of the injected book data, so the book just never updates. 

**Describe the solution you'd like**
JEI integration for these recipes would be ideal. Otherwise, I'm not sure how else this might be resolved. 

**Additional context**
Below is the script itself if you're interested. I had tried a couple methods and then finally just tried injecting the raw JSON without anything fancy (was trying to make building the list a little easier). I'm not getting any errors, it just never shows in the book, even after a full restart.
[ritual_entries.txt](https://github.com/klikli-dev/occultism/files/6441300/ritual_entries.txt)

**Comment by klikli-dev** [comment]
That's an interesting one - could you also open this in Patchouli's Github and link here? 
I am using patchouli "as is", that is, without any changes to the load order, but it may be possible to adjust patchouli to allow for that either on their side, or with something I can do.

As for JEI integration - it's something I'd like to do, but I frankly haven't figured out how to display the ingredients properly. I'll create an enhancement for that specifically

**Comment by MuteTiefling** [comment]
Sure thing! Just ping me if there's anything else you need ^_~ Glad to help.
