### ISSUE TITLE
Copper Dust Missing Tags

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#22]
**Describe the bug**
Copper Dust is missing the tag `forge:dusts/copper` and `forge:dusts`

**To Reproduce**
N/A

I hope it's okay I deleted the rest of the fields :P

**Comment by klikli-dev** [comment]
Do other metal dusts from occultism work for you? Copper is set up and linked to forge:dusts as well

**Comment by NillerMedDild** [comment]
Nope, Silver/Iron/Copper Dusts aren't in their respective dust tags according to my game. I do see them in your datapack though, so it's probably something on my end, sorry for the trouble :)

**Comment by NillerMedDild** [comment]
Follwup: I was indeed doing something stupid, I was replacing the forge dust tags with my own ^^'
