### ISSUE TITLE
Rituals crafting first item on list without offerings

### ISSUE THREAD

**Issue by Sagragoth** [klikli-dev/occultism#223]
Rituals craft the first recipe on their list with no offerings.

**To Reproduce**
1. Create a valid ritual setup for Strigeor's higher binding
2. Insert a bound Djinn
3. Watch as the crafting starts and eventually gives the finished storage with no offerings

Tested with Eziveus as well, immediately starts crafting lenses.  May have something to do with recent changes to ritual json format.

**System**
- Occultism Version:  occultism-1.1.0.jar
- OS: Windows 10
- Minecraft Version: 1.16.5

**Comment by klikli-dev** [comment]
@Sagragoth thanks for the report - is this on Occultism only (+ convenience mods such as JEI), or with a mod pack?
