### ISSUE TITLE
Clicking on the ritual 'fake items' in JEI crashes the game

### ISSUE THREAD

**Issue by pm065** [klikli-dev/occultism#224]
**Describe the bug**
My game crashes if I click on the fake 'ritual items' in JEI: https://paste.ubuntu.com/p/qCYBrYqW2W/
For some reason, Not Enough Crashes did not stop the game simply shutting off when the crash occurred. It displayed a blank GUI screen for a bit then just closed.

**System (please complete the following information):**
- occultism-1.16.5-1.1.1
- Windows 10
- 1.16.5
- Can be reproduced with just JEI and Occultism (plus Patchouli and Curios)

**Comment by pm065** [comment]
Wait, no, actually looks like a crash report IS thrown: https://paste.ubuntu.com/p/qCYBrYqW2W/

**Comment by DeadNotSleepin54** [comment]
I am having the same issue. When players check ritual recipes in JEI it crashes on the client side, stating a nullpointerexection: registry object not present error. I am using the most up to date release on both mods (JEI & Occultisim).

**Comment by klikli-dev** [comment]
Hmm that looks like the ritual recipe itself is not loaded client side - I'll investigate. Thanks for the report!

**Comment by pm065** [comment]
Wow, thanks for such a fast fix! (:
