### ISSUE TITLE
Suggestion: Potion of the Third Eye

### ISSUE THREAD

**Issue by UmbralSurvivor** [klikli-dev/occultism#227]
**Is your feature request related to a problem? Please describe.**
The effect for Demon's Dream lasts too short to gather a good amount of items without mods that add the ability to mine multiple blocks.

**Describe the solution you'd like**
I would suggest making a Potion of the Third Eye, lasting for 45 seconds (1:30 extended). Brewed from a Demon's Dream and Night Vision potions. This would allow for a greater amount of items gathered without having to refresh the buff, while also being locked behind brewing potions.

**Comment by klikli-dev** [comment]
@UmbralSurvivor currently the intended progression is to get the infused lenses & pickaxe which replace the demon's dream fruit effect :) 

Potions is something the mod is not touching at all, so I wanted something that is a bit more in line with the rest of the content. 

I'll close this, but feel free to comment for me to reopen in case you are aware of the lenses & see further use for the potion!
