### ISSUE TITLE
[Suggestion] Allow dispensers with flint & steel to start spirit fires

### ISSUE THREAD

**Issue by lamoyrl90** [klikli-dev/occultism#233]
Just as the title says, it would be pretty handy and intuitive to allow dispensers with flint and steel to start spirit fires. This fancy little setup I put together turned out to just be an overengineered incinerator.

Thanks for your consideration! (Love the mod, by the way!)

**Comment by theboo** [comment]
fyi, spirit fire burns forever if u light it on netherrack... idk if ur just tryin to automate it or not

**Comment by klikli-dev** [comment]
@lamoyrl90 Dispensers currently do not use the Forge Event System, so I cannot intercept the flint and steel fire start event. It may be possible to replace the entire dispenser behaviour for flint and steel, but before I do further research I'd like to know if @theboo's suggestion solves your issue :)

**Comment by lamoyrl90** [comment]
Yeah, I didn't realize it would burn forever on netherrack. Makes sense. Thanks!
