### ISSUE TITLE
Pedantry: Versions are sorted in the wiki wrong

### ISSUE THREAD

**Issue by pm065** [klikli-dev/occultism#234]
They go 1.0.10, 1.0.11 (etc etc) 1.0.3, 1.0.4

To fix maybe prepend a zero on the single-digit minor releases?

So 1.0.03, 1.0.04, 1.0.05 etc.

**Comment by klikli-dev** [comment]
The versioning scheme SemVer that I am trying to apply consistently does not permit leading zeros currently.
That said, if someone figures out a way to sort the wiki pages properly (e.g. with folders per major, and subfolders per minor version) & integrate that with the build pipeline I'm happy to accept a PR :D

**Comment by klikli-dev** [comment]
Closing this as stale. Feel free to comment to reopen, or directly provide a PR.
