### ISSUE TITLE
feat: Show extract/deposit location of foliot transporter in book of calling description

### ISSUE THREAD

**Issue by Noxally** [klikli-dev/occultism#239]
Perhaps change the default foliot transporter config to be an empty blacklist rather than whitelist. 

Would also be nice to be able to see where each foliot is bound to.

**Comment by klikli-dev** [comment]
I'm leaving the default as-is for now, as this is actually shared over all jobs and spirits that use the filter and can't be configured separately - I'll have to come up with a different system if the defaults are important.
