### ISSUE TITLE
machine operators and transporters not functioning properly

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#24]
**Describe the bug**
When trying to tie a spirit to an inventory or storage actuator with the book of calling it just tells you that this spirit has left this plane of existence

**To Reproduce**
1. Place spirit
2. shift right click on inventory to attach spirit to said inventory
3. get told no

**Expected behavior**
it should work

**Screenshots**
https://gyazo.com/8f2a5619f4d0ca5ec64eeeb1dc6ab825
.
**System (please complete the following information):**
- Occultism Version: 0.2.6

**Comment by klikli-dev** [comment]
Does this bug still reproduce on the latest version 0.2.8?
I did not add any fixes for it but want to ensure it repros before going deeper into it.

**Comment by theboo** [comment]
I haven't messed with the mod much since you've been away, I'll check when I get home from work tonight!

**Comment by theboo** [comment]
can confirm same behavior in 0.2.8 https://gyazo.com/622eff6da172944597207fbc9abdd800

**Comment by klikli-dev** [comment]
Thank you! I'll dive into it given time then

**Comment by klikli-dev** [comment]
It seems the fix used in #32, when applied to the books of calling ( 5fce82e0635e70033c5e3625946e984b0e12d8a4 ) fixed this issue, I cannot currently reproduce it.  Please re-open if it remains in 0.2.10.
