### ISSUE TITLE
feat: Require previous tier of stabilizer to make the next tier

### ISSUE THREAD

**Issue by faeldray** [klikli-dev/occultism#241]
**Is your feature request related to a problem? Please describe.**
It just seems odd to me that tiers can be skipped outright if the player has the resources. Besides, it means that obsolete tiers of storage stabilizers get used for something rather than getting discarded.

**Describe the solution you'd like**
Have the recipes for stabilizers of tier 2 and up use the previous tier as an ingredient. So tier 2 requires tier 1, tier 3 requires tier 2, and tier 4 requires tier 3. This could replace the otherstone pedestals in the current recipes.

If you want to go with this suggestion, I would gladly do a pull request to make the change even easier for you.

**Comment by klikli-dev** [comment]
That's a valid point - if you could provide a PR that would be stellar!

**Comment by faeldray** [comment]
Sure thing. Before I do the PR, did you want me to change anything else about the recipes for the sake of balance, since they'll have to make all the tiers now? Like maybe use ingots for the metals instead of full blocks and/or reduce the amount of spirit attuned gems required?

**Comment by klikli-dev** [comment]
Let's keep the recipes as is for now, I'll do a balancing pass if it feels too much. 
That said, I think I'll use that opportunity to increase the default storage (as most modpacks do so anyway), so I think it should even out nicely

**Comment by faeldray** [comment]
Sounds great, I'll hopefully get the PR for you today.

**Comment by klikli-dev** [comment]
Thanks a lot!
