### ISSUE TITLE
Occultism Copper and Silver Ores are missing tag "forge:ores"

### ISSUE THREAD

**Issue by AshtonSnapp** [klikli-dev/occultism#249]
**Describe the bug**
While working on a factory using Create, a block category detector from Gauges and Switches, and the Orechid from Botania, I found that the block category detector did not recognize the occultism copper and silver ores as ores, and therefore would not enable the drills. After a quick investigation, I found that while the copper ore had the "forge:ores/copper" tag and the silver ore had the "forge:ores/silver" tag, they were both missing the "forge:ores" tag, while every other ore mined had the "forge:ores" tag.

**To Reproduce**
1. Place the Industrial Block Category Detector block from the Gauges and Switches mod.
2. Click the green "up" button on the block until the filter is set to ores.
3. Place a redstone lamp to one of the sides of the block category detector, as long as it isn't the front.
4. Place an occultism ore in front of the detector. The lamp will not light up.
5. Place a vanilla ore in front of the detector. The lamp will light up.

**Expected behavior**
I expected that the category detector would detect occultism ores as ores.

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.30
- OS: [e.g. Windows] Manjaro Linux
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 

- Astral Sorcery 1.16.4-1.13.9
- Advanced Peripherals 0.5b
- Pam's HarvestCraft 2 Fruit Trees 1.0.1
- MrCrayfish's Gun Mod 1.0.1
- Mining Helmet 2.0.1
- JEI 7.6.1.65
- Genesis 0.4.3
- Pehkui 2.2.0+1.16.5-forge
- Doggy Talents 2 task '.jar' property 'archiveVersion'
- Abnormals Core 3.1.1
- Goblin Traders 1.3.1
- Caelus API 1.16.5-2.1.3.0
- Colytra 1.16.5-5.1.1.0
- Gauges and Switches 1.2.10
- Create mc1.16.5_v0.3.1c+151
- Waystones 7.3.1
- Shutup Experimental Settings!
- mgui 3.2.0
- Journeymap 5.7.1b2
- ConnectedTexturesMod MC1.16.1-1.1.2.6
- Cooking for Blockheads 9.3.1
- Comforts 1.16.4-4.0.1.0
- Serene Seasons 1.16.5-4.0.1.91
- PneumaticCraft: Repressurized 1.16.4-2.9.3-120
- Building Gadgets 3.8.0
- McJtyLib 1.16-5.0.19
- Mapper Base 1.16.4-2.3.0.0
- Bedspreads 1.16.5-5.1.0.2
- iChunUtil 10.2.0
- JER 0.12.0.100
- Forge 36.2.4
- Blood Magic 1.16.3-3.0.6-11
- Absent by Design 1.16.4-1.3.1
- Scuba Gear 1.0.3
- The Twilight Forest NONE
- Supplementaries 1.16.5-0.12.1
- Immersive Posts 4.1.0
- Universal Mod Core 1.0.1
- Crafting Tweaks 12.2.1
- The One Probe 1.16-3.0.7
- EmbellishCraft 1.16.4-3.3.0.0
- Titanium 3.2.7
- Mana and Artifice 1.3.0.6
- Immersive Engineering 1.16.5-5.0.0-135
- Pam's HarvestCraft 2 Crops version
- SuperMartijn642's Core Lib 1.0.8
- Botania 1.16.4-411
- Personality 1.0.2
- TrackAPI 1.2
- Pam's HarvestCraft 2 Food Extended version
- Bountiful 1.16.4-3.3.1
- Libra 0.3.6
- Curios API 1.16.5-4.0.5.1
- Tetra 3.11.1
- Eidolon 0.2.7
- Somnia Awoken 1.16.5-2.1.1-beta.2
- Patchouli 1.16.4-48
- Origins (unofficial forge port) 0.7.3.1
- Pam's HarvestCraft 2 Food Core version
- Collective 2.26
- AutoRegLib 1.6-47
- FramedBlocks 2.7.2
- Tough As Nails 1.16.5-4.0.1.15
- Backpacked 1.9.0
- Backpacker 1.2.3
- Corail Tombstone 6.3.4
- Quark r2.4-305
- Sakisiil's Origins Pack (Fabric and Forge) 1.0
- Obfuscate 0.6.0
- MrCrayfish's Vehicle Mod 0.45.2
- Builders Crafts & Addition 1.16.5-20210517a
- WorldEdit 7.2.5+57d5ac9
- Starter Kit 2.4
- Sapience 1.1.1
- MrCrayfish's Furniture Mod 7.0.0-pre22
- MrCrayfish's More Furniture Mod 1.3.1
- Architectury 1.12.145
- AppleSkin 1.0.14
- Vampirism 1.7.8
- Teamlapen Library 1.7.8
- Vampirism Integrations 1.5.0
- Engineer's Decor 1.1.12
- CC: Tweaked 1.95.2
- Occultism 1.16.5-1.3.0 (wait a minute)
- ObserverLib 1.16.4-1.5.1
- Light Overlay 5.8.0
- Cloth Config v4 API 4.1.1.19
- Trash Cans 1.0.10
- Mannequins 1.0.0-1.16.5
- FastLeafDecay v25
- CodeChickenLib 3.5.1.408
- EnderStorage 2.7.1.166
- Chisels & Bits NONE
- GeckoLib 3.0.3

(note: jfc that took a while to type out. most of the mods are not relevant, but I figured you were asking for a _full_ list)

**Comment by klikli-dev** [comment]
Thanks for the report - I'll add the tags.
Iesnium makes sense, as nobody would import forge:ores/iesnium into forge:ores, it's weird though that copper and silver are not tagged, as those are standard ones.
