### ISSUE TITLE
Drop ritual results instead of adding them directly to player inventory (enables automation)

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#262]
**Is your feature request related to a problem? Please describe.**
So, I'm testing ritual automation and I've found that I can activate them fine with a fake user. And this works out wonderfully for mob summons. But it seems that for items, it tries to give the item to the fake player, resulting in it going poof. 

**Describe the solution you'd like**
Would it be possible to simply drop the item on the ground? Or am I missing something already existing in the mod that would allow these to be automated?

**Comment by klikli-dev** [comment]
Will switch it to drop :)

**Comment by MuteTiefling** [comment]
Awesome, you rock :D
