### ISSUE TITLE
Djinni Machine Operator doesn't work with chunk-loading

### ISSUE THREAD

**Issue by KGB-8375** [klikli-dev/occultism#268]
**Describe the bug**
Leaving a djinni machine operator in the spawn chunk with the storage accumulator, then starting a job does nothing until players are close enough

**To Reproduce**
1. Create djinni machine operator in spawn chunk
2. Travel outside the range
3. Start a job for the djinni
4. Nothing happens
5. get closer
6. job gets done

**Expected behavior**
Djinni should move items into/out of the machine when the chunks are loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/60853993/123864075-508f7500-d8f8-11eb-9695-be90efff0536.png)

**System (please complete the following information):**
- Occultism Version: 1.2.4 
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods:
   - [Hell-1.1.zip](https://github.com/klikli-dev/occultism/files/6736332/Hell-1.1.zip) (custom pack)

**Additional context**
On a multiplayer server

**Comment by klikli-dev** [comment]
This is not really something I can influence - the spirits are normal minecraft entities with normal minecraft AI - chunk loading/unloading is all handled automatically without my influence :)

This is likely either an issue with the chunk loading mod (unlikely, they usually just use vanilla mechanics as well), or an optimization mod that turns off AI if not near a player (very likely). 
Try to remove mods like performant and others of it's kind and see if that helps.

**Comment by KGB-8375** [comment]
Its in the spawn chunk, there is no chunk loader (yet). But Ill try removing performant and others

**Comment by KGB-8375** [comment]
Ok, I gave this a try in a singleplayer world with only the newest version of occultism, patchouli, curios, and waystones loaded. The work order worked as expected when I was at the spawn chunk, the accumulator opened as expected when I tp'd away since the spawn chunk was loaded, however when I started the work order from that distance my game straight up crashed.

Crash log:
https://pastebin.com/Rsay7pgH

**Comment by klikli-dev** [comment]
Thanks for checking - that is actually another issue, it seems it cannot find the tile entity - just to verify, you are using a storage accessor? The methods called in the log should not even be called for the accessor, so there may be a regression somehwere

**Comment by KGB-8375** [comment]
I used a storage wormhole this time, on the server I was using an accessor. If you want I can try with the accessor as well

**Comment by klikli-dev** [comment]
Can you try with the accessor as well, just to compare?
I'll look into the wormhole

**Comment by KGB-8375** [comment]
Sending the request with the accessor works as expected

**Comment by KGB-8375** [comment]
So whatever issue I had with the accessor not working must've been caused by a different mod in the pack like you theorized. It seems the only issue now is with the wormhole causing crashes

**Comment by KGB-8375** [comment]
Fun fact: Optifine's Smooth World setting causes this issue in singleplayer... but that doesn't even make sense because my server didn't have optifine... (I've been testing mods for 3 hours, still going through each one in the pack)

**Comment by KGB-8375** [comment]
So it looks like both performant and optifine's smooth world break the functionality, none of the other mods in my pack caused the issue (I'm leaving this in case someone else has the issue)
