### ISSUE TITLE
Sending an order to a machine operator from a storage wormhole when far away from the storage accessor crashes the game

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#271]
see https://github.com/klikli-dev/occultism/issues/268#issuecomment-873016756

https://pastebin.com/Rsay7pgH

**Comment by KGB-8375** [comment]
I've updated and tried again. Crash still happens on 1.5.3

https://pastebin.com/NE3Y6j1A

**Comment by klikli-dev** [comment]
It's a different crash now, which weirdly didn't happen for me.
I'll try to reproduce it though!

**Comment by KGB-8375** [comment]
It could be related to the overkill distance I tested it from (10,000,000 blocks away from spawn)

**Comment by klikli-dev** [comment]
Will be handled in #272
