### ISSUE TITLE
Crash on packet encode when ordering machine operator via wormhole large distances from storage actuator

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#272]
Appears after fixing #271

See https://github.com/klikli-dev/occultism/issues/271#issuecomment-873153207

https://pastebin.com/NE3Y6j1A

**Comment by klikli-dev** [comment]
@KGB-8375 found the culprit, thanks for the second log!

Code meant to run only on the logical server was running on logical client and caused the client to delete the location of the linked storage actuator (which is actually intended to handle serverside logic for players destroying their storage actuator).
It did not repro for me at first because I opened the wormhole in that sweet spot after it was set up but before it deleted the location ..

**Comment by KGB-8375** [comment]
Tyvm, I'll try it soon. You're the best mod dev of the year mate
