### ISSUE TITLE
Invisible spirits + scared cats

### ISSUE THREAD

**Issue by KGB-8375** [klikli-dev/occultism#283]
This is two suggestions since the second relies on the first to make much sense.

Will there ever be a system to make the spirits invisible on the first plane, requiring goggles or even more powerful items to see more powerful spirits? Or possibly disguise as other mobs?

If this does get added in the future it would also be interesting if cats/ocelots ran away from spirits even when they're invisible/disguised, giving a way for players to detect them without proper equipment.

I don't expect this to get added soon since its not super useful, but would be neat since it would be more like the books. It could be useful for future content, if bodyguards were added for example.

**Comment by klikli-dev** [comment]
While this is a fun idea, it's currently not planned - I did toy with the idea a bit when implementing the otherworld blocks and goggles, but it would require quite a lot of time to implement for a feature that would be mainly visual in nature, so I decided against it.
