### ISSUE TITLE
Change how shift-crafting gives items to player (possibly reduces negative interactions with crafting optimization mods)

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#284]
so currently when you shift click to craft a stack of something in the matrix/accessor, it will craft the stack but do it one item at a time.. It is fairly quick in SP, but when you're on a busy server it can be painfully slow haha.. example here: server running at 16 tps

https://gyazo.com/6e0db78337471080adcf7287fd2d1583

Suggest to make it craft the whole stack/whatever is available if under a stack at once similar to RS or even a vanilla crafting table.

**Comment by klikli-dev** [comment]
I'll have to look into this again - I already had it on my todo list but ended up not implementing it. I do recall doing it like vanilla doesn't work, but I don't recall why - will look into it!
