### ISSUE TITLE
[1.16.5] Server Crash with Crusher Demon and Emendatus Enigmatica

### ISSUE THREAD

**Issue by MokahTGS** [klikli-dev/occultism#287]
We are getting a bad server crash with the Enigmatica 6 modpack and using the crusher demon.  Giving the demon an ore chunk from the Emendatus Enigmatica mod causes the crash.

MC 1.16.5
Forge 36.1.31
occultism-1.16.5-1.5.4
EmendatusEnigmatica-1.16.5-1.2.7

Crash report: https://pastebin.com/dX8LhfsB

**Comment by NillerMedDild** [comment]
I believe this is fixed already, in 1.5.5: https://github.com/klikli-dev/occultism/wiki/1.5.5

**Comment by KGB-8375** [comment]
Yes this is a known issue that was already fixed. Please try updating the mod
