### ISSUE TITLE
Ore crushing guy crashes my game

### ISSUE THREAD

**Issue by DrFriendlyFire** [klikli-dev/occultism#294]
Occultism: 1.5.4
OS: Windows
Version: 1.16.5
Modpack: Engimatica 6 V: 0.5.4

I can summon the ore crushing guy easily, but every time that I give him ore, when he finishes and spits out the ore, it crashes my server every time without fail. I've tried it gold and iron.

**Comment by klikli-dev** [comment]
This was fixed in 1.5.5, see https://github.com/klikli-dev/occultism/issues/287
