### ISSUE TITLE
Single Player Crash When Generating World

### ISSUE THREAD

**Issue by Darkfiend009** [klikli-dev/occultism#3]
**Describe the bug**
Client crash when generating a new Minecraft world. I added Occultism to a modpack i am developing. Here is the crash log: https://pastebin.com/EENCsXfw

**To Reproduce**
1. Load modpack
2. Click 'Single Player'
3. Create world
4. Crash while generating world

**Expected behavior**
World to generate without crashing

**System (please complete the following information):**
 - OS: Windows 10
- Minecraft Version: 1.15.2, Forge 31.1.63, Occultism 0.2.1
- Modpack Link and Version: See crash log above. Modpack still in development

**Additional context**

**Comment by klikli-dev** [comment]
Can you try to reproduce this on a clean instance with no other mods?
The error it throws is somewhat nonsensical (technoblabber incoming) as the mentioned method exists even on vanilla entities. Might be that another mod is trying to access-transform it.

**Comment by klikli-dev** [comment]
Alpha 0.2.2 *might* fix this issue. Please test it once it's available on forge and let me know if it worked. Thank you!

**Comment by lag42** [comment]
i was also getting a crash when creating a world with an extremely similar looking crash log, 0.2.2 did fix it for me
