### ISSUE TITLE
[Feature Request] Optional boolean in data pack crushing recipes

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#301]
**Is your feature request related to a problem? Please describe.**
If crushing spirits are given recipes for things that should only ever be 1:1, the higher tier ones still multiply output. For instance, 1 ingot becomes 3 dust if a marid processes it.

**Describe the solution you'd like**
Add an optional flag in the datapacks that can exclude that recipe from multiplication. It still works in the higher tier crushers to get faster outputs, but no multiplication.

**Additional context**
That's all. Thanks as always :D

**Comment by klikli-dev** [comment]
Oh boy that's an important one, completely missed that. Thanks!

**Comment by MuteTiefling** [comment]
Many thanks!
