### ISSUE TITLE
Portable pentacles

### ISSUE THREAD

**Issue by KGB-8375** [klikli-dev/occultism#311]
**Is your feature request related to a problem? Please describe.**
The player constantly has to redraw every circle by hand, making it difficult to make "ritual" based actions like setting the time to night or the weather to rain in different locations without the hassle of preparing another beginner-level pentacle.

**Describe the solution you'd like**
It would be nice if the player could pick up and move the whole pentacle using a soul-gem-like item on the golden sacrificial bowl, then be able to place the circle down again somewhere else.

One idea of how to add this would be an infused brush that uses a spirit to clear out all chalk symbols in an 8 block radius of the sacrificial bowl, and have infused chalk that can instantly draw the last circle it "remembers". Before clearing the circle you would shift+click with the infused chalk on the golden sacrificial bowl to memorize the circle. Extra items such as soul crystals and candles would be either be picked up manually or could break when the brush is used leaving the items left on the ground, and when the infused chalk is used it could automatically highlight where those items should go.

**Additional context**
The pentacles in this mod remind me a lot of circle magic from witchery, which had a very similar feature with their circle talismans.

**Comment by klikli-dev** [comment]
At first I wasn't all that into this - the "grind" behind the pentacles is part of the balance - but the more I think about it, the more I like it as a mid-tier feature. I'll look into it given time!

**Comment by klikli-dev** [comment]
After further consideration I decided against it. Occultism already has relatively high yield for the required work and resources, so a lack of portability is something of a balancing factor. 

This might make sense as an add-on mod, so if someone wants to develop it I can assist if anything needs to be done on occultism's side to make it compatible, but won't make it into the main mod.
