### ISSUE TITLE
Otherstone Trader Recipe doesn't respect output quantity 

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#315]
**Describe the bug**
Otherstone Trader Recipe doesn't respect output quantity 

**To Reproduce**
Trade stone with Otherstone trader. Four stone gets one otherstone.

**Expected behavior**
Recipe JSON suggests it should give 2 otherstone. 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.7.1
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Small instance with only Occultism, JEI, Curios, and Patchouli,

**Additional context**

```{
  "type": "occultism:spirit_trade",
  "ingredients": [
    {
      "item": "minecraft:stone"
    },
    {
      "item": "minecraft:stone"
    },
    {
      "item": "minecraft:stone"
    },
    {
      "item": "minecraft:stone"
    }
  ],
  "result": {
    "item": "occultism:otherstone",
    "count": 2
  }
}```

**Comment by MuteTiefling** [comment]
And, if not a bug, then consider this a feature request as I'd like to be able to increase his output for e6e as a considerably cheaper way of getting otherstone compared to the fire.

**Comment by klikli-dev** [comment]
Definitely a bug! The change was made to enable making the trader more useful than the fire .. will look into that!
