### ISSUE TITLE
Specify item use and sacrifice in jei

### ISSUE THREAD

**Issue by khjxiaogu** [klikli-dev/occultism#317]
**Is your feature request related to a problem? Please describe.**
Ritual receipt is very useful in jei, but when an item use or sacrifice is needed, it just say "require sacrifice" and provide no further infomation. I have to check out the book to find out what else is needed, which is not convenient.

**Describe the solution you'd like**
When an item use is needed, display what item have to be use instead of the default flint and steel.
When a sacrifice is needed, show text message about the sacrifice under the current "require sacrifice" item.

**Comment by klikli-dev** [comment]
Thank you - I've been planning an overhaul for a while, I created an omnibus ticket for how rituals should work: https://github.com/klikli-dev/occultism/issues/319
