### ISSUE TITLE
Show the shape of pentacles in jei

### ISSUE THREAD

**Issue by khjxiaogu** [klikli-dev/occultism#318]
**Is your feature request related to a problem? Please describe.**
When looking for ritual receipts in jei, It would tell me what pentacle is needed. By the name, it's not easy for newcomers to find the specific pentacle.

**Describe the solution you'd like**
Add receipt of pentacles about how they look like. Or just show its formation.

**Comment by klikli-dev** [comment]
Thank you - I've been planning an overhaul for a while, I created an omnibus ticket for how rituals should work: https://github.com/klikli-dev/occultism/issues/319
