### ISSUE TITLE
Cannot search for specific enchanted books with prefix `#`

### ISSUE THREAD

**Issue by scotty9090** [klikli-dev/occultism#323]
Using the storage system, I can search for "Enchanted Book" but when specifying the enchantment name (e.g. "Protection") no results show up.  

It would be great if this could behave more inline to how JEI does where you can search for a specific enchantment name - Protection or Protection V and be able to see only those books.  I haven't tested potions but similar functionality would be useful there as well if it doesn't already exist.

**Comment by klikli-dev** [comment]
Turns out this stopped working at some point when either vanilla or forge made slight changes to the text component system. Will be fixed in next patch.
