### ISSUE TITLE
Server hang/crash when replacing lumberjacks's storage

### ISSUE THREAD

**Issue by Meegooo** [klikli-dev/occultism#329]
**Describe the bug**
If you replace lumberjack's storage, in singleplayer client crashes, in multiplayer server hangs and then gets killed by watchdog. 

**To Reproduce**
1. Get a foliot lumberjack
2. Place a chest, bind foliot to the chest.
3. Wait until foliot deposits some items (might not be necessary)
4. Break the chest.
5. Wait until foliot comes to the now missing chest with an item in hand.
6. Place new chest in the same location where the old chest was.
7. Crash.

**Expected behavior**
No crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.8.0
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Reproducible just with occultism and the dependencies (sidenote, curios is missing from mods.toml and not having one crashes the game)

**Additional context**
Might also affect janitor and every spirit that deposits items, but I tested only for lumberjack.
[Crash log](https://gist.github.com/Meegooo/d5e119723dd4958bd33d31832f6a1be7)

**Comment by klikli-dev** [comment]
Thanks a lot for the report & log - will look into it!
