### ISSUE TITLE
Windows Security Center flagging update as a trojan

### ISSUE THREAD

**Issue by Maghorn** [klikli-dev/occultism#337]
**Describe the bug**

**To Reproduce**
1. Start mod update in Curseforge
2. Get I/O error
3. Windows sends virus alert

**Expected behavior**
The update would be installed without issue.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/89198477/130065165-825a4669-78aa-4056-812c-36883c624551.PNG)

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.8.2
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: N/A

**Additional context**
N/A

**Comment by klikli-dev** [comment]
Are you sure it is this mod and not another file that curseforge is downloading?
When downloading the 1.16.5-1.8.2 jar file from curseforge and scanning it with windows defender there is no result.
Similarly virustotal (which includes windows defender) does not report anything on the file: https://www.virustotal.com/gui/file-analysis/MDZkNDFiODgyMWE1MzBlZmY0NzQyZWNkNDllMmJlZjc6MTYyOTM3NTU5MQ==/detection

**Comment by Maghorn** [comment]
I can't confirm where it was coming from, but it looks like Windows is ignoring the file it was flagging before? I just tried the update again and didn't get any errors.
