### ISSUE TITLE
Should words in $(this,thing,item)...() scope be translated in ru_ru?

### ISSUE THREAD

**Issue by Dimagreg** [klikli-dev/occultism#352]
There are multiple instances of words in $ scope that are not translated for example $(thing)Third Eye$() in **src/main/resources/data/occultism/patchouli_books/dictionary_of_spirits/ru_ru/entries/getting_started/third_eye.json** that i assume are links in the dictionary book and i observed that in zh_cn translation those words are translated but i believe this would create a conflict if they all do not have the same name. Also there is a direct link such as $(l:getting_started/datura)Demons's Dream$(/l)

What are those $(this, thing, item, o ,bold, l)...() scopes and what are they for?

**Comment by klikli-dev** [comment]
@Dimagreg that is a great question!
These are formatting directives for patchouli, you can find an overview here: https://github.com/VazkiiMods/Patchouli/wiki/Text-Formatting-101, the text within the directives will be formatted differently, or link to the specified page. 

The text within "$()" [$(xyz)...$() -> the ...] can be freely translated, anything within the "(" and ")" [$(...)xyz$()-> the ...] should not be translated, as that would break the links, e.g. `l:getting_started/datura` is a link that should not be changed
