### ISSUE TITLE
Thunder spirit job id in ritual does not match actual job id

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#357]
**Describe the bug**
Minor issue :D Ritual for the thunder weather spirit is missing a translation entry

**Screenshots**
![image](https://user-images.githubusercontent.com/9543430/131254794-01c7bb5c-1fb5-474d-a9aa-b583706a57ef.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.9.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Enigmatica 6

**Additional context**

**Comment by klikli-dev** [comment]
Seems I used two different IDs in the recipe vs for the actual job - thanks!
