### ISSUE TITLE
Unable to Summon Unbound Afrit

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#358]
**Describe the bug**
The ritual completes, but no mobs appear. Seems to be the case for the Wild Hunt too.

**To Reproduce**
1. Place golden bowl
2. Insert Unbound Afrit dummy
3. Alternatively build out the entire ritual with proper items

**Expected behavior**
A big meany to appear to kick my face.

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.9.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Noticed in Enigmatica 6, confirmed in fresh pack with only JEI and Occultism.

**Comment by klikli-dev** [comment]
Seems *someone* forgot to include the entity to summon in the ritual recipe .. oops!

**Comment by MuteTiefling** [comment]
^_^
