### ISSUE TITLE
Rituals are free if performed a second time

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#360]
**Describe the bug**
When a ritual is performed once, it consumes the items and gives output as expected. If, however, the same ritual is run a second time, the items are not consumed and the result is given for free. It seems to continue working for free until the game restarts. 

**To Reproduce**
1. Build out Strigeor's Higher Binding
2. Place items for a Soul Gem
3. Wait for the ritual to complete
4. Place more items for a second Soul Gem
5. This time the ritual will run for a while, but not consume the items

**Expected behavior**
Rituals to consume their items each run

**Screenshots**
https://streamable.com/f2fkql

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.9.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Test pack with JEI and Occultism only

**Comment by MuteTiefling** [comment]
Ah, just noticed this too, when I look in JEI now after completing the ritual once, this is what's shown: 
![image](https://user-images.githubusercontent.com/9543430/131268733-d3d004b9-3610-49e6-b8d5-78b25e95ce2d.png)

**Comment by klikli-dev** [comment]
Thank you, especially for that second screenshot, I think I have an idea of what is going on. Seems like the recipe itself is "fulfilled", instead of a copy!
