### ISSUE TITLE
Summon Foliot: Janitor Summons Pig

### ISSUE THREAD

**Issue by SjessN** [klikli-dev/occultism#365]
**Describe the bug**
Summon Foliot: Janitor Summons Pig

**To Reproduce**
1. Perform the ritual

**Expected behavior**
I expected a janitor but got a pig.

**Screenshots**

**System (please complete the following information):**
- Occultism Version:  1.9.2
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Verified in empty modpack. Just occultism
![2021-08-30 (2)](https://user-images.githubusercontent.com/57833143/131320352-8844d1c4-6bfc-447f-a1cb-9746c6a64842.png)

**Comment by klikli-dev** [comment]
I'm so sorry but this is hilarious haha.
Copy paste error in the recipe! 

Fixed in #362

**Comment by SjessN** [comment]
oh Jeeze. I failed at bug reporting. Sorry! I didn't see you already had it dealt with. I need more coffee.
