### ISSUE TITLE
Obsidian duplication bug when mekanism is installed

### ISSUE THREAD

**Issue by Morilli** [klikli-dev/occultism#375]
Mekanism adds their own version of obsidian dust as well, which can be created in their `Enrichment Chamber`, which creates 4 `Obsidian Dust` from one `Obsidian`.

Usually, you would then need 4 of those to create one `Obsidian` again, but Occultism adds a recipe which smelts 1 `Obsidian Dust` into one `Obsidian`, allowing to effectively duplicate Obsidian (at the cost of some energy, I suppose).

I believe a relatively simple fix for this would be to make mekanism and occultism `Obsidian Dust`s incompatible, so that mekanism `Obsidian Dust`s don't get caught by Occultism's recipe.

**Comment by Morilli** [comment]
Hm, I can definitely try out kubejs to solve the issue for now. I wanted to test with some other mods that add obsidian dust or the likes but seems that every other such mod is 1.12 only.

I believe the crucial issue here is that it's possible to smelt one obsidian dust back to obsidian. Haven't invested too much into Occultism but it seems that obsidian dust not does *need* to be added to the ore dictionary, as it's not intended for mass-production or usage purposes, right?

**Comment by klikli-dev** [comment]
After looking into this (and your KubeJS) solution, I think you are absolutely right - the smelting back is the problem, and to be honest, I think I can remove this in general. I initially added it so you could reclaim your obsidian, but the utility of that is minimal, and it carries the risk of recipe weirdness with other crushing mods

**Comment by Morilli** [comment]
Well, thanks for "fixing" this!
