### ISSUE TITLE
[1.16.5] Crash On Summoning Djinn To Clear Weather 

### ISSUE THREAD

**Issue by kjj194** [klikli-dev/occultism#381]
**Describe the bug**
When summoning the Djinn to clear the weather in a Compact Machines dimension it crashes the server.
**To Reproduce**
1. Create Summoning ritual in compact machine dimension
2. Ritual Completes 
3. Server Crashes

**Expected behavior**
Djinn is summoned and nothing happens because there is no weather to clear.
**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.7.2
- OS: [e.g. Windows] Windows Client, presumably linux server (Through Cryhosting)
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Enigmatica 6 0.5.9 https://www.curseforge.com/minecraft/modpacks/enigmatica6

**Additional context**

**Comment by kjj194** [comment]
Took a minute but I got a pastebin of the crash report. https://pastebin.com/M6EakQqE

**Comment by kjj194** [comment]
If anyone else experiences this crash loop running /kill @e[type=occultism:djinni] from the server console while joining will kill all the djinns currently in world which fixes the problem.

**Comment by klikli-dev** [comment]
Thanks for the report - the clear weather functionality is based on the clear weather commands, but compact machines has (which makes sense) a slightly different world setup. I'll adjust
