### ISSUE TITLE
Can only access one actuator from accessor even if you have 2 accessors tied to different actuators

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#382]
**Describe the bug**
If you have 2 storage actuators, and a remote accessor for each in your inventory, you can only access one of the actuators even if you switch to a different one in your hotbar. The only way to access the 2nd actuator remotely is to get the first one completely out of your inventory

**To Reproduce**
Steps to reproduce the behavior: shown in gif
https://gyazo.com/b99893d42a30b6d63905c9a6932f0929

**Expected behavior**
should be able to access multiple actuators with multiple accessors in your hotbar

**System (please complete the following information):**
- Occultism Version: 1.10.1

**Comment by theboo** [comment]
just realized i had my hotbar cutoff in the gif... but i was switching between accessors lol

**Comment by klikli-dev** [comment]
Closed in 3d75dcb04b986487a3048066f1c4ec8f2ed45256
