### ISSUE TITLE
Latest version of Occultism breaks vanilla crafting recipes (On Multiplayer)

### ISSUE THREAD

**Issue by SephirothWS** [klikli-dev/occultism#392]
**Describe the bug**
Occultism 1.11.0 appears to disable many other vanilla crafting recipes. Probably a side effect to the new recipe handler added in by the mod.

**To Reproduce**
1. Install Occultism
2. Install JEI
3. Launch Game
4. Connect to a dedicated server.
5. Check recipe for Oak Planks
6. ???
7. Profit

**Expected behavior**
Should be able to see the ability to craft oak wood to oak planks.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.11.0
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
@SephirothWS a few questions to help narrow this down:
- does this also happen in SP, or only when connecting to a server?
- can you please provide a log of both client + server for the time when this happens?
- 
Thank you!

**Comment by SephirothWS** [comment]
Singleplayer does not experience this issue. Only when connecting to a server.
I do not have access to server logs, unfortunately.

**Comment by klikli-dev** [comment]
I see - thank you, that is already a good start. I'll see if I can reproduce it on my end :)

**Comment by SephirothWS** [comment]
For a bit more information, the pack is a currently in development pack which doesn't have a public release, however Our environment runs Forge version 36.2.4 on 1.16.5. Attached is the pre-generated modlist.html file in case you wanted to see what other mods we have in our setup. Just rename it to .html and load in browser.
[modlist.txt](https://github.com/klikli-dev/occultism/files/7134524/modlist.txt)

**Comment by klikli-dev** [comment]
thanks! As it turns out it does reproduce in a "vanilla" occultism setup, and even in 1.10.x - the good news is, it should make it a lot easier to find

**Comment by SephirothWS** [comment]
Excellent, glad to help you pinpoint the issue. :) Keep up the AMAZING work!

**Comment by klikli-dev** [comment]
Thanks a lot - and a patch is already building, should be on curseforge within the hour
