### ISSUE TITLE
All rituals are waiting on item use and will not complete

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#400]
**Describe the bug**
When performing any ritual, after placing the book/gold bowl item, the ritual will start but have grey particles floating down as if it is waiting on a sacrifice. This happens on any ritual, including ones that do not need a sacrifice(like foliot crusher). And for rituals that do need a sacrifice, it will not continue the ritual after the sacrificial mob has been murderfied.

This is the same issue that was reported by `Brugged` on discord, meant to test yesterday after work but forgot haha

looks like the issue started on version 1.10.4 where right click behavior was changed xD

**Screenshots**
you can see trying to summon janitor foliot that the ritual starts but just sits there with grey particles floating downward
https://gyazo.com/fd0c4516e10c4516beb913b41305eccf

**System (please complete the following information):**
- Occultism Version: 1.11.1 but the original report was on version 1.10.4, no other mods besides dependencies are needed to reproduce

**Comment by klikli-dev** [comment]
The "item to use"-fix broke it 🙄 
Easy fix, at least
