### ISSUE TITLE
Grinder Killing Cthulhu Familiar Crashes

### ISSUE THREAD

**Issue by laserjet25** [klikli-dev/occultism#428]
**Describe the bug**
When Cthulhu familiars are targeted by a Draconic Evolution mob grinder, the game crashes.

**To Reproduce**
1. Create a mob grinder with Draconic Evolution
2. Spawn a Cthulhu in the grinder room
3. Wait for a Cthulhu familiar to spawn

**Expected behavior**
The game should not crash.

**System (please complete the following information):**
- Occultism Version: 1.11.3
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
[Monumental Experience](https://www.curseforge.com/minecraft/modpacks/monumental-experience)

[Crash Report](https://github.com/klikli-dev/occultism/files/7181838/crash-2021-09-14_19.43.19-server.txt)
**Additional context**

**Comment by vemerion** [comment]
Whoops, completely missed that RandomPositionGenerator.findRandomTarget() can return null! Should be an easy fix :)

**Comment by klikli-dev** [comment]
Oi that is easy to miss :D
