### ISSUE TITLE
Getting duplicate familiars from rituals

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#431]
**Describe the bug**
Getting duplicate familiars from rituals

**To Reproduce**
1. Set up Hedyrin's Lure
2. Insert a Hopper, Chest, Iron Block, and Dispenser
3. Initialize Greedy Familiar Ritual
4. Kill a Zombie

**Expected behavior**
Get a single Greedy Familiar

**Screenshots**
https://streamable.com/0zyzei

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.11.4
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Occultism, JEI, Curios, Patchouli

**Comment by theboo** [comment]
can confirm same issue as the one i mentioned in discord the other day in discord... thought it was only when using the dummy ritual items, but seems it applies to the actual ritual itself when summoning familiars.

tested with base recipes in occultism ver 1.11.7

https://gyazo.com/2d974a515e693882d3ad5d12dd79f56d
