### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by Traverse-Joe** [klikli-dev/occultism#435]
**Describe the bug**
Ticking Entity seems to be caused from Entity Blaze

**To Reproduce**
1. Kill Blaze
2. Repeat till crash.

**Expected behavior**
No crash. 

**System (please complete the following information):**
- Occultism Version: 1.13.0
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: https://cdn.discordapp.com/attachments/883907557868072971/889254182043926528/A_Simplex_Life-2.5.1.zip

**Additional context**
https://gist.github.com/Traverse-Joe/ce46c1518a976ab113fd696ced07a7b4

**Comment by theboo** [comment]
Ticking entity in that crash report is a wilden hunter from ars nouveau

**Comment by theboo** [comment]
do you happen to have the greed effect from a dragon familiar when this is happening? looks like something is borked there xD is new

https://github.com/klikli-dev/occultism/blob/01b9cd51b8eaf868f901ea50efebfaeaecae13b6/src/main/java/com/github/klikli_dev/occultism/handlers/LootEventHandler.java#L76

**Comment by Traverse-Joe** [comment]
currently i haven't even started Occultism yet so i shouldn't have the Dragon_Greed

**Comment by Traverse-Joe** [comment]
I think its because when a player dies they drop exp and its not checking for EntityPlayer / instance of EntityPlayer but not sure we downgraded for the time being because it was a recuring crash every time someone died

**Comment by klikli-dev** [comment]
> I think its because when a player dies they drop exp and its not checking for EntityPlayer / instance of EntityPlayer but not sure we downgraded for the time being because it was a recuring crash every time someone died

That was it exactly - I wasn't aware killing player could be null in this event.
