### ISSUE TITLE
infused lenses in Otherworld goggles page in patchouli book has blank recipe and doesnt show pentacle

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#436]
recipe page for the infused lenses in otherworld goggles page in patchouli in occultism 1.13 with no other mods outside of dependencies:

![image](https://user-images.githubusercontent.com/3585761/133950507-51096198-a3e9-41bb-b404-d7c3102c8eb9.png)

**Comment by klikli-dev** [comment]
Excellent recipe! :D
