### ISSUE TITLE
Allow lumberjack to pick up more than one "bundle" before returning.

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#438]
currently the lumberjack spirit can only pick up one item "bundle"(i forget what the clumped together items are called haha) at a time, making him need to take many trips his attached storage to pick up all the items from large trees. 

Would be nice if he could pick up multiple bundles in an area until he reaches a full stack of what he is picking up or runs out of that item in the area before returning to the storage to offload.

**Comment by klikli-dev** [comment]
I currently don't plan to do this, as it would complicate the AI further - but might revisit/reopen later.
