### ISSUE TITLE
Allow lumberjack to pick up items in the forge:fruits tag

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#439]
currently(as of occultism 1.13) the lumberjack leaves all fruits on the ground including apples from oak trees. 

Suggest to add items in the `forge:fruits` item tag to the list of items he will pick up. This should cover most modded fruits as well.

**Comment by klikli-dev** [comment]
Hmm, forge:fruits is already in the list of items / has always been. 
I'll have to look into why he's ignoring them
