### ISSUE TITLE
SpiritFire Spreading

### ISSUE THREAD

**Issue by AveryFae** [klikli-dev/occultism#44]
We were attempting the Occultism rituals and the like and had spirit fire on the ground, firetick has been set to not spread, but spirit fire doesn't seem to respond to this. It's run rampant through our home area and into the biomes close by, and we've had to fight to keep it under wraps because even just one spot of spirit fire will spread like crazy. Water does extinguish it, but if firetick has been set to not allow fire to spread, spirit fire should respond to this command, which it doesn't appear to do. 

We did not capture any screenshots (I honestly didn't find this bug report until after the fact), and we don't dare to replicate how it started because of how much of a pain it was to get it under control. Spiritfire's been used before without problem, so we're uncertain as to how this came to be. This is simply to bring awareness to it and to see if a solution can be found as it makes it very discouraging to continue down the Occultism path. 

Thank you for your time.

**Comment by daniel-eder** [comment]
Which version of the mod has this been tested on? 0.2.10 removes spread code, but due to the spreading being one big chunk of code I might have missed some cases.

**Comment by klikli-dev** [comment]
Which version of the mod has this been tested on? 0.2.10 removes spread code, but due to the spreading being one big chunk of code I might have missed some cases.

**Comment by AveryFae** [comment]
0.2.8 is what our current one is, so thank you for the information! We'll update our mod and then inform you if the problem persists. 

Sent from Yahoo Mail on Android 
 
  On Mon, Jul 6, 2020 at 2:22 AM, Kli Kli<notifications@github.com> wrote:   


Which version of the mod has this been tested on? 0.2.10 removes spread code, but due to the spreading being one big chunk of code I might have missed some cases.
