### ISSUE TITLE
Fillet Knife Dupe

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#442]
**Describe the bug**
Shift-clicking the result of a fillet knife and a fish in an occultism storage results in the knife being duplicated.

**To Reproduce**
Steps to reproduce the behavior in screenshots:

Required things:
![billede](https://user-images.githubusercontent.com/21295394/134225358-5c93371f-ff19-4617-82ac-cfc7121172ac.png)

Getting ready to craft:
![billede](https://user-images.githubusercontent.com/21295394/134225544-1718f9dd-fc6b-4f08-9606-ba98099867bb.png)

After shift-clicking result:
![billede](https://user-images.githubusercontent.com/21295394/134225566-9f500c76-65e2-485d-831d-bb28ae7ef880.png)

Both recipe and knife are from Aquaculture. I think the issue is that the knife is unbreakable, but the recipe may be trying to consume durability.

**Expected behavior**
For the amount of knives to remina constant :P

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.13.2
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Enigmatica 6 v0.5.11 in-dev

**Additional context**
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3293

**Comment by klikli-dev** [comment]
That's a lovely one - let's see if I can get Aquaculture set up in my dev env :)

**Comment by NillerMedDild** [comment]
Dayum, nice work!
