### ISSUE TITLE
[1.14.0] Startup crash

### ISSUE THREAD

**Issue by katur239** [klikli-dev/occultism#447]
**Describe the bug**
Failure message: Occultism (occultism) encountered an error during the load_registries event phase
		java.lang.ExceptionInInitializerError: null

Exception message: java.lang.NoSuchFieldException: craftingRemainingItem

**To Reproduce**
During startup

**System (please complete the following information):**
- Occultism Version:  1.14.0
- OS: [e.g. Windows] W 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 

**Additional context**
https://pastebin.com/dPM9JWZd

**Comment by optmisticnihilist** [comment]
Similar error at startup and same specs. reverting back to 1.13.3 resolved it.

[crash-2021-09-25_11.36.42-fml.txt](https://github.com/klikli-dev/occultism/files/7230053/crash-2021-09-25_11.36.42-fml.txt)

**Comment by klikli-dev** [comment]
Thanks for the logs - these are related to the mapping changes. Weirdly these field names are still shown unchanged in my dev env and do not cause a crash there, so I'll have to investigate what is going on there

**Comment by klikli-dev** [comment]
@optmisticnihilist @katur239 the next patch will close this issue - please report back if it still persists after this!
