### ISSUE TITLE
Recipes gets filled from JEI without pressing + in Dimensional Storage

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#452]
**Describe the bug**
When inside the Dimensional Storage Actuator, if you look through recipes in jei, the crafting grid will automatically be filled with the latest thing you looked at, whether you clicked the plus or not.

**To Reproduce**
1. Make dimensional storage
2. Make sure you have Iron Ingots in the storage (just as an example)
3. Look up the recipes for Iron Bars in JEI

**Expected behavior**
For the grid not be filled

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.14.2
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Enigmatica 6 0.5.14 in-dev

**Additional context**
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3326

**Comment by klikli-dev** [comment]
That's almost magical. I'll look into it - but it's super weird. The recipe filling is triggered by JEI, I don't think there is even an intended codepath that lets a mod do that.

**Comment by NillerMedDild** [comment]
Ah cool, thanks for the fix!
