### ISSUE TITLE
"hidden" advancements are now shown in advancement tab

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#457]
in occultism v1.14.2 the "hidden" advancements for pack devs are now shown in the advancement menu along with the familiar advancements, and they dont look so nice xD

![image](https://user-images.githubusercontent.com/3585761/135017282-f788425c-ea8d-4708-bb84-1c34560182b1.png)
![image](https://user-images.githubusercontent.com/3585761/135017287-73a66eba-a26d-4178-8397-45b0802b0a02.png)

**Comment by klikli-dev** [comment]
Opps, a bit of a mixup.
The root should actually be visible now but somehow the text got lost .. and the crusher was a testing side effect :D
