### ISSUE TITLE
Sapling trader not giving stable saplings

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#46]
**Describe the bug**
Putting unstable saplings in a sapling trader's inventory seems to do nothing. The spirit just holds the sapling for the 30 seconds it is alive and then dies returning the unstable saplings you gave it.

**Expected behavior**
Pretty sure it is supposed to take the unstables and give u stable ones

**System (please complete the following information):**
- Occultism Version: 0.2.10
- Modpack Link and Version, or list of mods: JEI, patchouli and occultism

**Comment by klikli-dev** [comment]
For me this works on 0.2.10. Once I put the sapling in the purple particle effect appears and after some time the sapling is converted.
![image](https://user-images.githubusercontent.com/60774993/86729825-2cbf8900-c02e-11ea-9a01-a7b513c921cc.png)

Please note that each trader has only one recipe, so summoning the right one is critical.

**Comment by theboo** [comment]
yes i am seeing the purple particle effect indicating it is working, i just haven't seen any conversion(i am definitely summoning the sapling trader)... ill give it another shot in a bit, thanks!

**Comment by theboo** [comment]
yeah it doesnt seem to be working for me.. 

https://gyazo.com/d1dd5159bc40f42140c72ebc0bf806e1

**Comment by klikli-dev** [comment]
Thank you for the re-test - I retried it a few times and managed to make it fail 2 after a few successful attempts. The issue was that I set the time to convert and the spirit maximum age to the same, so depending on tick times that last conversion time sometimes gets skipped - in my first experiment I simply got lucky.
