### ISSUE TITLE
Server crash during possesed endermite ritual

### ISSUE THREAD

**Issue by korocota** [klikli-dev/occultism#465]
**Describe the bug**
Started a Posssed endermite ritual, chicken spawned when I used the egg, killed it with an Ars Nouveau projectile spell, server crashed.

Not sure if it's due to the chicken or due to the spell entity.

**To Reproduce**
1. Start Possesed Endermite Ritual
2. Kill a chicken with an ars nouveau spell in range of the ritual right after the egg toss.
3. Crash

**Expected behavior**
Finish ritual 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.15.0
- OS: win10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Its somewhere in the attached log

**Additional context**

[crash-2021-10-05_12.30.23-server.txt](https://github.com/klikli-dev/occultism/files/7285120/crash-2021-10-05_12.30.23-server.txt)

**Comment by klikli-dev** [comment]
@korocota thank you for reporting - for reference, does this also happen when you kill the chicken with a sword? 
Just to narrow down possible causes

**Comment by korocota** [comment]
It doesnt happen when I kill it with a sword

**Comment by klikli-dev** [comment]
The log is a bit inconclusive as to where the null pointer error happens (specifically, the entity which seems to be null is accessed only a few lines of code before), so I added some general sanity checks. If the issue persists in 1.15.1, please comment here so I can reopen it.
