### ISSUE TITLE
Ore Miner cannot be autocrafted by Refined Storage

### ISSUE THREAD

**Issue by NielsPilgaard** [klikli-dev/occultism#478]
**Describe the bug**
Ore Miners and similar crafts cannot be autocrafted with Refined Storage, I'm guessing because NBT varies between all Ore Miners.

**To Reproduce**
1. Make a Refined Storage system
2. Set up autocrafting for an Ore Miner
3. Activate the autocrafting
4. Watch the ritual complete, but not the autocrafting job.

**Expected behavior**
Would've been nice if the Ore Miner was somehow recognized by RS 😅 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.16.0
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Enigmatica 6 v0.5.16

**Additional context**
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3471

**Comment by klikli-dev** [comment]
Thanks a lot - I will close it here then. If there is anything I can do on my end to facilitate this (e.g. an nbt flag, passing info to the API, etc) let me know!
