### ISSUE TITLE
[Issue] Foliot pathing problems

### ISSUE THREAD

**Issue by Emblin13** [klikli-dev/occultism#494]
Modpack: All The Magic 2: Spellbound, ver. 2.1.0
Minecraft version: 1.16.5
Forge version: 36.2.8
Mod version: 1.17.4

I have what should be a fully automated ore crushing system, with a Foliot Transporter that takes ore from a chest and hands it to a Marid Crusher, who then drops stuff to be picked up by a Foliot Janitor and deposited in chests above a furnace. The Marid Crusher does everything fine, but a serious issue I'm having with both the janitor and transporter, but mostly the transporter, is that they are getting stuck on nothing and not being able to pick up / deposit items when they're right next to them. 

On the left is the chest with ore, and on the right is where the products are smelted
![2021-10-31_02 52 07](https://user-images.githubusercontent.com/16312861/139577164-62bf1045-7fa2-4db2-b9ae-195317dcdf26.png)

As you can see in the image, the janitor can't reach those items for some reason, and gets stuck there doing nothing. This has happened on multiple occasions 
![image](https://user-images.githubusercontent.com/16312861/139577192-8f51c2aa-8a15-45c3-9948-6cad6e07c0dd.png)

**Comment by klikli-dev** [comment]
Thanks for the report - as discussed in discord I'll increase the pickup range. If the issue persists once the patch is live, please comment here so I can reopen it!
