### ISSUE TITLE
Clarify in book that guardian familiar spawns with random amount of limbs and can only be repaired once

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#499]
**Describe the bug**
The guardian familiar seems to be summoning without any limbs at all, only the body making it so you only get one player death before he dies. The blacksmith familiar is able to give him one limb back, but seemingly cannot give more.

**Expected behavior**
limbs!

**System (please complete the following information):**
- Occultism Version: 1.18.0
- OS: [e.g. Windows]
- Minecraft Version:1.16.5
- Modpack Link and Version, or list of mods:

**Comment by vemerion** [comment]
It should start with a random number of limbs (here is the logic for it https://github.com/klikli-dev/occultism/blob/main/src/main/java/com/github/klikli_dev/occultism/common/entity/GuardianFamiliarEntity.java#L94). I did it as a way of balancing it, but of course it is debatable whether or not we want to keep it like that.

**Comment by klikli-dev** [comment]
The discussion in Discord that triggered the ticket was with me unaware of the code/reasoning - but this is actually a good fit to avoid a super-anti-death familiar

**Comment by theboo** [comment]
Makes sense, but it might be good to add something to the book explaining that he has a chance to spawn with however many pieces and that the blacksmith can repair a limb one time
