### ISSUE TITLE
Crash when opening spirit trader GUI

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#5]
**Describe the bug**
Crash when opening spirit trader GUI.
Created based on additional context in https://github.com/klikli-dev/occultism/issues/4 

**To Reproduce**
1. Spawn trader
2. Shift-click to open gui
3. Crash

**Expected behavior**
The gui opens without a crash.

**System (please complete the following information):**
- Occultism Version: 0.2.2
- OS: [e.g. Windows]
- Minecraft Version:
- Modpack Link and Version, or list of mods:

**Comment by theboo** [comment]
this crash seems to be fixed in 0.2.3!
