### ISSUE TITLE
Server crash and inventory lag from mostly full medium tier storage system

### ISSUE THREAD

**Issue by VallenFrostweaver** [klikli-dev/occultism#501]
Minecraft 1.16.5
Forge 36.2.2
Occultism 1.18
Run on a multiplayer server with the MMT modpack v1.0.1

Server Crash from heavily laden inventory? Crash report here:
[https://www.toptal.com/developers/hastebin/habomeqiye.properties](https://www.toptal.com/developers/hastebin/habomeqiye.properties)
Details from the player that crashed it:
![image](https://user-images.githubusercontent.com/13642054/140502043-13001ccf-4bd1-411a-ba4b-5d594123dc3d.png)

**Comment by klikli-dev** [comment]
Can you provide a rough overview of the items in there, especially any special or unique modded stuff (such as items with a lot of nbt), or any concrete steps on how to reproduce?
Generally speaking that is on the lower end of usage scenarios I have heard of and should not cause a 60 second tick.

Additionally, if there was any info from performance tracing mods hat clearly indicate how much each part of a tick that would help as well in replicating and fixing this.

Thanks!

**Comment by VallenFrostweaver** [comment]
> Additionally, if there was any info from performance tracing mods hat clearly indicate how much each part of a tick that would help as well in replicating and fixing this.
What kind of performance tracing are you interested in? Not sure what reporting may be of assistance or that you found useful in the past or not. In the interim, I've asked the player for inventory summary details per your instructions.

**Comment by VallenFrostweaver** [comment]
Here's the player's answer:
![image](https://user-images.githubusercontent.com/13642054/140507789-b5fca12c-2233-4a51-a6aa-57f78198c657.png)

**Comment by klikli-dev** [comment]
> Here's the player's answer: ![image](https://user-images.githubusercontent.com/13642054/140507789-b5fca12c-2233-4a51-a6aa-57f78198c657.png)

Thanks a lot for getting more info @VallenFrostweaver  - It does sound like there might be an underlying issue with items with large nbt (which would not be unusual in minecraft), so I will investigate that for sure, although it's usually a bit tough to replicate such scenarios in a dev environment



> > Additionally, if there was any info from performance tracing mods hat clearly indicate how much each part of a tick that would help as well in replicating and fixing this.
> 
> What kind of performance tracing are you interested in? Not sure what reporting may be of assistance or that you found useful in the past or not. In the interim, I've asked the player for inventory summary details per your instructions.

I have found the "profiles" generated by https://www.curseforge.com/minecraft/mc-mods/spark to be very useful. They are uploaded to https://spark.lucko.me/ and then look something like this: https://spark.lucko.me/mYlmRSNgR1?hl=51 and allow to break down exactly where tick time is spent on

**Comment by VallenFrostweaver** [comment]
> I have found the "profiles" generated by https://www.curseforge.com/minecraft/mc-mods/spark to be very useful. They are uploaded to https://spark.lucko.me/ and then look something like this: https://spark.lucko.me/mYlmRSNgR1?hl=51 and allow to break down exactly where tick time is spent on

I'm familiar with Spark so I'll see about getting that run at some point when the player is online and messing with that inventory. It might be a few days though.

**Comment by klikli-dev** [comment]
Closing this as stale - please comment/ping me if any new info shows up so I can reopen

**Comment by klikli-dev** [comment]
[crash-2021-12-17_00.36.17-server.txt](https://github.com/klikli-dev/occultism/files/7739853/crash-2021-12-17_00.36.17-server.txt)
That crash might be related
