### ISSUE TITLE
server crashed when summonning djinni

### ISSUE THREAD

**Issue by ColdTearsYY** [klikli-dev/occultism#516]
**Describe the bug**
server crashed when summonning djinni

**To Reproduce**
forget

**Expected behavior**
time change

**Screenshots**
(https://paste.ubuntu.com/p/mhxx9Dw7wY/)

**System (please complete the following information):**
- Occultism Version: see in crash report
- OS: [e.g. Windows]Windows
- Minecraft Version:1.16.5
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
This bug is fixed in more recent occultism versions, see #484
