### ISSUE TITLE
Summon Parot resulted in a named chicken

### ISSUE THREAD

**Issue by demfels** [klikli-dev/occultism#52]
**Describe the bug**

**To Reproduce**
Perform the parrot summoning ritual

**Expected behavior**
A parrot should have been summoned, instead, it resulted in a named chicken...

**Screenshots**
![image](https://user-images.githubusercontent.com/4838280/89131936-17773680-d4d6-11ea-9078-d8d53f19ee01.png)

**System (please complete the following information):**
- Occultism Version: occultism-0.2.11.jar
- OS: [e.g. Windows] Client Windows/Server Unix
- Minecraft Version: 1.15.2
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/ultimate-pack-1-15-2/relations/dependencies

**Comment by klikli-dev** [comment]
This is not a bug, it's a random event (the wrong bird was summoned). You may have to attempt the summoning multiple times until the right bird spawns.
