### ISSUE TITLE
[1.16.5] a familular idea inspired from a Botania addon + additional ideas

### ISSUE THREAD

**Issue by SteamDoge9000** [klikli-dev/occultism#525]
a new familular; this familular would have to represent a hand of some kind (master hand would work but not sure if that would fit this mods style). the Purpose of this famular while not in a ring can be decided, but when in the ring, it can be used to give the wearer and __EXTRA RING__ Slot along with it giving the wearer back the slot the ring is residing in (2 slots total). this would allow the user to have more options to what curos rings to wear. given the context of this being a powerful utility, It should be an expesive thing for the familular to be summoned and a normal soul ring may not cut it. A special ring  could be made using the hand familiar as a ingredient

this idea comes from something that Ive seen in a addon called Extra Botania with the Ring of the Elven king that when worn, any trinket that is in a baubles (or curos at this point) box will be counted as an active item 

**Additional context**

maybe some more options for other curos slots. like maybe a charm that makes refrence to a swine god (pig) and when its worn, it will act like a gold item being worn and might have a chance to passify the brutes and the other pig creatures (that is until provoked). a funny thing that can happen when wearing this is that you cannot eat pork or food items that are made with pork. doing so while this charm representing a holy symbol of the swine god (or maybe can be infused with it) will upset the deity and will cause any pig-like entities around them to suddenly go aggressive

Soul items that can go into other curos slots, but may be more expesive depending on what its being made into when forging the item in a ritual

some famular that when worn will provide the wearer wtih good forution (looting and fortune III) and could stack on to other items wtih looting and fortune on them, but will make the user take 2-3x more damage (incoming damage is increased). Upgrading this with a blacksmith will make it even better but will make the user take more damage than usual (maybe 6x depending on how you want it to go)
You can make this acordingly, but I think that an item that will give you better fortune should come at cost of being more damage prone (multiplying the damage you take)

**Comment by klikli-dev** [comment]
Moved to https://github.com/klikli-dev/occultism-feature-tracker/issues/9
