### ISSUE TITLE
Night ritual causes crash

### ISSUE THREAD

**Issue by adamsong** [klikli-dev/occultism#528]
**Describe the bug**
Using the night time ritual the game crashes, with cast error ([Here](https://github.com/klikli-dev/occultism/blob/d2fe02abeb35700134c733441624f4e6f1e26b50/src/main/java/com/github/klikli_dev/occultism/common/job/NightTimeJob.java#L43))

**To Reproduce**
1. Perform the Dusk Spirit ritual
2. Wait as the spirit does its thing
3. Crash

**Expected behavior**
It should become night, not crash

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.18.0
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: [Create Above and Beyond](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond)

**Additional context**
Daytime spirit works

**Comment by klikli-dev** [comment]
Many thanks for testing day and night! Apparently I forgot to apply the fix to this one.
