### ISSUE TITLE
Candle tag not showing

### ISSUE THREAD

**Issue by Void01702** [klikli-dev/occultism#533]
The candle tag doesn't show in JEI, which possibly mean it doesn't work

**To Reproduce**
1: open inventory
2: search "$candle" in jei
3: nothing is showing

**Expected behavior**
The tag should work

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/688410719611256852/912758339589525534/Minecraft__1.16.5_-_Singleplayer_23_11_2021_18_35_32.png)

https://cdn.discordapp.com/attachments/688410719611256852/912758390181212180/Minecraft__1.16.5_-_Singleplayer_23_11_2021_18_35_52.png

**System (please complete the following information):**
- Occultism Version: 1.19.1
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: AI improvements; Akashic tome; Appleskin; Aquaculture; Archers paradox; Architectury; Attribute Fix; Auto reg lib; Better biome blend; Better burning; Yung's better caves; Yung's better dungeons; Yung's better stronghold; Bookshelf; Caelus; Cakechomp; Catalogue; Ceramics; Chunk pregenerator; Clumps; Cofh core; Common capabilities; Configured; Connected glass; Create additions; Create addon; Create gears; Create; Create plus; CTM; Curio of undying; Curios; Curious elytra; Cyclops core; Dark painting; Decorative blocks; Diet; Eidolon; Enchantment descriptions; End reborn; Ensorcellation; Entity culling; Equipement compare; Experience bug fix; Farmers delight; Fast bench minus replacement; Fast furnace minus replacement; Fast leaf decay; Fast suite; Ferrite core; Flywheel; Framed blocks; Framed compact drawers; Friendly Fire; FTB library; Glassentials; Go prone; Hwyla; Iceberg; Immersive engeneering; Immersive petroleum; Industrial foregoing; Iron chest; Iron shulker box; Jeed; JEI; Journey Map; Just enough beacons; Just enough professions; Just enough ressources; Klee slab; Lazy dfu; Mantle; Masonry; Materialis; Max health fix; Mekanism; Mekanism generators; Mekanism tools; Mgui; Mod name tooltip; More create stuff; Mouse tweaks; Neat; Netherite horse armor; Nether portal fix; Occultism; Overloaded armor bar; Pass through signs; Patchouli; Placebo; Polymorph; Pretty pipes; Pretty pipes fluid; Psi; Quark; Save your pets; Scaffolding power; SoL carrot; Spark; Storage drawers; Swing through grass; Tcon planner; TiC; Tetra; Undergarden; Thermal expansion; Thermal foundation; Thermal innovation; Thermal locomotion; TiC rapier; Tinkers delight; Titanium;  Torch slab mod; Toughness bar; Wyrmroost; Yung's API; Yung's bridges

**Comment by theboo** [comment]
Cleared this up in discord... It is a block tag which does not show up with advanced tooltips on and IE installed(it only shows item tags)... There are other mods that do but no clue which lol.. instructed them to use f3 screen and look at the block placed in world

**Comment by klikli-dev** [comment]
Thanks for investigating!
