### ISSUE TITLE
Cannot perform Summon Unbound Afrit

### ISSUE THREAD

**Issue by atrobman** [klikli-dev/occultism#534]
**Describe the bug**
When trying to summon Unbound Afrit, ritual is not detected

**To Reproduce**
1. Construct Abras' Open Conjure pentacle
2. Insert items (Netherrack, Gunpowder, Nether Quartz, Flint and Steel)
3. Use Book of Binding: Afrit (Bound) on Golden Bowl

**Expected behavior**
Ritual proceeds to Sacrifice

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.14.1
- OS: Windows 10
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Enigmatica 6

**Comment by klikli-dev** [comment]
Closing this for the time being as people on E6 definitely have been able to use this ritual in the recent past.
Please drop by in discord @atrobman so people can help diagnose the issue. 
If it is something wrong with the code please ping me and I will reopen this
