### ISSUE TITLE
Shift-crafting Ingots into blocks from Dimentional Storage Actuator turns the remaining ingots into either bars or weighted pressure plates.

### ISSUE THREAD

**Issue by KajesLorian** [klikli-dev/occultism#54]
While bulk crafting large stacks of iron nuggets to iron blocks in the Dimensional Storage Actuator I noticed that when shift-crafting the ingots into blocks if there are two ingots left over in the crafting recipe it will automatically craft them into Heavy Weighted Pressure Plates.

**To Reproduce**
1. Select the Dimensional Storage Actuator
2. Use iron ingots to make the shape for iron blocks
3. Shift-right-click ONCE to make as many iron blocks as the storage can make
4. Receive either a heavy weighted pressure plate in my inventory if there were two remaining ingots in crafting space or a stack of 16 iron bars if there were 6 remaining ingots

**Expected behavior**
I expect the remaining ingots to stay in the crafting space

Gif of problem in action:
https://i.imgur.com/sOQTneW.mp4

**System (please complete the following information):**
- Occultism Version: 0.2.11
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.15.2
- List of mods: 
Abnormals-Core-1.15.2-1.0.6.jar
AkashicTome-1.3-13.jar
AmbientSounds_v3.0.20_mc1.15.2.jar
angelblock-2.0.jar
angelring-1.15.2-1.2.0.jar
Apotheosis-1.15.2-3.3.5.jar
Ars+Nouveau+1.15.2+-+0.17.1.jar
Artifacts-1.15.2-2.5.1.jar
AutoRegLib-1.5-40.jar
autumnity-1.3.3-1.15.2.jar
berry_good-2.0.0.jar
BetterCaves-1.15.2-1.0.jar
Bloomful-1.15.2-1.4.1.jar
Bookshelf-1.15.2-5.6.40.jar
bottleyourxp_1.15-1.3.jar
Bountiful-1.15.2-3.1.2.jar
Buzzier-Bees-1.15.2-1.5.2.jar
bwncr-1.15.2-3.6.13.jar
Cauldron-1.2.jar
Charm-1.15.2-1.5.9.jar
citadel-1.1.11.jar
Clumps-5.0.2.6.jar
CodeChickenLib-1.15.2-3.3.1.379-universal.jar
cofh_core-1.15.2-0.6.2b.jar
collective-1.15.2-1.39.jar
comforts-FORGE-1.15.2-2.0.0.4.jar
Controlling-6.1.5.6.jar
CosmeticArmorReworked-1.15.2-v3a.jar
Covalent-1.15.2-1.0.2.jar
craftingstation-3.1.0.jar
create-mc1.15.2_v0.2.4d.jar
Cucumber-1.15.2-3.0.9.jar
curios-FORGE-1.15.2-2.0.2.6.jar
cyclepaintings_1.15-1.3.jar
decorative_blocks-1.15.2-1.7.jar
DoggyTalents-1.15.2-1.15.2.3.jar
doubledoors_1.15-2.1.jar
dragondropselytra_1.15-1.1.jar
Druidcraft-1.15-0.4.31.jar
EnderStorage-1.15.2-2.5.0.151-universal.jar
Enhanced-Mushrooms-1.15.2-v1.2.2.jar
exnihilosequentia-1.15.2-1.2.1.0.jar
extlights-2.1.jar
extraboats-1.3.6-1.15.2.jar
extratags-1.1.jar
FastLeafDecay-v22.jar
findme-1.15.2-1.3.0.jar
fixedanvilrepaircost_1.15-1.1.jar
FluxNetworks-1.15.2-5.0.3-4.jar
ftb-backups-2.1.0.2.jar
furniture-7.0.0-pre16-1.15.1.jar
FutureVersions+v3.0.jar
goblintraders-1.2.0-1.15.2.jar
guardvillagers-1.15.2-1.0.8.jar
Hwyla-forge-1.10.8-B72_1.15.2.jar
ImmersiveEngineering-1.15.2-4.0.0-117.jar
incubation-1.0.4-1.15.2.jar
Industrial+Agriculture[Core]-1.15.2-1.7.0.jar
Industrial+Agriculture[Powah]-1.15.2-1.6.0.jar
infinitetrading_1.15.2-1.2.jar
inventorytotem_1.15-1.1.jar
jei-1.15.2-6.0.3.15.jar
journeymap-1.15.2-5.7.0b3.jar
JRFTL+[1.15.2]-1.1.jar
Kiwi-1.15.2-2.8.2.jar
KiwiBirds+1.3+1.15.2.jar
Kottle-1.5.2.jar
Lollipop-1.15.2-1.0.16.jar
lumberjack-2.0.1.jar
Mantle-1.15.2-1.5.15.jar
mcw-bridges-1.0.4fix-mc1.15.2.jar
mcw-doors-1.0.0-mc1.15.2.jar
mcw-trapdors-1.0.0fix-mc1.15.2.jar
mcws-roofs-1.15.2-v2.0.0.jar
mcws-win-1.15.2-v1.0.2.jar
mobcatcher-2.2.jar
mooshroomtweaks_1.15.2-1.2.jar
MysticalAdaptations-1.15.2-1.2.3.jar
MysticalAgradditions-1.15.2-3.0.1.jar
MysticalAgriculture-1.15.2-3.0.10.jar
MysticalCustomization-1.15.2-1.0.0.jar
NetherPortalFix_1.15.2-6.0.2.jar
NomadicTents-1.15.2-11.0.0-beta.jar
nomowanderer-MC1.15.2_1.2.jar
occultism-0.2.11.jar
omgourd-1.15.2-0.5.0b.jar
PackingTape-1.15.2-0.9.6.jar
paperbooks_1.15-1.1.jar
Patchouli-1.15.2-1.2-35.jar
PickleTweaks-1.15.2-4.0.4.jar
Placebo-1.15.2-3.1.0.jar
Powah-1.15.2-1.1.15.jar
Quark-r2.1-245.jar
rats-5.3.2-1.15.2.jar
refinedstorage-1.8.8.jar
Reliquary-1.15.2-1.3.4.995.jar
repurposedstructures-1.15.2-1.7.2.jar
respawnablepets-1.1.4.jar
RingOfAttraction-1.15.2-1.1.36.jar
RingOfBlink-1.15.2-1.1.31.jar
RingOfEnderchest-1.15.2-1.1.34.jar
RingOfGrowth-1.15.2-1.1.33.jar
RingOfMiner-1.15.2-1.1.31.jar
RingOfRepair-1.15.2-1.1.33.jar
RingOfTeleport-1.15.2-1.1.32.jar
rndbmflowers_1.15-1.2.jar
scuba-gear-1.15.2-1.0.1.jar
shulkerbox-1.9.2.jar
shulkerdt_1.15-1.2.jar
simplytea-1.15.2-2.2.1.jar
Statues-1.15.2-0.1.5.2.jar
StorageDrawers-1.15.2-7.0.2.jar
strawgolem-1.15.2-1.7.1.jar
structure-gel-api-1.15.2-1.1.0.jar
Swamp-Expansion-1.15.2-1.7.3.jar
the-conjurer-1.15.2-1.0.7.jar
ToolBelt-1.15.2-1.14.1.jar
torchmaster-2.2.2.jar
towers_of_the_wild-1.15.2-1.2.0.jar
tramplestopper-1.15.2-2.0.0.1-universal.jar
trashcans-1.0.3-mc1.15.jar
valhelsia_structures-15.0.3a.jar
Waddles-1.15.2-0.8.6.jar
WAWLA-1.15.2-3.0.4.jar
Waystones_1.15.2-6.0.2.jar
worldedit-forge-mc1.15.2-7.1.0.jar

**Additional context**
Happens with both gold and iron ingots

**Comment by klikli-dev** [comment]
Thanks for the report - that is a very valid issue. I'll look into this, but it may need a bit of a rework of the crafting system. I will look into it during the (eventual) 1.16 upgrade and if feasible backport to 1.15
