### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by XionioXMaster** [klikli-dev/occultism#545]
**Describe the bug**
https://paste.loliidc.cn/?ef0b6f465b58621e#7p7i44uxtuTJbCyuHrnxPR9yJGFftdiAxzS8H6KwCvim

**To Reproduce**
I have no idea how to reproduce, someone on the server did it

**Expected behavior**
?

**Screenshots**
nope

**System (please complete the following information):**
- Occultism Version:  1.21.1
- OS: [e.g. Windows] unbuntu 20
- Minecraft Version: 1 16 5
- Modpack Link and Version, or list of mods: no

**Additional context**
Yes, I am using loliserver as my server base, this is Forge + Spigot. But if Spigot finds such a bug, then it can be reproduced on Forge as well. But the player just did how to reproduce it, I don't know.

**Comment by klikli-dev** [comment]
I've had a similar report before, but in both cases the actual crash/stalling is in a vanilla method related to the dimension registry, which my mod only accesses. The access to the registry is directly based on the item NBT of the storage controller, but vanilla really should even handle invalid data without such behaviour, which makes it a bit tricky to fix, especially without a way to reproduce it.

That said, could you try to obtain the item NBT for the following:
- The storage remote the player used that caused the crash
- The storage actuator (harvested as item)

You can obtain the nbt by holding the item in your hand and running `/occultism nbt`, it should print the nbt to chat and it should show up in the log. A pastebin of that would be fantastic.

Thanks for your assistance!

**Comment by XionioXMaster** [comment]
> I've had a similar report before, but in both cases the actual crash/stalling is in a vanilla method related to the dimension registry, which my mod only accesses. The access to the registry is directly based on the item NBT of the storage controller, but vanilla really should even handle invalid data without such behaviour, which makes it a bit tricky to fix, especially without a way to reproduce it.
> 
> That said, could you try to obtain the item NBT for the following:
> 
> * The storage remote the player used that caused the crash
> * The storage actuator (harvested as item)
> 
> You can obtain the nbt by holding the item in your hand and running `/occultism nbt`, it should print the nbt to chat and it should show up in the log. A pastebin of that would be fantastic.
> 
> Thanks for your assistance!

I will interrogate several players and find out what caused this

**Comment by XionioXMaster** [comment]
Sorry, I couldn't figure out the reason(

**Comment by klikli-dev** [comment]
@XionioXMaster thank you for looking into it though!
I will close this for now, but if you do find any info on it please ping me and I will reopen it and investigate!
