### ISSUE TITLE
broken book

### ISSUE THREAD

**Issue by barzedon** [klikli-dev/occultism#548]
- Occultism Version: occultism-1.17.1-1.21.1
- OS: windows 10
- Minecraft Version: 1.17.1 Forge
- Modpack Link and Version, or list of mods: Patchouli-1.17.1-57; jei-1.17.1-8.3.0.39; curios-forge-1.17.1-5.0.2.3
![Безымянный](https://user-images.githubusercontent.com/63967800/144764148-98c92108-ba91-40d1-ae99-bb552cd53788.png)

**Comment by klikli-dev** [comment]
@barzedon thanks for reporting! The Russian translation is maintained by community contributors and currently out of date. As soon as a volunteer updates it, it will work again,
If you switch your game language to English the book will work.

**Comment by barzedon** [comment]
ok, thanks
