### ISSUE TITLE
Big problems with TPS Create + Occultizm

### ISSUE THREAD

**Issue by XionioXMaster** [klikli-dev/occultism#554]
**Describe the bug**
![image](https://user-images.githubusercontent.com/86433158/145199403-1c0e2ed0-71d2-47f9-abec-b3929370112a.png)
**Create brass funnel**
and add filter
![image](https://user-images.githubusercontent.com/86433158/145202374-44eaa76a-cf97-4a03-8571-0cbefb6bfd40.png)

![image](https://user-images.githubusercontent.com/86433158/145202424-78df3b68-2108-4452-9ecb-a47081f20840.png)
Tying to a wormhole
naturally, a fire should burn from below! The wormhole must be new!
on top of a mob farm! We kill several dozen mobs and the TPS server falls until we break the wormhole
![image](https://user-images.githubusercontent.com/86433158/145202639-055b97d5-efeb-4b97-839f-ef995511449c.png)
also set the value to 1 on the filter
![image](https://user-images.githubusercontent.com/86433158/145202985-9ca752ac-c86b-4903-8704-c758c52d2d82.png)

as we see the TPS falls gradually, the more we kill the faster the TPS falls
![image](https://user-images.githubusercontent.com/86433158/145203107-5f541f49-869e-4158-85d3-b40a15065879.png)

**To Reproduce**
up

**System (please complete the following information):**
- Occultism Version: 1.22.0
- OS: [e.g. Windows] unbuntu 20
- Minecraft Version: 1 16 5 
- Modpack Link and Version, or list of mods:

**Comment by XionioXMaster** [comment]
Sometimes you need to kill a lot of mobs, but in any case, the delay can reach 14 TPS

**Comment by klikli-dev** [comment]
Apologies - I am not quite sure I understand what is going on. 
Do you have any ideas what causes the low TPS?
Are lots of items being imported into the wormhole?

**Comment by klikli-dev** [comment]
Closing as stale for now, please comment + ping me to reopen

**Comment by Grath** [comment]
@klikli-dev I can corroborate this, I was experiencing extreme tick latency in All The Mods - Spellbound, with filtered Create chutes connected to Wormholes attempting to export many types of items from storage particularly when combined with several dimensional mineshafts generating ores. This was causing more latency per tick per wormhole than several other bases with medium-to-heavy Create usage, lots of automation. I don't know if this is Occultism's fault or Create's, though.
![image](https://user-images.githubusercontent.com/1895280/149063935-6d0a31e0-d0ea-4c07-ae36-c979a35a770f.png)
