### ISSUE TITLE
JEI Searches involving Occultism blocks/items causing excessive lag and crashes

### ISSUE THREAD

**Issue by IdrisQe** [klikli-dev/occultism#555]
**Describe the bug**
Currently playing the Create Above and Beyond modpack, and Occultism has been a continual thorn in our side, since every time we start searching for something in JEI there's a 1/10 chance that the first couple letters will happen to bring up a bunch of occultism items, which inevitably causes immense slowdown that stays even after closing the search and JEI - which is what happens in the case of my partner, or in my case, it immediately freezes my client, causes the "saving world" screen to pop up for a moment, before then crashing to desktop. Thankfully it doesn't crash the server too.

Never had this issue with any other mod before, even ones that add tons of complex models and items, so I have no idea why it's an issue. It even gave me an out of memory error despite having 4GB allocated to my client alone, the server having another 4GB allocated.

**To Reproduce**
Open JEI, search something random like "cr" to find the **Cr**ushing Wheels for Create, instead get a bunch of Occultism items talking about Dragon Familiars in**cr**easing something, game locks up, game freezes, game crashes.

**Expected behavior**
The items should show up without much lag, much less causing an out of memory error when my memory usage usually fluctuates between 500MB and 2800MB out of 4096MB.

**System**
- Occultism Version: 1.20.1
- OS: Windows 10 (64 Bit)
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: [Create Above and Beyond](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond) Version 1.2 (1.1 also had this issue)

- Additional Mods (_Although this issue also happened before modifying the pack_): 
Actually Compatible, Ambient Environment, Better Beacon Placement, Better Conduit Placement, Better FPS Distance, Better Third Person Forge, Bigger Sponge Absorption Radius, Bottled Air, Caelus API Forge, Chalk, Clean Cut, Clear Skies Forge, Collective, Conduits Prevent Drowned, Crying Ghasts, Curious Elytra, Customizable Elytra, Cycle Paintings, Damage Tilt, Dismount Entity, Double Doors, Durability101, Easy Elytra Takeoff, Easy Magic, Entity Culling, Extended Bonemeal, Fast Suite, Fast Workbench, Fire Spread Tweaks, Fixed Anvil Repair Cost, Go Prone, GUI Clock, GUI Compass, Hand Over Your Items, Hidden Recipe Book, Horse Stand Still, HUD Quiver, Inventory Totem, Item Stitching Fix, Krypton Reforged, Lava Clear View, Lazy DFU, Too Fast, Name Tag Tweaks, Nether Portal Spread, No Hostiles Around Campfire, Not Enough Animations, Pass Through Signs, Performant, Pitch Dark, PuzzlesLib, Realistic Bees, Respawning Shulkers, Sapience, Saffolding Drops Nearby, Smaller Nether Portals, Sneaky Magic, Snow Under Trees, Spawn Normalization, StepUp, Sulfuric, TCon Planner, Trajectory Preview, TRansliterationLib, Villager Names, Weaker Spider Webs, Well Behaved Mobs

- JVM Flags (_In case they're relevant_):
`-Xms:4096M -Xmx:4096M -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=50 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=20 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true`

**Crash Report**
https://pastebin.com/MQcFqhyg

**Comment by klikli-dev** [comment]
I cannot reproduce this in a "clean" environment (Occultism + Dependencies only), which is an indicator that another mod plays a role in the problem (possibly something that modifies rendering). Can you make this happen in a very basic occultism setup, somehow? 

Generally Occultism doesn't really do anything special with its items, all the rendering is vanilla.

Could you also open an issue in the JEI github and link this issue? 
While the actual crash is from minecraft's rendering, it is called by JEI, so it might be mezz already has come across this in another case and has some input

**Comment by IdrisQe** [comment]
No optifine at all, I'll have to do further testing. Strange though since this was happening with the default modpack with me... Hm, I'll have to do further testing. I'll add more info when I'm able to test some more

**Comment by IdrisQe** [comment]
Update: Have yet to test the mod on its own, but I figured out the actual cause: It's the ritual pentagrams/pentacles. Since my partner is able to search without crashing, she managed to find the cause, it seems any time more than a few of them are visible at the same time in a GUI it causes immense, crippling lag. Even in the creative menu with JEI closed it sends me down to single digit FPS (but doesn't crash me) when I'm looking at a section of Occultism's creative inventory with a lot of them. And there's a _lot_ of them. I'm guessing between the rest of the modpack going on around and the excessively high-resolution textures of the pentacles, either my 4GB allocated RAM or low total VRAM can't handle it and crashes the game.

**Comment by klikli-dev** [comment]
@IdrisQe that is extremely helpful - it also explains neatly why it doesn't repro on my end, my dev machine is rather high in both allocated RAM and available VRAM. Usually I'd assume the texture is only uploaded to VRAM once (as it is with blocks in the world), but I suspect within GUI contexts that may not be the case. I'll reduce it down to 16x16 px.

This issue will be closed once the patch is out, but if the issue persists after that, please ping me so I can reopen it.
