### ISSUE TITLE
Reimplimnet the Decay

### ISSUE THREAD

**Issue by SteamDoge9000** [klikli-dev/occultism#561]
**Is your feature request related to a problem? Please describe.**
I have the max ore crusher and it producing 6 from ore is OP, but I feel it needs to be more expensive to have to aquire it, let alone it being more expensive for a indefinite stay

**Describe the solution you'd like**
The Decay to be re-implimented, wtih a complex ritual to make it stay for a longer than nomral time, the higher the being the more complex the requirments are needed to make it stay longer to perminant manifestation

**Additional context**

im saying this because im not sure if you removed decay on some of the beings, the ore crusher all levels except for the first being the basic

**Comment by klikli-dev** [comment]
This is configurable via datapack, in the ritual recipes. It's currently not planned to change the default recipes. 
To achieve what you describe you need to take two steps:
- For the existing rituals, add a decay like it is for the t1 crusher
- To provide "longer" variants of the same spirit, copy the existing ritual, adjust the recipe cost and increase the decay time

**Comment by SteamDoge9000** [comment]
is it a bug that the higher tiers are not having a decay value?

**Comment by klikli-dev** [comment]
No, that is actually intentional, a lot of the feedback was against decay on higher tiers - hence the default to have none, but the option to configure it

**Comment by SteamDoge9000** [comment]
well if thats the case, then it should be made more expensive for higher tiers, cus 6 per ore is overpowered in getting lots of resourses quckly, maybe buff up the recipie a bit

**Comment by klikli-dev** [comment]
Generally speaking I'm open for balancing suggestions for the default recipes (although those would best be brought up in discord so others can weigh in), but as the mod is mostly used within modpacks and not standalone this is generally something modpacks need to adjust to fit their balancing

**Comment by SteamDoge9000** [comment]
well maybe try todo so, im thinking maybe the marid crusher might need more "hard to aquire" resources for the defult recipie since the decay is no longer an issue
