### ISSUE TITLE
missing item lang

### ISSUE THREAD

**Issue by Warbringer12** [klikli-dev/occultism#563]
**Describe the bug**
found a item that is missing its item lang
also looked through your lang file and found that it was missing
name of item is: item.occultism.otherstone_tablet

**Screenshots**
![image](https://user-images.githubusercontent.com/44590540/145660278-464f5580-5c2d-49bd-9d97-0b5b7b4a8db4.png)

**System (please complete the following information):**
- Occultism Version:  1.16.5-1.2.2.1
- Minecraft Version: 1.16.5

**Comment by klikli-dev** [comment]
Thanks for the report! Fantastic how that has gone through like 50 versions unnoticed :D
