### ISSUE TITLE
Cant Use 1.18.1 Occultism

### ISSUE THREAD

**Issue by ModernGamingWorld** [klikli-dev/occultism#571]
Your Mod for 1.18.1 is crashing cause it requires Patchouli and there is now a 1.18.1 Patchouli Version on Curseforge

**Comment by klikli-dev** [comment]
@ModernGamingWorld thanks for the report!
This is known & intended - I updated the mod ahead of time (based on a dev version of patchouli) so it will be ready once Patchouli releases.

Patchouli will likely be available in the next few days.

**Comment by itsdinkd** [comment]
Still not out. Can you remove dependency so we can release occultism in modpacks?
