### ISSUE TITLE
Minor Bug, feature fix recomendation: adjust some of the tall visual mobs hitboxes

### ISSUE THREAD

**Issue by Shibva** [klikli-dev/occultism#577]
![image](https://user-images.githubusercontent.com/38770780/145898921-6eba69b5-8482-4b53-b53c-90bb8d8e0b1a.png)

this should be self explanitoy. some mods (like epic fight) and nametags dont properly show if their hitbox is too smal and is obstructed by the mobs render

Sollution to isssue: fix the hitbox so its their proper size

that is all, simple, sweet and to the point

**Comment by klikli-dev** [comment]
@SteamDoge9000 thank you for the report - do you happen to have a list of affected mobs?

**Comment by Shibva** [comment]
well any mod that uses the top of the hit box to render things should be the ones, mods like epic fight do this  wtih their HP render

I should have also mechoned this was a bug for 1.16.5 but might be also best to adjust them for other versions as well
