### ISSUE TITLE
mods.toml for 1.18 somehow ended up in 1.17 asking for all the wrong dependency versions including forge

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#578]
occultism for 1.17.1 wont launch due to asking for 1.18 versions of forge and dependency mods:

https://github.com/klikli-dev/occultism/blob/version/1.17/src/main/resources/META-INF/mods.toml

was gonna fix it myself, but unsure which minimum versions of the mods you want haha

**Comment by klikli-dev** [comment]
Closed in 474cfb42330e22388fbccfb9ac0a3b48ab512a66
