### ISSUE TITLE
Suggestion for a new familliar 

### ISSUE THREAD

**Issue by AegisCorp123** [klikli-dev/occultism#579]
Hello I hope you are doing well, thank you very much for having created this great mod, I suggest you a family to add that would go I think very well with the theme of the mod, Azathoth, it could look like a small round mass with lots of tentacle, thank you very much for reading this have a nice day 

To enable them it could be a boost of regeneration or resistance, it is you who choose sorry for my bad english im french

**Comment by klikli-dev** [comment]
Moved to https://github.com/klikli-dev/occultism-feature-tracker/issues/9
