### ISSUE TITLE
Ritual Ingredients are not consumed with a low ritualDurationMultiplier

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#581]
**Describe the bug**

**To Reproduce**
1. Set 	`ritualDurationMultiplier = 0.1`
2. Perform any ritual
3. Ingredients are not consumed upon completion

**Expected behavior**
Insert Fry Meme: Shut up and take my items!

**Screenshots**
Moments after summoning the dude:
![2021-12-16_07 35 34](https://user-images.githubusercontent.com/9543430/146373236-64837f2f-6479-4280-8a66-87c5bbbdd33d.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.23.3
- OS: Windows
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Limited instance with only JEI, Occultism and dependencies, and IE
![image](https://user-images.githubusercontent.com/9543430/146373427-50225354-6519-4ff1-8acf-61e5de9effcc.png)

**Comment by klikli-dev** [comment]
Well I'm an absolute moron, I had it end the ritual based on the multiplier, but not speed up consumption. A+ move! 

EDIT: To counter meme with meme
![image](https://user-images.githubusercontent.com/60774993/146652291-13c23942-be94-4d15-bf51-c87e45a49a3e.png)
