### ISSUE TITLE
Lumberjack gets confused if items are stuck on leaves

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#583]
https://gyazo.com/6d4bfd8761c63e5997539aa60d424dcf

this was done in 1.18, as you can see in the gif, the lumberjack keeps trying to go fetch the items stuck on the leaves, realizes it cant, goes to try to break the next tree, notices the items stuck on leave again, goes back, realizes it cant reach those items, in a loop. What isnt shown is if that saplings below these decaying leaves grows, that item will never fall from leaf decay so he will just run around in circles between trying to grab that item and breaking the next tree until the item(s) despawn.

While this happened, he decided to ignore the smaller tree just behind those decaying leaves with the item and after felling the rest of the trees, he will not break that rear tree... (similar to eso's is

**Comment by klikli-dev** [comment]
I'm going to implement a potential solution for this (increasing the lumberjack pickup range), the commit will close this issue.
If possible please test if it still happens on your end and comment/ping if it does. thanks!

**Comment by theboo** [comment]
will do!

**Comment by theboo** [comment]
@klikli-dev 
still gets fairly confused, these sticks are 4-5 blocks above him... tbh i think the only options here would be to have it able to reach up to the tallest mega spruce trees, or only able to grab items at his level idk
https://gyazo.com/c161e03019b01cd768db64d0d969a808

**Comment by esotericist** [comment]
i think restricting the minions to only trying to pick up items that they can successfully to/able to reach with pickup range is probably the ideal.

note that this problem can impact janitors, too. i've watched one obsess on an item eight blocks above while ignoring items  nearby on the ground
