### ISSUE TITLE
please provide a config option for holiday theming.

### ISSUE THREAD

**Issue by esotericist** [klikli-dev/occultism#585]
**Is your feature request related to a problem? Please describe.**
seriously, mandatory holiday theming is extremely annoying, and while i don't have to deal with it (since i'm not running a version with it), it really shouldn't ever be forced on people.

**Describe the solution you'd like**
a config setting to turn off holiday things.

**Additional context**
my general policy is to remove mods that have holiday features that i cannot somehow disable, and i'd hate for a mod as otherwise interesting as this to run afoul of that.

**Comment by vemerion** [comment]
Oh noes, the Grinch has a github account! 😱 

Edit: On a more serious note, every texture in Minecraft is configurable via a simple resource pack 🙂

**Comment by klikli-dev** [comment]
But ... but .. holiday content! 

While I'd generally defer to resource packs too, I'll add a config in this case, in case future holiday content is not resource pack accessible.
