### ISSUE TITLE
Lumberjack no longer re-plants saplings

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#593]
as of occultism version 1.23.4 the lumberjack does not seem to re-plant saplings.
https://gyazo.com/36a589ec16c3b506d66dbf11f1c87b44

gif shown here with rapid leaf decay mod installed, but i first noticed this without the mod installed, just occultism and its dependencies

**Comment by theboo** [comment]
on further review, he will re-plant the saplings if he picks one up while walking close enough to where he should plant it... i think this is due to the new longer pickup range, he can pick up saplings from further range than he can place them so they rarely end up getting placed.

**Comment by esotericist** [comment]
it was pretty dicey even before 1.23.4.

also the lumberjack has no concept of 'large' trees; it will not attempt to replant a 2x2 spruce properly, which saddened me. but 2x2 spruces are more likely to wedge the lumberjack anyway, so i just coped XD

**Comment by klikli-dev** [comment]
Yeah that is somewhat wonky, in lieu of reworking it into a proper mechanic I'll add a nice little workaround :D

If anyone has the patience to provide a proper sapling planter mechanic: Contributions welcome :D
