### ISSUE TITLE
[1.16.5-1.18.1] Lumberjack can not fell trees with 2 block wide leaves 2 blocks up from base

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#595]
Kinda feel bad with all these lumberjack issues lol.

The lumberjack is not able to mine certain forms of trees, namely spruce trees with 2 blocks of leaves around the 2nd log up from the bottom. 
https://gyazo.com/248e53b4a6bbada171658fb7b3b4278a

**Comment by esotericist** [comment]
oh! i think this is the thing i ran into!

**Comment by klikli-dev** [comment]
Ah that seems to be the core issue here .. and boy do I dislike "tree detection". Here we go again :D
