### ISSUE TITLE
Spirits Will Suffocate if placed near any block/tile entity

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#6]
**Describe the bug**
Spirits seem to suffocate if placed anywhere next to any block.

**To Reproduce**
1. Place spirit 'near any block/tile entity such as furnace'
2. watch it suffocate

**Expected behavior**
Probably shouldn't suffocate so easily xD

**Screenshots**
![2020-05-03_18 30 56](https://user-images.githubusercontent.com/3585761/80931055-647b2d80-8d6c-11ea-8a37-60a706d3a299.png)

**System (please complete the following information):**
- Occultism Version: 0.2.4
- OS:windows
- Minecraft Version:1.15
- Modpack Link and Version, or list of mods: jei, occultism, patchouli

**Comment by klikli-dev** [comment]
Hopefully fixed in Fixed in v1.15.2-0.2.5 (I can no longer reproduce it after introducing some measures)
