### ISSUE TITLE
[1.18.1] iesnium can conditionally spawn in the overworld, visible to plain sight and mineable with a stone pickaxe

### ISSUE THREAD

**Issue by esotericist** [klikli-dev/occultism#600]
**Describe the bug**
iesnium can conditionally spawn in the overworld, visible to plain sight and mineable with a stone pickaxe
 
**To Reproduce**
1. have terralith installed ([datapack based worldgen](https://www.curseforge.com/minecraft/mc-mods/terralith))
2. find a biome with nether-based blocks (in this case, it was the 'yellowstone' biome, but i'm wondering if this could happen with the volcanos too)
3. just happen to find exposed iesnium ore laying out in the open
4. mine it with a stone (!!!) pickaxe
5. profit! no ??? needed

**Expected behavior**
i'm pretty sure i'm not supposed to find iesnium out in the overworld, and i'm pretty sure i'm not supposed to be able to mine it with a basic stone pickaxe

**Screenshots**
https://cdn.discordapp.com/attachments/360995219321126935/922332569289232404/unknown.png

**System (please complete the following information):**
- Occultism Version: 1.18.1-1.23.5
- OS: linux
- Minecraft Version: 1.18.1-39.0.5
- Modpack Link and Version, or list of mods: 
`QuarkOddities-1.18.jar, RootsClassic-1.18-1.1.16.jar, torchslabmod-1.18.1_v1.7.2.jar, netherportalfix-forge-1.18-9.0.0.jar, jei-1.18.1-9.1.0.46.jar, scannable-1.18.1-forge-1.7.6+da03abb.jar, goblintraders-1.7.0-1.18.1.jar, mcw-windows-2.0.2-mc1.18.1.jar, kleeslabs-forge-1.18-11.0.0.jar, goldenhopper-1.2.5-1.18.1.jar, villagernames_1.18.1-3.5.jar, journeymap-1.18-5.8.0alpha9.jar, cookingforblockheads-forge-1.18-11.0.0.jar, Controlling-forge-1.18-9.0.4.jar, Placebo-1.18.1-6.0.2.jar, configured-1.5.1-1.18.1.jar, charginggadgets-1.5.0.jar, sophisticatedbackpacks-1.18.1-3.13.6.452.jar, guardvillagers-1.18.1.4.0.jar, buildinggadgets-3.10.1-build.3+mc1.18.jar, mcw-doors-1.0.5-mc1.18.1.jar, PickUpNotifier-v3.1.0-1.18.1-Forge.jar, mahoutsukai-1.18.1-v1.33.6.jar, farsight-1.18-1.5.jar, catalogue-1.6.0-1.18.1.jar, balm-2.3.1+0.jar, WaterStrainer-1.18-12.1.0.jar, ToastControl-1.18.1-6.0.0.jar, PackingTape-1.18-0.12.2.jar, FpsReducer-forge-1.25-mc1.18.jar, mininggadgets-1.10.2.jar, JustEnoughResources-1.18.1-0.13.1.137.jar, cloth-config-6.1.48-forge.jar, MmmMmmMmmMmm-1.18-1.5.0.jar, supplementaries-1.18-1.0.7.jar, Terralith_v2.0.5_~_Fabric+Forge.jar, konkrete_forge_1.3.2_MC_1.18.jar, selene-1.18-1.11.jar, drippyloadingscreen_forge_1.4.2_MC_1.18.jar, craftingtweaks-forge-1.18.1-14.0.1.jar, mcw-bridges-2.0.1-mc1.18.1.jar, torchmaster-18.0.2-beta.jar, EnchantmentDescriptions-Forge-1.18.1-9.0.2.jar, MouseTweaks-forge-mc1.18-2.19.jar, ToolBelt-1.18-1.18.0.jar, signpost-1.18-2.00.3.jar, waystones-forge-1.18.1-9.0.1.jar, BetterControls-Forge-1.18+v1.2.2.jar, Jade-1.18-4.1.0.jar, forge-1.18.1-39.0.5-universal.jar, VanillaTweaks-1.18.1-1.5.52.jar, mcw-trapdoors-1.0.4-mc1.18.1.jar, mcw-fences-1.0.2-mc1.18.1.jar, Ding-1.18-1.3.0.jar, curios-forge-1.18.1-5.0.3.0.jar, Patchouli-1.18.1-61.jar, gravestone-1.18.1-1.0.0.jar, collective-1.18.1-3.8.jar, SewingKit-1.18-1.5.0.jar, JustEnoughProfessions-1.18-1.2.2.jar, AutoRegLib-1.7-52.jar, Quark-3.0-beta-331.jar, FramedBlocks-4.0.0.jar, BetterThirdPerson-Forge-1.18-1.5.4.jar, constructionwand-1.18.1-2.6.jar, architectury-3.2.51.jar, appleskin-forge-mc1.18-2.2.0.jar, occultism-1.18.1-1.23.5.jar, productivebees-1.18-0.8.0.2.jar, light-overlay-6.0.4-forge.jar, PuzzlesLib-v3.1.1-1.18.1-Forge.jar, MineMenu-1.18-1.10.0.jar, prettybeaches-forge-1.18-7.0.0.jar, geckolib-1.18-forge-3.0.3.jar, mcw-lights-1.0.2-mc1.18.1.jar, Link to mindshaft-0.7.4-1.18.1.jar, BetterAdvancements-1.18.1-0.1.2.121.jar, SlabMachines-1.18.1-1.1.1.jar, supermartijn642configlib-1.0.9-mc1.18.jar, VisualWorkbench-v3.1.0-1.18.1-Forge.jar, woodenhopper-1.18-1.2.0.1.jar, FastSuite-1.18.1-3.0.0.jar, comforts-forge-1.18-5.0.0.1.jar, supermartijn642corelib-1.0.15a-mc1.18.jar, simplylight-1.18.1-1.4.0-build.26.jar, ceramicshears-1.18-1.5.0.1.jar, FastWorkbench-1.18.1-6.0.0.jar, brickhopper-1.18-1.3.0.1.jar, IKnowWhatImDoing-5.0.0-forge.jar, FastFurnace-1.18.1-6.0.1.jar, chunkloaders-1.1.7b-mc1.18.jar, TradingPost-v3.1.2-1.18.1-Forge.jar, curiousshulkerboxes-forge-1.18.1-4.2.0.0.jar, veinmining-forge-1.18-0.14.jar, enderbundle-1.08.jar, treeharvester_1.18.1-4.2.jar, now-playing-1.2.0-forge-1.18.jar, tis3d-1.18.1-forge-1.6.8+504189c.jar, markdown_manual-1.18.1-forge-1.1.0+1299320.jar, absentbydesign-1.18-1.6.0.jar, ferritecore-4.0.0-forge.jar, shutupexperimentalsettings-1.0.4-1.18+.jar, ShoulderSurfing-1.18-2.2.2.jar`
 

**Additional context**
i'm pretty sure all you need to replicate this is terralith and occultism and a lot of luck, and that whole list of mods is probably unnecessary to reproduce

i also wouldn't be surprised if anything that uses similar nether blocks in the overworld as part of world generation could produce this result.

note that terralith is 100% datapack based, and thus not using forge hooks. this is *effectively* vanilla worldgen, which might potentially be part of the issue.

**Comment by klikli-dev** [comment]
Thanks for the report!

The underlying cause for the ore to spawn in the overworld is that it's not actually limited to the nether (I don't think minecraft even supports this without some hackery), but rather to nether blocks. So this part is OK.

The visible iesnium ore spawning reminds me of another 1.18 issue ( #584 ) where the wrong ore block was set up with worldgen.
Could you test (using the divination rod) if proper "hidden" iesnium spawns in the nether? (ideally in a new world on your pack).

I suspect your generated world is either from before fixing that issue, or the datapack for terralith still has the jsons from before that fix.

**Comment by esotericist** [comment]
oh, i'm 100% certain that specific span of worldgen was from a few versions ago, because i ran a `/forge generate` out to a fair distance before i started playing.

so it seems likely this is a stale report, at least for the actionable part? i can try to look into the iesnium thing with the divination rod later.

**Comment by klikli-dev** [comment]
Thank you - then I'll close it for now, but if it pops up on a recent worldgen version please comment / ping me so I can reopen.
The divination rod would be a nice touch, but in that case I'm 99.99% sure that it's just the old issue so it's not strictly necessary :)
