### ISSUE TITLE
[1.18.1] Summoning Afrit Crashes Game - Reported on ATM7

### ISSUE THREAD

**Issue by MokahTGS** [klikli-dev/occultism#601]
**Describe the bug**
Crash when summoning Afrit.

https://github.com/AllTheMods/ATM-7/issues/111

I do not know if this was actually reported to you guys.

**Comment by klikli-dev** [comment]
Thanks for the report - this specific bug was fixed in https://github.com/klikli-dev/occultism/milestone/132; but there is a new one: https://github.com/klikli-dev/occultism/issues/602

**Comment by MokahTGS** [comment]
Ah okay, glad you got it sorted...fix one bug, two more spring up...
