### ISSUE TITLE
Transporter Foliots with fuel and output

### ISSUE THREAD

**Issue by enigmanark** [klikli-dev/occultism#604]
When using 2 Transporter foliots, one for supplying charcoal to the furnace for cooking logs into charcoal, and the other for getting the charcoal out and putting it into a storage drawer, the Foliot that is supposed to just take the output charcoal is also taking the fuel slot charcoal

**To Reproduce**
Place down furnace with 2 transporter foliots, set one to supply charcoal to the furnace and retrieve from charcoal chest, another retrieves charcoal from the furnace and places into same charcoal chest

**Expected behavior**
I expected the Foliot to only remove the output charcoal

**Screenshots**

**System (please complete the following information):**
- 1.16.5-1.23.6
- Windows 10
- 1.16.5
- Custom pack

**Additional context**

**Comment by klikli-dev** [comment]
Did you set the correct sides on the furnace?
The foliot (nor anything in minecraft) does not know what an input or output slot is, but the furnace exposes certain slots to certain sides. If you set that side with the book it should work

**Comment by enigmanark** [comment]
Yeah I figured it out I didn't know that xD Never had that issue with tech mod pipes
