### ISSUE TITLE
Demon's dream seeds drop from grass harvested with shears

### ISSUE THREAD

**Issue by ochotonida** [klikli-dev/occultism#609]
**Describe the bug**
Unlike vanilla seeds, demon's dream seeds will still drop from grass when it is harvested using shears.

**To Reproduce**
1. Break grass using shears until demon's dream seeds drop

**Expected behavior**
Grass should not drop demon's dream seeds when harvested with shears.

**System (please complete the following information):**
- Occultism Version: 1.23.8
- OS: Windows
- Minecraft Version: 1.18.1, 1.16.5
- Modpack Link and Version, or list of mods: Curios, GeckoLib, Patchouli

**Comment by klikli-dev** [comment]
Thanks for the report!
Should be fixed when proper looting is implemented in #606
