### ISSUE TITLE
1.16.5 bug?] "Guidebook" contents are missing

### ISSUE THREAD

**Issue by Shibva** [klikli-dev/occultism#614]
**Describe the bug**
all entries in the book are mssing

**To Reproduce**
???
**Expected behavior**
self explanitroy

**Screenshots**
![image](https://user-images.githubusercontent.com/38770780/147869665-34cd0a5a-7e83-48d9-b38e-591596178dae.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.24.0.jar
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 16.5
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
This does not reproduce in the dev env, neither in SP nor MP.
Can you please provide additional information:
- Log file 
- the language your game is running on
- Modpack / list of mods

**Comment by Shibva** [comment]
odd... going back a version fixed it, lets see if it happens again

**Comment by Shibva** [comment]
could it be possable that the auto-release rleased the version released recently durring something bieng inplimented and that somehow messing up the book syntax?

**Comment by Shibva** [comment]
isssue auto-resovled itself, idk why or how it happend ot begin with
