### ISSUE TITLE
Portable Storage Not remembering settings

### ISSUE THREAD

**Issue by CursedKing** [klikli-dev/occultism#615]
Portable storage doesn't remember settings so everytime you leave it, it reverts back to default or even when you click on JEI recipe it returns to default

**Comment by klikli-dev** [comment]
Note to self: All storage guis do not send the settings to the server, but rather only set them locally

**Comment by klikli-dev** [comment]
Note: Will only be fixed on 1.18 as it's a minor bug that went unnoticed for months at least. Backport PRs will be accepted though.
