### ISSUE TITLE
[1.16.5 Cross compatability (and up if it also exists in newer versions] Polymorph integration

### ISSUE THREAD

**Issue by Shibva** [klikli-dev/occultism#617]
**Is your feature request related to a problem? Please describe.**
No but I did create another report on their end to possibly make this easier to achieve (if needed)

Polymorph (in case you don't know) seems to serve as a mod with the same purpose as the old NoMoreRecipieConflicts mod for newer version in terms of adding a button to "Cycle" possible recopies that overlap with one another that create conflicts. This mod fixes this issue by adding a cycle button to the crafting GUI and allows the user to select what recipe they want to craft using it (its like the machined older mod, but a bit better)

The issue is that it seems the Dimensional Storage Actuators GUI does not include this little widget (and possibly functionality to this mod)

**Describe the solution you'd like**
BY adding this integration, the same features that can be done on a crafting table (craft select or whatever you wish to call it by) will be able to be done in the actuator's GUI

**Additional context**
A separate issue (suggestion) has been posted on their end to allow for possible collaboration (depending on what end needs todo their thing to make this happen)

link to Polymorphs Issue (suggestion) that I made on their end can be found here
https://github.com/TheIllusiveC4/Polymorph/issues/132

**Comment by Shibva** [comment]
addional context:

imo I think it should go in one of these locations, though the choice on where you wish to put it is up to you
<img width="332" alt="image" src="https://user-images.githubusercontent.com/38770780/148469348-c952db24-f1fa-4a71-8970-f03fe5aca480.png">

**Comment by klikli-dev** [comment]
Resolved in https://github.com/TheIllusiveC4/Polymorph/issues/132
