### ISSUE TITLE
Stable Wormhole Multiplayer Crash

### ISSUE THREAD

**Issue by Vancara21** [klikli-dev/occultism#618]
**Occultism's Stable Wormholes crash multiplayer server when Actuator is not loaded**
On a multiplayer server, when a Stable Wormhole is interacted with by means of right clicking it and the Dimensional Storage Actuator it is linked to is not within a loaded chunk, the server crashes. This seems to also happen in any instance cross dimensional (Actuator is in the overworld, Stable Wormhole is in the Nether or End), regardless of whether or not the chunk is force loaded.

**To Reproduce**
1. Create and place down a Dimensional Storage Actuator
2. Create a Stable Wormhole and link it to said Actuator
3. Travel to the nether / end / far away from the Actuator so that the chunks unload
4. Right click the Stable Wormhole
5. Crash! :D

**Expected Behavior**
I expected it to be able to access the stored inventory as per normal and not crash the server.

- Occultism Version: Occultism-1.16.5-1.20.1
- OS: Windows 10
- Minecraft Version: 1.16.5 Forge 36.2.20
- Modpack Link and Version, or list of mods: Create Above and Beyond v1.3

**Additional context**
For frame of reference, the Remote Accessor bauble works perfectly fine cross dimensional and over long distances. I have not tested whether automation pulling items into and out of the wormhole causes a crash under these circumstances. I have not had sufficient testing with forceloading through FTB nor use of other chunk loaders as those are banned items.

I am attaching the crash report from a previous instance where the wormhole and actuator were both in the overworld, just over long distances where the actuator was not loaded. I can provide more crash reports upon request of the server owner, which shouldn't take much as I'm part of the staff team on said server (Attachment 1.) I also added a recent crash report that occured when I tried forceloading the actuator in the overworld with FTBChunks and interacting with a Stable Wormhole placed in the nether (Attachment 2.)
[crash-2022-01-04_03.24.35-server (1).txt](https://github.com/klikli-dev/occultism/files/7825536/crash-2022-01-04_03.24.35-server.1.txt)
[crash-2022-01-06_23.59.23-server.txt](https://github.com/klikli-dev/occultism/files/7825604/crash-2022-01-06_23.59.23-server.txt)

**Comment by klikli-dev** [comment]
Should be fixed on latest 1.16.5. If it still reproduces for you, please ping me so I can reopen.
