### ISSUE TITLE
Underground groves can generate over end portals

### ISSUE THREAD

**Issue by enderger** [klikli-dev/occultism#620]
**Describe the bug**
Underground groves can generate over end portals, resulting in broken strongholds.

**To Reproduce**
Since this bug is highly world based, I’ll leave a link to a documented instance of this happening: https://m.youtube.com/playlist?list=PL3e14exB92LIuz5CX5-QVv-4-MPC-21QZ (episode 1 shows the world creation requirements, the bug exhibits in episode 7)

**Expected behavior**
Groves should avoid strongholds, or at least refuse to overwrite end portal blocks.

**Screenshots**
See reproduction steps

**System (please complete the following information):**
- Occultism Version: ?
- OS: ?
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: Create: Above and Beyond

**Additional context**
I am not affiliated with the one who found the bug, I’m just relaying the info here.

**Comment by klikli-dev** [comment]
This won't be fixed in 1.16.5 (as that version only receives very limited support now), but in 1.18.
As it should be relatively rare it should not be a huge issue until most of modding has moved on to 1.18.
