### ISSUE TITLE
Opening the storage system causes instant server crash

### ISSUE THREAD

**Issue by JinxSwift** [klikli-dev/occultism#624]
**Describe the bug**
Everything was fine for a a day after making the dimensional storage system, then suddenly anyone opening the system in any way, be it the wireless remote, black hole, or storage system directly, instantly crashes the server. System was not full to capacity, was working normally for a full day with three players using it.

**To Reproduce**
1.Right click anything storage related.

**Expected behavior**
It should open and let me access the storage.

**System (please complete the following information):**
- Occultism Version: 1.25.3
- OS: Windows 10
- Minecraft Version: 1.18.1
- Modpack Link and Version, or list of mods: 
- https://www.curseforge.com/minecraft/modpacks/all-the-mods-7
- AllTheMods7 0.2.25 to 0.2.28b (issue started on 2.25, updating to each later version didn't fix it)

**Additional context**
Crash log follows :
[crash-2022-01-14_22.50.18-server.txt](https://github.com/klikli-dev/occultism/files/7874196/crash-2022-01-14_22.50.18-server.txt)

**Comment by JinxSwift** [comment]
From the little of the crash log I can understand myself, the issue seems to be related to packet splitting. Refined Storage had a very similar issue a long time ago.

**Comment by klikli-dev** [comment]
That seems to be it, which makes sense as the code is the same code that RS uses. 
Going to try and repro it on my end to fix it

**Comment by klikli-dev** [comment]
@JinxSwift 1.25.4 is building now (should be on Curseforge within the hour), please let me know if it fixes the error.
I could not reproduce it on my end (couldn't get a storage system full enough to hit package split limit) due to a lack of time, but based on the error I believe I found the issue - however, there might be followup problems that I don't see on my end.

**Comment by JinxSwift** [comment]
Wowzers you are FAST! :) So far so good! It's working with no problem.  My system is 1548/2688 in storage capacity and we're smooth sailing for now. I'll follow up if it locks up again. (your mod is one of the best I've seen in actual years btw. thanks)
