### ISSUE TITLE
[1.16.5 minor bug] Familulars not bound to Friendly Fire mechanic (secondary mod)

### ISSUE THREAD

**Issue by Shibva** [klikli-dev/occultism#625]
**Describe the bug**
when using the "Friendly Fire" mod, pets should be protected from harm, though this seems to not be the case for familiars

**To Reproduce**

install the mod Friendly fire

summon a familular that's bonded to you

hit it and it will take damage (note: the mod is programed to allow for the owner to hurt their mobs tamed to them if they sneak while punching them)
**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.24.0
- OS: Windows 10
- Minecraft Version: 1.16.5: 

**Additional context**

**Comment by Shibva** [comment]
additional note: if you die and then respawn while far away and sitting, they will stop sitting and come to you when you respawn, why this is the case is unknown, but I doubt it has anything to do with the Chicken Chunks chunkloader since it's not an issue for the other pets

Edit: I mean if you die far away and the familiars are close to your respawn point they will stop sitting

additional Thoughts: might be a good idea to also think of a way you can still make the Cthulu sad since you do need to punch him to get an advancement, he was the first victim when I was trying to pat him... he's been long dead for a while and just remembered this when I made another

**Comment by Shibva** [comment]
another note that I just remembered: it seems that familiar rings don't work properly (hold their given buffs) if you cross dimensions, how to recreate this should be self-explaniotry

**Comment by klikli-dev** [comment]
This issue should be opened with the friendly fire mod as a feature request - it would most likely have to add some specific compatibility for occultism, as familiars are not regular tamed entities (which that mod is likely targeting). I doubt it would be possible to make friendly fire work with familiars from my end, at least not without a mixin. 

As for the cross dimension issue, if this reproduces on latest 1.18, please create a separate issue so I can track it.

**Comment by Shibva** [comment]
as far as I know, its not, but the Dimensional Bug is present for 1.16.5
