### ISSUE TITLE
Beavers searching for trees, crashing world instead

### ISSUE THREAD

**Issue by Nachtflame** [klikli-dev/occultism#641]
**Describe the bug**
World crashing to launcher, seemingly at random

**To Reproduce**
Have game running

**Expected behavior**
~~Game to run smoothly~~ (er, I suppose this IS modded MC);
Game to NOT crash due to beavers

**Screenshots**
n/a

**System (please complete the following information):**
- Occultism Version: occultism-1.18.1-1.26.0
- OS: Win10
- Minecraft Version: 1.18.1
- Modpack Link and Version, or list of mods: WiP pack [modlist.txt](https://github.com/klikli-dev/occultism/files/7980715/modlist.txt)

**Additional context**
Crash reports - 
[crash-2022-02-01_09.32.50-server.txt](https://github.com/klikli-dev/occultism/files/7980691/crash-2022-02-01_09.32.50-server.txt)
[crash-2022-02-01_07.31.59-server.txt](https://github.com/klikli-dev/occultism/files/7980692/crash-2022-02-01_07.31.59-server.txt)
[crash-2022-02-01_09.18.38-server.txt](https://github.com/klikli-dev/occultism/files/7980693/crash-2022-02-01_09.18.38-server.txt)

**Comment by solcrest** [comment]
I believe these crashes are happening when trees try to grow. I've also noticed that bonemeal does not grow trees with this update.

**Comment by Nachtflame** [comment]
Hmm....  Except there are no saplings in loaded/render range where I was at in the world.
This is a test world for my current WiP pack. I've not planted a single sapling, and there are no Lost Cities within 1000 blocks (only place planted saplings would generate).

**Comment by Anaerin** [comment]
Have the same issue here. And it does appear that the crash is happening somewhere in 
```
com.github.klikli_dev.occultism.handlers.FamiliarEventHandler.beaverFindTree(FamiliarEventHandler.java:65)
```
and/or
```
ASMEventHandler_630_FamiliarEventHandler_beaverFindTree_SaplingGrowTreeEvent.invoke(.dynamic)
```

Players confirmed it happened after planting a sapling; bonemealing said sapling is what caused the crash.
