### ISSUE TITLE
World Ticking Error Crash after a few seconds of playing

### ISSUE THREAD

**Issue by RallyRunner** [klikli-dev/occultism#643]
**Describe the bug**
Just playing the game and it crashes after a while.

**To Reproduce**
1. Walk around to play the game

**Expected behavior**
For it not to crash.

**Screenshots**
This pastebin includes the crash report.
https://pastebin.com/bza9SHRM

**System (please complete the following information):**
- Occultism Version: 1.26.0
- OS: [e.g. Windows] MacOS
- Minecraft Version: 1.16.5
- Modpack Link and Version, or list of mods: 
Crucial 2 Pack + Occultism (Custom Made)

**Comment by esotericist** [comment]
looks like a duplicate of #642 and #641

**Comment by Shibva** [comment]
same issue here, but i have no beavers, it seems to be a strange error that happens

**Comment by klikli-dev** [comment]
Yeah crash is definitely from the beaver based on the log. Beaver need not necessarily be in the world for it to happen

**Comment by Shibva** [comment]
Can confirm this issue for it happening without the beaver, I dint have one when it happened

also, this issue is relevant in 1.16.5 as it happened to me on that version
