### ISSUE TITLE
Suggestion: Storage Stabilizer and Dimensional Storage

### ISSUE THREAD

**Issue by TrueGuardian32** [klikli-dev/occultism#645]
**Is your feature request related to a problem? Please describe.**
When your doing a magic only modpack this mod is invaluable, but there are a few issues I'd like to have fixed or added. For example making a higher tier stabilizer that allows for near infinite storage or the option to increase the amount stored. But I'd also like a fix for if there is a recipe conflict. There are no recipe conflict mods but you can't use them with the internal crafting GUI. 

**Describe the solution you'd like**
Either an Infinite Storage Tier maybe with a boss that you have to fight, or a way to change the number of slots in settings for the existing stabilizers. 
Also a recipe conflict selector so you can select which item you want when bulk crafting. 
**Additional context**
I mostly play on 1.16.5 until more of the 1.16.5 mods are ported up.

**Comment by theboo** [comment]
First solution: There are already configs to change the slots added per stabilizer, as well as slot size. This is a server config so will be found in `saves/worldname/serverconfig/occultism-server.toml` or on a server it would be in `world/serverconfig/occultism-server.toml` 
![image](https://user-images.githubusercontent.com/3585761/152724875-334f0525-b2e4-4d4e-8fec-94ec446371f6.png)

As for your second request regarding recipe conflicts, the polymorph mod does work with the latest occultism versions for 1.16.5 as seen in the screenshot below, click the circular arrows and the other options for the recipe pop up.
The latest version of this mod for 1.16.5 can be found here: https://www.curseforge.com/minecraft/mc-mods/polymorph/files/3604756

![image](https://user-images.githubusercontent.com/3585761/152724831-e1d96069-2078-4d56-96d1-02413cbc49ee.png)

**Comment by TrueGuardian32** [comment]
Ah Alright! Thanks, didn't know I went searching the configs that day and couldn't find them. Thank you for the amazing mod!
