### ISSUE TITLE
Re-add working goggles overlay rendering for 1.18

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#651]
overlay rendering changed in 1.18 causing issues, see #650

**Comment by Cinderheart** [comment]
Commenting here with my own issues. 

As per Mischief of Mice's video, the intended effect of the goggles is a less extreme purple overlay. 
Instead, the goggles maintain the vision overlay you last had. Wearing them normally has no overlay, and wearing them while under the effects of the demon dream fruit causes that overlay to last until you take the goggles off.

occultism-1.18.1-1.26.9
Minecraft-1.18.1
Forge-39.0.88

Testing world with only the bare minimum mods - Patchouli, Occultism, JEI, JER, GeckoLib, and Curios API (Forge)

**Comment by klikli-dev** [comment]
Closed in 03b1f6ce911d4f9ef862b869b522ad74c67e44ee

**Comment by Cinderheart** [comment]
Awesome, thank you.
