### ISSUE TITLE
In the Crafting Grid of Refined Storage, the amount of items consumed when Shift+Click is wrong.

### ISSUE THREAD

**Issue by tetuis** [klikli-dev/occultism#652]
**Describe the bug**
(It may be difficult to understand because it is machine translation.)
When using Dimensional Storage with Refined Storage's External Storage, the amount consumed when crafting with Shift+Click is unusually low.

**To Reproduce**
1. Connect the External Storage to the Dimensional Storage Actuator.
2. Stores 320 coal.
3. Craft the Block of Coal with Shift + click.
4. You have crafted 35 Block of Coal and have 257 Coal left over.

**Expected behavior**
There should be 5 Coal left.

**Screenshots**
![1](https://user-images.githubusercontent.com/69350996/153480283-d9369358-5402-445e-ae4f-c3d109e78cd2.png)
![2](https://user-images.githubusercontent.com/69350996/153480299-0a66f399-f37b-43fd-8899-cf8978ee6ba7.png)
![3](https://user-images.githubusercontent.com/69350996/153480312-91eb696c-15eb-4b7d-94fa-f4535e58ca27.png)

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.26.3
- OS: Windows 10
- Minecraft Version: 1.16.5(Forge 36.2.26)
- Modpack Link and Version, or list of mods: Refined Storage 1.9.17

**Additional context**
none

**Comment by tetuis** [comment]
I'm sorry. The remaining amount is 252. I made a mistake while typing.

**Comment by MuteTiefling** [comment]
@theboo asked me to test this out and I can confirm.

Video for some extra details: https://streamable.com/s8qxnf

The short of it: Works as expected with auto crafting and manually crafting 1 item at a time. It only appears to break if using Sneak Click to do a full stack in Refined Storage. Assuming maths are getting wonkers with the increased stack size. Also works as expected when crafting inthe actuator.

**Comment by MuteTiefling** [comment]
Works correctly with the stack size override disabled.

**Comment by Darkere** [comment]
If I see this correctly, overriding `extractItem` on your itemhandler should fix this. The default implementation only allows extracting a maximum of `Item#maxStackSize` at once. 

I've made an issue on our side too https://github.com/refinedmods/refinedstorage/issues/3242

**Comment by klikli-dev** [comment]
thank you so much everyone - I'll fix this on my end
