### ISSUE TITLE
Make Familiar Rings be able to be toggle on and off with a keybind.

### ISSUE THREAD

**Issue by BlackStone5677** [klikli-dev/occultism#659]
Make Familiar Rings be able to be toggle on and off with a keybind.
Familiar abilities are great but for how powerful they are some of them can get a little annoying in some cases, for example the drikwing has the ability of slow falling, multi-jump and jump boost. these are all great but hitting the roof with every jump is not really useful in enclosed spaces. or for example the greedy familiar's ability is to pick up items in a larger radius but in some mob farms and such you can end up with lot's of junk in your inventory. You can take of the ring and that would disable the ability, but I think this is alot more handy and would be alot more convenient to not have to take off my drikwing ring every time I go through a door lol. An alternative would be to have the effects disable while holding shift while that's great for some stuff it's not really as good. and I think it would be alot better if the status effects didn't just linger around after toggling and would just clear, so it would be an instant effect. it also adds more reason to use the ring over the familiars themselves

**Comment by theboo** [comment]
every familiar has its own keybind to enable/disable while in a ring already..

![image](https://user-images.githubusercontent.com/3585761/154869110-15699c8f-e209-495e-99f4-8ef7bc37e586.png)
