### ISSUE TITLE
Clicking on Iesnium ore in JEI with Lychee(Forge) installed causes a crash.

### ISSUE THREAD

**Issue by Cinderheart** [klikli-dev/occultism#665]
Clicking Iesnium ore in JEI causes a crash. As will pressing R on it.

1. Click on Iesnium Ore with JEI and Lychee(Forge) installed in the JEI menu to instantly crash.

**Expected behavior**
The page saying to look at the Dictionary of Spirits for more information should appear.

**System (please complete the following information):**
- Occultism Version:  occultism-1.18.1-1.26.8
- OS: Windows 10
- Minecraft Version: 1.18.1
- Forge Version: 39.0.88
- Modpack Link and Version, or list of mods: Test modpack for just this bug. Contains only Occultism, JEI, Lychee, and the various library mods they need.
Curios API
GeckoLib
JustEnoughItems
JustEnoughResources (for testing, thought it might have been the cause before I realized it was Lychee)
Lychee
Occultism
Patchouli

**Comment by klikli-dev** [comment]
Please provide a crash log then we can look into it :)

**Comment by Cinderheart** [comment]
Sure thing. Should be easy to reproduce too.
[crash-2022-02-26_15.48.48-client.txt](https://github.com/klikli-dev/occultism/files/8147476/crash-2022-02-26_15.48.48-client.txt)

**Comment by klikli-dev** [comment]
@Cinderheart thank you! Based on the crash log the crash happens in lychee render code - can you please create an issue on their end (and link back here in case they need any info or changes on Occultism's side?

**Comment by Cinderheart** [comment]
Sent.

**Comment by klikli-dev** [comment]
Fixed in https://github.com/Snownee/Lychee/issues/11
