### ISSUE TITLE
item.occultism.raw_silver and item.occultism.raw_iesnium

### ISSUE THREAD

**Issue by KlaraChaos** [klikli-dev/occultism#667]
**Describe the bug**
i think somthing went wrong and it shows the hole item string

**To Reproduce**
1. get raw silver or raw iesnium ore
2. open invetory
5. see wrong text

**Expected behavior**
that its onlyncalled raw iesnium or raw silver and not show the hole item string

**Screenshots**
![image](https://user-images.githubusercontent.com/75270975/156445167-9ca361cf-f4c0-48c7-ac12-4f9e4fc1677d.jpg) 
![image](https://user-images.githubusercontent.com/75270975/156445215-b60e68ea-f40a-46d8-8cd5-1d142ff4ff7e.jpg)

**System (please complete the following information):**
- Occultism Version: 1.18.1 -1.26.8
- OS: Windows
- Minecraft Version:1.18.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-3 version 1.6

**Comment by Cinderheart** [comment]
I'm still seeing this, ditto for the torch and campfire. Lemme make a testing world with only occultism and JEI as mods and then I'll file my own bug report. Maybe the mod just didn't update right in my modpack.

**Comment by ChiefArug** [comment]
Silver deepslate ore is also affected

**Comment by klikli-dev** [comment]
As raw metals are not ores thus not blocks the added texts don't work.
Continued in #670
