### ISSUE TITLE
Raw ores are missing the forge:raw_materials tags

### ISSUE THREAD

**Issue by ChiefArug** [klikli-dev/occultism#668]
**Describe the bug**
Forge finally decided on a tag for raw stuff, it is `forge:raw_materials/<material name>`. Currently Occultism raw ores do not have these tags, making them incompatible with mods that use them (like Tinkers Construct, you cannot melt Occultism raw ores in their smelteries)

**To Reproduce**
1. Load Occultism
2. Enable advanced tooltips (`F3` + `H`)
3. Hover over Occultism's silver raw ore item and see the tag missing
4. Hover over the raw ore item for copper and see it does have the corresponding `raw_materials` tags

**Expected behavior**
For the raw ore items to have there corresponding `raw_materials` tags, and the base `forge:raw_materials` tag too.

**System (please complete the following information):**
- Occultism Version: `occultism-1.18.1-1.26.8`
- OS: Windows 10
- Minecraft Version: 1.18.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/mps-s7

**Additional context**
A datapack which fixes this: 
[occultism_raw_materials_tag_fix.zip](https://github.com/klikli-dev/occultism/files/8176340/occultism_raw_materials_tag_fix.zip)

**Comment by klikli-dev** [comment]
@ChiefArug many thanks!
