### ISSUE TITLE
Various issues involving Unstable Otherworld Trees.

### ISSUE THREAD

**Issue by Cinderheart** [klikli-dev/occultism#674]
**Describe the bug**
Unstable otherworld trees do not behave as described within in-game documentation.
1. Breaking unstable otherwood while wearing Otherworld goggles drops an oak log. Using Demon's dream instead does work. Using an Iesnium pickaxe or infused pickaxe also works.
2. Right or left clicking an unstable otherwood log, sapling, or leaf block will make it flicker to it's undisguised form while wearing the Otherworld Goggles. Also happens while using Demon's dream, either alone or with the goggles.
4. Unstable otherwood leaves do not drop anything, no matter what you're wearing or ingesting or what tool you use, in any combination. They also have grey breaking particles, whereas stable otherworld trees have the proper purple ones.

**Expected behavior**
Otherworld saplings should drop from leaves when broken manually while under the effects of demon's dream, and drop oak saplings otherwise.

As eating demon's dream fruit gives us third eye II, I would also expect the otherworld goggles to give us third eye I as it is the other version of that effect.

**System (please complete the following information):**
- Occultism Version: 1.18.1-1.26.9
- OS: Windows 10
- Minecraft Version:1.18.1
- Forge-39.0.88
- Modpack Link and Version, or list of mods: Patchouli, Occultism, JEI, JER, GeckoLib, and Curios API (Forge)

**Additional context**
Love the mod, just needs some polish.

**Comment by theboo** [comment]
1. Otherworld goggles are not intended to let you mine otherworld materials, by the time you get them you should have stable saplings and a source for otherstone. They are fairly helpful when looking for iesnium however.
2. Haven't tested personally
3. Can confirm, broke about 4 groves worth of leaves and no sapling

**Comment by Cinderheart** [comment]
Ah, I checked the mod book and you're right with the goggles. 

Did you notice the grey particles as well when breaking the leaves? You can only see them if you've got the goggles on and no demon's dream.

**Comment by klikli-dev** [comment]
Oddly enough I had that commented in my code, but never fixed it:

![image](https://user-images.githubusercontent.com/60774993/157269756-8443f491-9f4d-412c-9ae1-9573a0c2b0c8.png)

Will look into that, hopefully it wasn't borked for good with 1.18

**Comment by klikli-dev** [comment]
Behaviour will be fixed in next patch:
- under the influence of daemon's dream unstable otherworld saplings will drop
- when (just) wearing goggles none will drop
- when using otherworld tools saplings will drop
- sapling drop rate on unstable otherworld trees is x2 compared to vanilla oak trees
