### ISSUE TITLE
Several items have broken names.

### ISSUE THREAD

**Issue by Cinderheart** [klikli-dev/occultism#675]
**Describe the bug**
block.occultism.spirit_campfire
block.occultism.spirit_lantern
block.occultism.silver_ore_deepslate
block.occultism.spirit_torch
item.occultism.raw_iesnium
item.occultism.raw_silver

Also mining iesnium ore in the world drops iesnium ore, which must be placed and mined again to get the raw iesnium. This might be intentional on your part. Also once you have that iesnium ore it can be mined with a diamond pickaxe.

**Expected behavior**
Plaintext names.

**System (please complete the following information):**
- Occultism Version: 1.18.1-1.26.9
- OS: Windows 10
- Minecraft Version:1.18.1
- Forge-39.0.88
- Modpack Link and Version, or list of mods: Patchouli, Occultism, JEI, JER, GeckoLib, and Curios API (Forge)

**Comment by klikli-dev** [comment]
Could you re-test this on the latest version (on 1.18.2)? 
I believe all of them are fixed there

As for the iesnium ore: that is indeed intended, although I might skip this in the future

**Comment by Cinderheart** [comment]
I will, but my current modpack I'm trying to make for my friends is in 1.18.1. I would love to update to 1.18.2 but sadly many mods still aren't on the newest version.

**Comment by klikli-dev** [comment]
No promises on 1.18.1 updates - it gets very time consuming to maintain multiple versions. If 1.18.2 is still not widely adopted a few weeks or months down the line I will probably backport the 1.18.2 changes though

**Comment by Cinderheart** [comment]
Ouch, but understandable.

ATM all the YUNGs mods are on 1.18.1 except for his patreon supporters who get early access to 1.18.2 versions, so I bet a lot of people are still on 1.1.8.1 for that alone.

**Comment by klikli-dev** [comment]
Closing this for now as, at least in dev, these item names work in latest
