### ISSUE TITLE
[Suggestion] Allow machine operator's deposit and extract locations to be different blocks - Warning: Might require to set up machine managers again

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#678]
Had a thought that would give the machine operator more compatibility with mods like create where you would have an input chest and an output chest, and mods like IE where many of the machines are multiblocks.

The thought is, instead of having the machine operator's GUI set the extract and deposit sides on one screen, you would make it work like the transporter where you have a button that cycles through deposit, extract, and with the operator, an extra "bind actuator" button. And allow deposit and extract to be separate blocks.

This would allow you to have on demand processing through stuff like create machines, while still keeping the functionality it has currently for single block machines. You would just have to select the proper sides for deposit and extract using the book in the same way as you do with the transporter rather than setting them in the gui itself.

**Comment by klikli-dev** [comment]
That sounds pretty exactly like it should have been done from the start haha.
I like it, will look into it :D
