### ISSUE TITLE
Divination rod does not find blocks 

### ISSUE THREAD

**Issue by explicitargo** [klikli-dev/occultism#679]
**Describe the bug**
Items like otherstones and otherworld trees are not spawning naturally.

**To Reproduce**
1. Install mod
2. Create a world
3. No matter how much I look (with divination staff and googles) I don't see any materials naturally generating.

**Expected behavior**
Items generate on the overworld.

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.27.3
- OS: W11
- Minecraft Version: MC 1.18.2 Forge 40.0.12
- Modpack Link and Version, or list of mods: Patchouli, Curios API, GeckoLib.

**Comment by klikli-dev** [comment]
Generation works, highlighting also works, but the scanner for some reason no longer finds blocks.

Correction: I am a moron. I tested by placing leaves, but placed the wrong ones. Both generation and and highlighting work
