### ISSUE TITLE
Problem with the Shub Familiar

### ISSUE THREAD

**Issue by thestupendousdonut** [klikli-dev/occultism#680]
The Shub familiar, which has shub spawn, keep spawning out of me for no reason. I read the guide book but it said nothing about it

It started when I glitched the /god mode when I went into survival, then I went into creative and did /ungod, then I was killed by a hunter, and my Shub soul was nowhere to be found. But then when I went to the location of where I died, these shub spawn just randomly spawned out of me and now I can't find a way to get rid of them. Even though I tried rejoining the game or dying and respawning

![proof againu minmecraft](https://user-images.githubusercontent.com/101373017/157782468-505f0851-c936-44e7-85b6-8281e64745dc.png)

**Comment by klikli-dev** [comment]
This sounds like something caused by the god/ungod and gamemode changes. The shub spawns are created by the shub niggurath itself, so it likely is still around but hidden. 
Try typing `/kill @e[type=occultism:shub_niggurath_familiar]` to get rid of it
