### ISSUE TITLE
Create mod detecting ritual recipes as valid mixer generated recipes.

### ISSUE THREAD

**Issue by manaphoenix** [klikli-dev/occultism#682]
**Describe the bug**
title...

**Screenshots**
![image](https://user-images.githubusercontent.com/7843805/158611048-bf1b7655-846d-4734-9409-bdfb24da0e2a.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.18.1-1.26.9
- Create Version: create-mc1.18.1_v0.4e
- OS: Windows 11 Pro
- Minecraft Version: 1.18.1-39.1.2

**Comment by klikli-dev** [comment]
Closed in https://github.com/Creators-of-Create/Create/issues/2870
