### ISSUE TITLE
Forge Mod Compatibilities

### ISSUE THREAD

**Issue by TrueGuardian32** [klikli-dev/occultism#683]
**Is your feature request related to a problem? Please describe.**
When I accidentally make the wrong item due to a recipe conflict or etc.

**Describe the solution you'd like**
Can you add forge tags to your rituals instead of using specified blocks. Such as Obsidian_dust [Can't remember the correct oredic name per moment.] Or the placed candle could be any oredic specifying candle? I can add oredic tags to the blocks but you would need to be the one to make it compatible... Eh this could be a stupid idea but I just wanted to share it before I lose my nerve. 

**Additional context**

**Comment by theboo** [comment]
First off, oredict isn't a thing, it's just tags, and it's not a forge thing, it's vanilla... Most of the rituals should be using tags for their input ingredients, can you please give an example of one that isn't?

 2nd, in 1.18+, any candle with the minecraft:candles block tag should work fine with the pentacles which includes vanilla candles. If you're on 1.16.5 the candles would need the forge:candles block tag

**Comment by TrueGuardian32** [comment]
Sounds good... Sorry if I sound stupid.

**Comment by theboo** [comment]
dont worry, you didnt sound stupid at all! if you come across any rituals/recipes that arent using tagged inputs where they should, drop them here and i'll gladly PR a fix!
