### ISSUE TITLE
Significantly decrease drop rate of demon's dream seeds from breaking grass

### ISSUE THREAD

**Issue by TheDeviantCrafter** [klikli-dev/occultism#686]
**Is your feature request related to a problem? Please describe.**
When breaking grass, I get roughly twice as many demon's dream seeds as I do wheat seeds. Considering more players will make a wheat farm than get into Occultism, this seems a bit high.

The seeds clog up the player's inventory.

**Describe the solution you'd like**
Decrease the drop rate of demon's dream seeds when breaking grass to be at least 4 times rarer than wheat seeds.

Adding a config option to allow pack devs to tweak the drop rate would also be appreciated.

**Comment by klikli-dev** [comment]
I agree, that is too high, I'll decrease this accordingly.

As for the config option: That already exists, the drop chance can be changed via datapack, currently it is 10% but can be changed in the following jsons:

![image](https://user-images.githubusercontent.com/60774993/159684017-8f4adad2-b371-451c-b351-5262eda31fa7.png)
