### ISSUE TITLE
Items lost when unequipped Surprisingly Substantial Satchel from curios slots.

### ISSUE THREAD

**Issue by qyl27** [klikli-dev/occultism#689]
**Describe the bug**
When the Surprisingly Substantial Satchel was taken from curios slots, the items in it were all lost.

**To Reproduce**
1. Install curios and occultism.
2. Make a Satchel and equip it into curios, and place some items on it.
3. Unequip it and open it in hand.
4. Re-equip it into curios.
5. Open it, and items are lost.

**Expected behavior**
Items should be shown.

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.29.0
- OS: Windows server 2019
- Minecraft Version: 1.18.2

**Additional context**
- Curios: 1.18.2-5.0.6.3
- Server brand: Arclight

**Comment by klikli-dev** [comment]
This does not reproduce in dev when following your steps.
Can you take a screen recording of how it reproduces?
Are any other mods in use?
