### ISSUE TITLE
1.18.1 No outlines from divination rod

### ISSUE THREAD

**Issue by Splittikin** [klikli-dev/occultism#693]
**Describe the bug**
Blocks aren't outlined by the divination rod. The blocks generate just fine and the item in hand changes sprite from distance correctly, there's just no outline on the block.

**To Reproduce**
1. Place/Find Iesnium
2. Attune divination rod
3. Use divination rod
4. Divination rod turns purple, but no outline on the ore.

**Expected behavior**
The block is outlined.

**Screenshots**
https://user-images.githubusercontent.com/45697042/163493604-eb7d13fb-115b-4c70-9951-96cd3b70ed59.mp4

**System (please complete the following information):**
- Occultism Version: 1.18.1-1.26.9
- OS: Linux (openjdk 18 2022-03-22)
- Minecraft Version: 1.18.1
- Modpack Link and Version, or list of mods: 
![image](https://user-images.githubusercontent.com/45697042/163493660-10ec4fc1-e2fc-47a5-8282-fbf51e08d20d.png)
(Note: OptiFine is being used in the video and is on the list, but I have tried in a separate singleplayer world without OptiFine installed and the issue persists.)

**Additional context**
The ore block I spawn in the video appears to flash a couple times, but this does not happen when OBS isn't running.

**Comment by klikli-dev** [comment]
1.18.1 is no longer supported as forge moved on to 1.18.2 (the versions are not compatible, and maintaining both is too much of a strain to keep up) 
Does the issue reproduce with just Occultism + Dependencies on the latest 1.18 release?

**Comment by Splittikin** [comment]
No, it works fine in the 1.18.2 version.
