### ISSUE TITLE
Make actuator use the item you have most

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#694]
**Is your feature request related to a problem? Please describe.**
I'm unsure how occultism chooses what item, but when you autofill recipes from JEI with tagged inputs, the actuator often chooses an item you dont have very much of, or maybe a more expensive item that happens to be in the tag.

**Describe the solution you'd like**
Would be really nice if occultism used the item you have the most of in storage vs however it chooses its items now. Both refined storage and pretty pipes are able to use the item you have most in the tag, would be nice to see it here!

**Additional context**
A couple examples would be:

1. in enigmatica 6 expert, auto filling anything from JEI that has inputs using the `forge:glass` tag, occultism will always choose `atum:crystal_glass` over just regular `minecraft:glass`, even though you might only have 8 crystal glass in the storage vs 2k normal glass.
2. crafting anything with the `forge:stone` tag in the inputs seems to always pick `undergarden:shiverstone` which you might not have much of, but could have thousands of other stone variants.

I fully understand if this cant make it in to 1.16(which would be awesome xD), even having it for future versions would be ideal i think!

**Comment by klikli-dev** [comment]
I see, that's definitely an important feature. Currently the system searches the slots in order, and exits as soon as it collected the desired amount. The first stack found determines the type, because after that it can only take if the items stack. 

Implementing this needs to be done somewhat carefully, because in order to be aware of how much of each type there are we actually need to go through all, count them and then basically do what we do now on top of that. With big systems that can easily get out of hand

**Comment by theboo** [comment]
yeah that makes sense! Might look at how RS does it as they seem to do it pretty performantly, even when using external storage. 

Another slightly less important QOL feature RS/ID storage networks have is the ability to tell you in JEI when you are missing items. But that might be out of the scope of occultism :D

Similar to this image(i am using RS here with an external storage on an occultism wormhole): 
![image](https://user-images.githubusercontent.com/3585761/163729152-4f68782b-3b47-4c7e-a447-e2b7b153e4fe.png)

**Comment by klikli-dev** [comment]
The latter is indeed out of scope, I looked into it before but decided I can't make time for it now.
However I did backport the "take item with highest quantity" feature to 1.16 (luckily this part of the code is almost the same in both minecraft versions) :)

**Comment by theboo** [comment]
Amazing! Thanks a bunch!
