### ISSUE TITLE
Trying to craft anything in the dimensional actuator causes crash

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#7]
**Describe the bug**
Crafting anything in the actuator GUI grid causes insta-crash. After this crash, if you reload the world and try to open the same actuator you instantly crash with a different crash report.

**To Reproduce**
1. open actuator GUI
2. try to use the built in crafting grid to craft anything(i chose wood planks for this test)
4. See error: https://pastebin.com/LwfHa6y7
5. reload word
6. open same actuator
7. https://pastebin.com/aCHt44FX

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 
- OS: [e.g. Windows]
- Minecraft Version:
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by theboo** [comment]
just noticed, when you load the world back up after crashing, your crafted item is sitting on the ground. Also the 2nd crash that happens after you first reload the world only happens on the first time reloading after the first crash.

**Comment by klikli-dev** [comment]
Fixed in v1.15.2-0.2.5
