### ISSUE TITLE
Add es_ES translation - thanks @Krypt0p

### ISSUE THREAD

**Issue by Krypt0p** [klikli-dev/occultism#701]
**Is your feature request related to a problem? Please describe.**
So I tried to make a Spanish translation for this mod. Everything seemed ok while doing it, no problem taking the original en_us and copy it to generate a new archive with all the info of the mod to translate it to Spanish. All done, but when I try to add the es_es version into the .jar file (and test it), got some errors ingame and I can't make it to work properly.

**Describe the solution you'd like**
Need some advice on what I can do to fix the problem seem in the pictures, or what am I doing wrong when translating...

**Additional context**
Added screenshoots of the error I'm getting ingame:

![2022-04-24_23 25 49](https://user-images.githubusercontent.com/104327938/164999291-5bf63f7a-c8ab-47c0-889a-6c0801642da2.png)

Added log of errors in txt:

[latest.log](https://github.com/klikli-dev/occultism/files/8550619/latest.log)

**Comment by klikli-dev** [comment]
@Krypt0p this is an error from patchouli, so you may be best served to ask in their discord: discord.gg/vm (there's a #patchouli channel), I am not an expert in translating books and if special rules have to be followed. 

Generally speaking, it seems like you are missing the template https://github.com/klikli-dev/occultism/blob/version/1.18/src/main/resources/data/occultism/patchouli_books/dictionary_of_spirits/en_us/templates/ritual.json, either the file is not part of your translation, or it has a json error (if so, try to put it into https://jsonlint.com/ to see what the errors are)

**Comment by Krypt0p** [comment]
@klikli-dev so checked the .json in https://jsonlint.com/ and seems to be fine. 

Checked other translations here, in GitHub, but doesn't seem that they changed anything (the ritual.json I have and the one in the chinese translation are exactly the same). I tried to revert the changes I saw (changing the lines where "pachouli:item" and leaving only "item") to see if it has something to do with it, but no.

I'm gonna ask in the patchouli discord as you told me, and I'll come back if I discover anything or got the answer! Thanks!

**Comment by klikli-dev** [comment]
A good lead to ask for is if translations need to do anything specific for templates, at least templates seem to be the problem here based on the error

**Comment by Aegide** [comment]
@Krypt0p could you please make a fork (that will include your translation) and a draft pull request ?

It will allow us to see your changes, and give you better advices.
<br><br>
> taking the original en_us and copy it to generate a new archive

_That's disgusting, but ok i'm guilty of doing the same when i want to test translations._

If you actually want to quickly test some of your translations, without recompiling the entire mod.
Then just change the content of **en_us** or **zh_cn** inside the archive.
I personally use 7zip and notepad++ to update my archive.

There is no need to suffer with "generating a new archive".

**Comment by Aegide** [comment]
Example of "dirty archive editing" :

![image](https://user-images.githubusercontent.com/43409914/165193817-b23f1ede-4774-4237-9347-cc0a9902a9b7.png)
