### ISSUE TITLE
Config occultism-server.toml is invalid, correcting

### ISSUE THREAD

**Issue by atlgeek007** [klikli-dev/occultism#704]
**Describe the bug**
Per #702 , I installed Minecraft 1.18.2, Forge 40.1.0, and Occultism  1.18.2-1.32.1 to test this out, along with AppleSkin, Controlling, Curios API, GeckoLib, JEI, Mouse Tweaks, The One Probe, and Patchouli.

Without making any changes to the occultism-server.toml config, I see this message in my logs on client startup:

[26Apr2022 15:02:30.338] [Thread-1/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /Applications/MultiMC.app/Data/instances/1.18.2/.minecraft/saves/New World/serverconfig/occultism-server.toml is not correct. Correcting

Closing the client, editing the file to include names like "ATLGeek007" and "Charibades" then starting the client results in the same message, and the config file getting clobbered with the default config on startup.

**To Reproduce**
1) install forge/occultism/dependencies
2) Start client
3) See "correcting" message in logs
4) attempt to customize spirit names
5) see changes immediately reverted on file reload

**Expected behavior**
A custom list of spirit names in the config file, that spirits are named with.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.32.1 
- OS: MacOS
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: Occultism, Patchouli, JEI, The One Probe, AppleSkin, Controlling

**Comment by klikli-dev** [comment]
Huh, seems the config system somehow is picky about being given immutable lists as default value and always wants to correct back to empty. Not the most useful "feature" haha.

Will be fixed promptly!

**Comment by atlgeek007** [comment]
You are the most amazingly responsive dev I've ever met.  Are you looking for a job? LOL

**Comment by klikli-dev** [comment]
Thanks a lot but I'm already happily occupied haha
