### ISSUE TITLE
Request: Another way to trigger otherworld vision with an addon

### ISSUE THREAD

**Issue by RCXcrafter** [klikli-dev/occultism#705]
**Is your feature request related to a problem? Please describe.**
I'm working on a tinkers construct compatibility addon and I would like to add an otherworld goggles modifier for helmets. Currently otherworld vision only works with items that extend OtherworldGogglesItem which isn't an option for me.
https://github.com/klikli-dev/occultism/blob/version/1.18/src/main/java/com/github/klikli_dev/occultism/util/CuriosUtil.java#L41

**Describe the solution you'd like**
I would like to request some sort of way for otherworld vision to check for something that I can add/remove through a tinkers construct modifier. A boolean NBT tag that says whether the item can give the player otherworld vision would be a simple and effective way of doing this I think. An item capability would also work but personally I think that's overkill for something that can only be on or off.

**Comment by klikli-dev** [comment]
Ah yes that was a rather short-sighted design decision on my end.
NBT can be done :)

**Comment by klikli-dev** [comment]
Added NBT and Tag support, see https://github.com/klikli-dev/occultism/blob/4f0682ba40a9428d2613c5589e73a6e858c43c78/src/main/java/com/github/klikli_dev/occultism/common/item/armor/OtherworldGogglesItem.java#L58 

`occultism:otherworld_goggles=true` will make an item be seen as goggles, the same applies to the `occultism:otherworld_goggles` tag.

**Comment by klikli-dev** [comment]
@RCXcrafter please let me know if it works as intended!

**Comment by RCXcrafter** [comment]
Thanks, I just tried it out and it works as intended.
