### ISSUE TITLE
Blacksmith Summon deletes picked up Items

### ISSUE THREAD

**Issue by FreddysChild** [klikli-dev/occultism#707]
**Describe the bug**
The Blacksmith keeps deleting certain Items that I pick up. For example Granit, Stone etc. but not Ore or Wood.

**To Reproduce**
1. Summon the Blacksmith
2. Put him in a ring and equip him
3. Place some Granit and use a pickaxe to destroy it.
4. Pick it up and you'll see that you got nothing in your inventory nor did you hear the usual "pick up" sound.

**Expected behavior**
The Blacksmith usually just uses Iron to repair equipment in the process.

**System (please complete the following information):**
- Occultism Version: 1.32.0
- OS: Windows
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: All the Mod 7 - 0.3.17

**Additional context**
(https://youtu.be/MTPvlFQygiw)

**Comment by klikli-dev** [comment]
This is not a bug but expected behaviour - the blacksmith uses stone-tagged blocks to repair equipment. There is only a chance for a successful repair on each stone consumed
