### ISSUE TITLE
Immortal Spiritfire Block

### ISSUE THREAD

**Issue by Cicopath** [klikli-dev/occultism#712]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It would be cool if spiritfire had its own block where it will never extinguish. Also, using spiritfire and netherrack together is not visually appealing.

**Additional context**
A few mods, including vanilla, have this feature. For example, soul fire from vanilla can only be created on soul soil or soul sand; and soul fire or cryptic fire from Oh The Biomes You'll Go can be created on brimstone or cryptic stone, respectively.

**Comment by Pultex** [comment]
think you can do this with a log under it
any log should work at least in the past

**Comment by klikli-dev** [comment]
That is correct, I am closing this issue.
If the fire on the log does not work as expected, please create a new issue
