### ISSUE TITLE
Storage Accessor causing server lag

### ISSUE THREAD

**Issue by nanakisan** [klikli-dev/occultism#717]
**Describe the bug**
Per the title I am currently on the M&A testing server running the Battlechicken Modpack. A player has reported that the storage accessor is force loading an unloaded chunk. In doing this the server's tps takes a dramatic hit.

**To Reproduce**
1: Have Storage Matrix
2: Have Storage Accessor bound to the matrix
3: Try to open it from a far enough distance where it isn't loaded

**Expected behavior**
Storage Accessor should not work when chunk is not loaded

**Screenshots**
None available

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.34.0
- OS: Windows 10
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/battlechicken-modpack

**Additional context**
This is all the information I currently have and can provide.

**Comment by klikli-dev** [comment]
Occultism does not provide any chunk loading mechanic, nor does it use the forge / mc builtin chunk loading.
It is possible minecraft or forge are now doing this automatically if a chunk is being accessed, but I was not made aware of any such change. 

Does this reproduce with only occultism and it's dependencies?

**Comment by klikli-dev** [comment]
Going to publish a potential fix for this, please just open a new issue and link to this one if it persists in 1.35.1
