### ISSUE TITLE
Summon Parrot ritual gives a chicken instead

### ISSUE THREAD

**Issue by Lavan** [klikli-dev/occultism#727]
**Describe the bug**

My wife tried to summon a parrot familiar, but ended up with a demon-named chicken. Tried it twice with same result.

**To Reproduce**
1. Perform the Summon Parrot familiar ritual as described in the documentation in a Hedyrin's Lure pentacle.
2. Sacrifice chicken
3. A chicken spawn instead of the parrot.

**Expected behavior**
A parrot familiar.

**Screenshots**
A screenshot exist but it only shows a chicken with a strange name.

**System (please complete the following information):**
- Occultism Version: 1.35.2
- OS: Windows 11
- Minecraft Version: MC 1.18.2 Forge 40.1.31
- Modpack Link and Version, or list of mods ATM 7 version 0.4.16 

**Additional context**
None

**Comment by klikli-dev** [comment]
It's a feature!

No really, it's chance based :) There's I think a 30% chance to get a named chicken instead. If you redo the ritual you will eventually and up with a parrot
