### ISSUE TITLE
[1.16.4] Third Eye Removed by trinket from Lost Trinkets

### ISSUE THREAD

**Issue by NillerMedDild** [klikli-dev/occultism#73]
**Describe your problem**
The mod Lost Trinkets has a trinket called `Magical Herbs`, which removes all negative potion effects from you. If you're wearing that when eating Demon's Dream Fruit, Third Eye will be instantly removed without notifying the user. 
This can result in the player being unable to progress in Occultism, as Otherworld Logs/Saplings will never drop.

**System (please complete the following information):**
- Minecraft Version 1.16
- Enigmatica 6, https://www.curseforge.com/minecraft/modpacks/enigmatica6, in-dev 0.3.3
- Lost Trinkets: https://www.curseforge.com/minecraft/mc-mods/lost-trinkets

Edit: Reported by user Thiana here: https://github.com/NillerMedDild/Enigmatica6/issues/674

**Comment by klikli-dev** [comment]
Thanks for the report! That could be a tricky one to solve, but I think I can declare demon's dream a positive effect to avoid issues of that kind.

**Comment by NillerMedDild** [comment]
That'd be nice!

**Comment by klikli-dev** [comment]
@NillerMedDild the next build should fix this - Demon's Dream is now declared beneficial instead of neutral. The associated hunger will still be removed by the magical herbs. .

**Comment by NillerMedDild** [comment]
Perfect, thanks!
