### ISSUE TITLE
Unbound Afrit Summoning Crashes servers.

### ISSUE THREAD

**Issue by alphaNumeric01** [klikli-dev/occultism#74]
**Describe the bug**
Multiplayer Server crashes when attempting to summon an unbound Afrit.

**To Reproduce**
Set up an unbound ritual.
Place items (netherrack, flint and steel, gunpowder, quartz,) on the pedestals.
Start the ritual. 
Sacrifice a Cow
Wait until all 4 ingredients vanish.
The server will crash just as the center book is about to disappear.

**Expected behavior**
I expect that an Afrit would show up. Instead, upon the center book vanishing, the server will crash with a StackOverflow exception.

**System (please complete the following information):**
- Occultism Version: 0.2.17
- OS: Windows 10
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: 

![image](https://user-images.githubusercontent.com/19354309/103435052-6547b600-4bbe-11eb-9567-b24b820b35e0.png)

**Comment by klikli-dev** [comment]
Hi @alphaNumeric01, thank you for your report! I tried to reproduce this on my end (both in SP and MP), but I can successfully summon and kill the Afrit without issue. Can you please provide the log from the /logs/ folder in your server from when this happens? 
Also, please try to reproduce this on a clean install with only Occultism, Patchouli (and for comfort, JEI) to avoid interactions with one of your other mods, and let me know if it still happens.

**Comment by alphaNumeric01** [comment]
Thanks for the reply! I will try it on a single player world later. In the meanwhile, here is the paste in with the crash log. 

https://pastebin.com/pjiScpx1

**Comment by alphaNumeric01** [comment]
Hello,

Just tried it in singleplayer and crashed as per described previously. The mod list is the bare minimum plus JEI and the full error log is in the pastebin below.

https://pastebin.com/eQ3i8bUq

**Comment by klikli-dev** [comment]
Thanks a lot! That crash log should allow me to fix it even if I cannot reproduce it!
