### ISSUE TITLE
[1.18] Can't delete words in JEI search bar properly when using the dimensional storage actuator

### ISSUE THREAD

**Issue by jinkhya** [klikli-dev/occultism#743]
**Describe the bug**
If you already have words written in JEI search bar and then you open your dimensional storage actuator, you can't delete the words in JEI. No matter if JEI Sync button is on or not.

**To Reproduce**
1. Place Dimensional Storage Actuator
2. type something in JEI Search bar
3. right click the actuator to open it. 
4. click in JEI search bar to remove the words you previously typed in step 2

**Expected behavior**
To be able to erase the words in JEI field :)

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.36.1
- OS: [e.g. Windows] Linux
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: Occultism and its dependencies + JEI 9.7.0.209

**Additional context**

**Comment by jinkhya** [comment]
Hello again, thank you for bringing a fix so quickly however it looks like it's not fully working. I have to click somewhere outside of occultism search bar before clicking in JEI search bar to erase words. 

Here's a more thorough explanation :) 
https://streamable.com/tqq450

**Comment by klikli-dev** [comment]
I'm open to ideas here, but it this might something I cannot control - I can only access the text of the JEI search bar (via API), but not the actual search bar control element, so I cannot set it into "focus". 

That you have to click outside of the search bar first is a bit odd though, that might be something I can change. 
Continued in #747
