### ISSUE TITLE
[1.18]Shift Crafting multiple dark oak barrels from Sophisticated storage in dimensional Actuator gives the wrong barrel

### ISSUE THREAD

**Issue by jinkhya** [klikli-dev/occultism#749]
**Describe the bug**
Shift Crafting multiple dark oak barrels from Sophisticated storage in dimensional Actuator gives the wrong barrel. it gives a barrel that looks like acacia but is missing any nbt tag that would normally define the kind of wood it is.

**To Reproduce**
1. Setup a simple dimensional storage
2. add dark oak planks and slabs and redstone torches
3. Setup the recipe for a sophisticated dark oak barrel
4. shift click the result to craft multiple barrels at once
5. you'll get an acacia looking barrel (which has no recipe)

**Expected behavior**
To be able to craft multiple of those barrels at once and get the right kind :)

**System (please complete the following information):**
- Occultism Version: 1.36.3
- OS: [e.g. Windows] Linux
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: Occultism + dependencies + JEI + Sophisticatedstorage 0.3.4.49 + dependencies

**Comment by klikli-dev** [comment]
Does this reproduce with vanilla recipes or other modded recipes that rely on tags (such as "any plank", "any plank slab")?

**Comment by jinkhya** [comment]
I've only had this issue with the sophisticated storage barrels so far. I would need to find a recipe that does the same thing, aka have a generic name but with different nbt depending on material used to craft. 

This is what the recipe looks like : 
https://github.com/P3pp3rF1y/SophisticatedStorage/blob/1.18.x/src/generated/resources/data/sophisticatedstorage/recipes/dark_oak_barrel.json

**Comment by klikli-dev** [comment]
Thanks, that is a good hint! 
I assumed it was an issue with tags, but this uses direct item references. Looks like something is going wrong with nbt

**Comment by klikli-dev** [comment]
I think I found the culprit - shift-crafting loses NBT when it sums up the result items (it only takes item type + count, not nbt).
Please ping me if the next patch does not fix it :)

**Comment by jinkhya** [comment]
Sadly I tried the jar you released on github, 1.36.4, and the issue still occurs :'(

**Comment by klikli-dev** [comment]
Thanks for testing .. turns out a constructor taking an NBT tag does not necessarily mean that NBT tag is used as the main NBT Tag  .. fix should hopefully come out soon

**Comment by jinkhya** [comment]
It works now thank you :D
