### ISSUE TITLE
[1.18] Way to look for enchanted books in dimensional storage

### ISSUE THREAD

**Issue by jinkhya** [klikli-dev/occultism#751]
**Is your feature request related to a problem? Please describe.**
Hello I don't know if this is possible in 1.18 but after finding https://github.com/klikli-dev/occultism/issues/323 it looks like this is no longer a thing : 
![image](https://user-images.githubusercontent.com/10158963/179022433-4c79286e-35fd-4b87-8dae-96be6733a12b.png)
I do have a smite book : 
![image](https://user-images.githubusercontent.com/10158963/179022511-9cc66fdc-de97-4691-88d8-992af1f3f575.png)

**Describe the solution you'd like**
Some way to look for specific enchants :)

**Comment by klikli-dev** [comment]
Seems when updating I used the wrong way to access tooltip content, should be fixable though :)
