### ISSUE TITLE
[1.18] Dragon familiars forget they're sitting if you go to another dimension

### ISSUE THREAD

**Issue by jinkhya** [klikli-dev/occultism#753]
**Describe the bug**
Hello again ! "oh no it's Jin again, what does she want now !!" :P
Well not a major issue but it turns out if you make dragons sit and go to another dimension (tried nether and end) and then come back, they're back to flying/following you around

**To Reproduce**
1. Summon a Dragon familiar
2. Make it sit
3. Go to the nether
4. Go back to the overworld

**Expected behavior**
For them to be good boys and keep sitting :) or do I need to play fetch more so they obey more ! ^^ Or do I need to find a dragon trainer? 

**System (please complete the following information):**
- Occultism Version: 1.36.6
- OS: [e.g. Windows] Linux
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: 

**Additional context**
Great job on those little dragons, the purring and playing fetch is adorable :)

**Comment by klikli-dev** [comment]
Closing this for now - dragons are based on vanilla tamed mobs and inherit the sitting logic from them.
If the bug still persists please ping me here to reopen it, or create a new issue
