### ISSUE TITLE
[1.18] Server crash NPE

### ISSUE THREAD

**Issue by bigenergy** [klikli-dev/occultism#755]
**System (please complete the following information):**
- Occultism Version: 1.36.6
- OS: ubuntu
- Minecraft Version: 1.182
- Modpack Link and Version, or list of mods: 

**Additional context**
[crash report.](https://gist.github.com/bigenergy/ffa27fea4236de9cd045094ad540d422)

**Comment by klikli-dev** [comment]
Does this reproduce with only occultism + dependencies? 
Based on the log a lot of mixins are involved that may interfere, but if we can repro it on a clean install it should not be too hard to fix

EDIT: Actually, I'm going to publish a fix for the NPE, please open a new ticket if there are any follow-up issues once it got past that NPE
