### ISSUE TITLE
Lumberjack Foliat wont cut down tree (1.19)

### ISSUE THREAD

**Issue by Magnabolt27** [klikli-dev/occultism#766]
I am playing on a server and the lumberjack foliat will walk over to a tree and just stand there doing nothing. He will deposit in chest but wont cut down the trees. idk if im just doing something wrong or what but need help.

**Comment by klikli-dev** [comment]
Closing this for now .. lumberjack is very quirky and currently there is no time to completely rework it's AI to the new minecraft villager AI system to make it more stable
