### ISSUE TITLE
Djinni Machine Operator Erases Storage Actuator's Inventory

### ISSUE THREAD

**Issue by alphaNumeric01** [klikli-dev/occultism#77]
**Describe the bug**
When shift-right clicking a storage actuator or a stable wormhole with a Djinni Machine Operator's Book of Calling in Machine Settings mode, the Djinni will erase all the items in the storage inventory except for a single item, which will rapidly flicker in and out of its inventory. All other items in the storage will disappear. 

**To Reproduce**
1. Set up a storage actuator with 5 t2 stabilizers. Make sure at lest 3 types of items are in the storage. (I used nether quartz, cobblestone, and coal blocks). Or set up a stabilized wormhole connected to the above actuator
2. Create a bound djinni operator and have the operator in the world. 
3. Right click open air with the book
4. Set the mode to 'Machine Settings'
5. Hit the x button on the bottom to close the menu.
6. Shift right click the actuator (or a wormhole linked to the actuator) with the book.
7. The djinni will go over to the wormhole or actuator and delete all the items, leaving only a single itemstack in the storage that it will attempt to infinitely extract and insert/
**Expected behavior**

The Djinni should either not go to the actuator/wormhole and delete all the items. 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 0.2.18
- OS: Windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: 

![image](https://user-images.githubusercontent.com/19354309/103466405-cb852380-4cf9-11eb-90cd-3da724b16ad5.png)

**Additional context**
Logs from the server are attached to this. Furthermore, it should include a list of mods as well.

https://pastebin.com/XSMBrpg9 (the latest.log)
https://pastebin.com/SmHqf3Mn (the error log if you want to look at it.)

**Comment by klikli-dev** [comment]
This was an interesting one - 1.16 changed something how entity/animal default inventories are handled, which silently caused MC to ignore the inventory I had set up for the spirits. For most things that default inventory worked as usual, but with the machine operator it caused the loop of ultimate deletion due to some confusion about the amount of slots available.

Next release will fix this
