### ISSUE TITLE
Game Crashes when Afrit essence is searched

### ISSUE THREAD

**Issue by FrostyTacos** [klikli-dev/occultism#775]
**Describe the bug**
When searching for Afrit essence in the Entry Index, if you click on the entry, the game crashes

**To Reproduce**
1. open Dictionary of spirits
2. click Entry index
3. type Afrit Essence
4. click available entry
5. game crashes

**Expected behavior**
I expect to be taken to the page on Afrit essence

**System (please complete the following information):**
- Occultism Version: 1.19.1-1.41.0
- OS: Windows
- Minecraft Version: 1.19.1

**Additional context**

**Comment by klikli-dev** [comment]
@Condor42 thanks for the report! Please provide a crashlog. Additionally, this may (most likely) be a patchouli issue, but with the crashlog I will hopefully be able to tell

**Comment by klikli-dev** [comment]
@Condor42 after much research by discord member Ciege, this is an issue between JEI and Patchouli and does not involve occultism.
Please create a report on their githubs and provide as much detail as possible.

You can link to this issue/comment, I will provide the research results for reference:

>  Its between JEI and Patchouli, specifically the R key bind in JEI that searches a recipe for an item you are hovering over, and the index search in Patchouli.
For some reason it is still attempting a search for a recipe, but your not hovering over one in JEI so it shoots a search for an unknown item (null?) and gets null ingredients. Boom, crash.
Tested by moving the JEI R key bind to num pad 3, did the search that usually crashed, no problem. Hit numpad 3, crash.

>  Its between JEI and Patchouli, specifically the R key bind in JEI that searches a recipe for an item you are hovering over, and the index search in Patchouli.
For some reason it is still attempting a search for a recipe, but your not hovering over one in JEI so it shoots a search for an unknown item (null?) and gets null ingredients. Boom, crash.
Tested by moving the JEI R key bind to num pad 3, did the search that usually crashed, no problem. Hit numpad 3, crash.

> RE-OPEN MC AGAIN... goto binds, change JEI recipe look up on hover's keybind from R to NumPad 3. Open test world. 
Occultism search: crusher, found 3 results, 2 misspelled (sorry). asdfg- no result, no crash
if i press numpad 3 with the index search open, instant crash
