### ISSUE TITLE
[1.18.2] en-us lang file overwriting minecraft oak sapling name

### ISSUE THREAD

**Issue by enigmaquip** [klikli-dev/occultism#780]
**Describe the bug**
Regular minecraft oak sapling takes on the name of the Unstable Otherworld Sapling

**To Reproduce**
1. Place block '...'
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6134440/185796356-4de9a1b6-0273-4415-977e-4caf965374e7.png)
![image](https://user-images.githubusercontent.com/6134440/185796734-1d8d89ba-b55e-4112-92cd-978ebef497ce.png)

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.40.0
- OS: Windows
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
Good find, thank you!
