### ISSUE TITLE
1.18.2: Cannot put Iesnium Dust in Blast Furnace

### ISSUE THREAD

**Issue by Raidobw2** [klikli-dev/occultism#783]
**Describe the bug**
Iesnium Dust blasting recipe seems to be in the wrong category, the furnace instead of the blast furnace
![image](https://user-images.githubusercontent.com/17010632/187020384-17a64e4c-f9de-4ce7-bf60-dfc731e70305.png)

**To Reproduce**
1. Look up uses for Iesnium Dust
2. Looks like you cannot blast it
3. Try blasting it anyways, nothing happens:
![image](https://user-images.githubusercontent.com/17010632/187020417-f4eb6ee9-e4e1-403a-aae9-f3891d4663f4.png)

**Expected behavior**
To be able to put it in a blast furnace, since other dusts from Occultism can be put in the blast furnace

**System (please complete the following information):**
- Occultism Version: occultism-1.18.2-1.40.2.jar
- OS: [e.g. Windows] Win10
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: In-dev FTB Plexiglass Mountain update 1.2.0 (currently unreleased)

**Additional context**
Looks like typo or error in datagen if that's what you use, should be an easy fix regardless
![image](https://user-images.githubusercontent.com/17010632/187020493-52e83b3e-7380-4d9c-9f89-05dd19f75457.png)

**Comment by klikli-dev** [comment]
Good catch, thanks!
