### ISSUE TITLE
Occultism adding back forge:storage_blocks/copper to Cut Copper

### ISSUE THREAD

**Issue by enigmaquip** [klikli-dev/occultism#784]
**Describe the bug**
the storage block tag was mistakenly added to cut copper sometime back in forge and was removed later
<https://github.com/MinecraftForge/MinecraftForge/commit/8f0d3da1e4228c326e9eaa676165bb150a348870>

src/main/resources/data/forge/tags/blocks/storage_blocks/copper.json
src/main/resources/data/forge/tags/items/storage_blocks/copper.json

could/should be removed from both 1.18 and 1.19

**Comment by klikli-dev** [comment]
Closes in 9b468b5d361ab69fdc8e37867464f38104a5a380
