### ISSUE TITLE
JEI + integration not working in crafting grid with staged recipes

### ISSUE THREAD

**Issue by Saereth** [klikli-dev/occultism#787]
**Describe the bug**
Occultism crafting grid integration with JEI + does not work with staged recipes (via gamestages/recipe stages) even if you have the recipe stage unlocked. Manually placing the items in the crafting grid does work. I was unsure if this is an occultism, recipe staging or JEI issue however so if I should report it else where let me know

**Screenshots**
![image](https://user-images.githubusercontent.com/9200909/190231353-38b189c1-2aa3-45aa-945d-9038e16203a3.png)

**System (please complete the following information):**
- Occultism Version: occultism-1.18.2-1.40.3

- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: FTB Inferno 0.3.3 (Unreleased)

https://github.com/jaredlll08/RecipeStages/issues/63

**Comment by klikli-dev** [comment]
Closed in https://github.com/jaredlll08/RecipeStages/issues/63
