### ISSUE TITLE
[1.16.4] maxMiningTime doesn't appear to have any effect. 

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#79]
**Describe the bug**
Set maxMiningTime = 1 for both the foliot and the djinni for testing purposes. Both appear to be running at the same speed as when it was set to 400. Expected this to be a drastic increase in speed. 

**To Reproduce**

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_foliot_unspecialized]
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 1
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 1000

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_djinni_ores]
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 1
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 2
		#The amount of mining operations the spirit can perform before breaking.
		durability = 5000

**Expected behavior**
Expecting ore to be flying out 

**System (please complete the following information):**
- Occultism Version: occultism-0.2.19
- OS: Windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/enigmatica6

**Comment by theboo** [comment]
as an addition, rollsPerOperation and durability seem to have no affect either. Pic below of some exaggerated settings, if im reading the config right it should be an operation per tick and 10 ores per operation, along with 100,000 durability. Everything is behaving as default still.

https://gyazo.com/e99d3176ffdb4d9b43c2ad165e3fed46

**Comment by klikli-dev** [comment]
Thank you for the report! @MuteTiefling is this with a spawned miner spirit item or created via ritual? (I will test either way ofc)
I suspect the spawned ones do not contain the NBT settings, leading to the fallback to default values.

**Comment by MuteTiefling** [comment]
Crazy fast turnaround on that, thanks! Much appreciated :D

**Comment by theboo** [comment]
Seems this fix is not working on servers... Tested on an enigmatica 6 v0.3.6(latest release) server and the miner seems to be set to default configs, but in single player it is working as it should

**Comment by klikli-dev** [comment]
I'll look into that, to be fair I did not test server separately

**Comment by klikli-dev** [comment]
In the latest version I cannot reproduce that issue. When on a server the nbt tags (accessed with `/occultism nbt` while holding the item -> will only show up after it has been placed in the dimensional mineshaft and the operation has started) reflect the settings, and the nbt is repsected, the djinni is producing insane amounts of ore.

![image](https://user-images.githubusercontent.com/60774993/104764159-483ae780-5767-11eb-9e52-444833d471bb.png)
![image](https://user-images.githubusercontent.com/60774993/104764202-57219a00-5767-11eb-880c-5c505766801e.png)

**Comment by klikli-dev** [comment]
@theboo confirmed it's working - visuals may be outdated on clients until the miner is placed in a mineshaft for the first time as we force-update nbt then.
