### ISSUE TITLE
Modonomicon causing crashes on attempting to enter a new world in 1.18.2

### ISSUE THREAD

**Issue by Hahahavana** [klikli-dev/occultism#796]
What the title says. Game hard crashes after it attempts to load into the world with the responsible server thread error being listed as 
"java.lang.NullPointerException: Cannot invoke "com.klikli_dev.modonomicon.book.BookEntry.getBook()" because "entry" is null"

**Expected behavior**
The game working.

**System (please complete the following information):**
- Occultism Version: 1.18.2-1.41.2
- Modonomicon Version: 1.18.2-1.0.17
- OS: Windows
- Minecraft Version: 1.18.2, latest forge version

**Crashlog**
https://pastebin.com/x3nh7hca

**Comment by renadi** [comment]
I also get this error.  Same environment but I also tried 1.0.16 modnomicon.

**Comment by RealDeadTom** [comment]
I'm also getting the same error. I tried downgrading and nothing. Not sure if its a mod conflict or what.

**Comment by Hahahavana** [comment]
> I'm also getting the same error. I tried downgrading and nothing. Not sure if its a mod conflict or what.

Best solution for now is to downgrade to 1.40.3 and remove modonomicon I think, particularly since it doesn't seem like the modonomicon update adds any new features outside the new documentation system. If it gets fixed in the future updgrading probably won't break old worlds.

**Comment by Hahahavana** [comment]
looks like it got fixed in the most recent update.
