### ISSUE TITLE
[Suggestion] Rename "White Candle" to "Tallow Candle"

### ISSUE THREAD

**Issue by hjake123** [klikli-dev/occultism#799]
Vanilla Minecraft already adds a White Candle made of wax, so it seems strange to duplicate the name for what is clearly a very different block. Also, as far as I can tell (?) there's no way to change the color of this mod's White Candle, so mentioning that it is White seems redundant.

**Comment by klikli-dev** [comment]
Occultism's candle predates Vanilla, and it was / sort of is planned to offer more versions in the future (similar to chalks multiple candle tiers could be used in the future).
I do see your point, but for now I'll keep the white as part of the name, I will revisit this though, if there definitely won't be more candles :)
