### ISSUE TITLE
JEI crafting integration with dimensional storage actuator

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#8]
would be cool to be able to use the JEI "+" sign to auto fill a table with ingredients from the storage like you can in a vanilla table/ refined storage/ AE2

**Comment by klikli-dev** [comment]
That's actually already a feature, but seems not to work after the release obfuscation - probably related to the crashes around the actuator, so hopefully should work once those are fixed :)

**Comment by klikli-dev** [comment]
Fixed in v1.15.2-0.2.5
