### ISSUE TITLE
Unstable otherworld sapling's sprite has a black background

### ISSUE THREAD

**Issue by ghost** [klikli-dev/occultism#800]
**Describe the bug**
when placed, unstable otherworld sapling's sprite has a black background

**To Reproduce**
1. Place block unstable otherworld sapling
2. See error

**Expected behavior**
expected the background to be transparent

**Screenshots**
https://user-images.githubusercontent.com/115538052/195045641-4fbf2ada-1f1f-4a55-b410-8efb1979c587.png

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.45.4.jar
- OS: windows 11
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Curios API (Forge), GeckoLib, Modonomicon, Occultism, Patchouli

**Additional context**

**Comment by klikli-dev** [comment]
Oh good catch, this is due to vanilla vs forge render differences. Going to have to stop referring to vanilla models and create a copy in this case - thanks!
