### ISSUE TITLE
storage controller crash

### ISSUE THREAD

**Issue by skybix** [klikli-dev/occultism#816]
**Describe the bug**
placing a dimensional storage controller in the world or loading into a world with one placed crashes your client

**To Reproduce**
1.placing a dimensional storage controller in the world or loading into a world with one placed crashes your client

**Expected behavior**
not to crash.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.18.2-1.48.0.jar
- OS: windows
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: 
geckolib-forge-1.18-3.0.53.jar
modonomicon-1.18.2-1.6.0.jar
Patchouli-1.18.2-71.1.jar

**Additional context**
crash report
https://pastebin.com/nRtLgFgT

**Comment by klikli-dev** [comment]
This seems to be a geckolib issue, it crashes when geckolib tries to render occultism.
I will have to investigate this, but you could try downgrading (or upgrading, both might work) your geckolib version to see if that fixes it

**Comment by skybix** [comment]
down grading to geckolib-forge-1.18-3.0.48.jar seems to work

**Comment by klikli-dev** [comment]
With latest geckolib (3.0.53) it actually works in the dev environment .. weird. I am closing this for now, if the issue persists in the future with 3.0.54 or later please let me know or report to the geckolib guys

**Comment by AzureDoom** [comment]
> With latest geckolib (3.0.53) it actually works in the dev environment .. weird. I am closing this for now, if the issue persists in the future with 3.0.54 or later please let me know or report to the geckolib guys

Was an issue with build jars, due to a change with getUniqueID being updated in properly. I just pushed a fix for this. 

Just a heads up to move to getInstanceId as with 1.19.3, getUniqueID will be gone. A lot of things are getting moved to cleaner/better systems. Anything being removed with 1.19.3 is marked with Deprecated with a Java doc on the method of what to use instead!

**Comment by klikli-dev** [comment]
Awesome, thanks a lot @AzureDoom, will look into cleaning up my api usage
