### ISSUE TITLE
[1.19.2] Client crash when we look Storage Controller

### ISSUE THREAD

**Issue by LovenKyuu** [klikli-dev/occultism#818]
**Describe the bug**
The network occultism still work with my storage accessor but, when we go close to 10 blocks, or when we look the storage controller, there is a crash client 

**To Reproduce**
1. Place block Storage controller
2. See it
3. Or go closer
4. Crash report has been edited

**Expected behavior**
We want to use the block storage controller or access to base, we could'nt because the storage controller is in the middle of the base

**System (please complete the following information):**
- Occultism Version: 1.19.2-1.48.0
- OS: Windows 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: TNP6 Limitless
 https://www.curseforge.com/minecraft/modpacks/tnp-limitless-6

**Additional context**
[crash-2022-11-05_10.16.08-client.txt](https://github.com/klikli-dev/occultism/files/9943464/crash-2022-11-05_10.16.08-client.txt)

**Comment by klikli-dev** [comment]
Please update to latest geckolib or downgrade one version, it's a geckolib issue @LovenKyuu
