### ISSUE TITLE
[Suggestion] Execute Command Ritual Type

### ISSUE THREAD

**Issue by vertexcubed** [klikli-dev/occultism#831]
**Is your feature request related to a problem? Please describe.**
For my modpack, I was planning on adding custom rituals that do things other than just craft or summon entities, but the only way currently to really do that is to summon an invisible armor stand and run commands at it.

**Describe the solution you'd like**
It'd be much simpler if there were a ritual type that executes a command at the sacrificial bowl, which could then run a command/function/whatever. In addition, being able to specify the text in jei with a translatable string would make this a much more elegant solution as opposed to summoning an invisible armor stand.

**Additional context**
Mock syntax concept:
```json
{
    "type": "occultism:ritual",
    "ritual_type": "occultism:execute_command",
    "activation_item": {...},
    "pentacle_id": "namespace:my_pentacle",
    "duration": 100,
    "command": "execute at @e[type=minecraft:player,distance=0..10] run tp ~ ~5 ~",
    "display_result": "ritual.namespace.teleport_command",
    "ritual_dummy": {...},
    "ingredients": [...],
    "result": {
        "item": "occultism:jei_dummy/none"
    }
}
```

**Comment by klikli-dev** [comment]
Note: the intended way to display what a ritual does is via the creation of ritual dummy item (e.g. via kubejs).
this had the advantage that a) the jei display does not get too cluttered and does not need to worry about scaling long texts and b) the item can be used in creative mode to test the ritual without ingredients
