### ISSUE TITLE
The dimensional storage actuator crashed my base’s chunk.

### ISSUE THREAD

**Issue by GetRext2519** [klikli-dev/occultism#832]
**Describe the bug**
I placed down the dimensional storage actuator with a storage stabilizer tier 1 having already being placed on the ground at the distance of three blocks to the left of where I put the actuator. That being two empty spaces and the stabilizer is on the third block. I also had a ritual being preformed in the background to Craft a second storage stabilizer of the same tier.

**To Reproduce**
1. Place block Storage stabilizer tier 1
2. Begin ritual somewhere within the same chunk like underground
3. Place dimensional storage actuator

**Expected behavior**
A crash to saving world then to desktop and anyone who comes close experiences the same and a black skeleton of the item is seen when trying to log in.

**Screenshots**
I wish I could give them to you but the server owner removed your mod before I could capture any.

**System (please complete the following information):**
- Occultism Version: 1.19.2
- 
- OS: Windows 11/Windows 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: All the mods 8

**Additional context**
I don’t expect it to be repeatable but if it is or is a known bug all the better.

**Comment by klikli-dev** [comment]
Please provide the crash log and any log files, then we can investigate. It sounds a bit like an issue we had with outdated geckolib but hard to tell without the log

**Comment by ebrinley2001** [comment]
I had the same issue as well in the All the Mods 8 pack. I just placed down the dimensional storage actuator and no stabilizers. Here is my crash log 

[crash-2022-11-12_15.57.44-client.txt](https://github.com/klikli-dev/occultism/files/9995908/crash-2022-11-12_15.57.44-client.txt)

**Comment by klikli-dev** [comment]
Ah yes that's a geckolib issue, it's outdated. 

Can you try to update to latest geckolib? @ebrinley2001 

Edit: On latest ATM 8 (unmodified, comes with forge 43.1.7 and Geckolib 1.19-3.1.36) this crash does not reproduce

**Comment by klikli-dev** [comment]
Closing this for now - if the issue remains after updating to latest ATM or latest geckolib (3.1.36) please ping me to reopen
