### ISSUE TITLE
[1.18.2] Storage System addon To allow redstone to play a role in item management

### ISSUE THREAD

**Issue by wolflord212312** [klikli-dev/occultism#841]
**Is your feature request related to a problem? Please describe.**
Issue when trying to automate create machines with occultism machine Operators,I See there is no way to make the machine operator put out a redstone signal when there is so many of a specific type of item in the storage actuator .

**Describe the solution you'd like**
Some way for the storage acuator to put out a redstone signal at a certain point,allowing for create Machines to run till number is met.

**Additional context**

**Comment by klikli-dev** [comment]
@wolflord212312 can you take a look at https://github.com/klikli-dev/occultism/issues/221 ?
External counting systems should work with the config option provided all the way at the bottom.

**Comment by wolflord212312** [comment]
Let me look here

**Comment by wolflord212312** [comment]
Ok ya i will try that out.

**Comment by klikli-dev** [comment]
Closing this for now, if there are issues with the external counting devices despite the option set, please comment here so we can reevaluate
