### ISSUE TITLE
Crash after using green links

### ISSUE THREAD

**Issue by Bluthirn** [klikli-dev/occultism#853]
**Crash after using green links**
When you use the green links in the "Dictionary of Spirits", the game crahes.

**To Reproduce**
1. Open the "Dictionary of Spirits"
2. Search for the page called "Summon Otherstone Trader" under the bookmark "Rituals" in the section "Summoning Rtuals".
3. Click on one of the two green coloured links called "Otherstone" or "Spiritfire".
4. The game crashes.

**Expected behavior**
That the links bring me to the desired page without crashing the game.

**Screenshots**
The section I was on.
![2022-11-22_22 51 24](https://user-images.githubusercontent.com/117023752/203428732-92504213-ce6b-4c26-86c4-a67edb713c06.png)
The link I tried to use.
![2022-11-22_22 51 39](https://user-images.githubusercontent.com/117023752/203428876-db7fa0f7-88b6-4cf5-a6ba-491adda40623.png)

**System:**
- Occultism Version: occultism-1.19.2-1.55.2.jar
- OS: Windows 11 Pro
- Minecraft Version: 1.19.2
- List of mods: curios-forge-1.19.2-5.1.1.0, geckolib-forge-1.19-3.1.38, modonomicon-1.19.2-1.13.0, occultism-1.19.2-1.55.2, Patchouli-1.19.2-77.

**Additional context**
The pages I located that have this green links are: "Summon Otherstone Trader", "Afrit Essence", "Infused Pickaxe", "Foliot Miner", "Marid Miner", "Familiar Ring", "Craft Otherworld Googles", "Stable Wormhole". "Storage Accessor", "Item use", "Possessed Endemite", "Possessed Endeman","Possessed Skeleton", "Possessed Ghast", "Headless Ratmann Familiar", "Chimera Familiar", "Shub Niggurath Familiar", "Lifting the Vail", "Spiritfire", "Divination Rod", "Candles", "First Ritual", "More Chalk", "Grey Particles", "Infused Pickaxe", "Iesnium Ore" and "Iesnium Pickaxe". I didn't test all of them. But the ones I did resulted in a crash.

**Comment by klikli-dev** [comment]
Ahh these are links to jei, not within the book. It looks like the jei install detection is not working as it should, will look into it

**Comment by klikli-dev** [comment]
Oh my god I am an idiot.
I am in one place directly referencing JEI .. obviously that won't work.
Will fix ASAP

**Comment by klikli-dev** [comment]
Closed in https://github.com/klikli-dev/modonomicon/issues/94 and https://github.com/klikli-dev/modonomicon/issues/93

Update to Modonomicon 1.13.1 once it is on Curseforge (will take a few minutes to hours) to fix the crash :)
