### ISSUE TITLE
The Underground Grove thing is spawning in the End and Nether

### ISSUE THREAD

**Issue by clootas** [klikli-dev/occultism#86]
**Describe the bug**
Underground grove structure spawning in The End & Nether

**Screenshots**
https://i.imgur.com/Os8oeo9.png

**System (please complete the following information):**
- Occultism Version: 0.2.20
- OS: Windows
- Minecraft Version: 1.16.4
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/mos-mods/files

**Comment by pm065** [comment]
It's still happening in the End at least, though it does look kind of cool:
![2021-05-02_16 06 29](https://user-images.githubusercontent.com/81559564/116817866-6c78d380-ab60-11eb-91bf-e2b4aa74c460.png)
