### ISSUE TITLE
Crash issue opening the dimensional storage.

### ISSUE THREAD

**Issue by 0zeron0** [klikli-dev/occultism#861]
**Describe the bug**
When i try to open the dimensional storage its stays thinking and cannot do anything else.
**To Reproduce**
1. press TAB to open storage menu
2. storage´s menu opens empty and stays thinking
3. try to wait for 10 minutes and finally have to close minecraft from window.

**Expected behavior**
Usually i press TAB and it opens the storage menu with any problem at all.

**Screenshots**
dont have screenshot.

**System (please complete the following information):**
- Occultism Version: 1.18.2
- OS: Windows 10 home
- Minecraft Version: 1.18.2
- Modpack Link and Version, or list of mods: https://www.modpackindex.com/modpack/35650/all-the-mods-7-atm7

**Additional context**
After crashing, i was decorating the 2 portals of the Blue Skyes mod with materials from those dimensions and i travel to the nether to put a All the mods teleporter there (to The Other dimension). When i return to Overworld and try to open the dimensional storage it crashes.
I dunno if it helps but this appears on my PolyMC register: 
Process crashed with exit code -805306369

**Comment by klikli-dev** [comment]
Please provide the crash log and latest.log from when this happens

**Comment by 0zeron0** [comment]
Here i send the console log, and the lastest.log from right now, every time i try to open storage it does the same result.
PolyMC version: 1.4.3

https://pastebin.com/rgn52SuG

[latest.log](https://github.com/klikli-dev/occultism/files/10202912/latest.log)

**Comment by 0zeron0** [comment]
I took a picture from the moment it gets hunged...opening my storage. I hope it helps... I cannot move or do anything but the game dont ''crashes'' per se. It gets not response and white veil if i press ESC for example.
![Minecraft Issue](https://user-images.githubusercontent.com/120327034/206922259-cdb6b555-14de-4eda-a8dc-ab551c7659d7.jpg)

**Comment by klikli-dev** [comment]
There seem to be no error messages or even any messages from occultism at all. 

You mention pressing TAB to open the storage menu. Does the hanging also happen if you just right-click the actuator block?

Also, can you please try to install just occultism + dependencies + latest forge on your launcher and see if you can open the storage then?

**Comment by 0zeron0** [comment]
Hi, it gets hunged right-cliking the actuator block too. Im thinking... ¿is there some issue with heavy quantitys of bloks just with five lvl2 upgrades? I mean like +5k cobble and +3k netherrak...for example. Im thinking maybe the problem comes from my pc that takes too much effort to process all the items inside at one especific quantity of them... Im going to try to open it with the help of friends from the server. Lets see if this afternoon i can fix somehow the problem, at leas why it frozes my game.

**Comment by 0zeron0** [comment]
Fixed, i dunno why but i put a pipe to a chest to extract some blocks and now i can open the storage menu again without problems...
