### ISSUE TITLE
livro esta com bug

### ISSUE THREAD

**Issue by D4rkPrime** [klikli-dev/occultism#862]
**Describe the bug**
![2022-12-11_20 20 21](https://user-images.githubusercontent.com/120343880/206934933-9732cc7a-c494-4a22-9945-abcbbdb6ce31.png)

**To Reproduce**
1. Place block '...'
2. Right click to open menu.
3. Click Button '....'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Theurgy Version: 
- OS: [e.g. Windows]
- Minecraft Version:
- Modpack Link and Version, or list of mods: 

**Additional context**

**Comment by klikli-dev** [comment]
Please provide the requested information, especially the mod and minecraft version as well as the modpack.

**Comment by D4rkPrime** [comment]
- occultism-1.19.2-1.55.4.jar
-java version 1.8.0.351 (64 bit)
- Minecraft Version 1.19.2
- Modpack ATM 8 1.0.6 b 
- modpack link https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Comment by klikli-dev** [comment]
hmm that does not reproduce with just occultism + dependencies.

I cannot get ATM 8 to start at all currently, but it seems like it might be a) outdated occultism version or b) a modification by the modpack to the book

**Comment by klikli-dev** [comment]
I am closing this for now. Please ping me if this 
a) reproduces for you on just occultism + dependencies if installed via curseforge launcher **or**
b) persists after the modpack updates
