### ISSUE TITLE
Machine Spirit tweaks

### ISSUE THREAD

**Issue by Ciege666** [klikli-dev/occultism#863]
**Is your feature request related to a problem? Please describe.**
Many people have issues with figuring out the machine spirit, this is a subtle suggestion to point them in the correct direction if possible.

**Describe the solution you'd like**
Change the order of the display selections to: Set Managed Machine (Sided), Set Extract (Optional), Set Storage Actuator.

**Additional context**
Main reason is when ever you are binding the machine spirit the machine block has to be bound first before the Storage Actuator will bind, this gives a subtle suggestion to bind the Machine Block first, less than subtle suggestion that the output is optional, and then the step that locks everything in.

Final bit, I would probably put the parts in parentheses on the next line, lead the eyes to the selections.

**Comment by klikli-dev** [comment]
I'm going to have to close this - I looked into it and while I agree that it would be helpful, the way it is currently set up does not allow for it at all - and a refactor of the entire book of calling system is currently not in the cards :s
