### ISSUE TITLE
Iesnium highlight not visible

### ISSUE THREAD

**Issue by enimog** [klikli-dev/occultism#864]
Hello, it's not possible to mine iesnium because it is not visible when using the divination rod. Reverting ccb6a03b (for 1.45.1) and recompiling from the latest commit fix the issue. Possible conflict with https://github.com/klikli-dev/occultism/issues/788 ?

**Comment by klikli-dev** [comment]
Thanks for the report, and thanks for testing the revert!
I will have to investigate - I changed it to the new rendering after a recommendation in the forge discord, because the old rendering did not work for at least one person.

**Comment by klikli-dev** [comment]
The issue does not reproduce for me in dev or in a clean install via CF. 
I am going to try and find more people with the issue to collect data & inquire in the forge discord for a solution that works for both the group that now has issues & the people that had issues with the old rendering

**Comment by enimog** [comment]
Maybe it has something to do with video drivers? Me and a friend both have the issue, but we are both using an AMD card. The person from #788 is using an NVIDIA card. In any case, I'm sorry to hear that you can't reproduce it on your side... I'd be very happy to test builds from you if you need it.

**Comment by klikli-dev** [comment]
@enimog after talking to the good people in the forge discord two suggestions have come up:
1. For you: Please verify you are on the latest AMD driver version for your card. There have been render issues with recent driver versions that are resolved on latest
2. For me: Moving the overlay rendering into a different render target - rendering it after particles, which I will implement presently

**Comment by klikli-dev** [comment]
v1.19.2-1.57.4 contains the changes - please ping me here if the issue persists after
