### ISSUE TITLE
Add alternative divination rod render method from 1.45

### ISSUE THREAD

**Issue by Raulwicke** [klikli-dev/occultism#866]
**Is your feature request related to a problem? Please describe.**
As of Occultism version 1.46, there was a rendering change to how the Divination Rod shows the outline for finding blocks. The change made it to where certain users can no longer see the outlines being rendered and as such cannot use the divination rod with any sort of effectiveness.

**Describe the solution you'd like**
Please add a configuration option to allow users who cannot see the new location rendering to access the rendering from the 1.45.0 branch of Occultism, as that rendering appears to still work.

**Comment by klikli-dev** [comment]
New setting: `occultism-client.toml#visual.useAlternativeDivinationRodRenderer`

@Raulwicke thanks for helping with this - if possible please try the new version 1.59.2 once it is out (on 1.19.2. or 1.19.3, should be largely identical) and let me know if that fixes the issue

**Comment by Raulwicke** [comment]
Issue is resolved! Whatever backend stuff has been worked on also makes the lines look CLEAN. Thanks for all the fix klikli.
