### ISSUE TITLE
Object

### ISSUE THREAD

**Issue by patayoda** [klikli-dev/occultism#867]
**Describe the bug**
My error is when i start Occultism and minecfrast says that the server doesnt recognize an obect i think that is the 
remote storer

**Comment by klikli-dev** [comment]
Please provide additional info
- latest.log
- your exact minecraft version, forge version and mod version
- the exact error message you are referring to
- your mod list or the exact modpack version

**Comment by klikli-dev** [comment]
Closed as stale, please ping me to reopen if you have the required info
