### ISSUE TITLE
RItual issue checking algho capability expansion(checking if there is no chalk)

### ISSUE THREAD

**Issue by najlitarvan** [klikli-dev/occultism#875]
would be nice if the ritual completion suggestion system was extended with the ability to detect if there is no chalk present and then told the player that it is missing a pentacle adn pointed to the right spot in the book, if links are possible would be nice if there was a clickable link in the chat that would open the book section.

Would be nice since it is common issue for new players

**Comment by klikli-dev** [comment]
The clickable link won't be possible because handling clicks on chat would require a mixin, which we don't use in occultism to avoid compatibility issues (as this type of modding is not recommended by forge).

However, hinting at the book is a good idea!
