### ISSUE TITLE
Suggestion: extra internal storage for some demons

### ISSUE THREAD

**Issue by ghost** [klikli-dev/occultism#876]
While playing I noticed that when a tree was chopped down by a lumberjack demon and the tree for some reason didn't drop a sapling, it would result in the demon not replacing sapling. My suggestion is to add an internal inventory specifically for those tasks so that even if no sapling is dropped the process doesn't eventually stop.

**Comment by klikli-dev** [comment]
That is generally a good suggestion, however this is currently not planned.
All the spirits share the same setup with one inventory, and having special additional inventories or slots would require more work than I can currently put into it. 

That said, if someone wants to contribute this change I would be open to discuss details, we'd just have to make sure it is compatible with all existing spirit jobs (in that case please ping me to reopen the ticket)
