### ISSUE TITLE
Mekanism machines don't show up in Storage Actuator UI

### ISSUE THREAD

**Issue by bigfoott** [klikli-dev/occultism#879]
**Describe the bug**
Mekanism machines don't show up in the storage actuator's machines UI tab (see video below)

**To Reproduce**
See video: https://www.youtube.com/watch?v=r11uasiGbbk

**Expected behavior**
The machine operator should try to input on the selected barrel.

**Screenshots**
https://www.youtube.com/watch?v=U5Ba5iwpHlk

**System (please complete the following information):**
- Occultism Version: 1.19.2-1.60.0
- OS: Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: ATM8 - https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Additional context**
Side note, I'm also running into [a different issue](https://github.com/klikli-dev/occultism/issues/878) at the same time, not sure if they're related.

**Comment by klikli-dev** [comment]
As mentioned in https://github.com/mekanism/Mekanism/issues/7706 this is actually working as intended.
If the mekanism machine is not configured correctly (if it does not "expose" it's inventory on the side that occultism is configured to look for it) then the machine operator will reject linking it, or if that configuration mismatch happens after linking, it will unlink it.

By ensuring the target sides are exposed before linking (or simply by linking again) this can be avoided

**Comment by bigfoott** [comment]
Hi! Thanks for the response. I've updated the Mekanism issue, as the bug persists even if the clicked face is properly set by mekanism. Fortunately making sure there aren't any unset sides seems to allow everything to work, so this issue can stay closed 👍 :)
