### ISSUE TITLE
[BUG]: Transporter item white/blacklist behaviour not documented in Dictionary, or too obscure

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#880]
### Bug Description

As a result players are confused because the transporter is by default in whitelist mode and thus does not move anything

### Logs and Crash Reports

n/a

### Bug Reproduction

n/a

### Expected Behavior

The entry about the transporter should inform about the whitelisting

### Minecraft Version

1.19.2

### Mod Version

1.65.1

### Modpack

ATM

**Comment by Radon8472** [comment]
Thank you that saved my day...
I am wondering since a week why my transporters are not working, and it was yust the filter rule
