### ISSUE TITLE
Ability to specify crusher tier in crusher recipes

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#881]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to specify that a recipe can only be done by a given tier or higher in the recipe. For example, a Foliot can crush Copper but not Iron. While an Afrit can crush both. 

**Describe the solution you'd like**
An optional value in the crusher recipes. Something like `tier: 1` where 1 would be foliot, 2 would be djinni, 3 would be afrit, and 4 would be marid. 

Any given tiere would be capable of crushing it's own tier and anything below it.

**Comment by klikli-dev** [comment]
The crushers currently (ironically) don't know their own tier haha

It is doable though, will look into that when I find some time

**Comment by klikli-dev** [comment]
@MuteTiefling the new setting is "min_tier" and works basically as you described. There's a sample recipe in a new markdown file in the crushing recipes folder 

Because we're fancy the min tier is also shown in JEI

**Comment by MuteTiefling** [comment]
Beautiful! Thanks!
