### ISSUE TITLE
[BUG]: client crash

### ISSUE THREAD

**Issue by silversmith-05** [klikli-dev/occultism#883]
### Bug Description

crash when looking pentacles in Dictionary of spirits.
But when I create a new world to test, this bug no longer occurs. It seems only appears in this world.
Is there anything I can do to fix it?

### Logs and Crash Reports

[crash-2023-01-27_18.20.44-client.txt](https://github.com/klikli-dev/occultism/files/10517959/crash-2023-01-27_18.20.44-client.txt)

### Bug Reproduction

1.open Dictionary of spirits
2.click pentacles
3.click any entry
4.game crashes

### Expected Behavior

I expected to open pentacles pages without crashes.

### Minecraft Version

1.16 or older

### Mod Version

1.29.1

### Modpack

Other

**Comment by klikli-dev** [comment]
This is an error that seems to be caused either by patchouli, or by some mod that interferes with patchoulis rendering, it does not come from occultism itself. The "offending" mod causes patchouli to try and render a pentacle glyph type that does not exist. 

You can try to report this error with patchouli, but I think they, like occultism, do not support 1.16 any more
