### ISSUE TITLE
Pentacle in-world visualization does not work

### ISSUE THREAD

**Issue by Nafnya-maks** [klikli-dev/occultism#884]
hello, the visualization of runes and the ritual of summoning endermite do not work for me mod version 1.18.2 1.66.2
![Снимок экрана_20230128_150814](https://user-images.githubusercontent.com/91015057/215268030-26693395-9b16-4b8c-9c67-bdd747ac3f0d.png)
![Снимок экрана_20230128_150857](https://user-images.githubusercontent.com/91015057/215268055-a78b12e1-c6c1-45a6-bf8a-907540dc6714.png)

**Comment by klikli-dev** [comment]
Are you using any performance or render optimization mods? 
This issue does not reproduce with just occultism + dependencies, so it is most likely caused by an another mod interfering with rendering

**Comment by Nafnya-maks** [comment]
To be honest, there are any mods for optimization, I don’t know, I play on the assembly FTB inferno
Yes, the problem is only with the occult blat magic and others work fine
It seems to me that this is due to the fact that there is a new book in occultism and it bugs

**Comment by klikli-dev** [comment]
Please try if this happens with just occultism + dependencies (e.g. by installing occultism via curseforge launcher, it will install all other required files). If not someone will have to find out which mod causes it by removing them from inferno until it works.

The new book works both with just occultism and in other packs (ATM, Enigmatica), so we'll have to find what is different about inferno - then either that other mod can be updated, or possibly occultism/modonomicon can include a workaround for thatm od

**Comment by Nafnya-maks** [comment]
I watched one youtuber on the passage of this assembly and he had a book of an old man and everything worked for him. I think it's because of the modonomicon mod. And yes, everything is fine with the ritual, I just used the wrong book in the center. Well, most likely I need to write to the inferno support so that they can help me
![Снимок экрана_20230129_134509](https://user-images.githubusercontent.com/91015057/215323848-7623ddd7-0412-494f-bccc-06ddaa6a16ae.png)

**Comment by klikli-dev** [comment]
@Nafnya-maks The issue is caused by the Mod Rubidium (see https://github.com/klikli-dev/occultism/issues/873) 

Removing it from your /mods folder or from your pack via the launcher will fix it and you can use it normally.

Modonomicon cannot fix this, and it is unlikely Rubidium will fix it either, because they have hundreds of open issues
