### ISSUE TITLE
[BUG]: Minecraft crashes when summoning a spirit

### ISSUE THREAD

**Issue by Cookie-Monsterrr** [klikli-dev/occultism#885]
### Bug Description

The game crashes when summoning spirits. I've tried lumberjack und crusher foliots and clear weather Gjinnis. The rituals themselves work fine, I get the (best friends forever) achievement and the text message that the spirit was summoned, then the game crashes. happens both in survival and creative

### Logs and Crash Reports

[crash-2023-01-29_10.19.08-server.txt](https://github.com/klikli-dev/occultism/files/10529561/crash-2023-01-29_10.19.08-server.txt)

### Bug Reproduction

1. Do a summoning ritual (I've tried foliot Lumberjack, Foliot crusher and Djinni clear weather) 
2. game crashes

### Expected Behavior

I expect the spirit to be summoned without my game crashing

### Minecraft Version

1.19.3

### Mod Version

1.67.0

### Modpack

Other

**Comment by klikli-dev** [comment]
The error you posted seems to be one with SmartBrainLib (which occultism uses for some spirits AI). I will test if there were breaking changes that I need to update to.

Meanwhile, can you also post the crash log when you summon the weather spirits? Because those do not use smartbrainlib

**Comment by klikli-dev** [comment]
@Cookie-Monsterrr hmm when updating to latest smartbrainlib in my workspace it still works.
Can you try this with just occultism (+ dependencies) but no other mods?

Looks like it might be caused by another mod in your modpack

**Comment by Cookie-Monsterrr** [comment]
@klikli-dev i am happy to report that it works now! thanks for the help!
