### ISSUE TITLE
[BUG]: Machine Operator "Forgets" Its Job After Reloading World?

### ISSUE THREAD

**Issue by TrashCasterMage** [klikli-dev/occultism#886]
### Bug Description

Assigning a djinni machine operator a job works initially, but it must be "retaught" using the Book of Calling each time after reloading the single player world.

### Logs and Crash Reports

Not facing a crash, but the logs do have this message being printed to the console repeatedly:

`[Render thread/ERROR] [minecraft/Brain]: No key memories in MapLike[{}]`

which seems to me like it could be related

### Bug Reproduction

1. Use a Book of Calling to ensure the Djinni Machine Operator has a machine it is bound to.
2. Save and Quit to title screen.
3. Re-open the minecraft world.
4. The Operators are now unable to interact with their respective machine blocks.

### Expected Behavior

Expected Operators to retain their machine blocks and be able to use them between closing and re-opening the world.

### Minecraft Version

1.18.2

### Mod Version

1.66.2

### Modpack

Other

**Comment by klikli-dev** [comment]
Thanks for the report!
The log statement is not the issue, it's expected, and as the operator is not using the Brain system it's unrelated.

That said, it should save the instructions on World close, I'll look into it.

Meanwhile, can you please try if this occurs when using just occultism + required dependencies (eg by installing occultism via curseforge launcher)?

**Comment by klikli-dev** [comment]
Disregard the above - it reproduces in dev.
Fixed in 1.67.2

Turns out when adding the option to have a separate extract location it was accidentally overwriting the wrong save data thus making it impossible to load on world load

**Comment by TrashCasterMage** [comment]
> Disregard the above - it reproduces in dev. Fixed in 1.67.2
> 
> Turns out when adding the option to have a separate extract location it was accidentally overwriting the wrong save data thus making it impossible to load on world load

Really did not expect this to get fixed overnight while I was asleep. That was fast! Thank you!

**Comment by belathus** [comment]
I'm experiencing this problem in version 1.21-neoforge-1.180.0. The machine operator forgets its settings on world restart -- specifically, it forgets both where its Storage Actuator is and where it is supposed to extract items from.
