### ISSUE TITLE
[BUG]: Machine Operator "Custom Name" Field Not Saving Unless Facings Change

### ISSUE THREAD

**Issue by TrashCasterMage** [klikli-dev/occultism#887]
### Bug Description

When setting up a Machine Operator, the "Custom Name" field for the machine doesn't save unless you modify one of the facings afterwards.

But modifying one the the facings _also_ seems to revert it to the previously saved name, as long as that previously-saved name is longer than the current name, which means that it's also not possible to shorten a machine's custom name.

### Logs and Crash Reports

None

### Bug Reproduction

1. Have a storage system and summon a machine operator.
2. Use the Book of Calling, in "Set Managed Machine" mode, on the machine you want to manage.
3. Change the Custom Name, but _not_ any of the facings.
4. Close out of the GUI, either with Escape or with the X button.
5. Finish setting up the Machine Operator.
6. Look at the Managed Machine in the storage system. Its Custom Name is not present.

To get the Custom Name to update, add in a step between 3 and 4:
3.5. Change one of the facings.

### Expected Behavior

The Custom Name should save, at least, when the "X" button is pressed, without having to change a facing.

### Minecraft Version

1.18.2

### Mod Version

1.67.2

### Modpack

Other

**Comment by klikli-dev** [comment]
hmm yes it should definitely save.
Weirdly enough I did that just yesterday while testing and it did work. I will investigate
