### ISSUE TITLE
[BUG]: multiblock view

### ISSUE THREAD

**Issue by Thorkellwashere** [klikli-dev/occultism#894]
### Bug Description

The multiblock view for every ritual is not appearing at all. it will show the black bar but nothing else

### Logs and Crash Reports

![image](https://user-images.githubusercontent.com/125210871/218328086-34745fe6-8269-4795-939e-ae1e8dbf61f6.png)
![image](https://user-images.githubusercontent.com/125210871/218328103-3cd9398d-d792-43fc-97f6-35daaf9d5022.png)
![image](https://user-images.githubusercontent.com/125210871/218328119-38582c48-4a15-4884-ad8e-89c0106b466d.png)

### Bug Reproduction

just try to place the multiblock view down

### Expected Behavior

i expect for there to be a bunch of ghost blocks appearing before me in the places where im supposed to put the blocks.

### Minecraft Version

1.18.2

### Mod Version

1.69.1

### Modpack

Other

**Comment by klikli-dev** [comment]
This is caused by the mod Rubidium (see https://github.com/klikli-dev/occultism/issues/873 ).
If you remove it it works again.
