### ISSUE TITLE
[BUG]: Internal exception.... fails to connect to server when upgrading to latest Occultism version both client and server

### ISSUE THREAD

**Issue by jpeaglesandkatz** [klikli-dev/occultism#896]
### Bug Description

Server loads fine.. when connecting from a client (with the same occultism version... I get greeted by:

![Screenshot_9](https://user-images.githubusercontent.com/10682544/219402643-ab60db89-0fb9-40f5-b7fa-99f25c7a1d69.png)

`[16:01:53] [Render thread/INFO] [xa.co.MinimapLogs/]: New minimap session initialized! [16:01:54] [Netty Client IO #1/WARN] [Oculus/]: Detected invalid path 'pentacles3book.occultism.dictionary_of_spirits.pentacles.name`

### Logs and Crash Reports

https://paste.gemwire.uk/view/e9a58835

### Bug Reproduction

Start server.. Try to collect with client..

Running ATM 8 pack with some added mods.

I went back to below version and the error still occurs.

### Expected Behavior

Can connect with client

### Minecraft Version

1.19.2

### Mod Version

occultism-1.19.2-1.67.0

### Modpack

Other

**Comment by klikli-dev** [comment]
@jpeaglesandkatz This seems to be an issue with oculus, or a compatibility issue between occultism and oculus, the error log comes from oculus message. 

What mods did you add to atm 8?

**Comment by jpeaglesandkatz** [comment]
Thank you for the response... Yeah I added a few mods but nothing spectacular... But you can delete this report.. I decided to go back to a full new latest version of ATM 8 server and client and go from there.
