### ISSUE TITLE
[BUG]: Dimentional Mineshaft produces nothing

### ISSUE THREAD

**Issue by enderfree** [klikli-dev/occultism#897]
### Bug Description

I play with a friend on a 1.18.2 server. He made a Dimentional Mineshaft, but it didn't work, so I went in solo to test it out and it does not work for me either.

### Logs and Crash Reports

-

### Screenshots and/or Videos

-

### Bug Reproduction

1. Place a Hopper.
2. Place a Dimentional Mineshaft on top of the Hopper. 
3. Place any bound mining spirit in the left slot of the Dimentional Mineshaft (in my case I tried with both the creative one and one I got from a ritual.)

Result: The bar progresses but on completion, no block was obtained. As of now, it has been 20min and I still obtained no blocks.

### Expected Behavior

When the bar is completed, the spirit should have mined something.

### Minecraft Version

1.18.2

### Mod Version

1.69.0

### Modpack

Other

**Comment by klikli-dev** [comment]
Please update the mod, this issue was fixed in 1.69.1
