### ISSUE TITLE
[BUG]: Startup crash - Mod occultism requires modonomicon 1.19.2-1.25.0 or above

### ISSUE THREAD

**Issue by sciguyryan** [klikli-dev/occultism#898]
### Bug Description

Hi there.

I've run into a startup crash that, frankly, makes no sense. It reads as follows:

Mod occultism requires modonomicon 1.19.2-1.25.0 or above
	Mod Version: 1.19.2-1.71.1

This doesn't make sense because I have modonomicon-1.19.2-1.26.0 installed, along side occultism-1.19.2-1.71.1.

I've redownloaded both files two or three times to just to confirm that there is nothing weird going on with the file versioning, but that hasn't fixed it either. I have no idea what's going on here, or how to fix it.

### Logs and Crash Reports

https://gist.github.com/sciguyryan/f0b296ee8cc53f35adcddd25d3da3dbe

### Bug Reproduction

As above.

### Expected Behavior

There should be no crash here.

### Minecraft Version

1.19.2

### Mod Version

1.71.1

### Modpack

Other

**Comment by klikli-dev** [comment]
This seems to be an issue in your setup or launcher - mod version checks are done entirely by forge ( that is, both the part where a mod informs the system about a version, and the part that verifies if all required versions are there ).

I just set up a minimal install of occultism on curesforge launcher and it loads without issue:

![image](https://user-images.githubusercontent.com/60774993/223368356-9b231059-1512-410e-b858-56385510e67f.png)

I have heard anecdotally that the curseforge API (which most launchers use) sometimes has caching issues - ie it will serve modonomicon 1.24.0 file, but pretend its 1.26.0 (which will also result in the missleading filename).

My recommendation would be to either use the CF launcher, or download the files in the correct versions (as shown in the screenshot above) from the curseforge site manually and place them in your mod folder
