### ISSUE TITLE
Ore dusts should be smeltable in blast furnace

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#9]
currently you cannot smelt stuff like gold or iron dust in the vanilla blast furnace. I think this would be a good addition.

**Comment by klikli-dev** [comment]
I was not aware such a thing existed in vanilla! As a modpack maker, do you happen to know the json recipe type for these?

**Comment by klikli-dev** [comment]
Added this in 0.2.5. The recipe type is minecraft:blasting :)
