### ISSUE TITLE
CANT HARVEST TREE

### ISSUE THREAD

**Issue by Nilran1** [klikli-dev/occultism#901]
he can move, but cant harvest tree
before he cant move, i deleted performance mods
https://youtu.be/DYF3aaQTmO0 video bag
![image](https://user-images.githubusercontent.com/83768483/224509351-f36aa968-42f9-48c3-b837-b59e5fe81da2.png)
also

Running on Java 17.0.3 (Eclipse Adoptium)
Magma version 1.18.2-cf0b461c
Bukkit version v1_18_R2
Forge version 1.18.2-40.1.80-cf0b461

**Comment by Nilran1** [comment]
https://user-images.githubusercontent.com/83768483/224509457-b7ea34ad-0184-4133-8e46-f3696aed7487.mp4

**Comment by Nilran1** [comment]
i fixed it, just installed another core server

**Comment by klikli-dev** [comment]
@Nilran1 what do you mean with you installed another core server?
This is an Issue we've seen a few times now, so concrete steps on how to fix it would be fantastic! 

Especially interesting would be which performance mod re-enabled the moving :)

**Comment by Nilran1** [comment]
> @Nilran1 what do you mean with you installed another core server? This is an Issue we've seen a few times now, so concrete steps on how to fix it would be fantastic!
> 
> Especially interesting would be which performance mod re-enabled the moving :)

forge server jar, not a magma

**Comment by Nilran1** [comment]
btw, i have still log error "minecraft/brain"
![image](https://user-images.githubusercontent.com/83768483/224539552-a18a4dba-19b8-4509-b521-ad31b516264e.png)

**Comment by klikli-dev** [comment]
> btw, i have still log error "minecraft/brain" ![image](https://user-images.githubusercontent.com/83768483/224539552-a18a4dba-19b8-4509-b521-ad31b516264e.png)

That is annoying but it's not an issue. It's due to now using minecraft's brain system, but not having any persistent "memories". villagers use this part of the brain system to store their home, but occultism has an existing system to store work location etc, so the brain is empty on startup.

I cannot suppress minecraft logging this error, but it is not acftually an error and save to ignore
