### ISSUE TITLE
[BUG]: Time magic description references weather magic

### ISSUE THREAD

**Issue by justisr** [klikli-dev/occultism#902]
### Bug Description

<img width="414" alt="image" src="https://user-images.githubusercontent.com/6403190/224567065-7e40199e-9b2a-428f-8ec9-5bced21d74b5.png">
States "Time spirits will only modify the weather once" which seems to be have been copy pasted from the Weather Spirits description.

### Logs and Crash Reports

N/A

### Bug Reproduction

Open Dictionary of Spirits, read "Time Magic" entry.

### Expected Behavior

Should state that the time spirits will only modify the time once before disappearing.

### Minecraft Version

1.19.2

### Mod Version

1.55.4

### Modpack

Create: Above & Beyond

**Comment by klikli-dev** [comment]
Good find, Thanks!
