### ISSUE TITLE
[BUG]: Missing/Bugged texture for leaves in 1.19.2, latest forge and mod version.

### ISSUE THREAD

**Issue by Daltaxy** [klikli-dev/occultism#903]
### Bug Description

a video will explain it better.
Typical purple and black missing texture block instead of the leaves. 
Looking at the top allowed me to see which mod was in cause
This could be due to Passable Foliage 🌳
https://www.curseforge.com/minecraft/mc-mods/passable-foliage
could also not be linked to your mod, in which case I apologise...

### Logs and Crash Reports

the log is too heavy, I had to use Mega for it: 
https://mega.nz/file/MdBkUSjR#MTINOQxep1Pru_N-dazmGGYg6UgwYzhqeins1rnM0iE

### Screenshots and/or Videos

https://user-images.githubusercontent.com/111076631/226139188-4351840b-14ec-4296-ae19-26f4b2a6920d.mp4

### Bug Reproduction

Find the specific leaves, it seems like. (found underground, mixed with the Lost Cities mod's railing)

### Expected Behavior

Normally textured leaves 

### Minecraft Version

1.19.2

### Mod Version

1.73.0

### Modpack

Other

**Comment by klikli-dev** [comment]
@Daltaxy It seems another mod is indeed interfering. If I try this with just occultism + dependencies the leaves are normal.

If you can find out which mod causes it (by removing mods until it works) you can create a ticket there and link them to this issues s I can work with them to fix it

**Comment by Daltaxy** [comment]
hey, I thought I replied here, I'm really sorry...
I tried removing mods and testing for a bit, but each time it would take 30 minutes to get in game and all...
I don't know if you closed it because of inactivity (understandable) or because you found the conflict, but it wasn't PassableFoliage and some other wood mods that I tried with, as the issue wasn't there with these mods together. 
At all cases, I was doing my own assembly of mods and I don't think the public will use the conflicting mod with Occultism, as this was never reported before.
Thank you for your attention, have a nice day

**Comment by klikli-dev** [comment]
@Daltaxy it was indeed closed as inactive (I try to keep the issues that are not feature requests decluttered to know what to focus on). That said, if you do find additional info feel free to ping me here so I can reopen the investigation!

**Comment by Xarmok** [comment]
In case anyone has this issue in the future like I did in 1.20.1, The mod that was causing the issue for me was the Better Foliage Renewed mod, once I removed that mod it fixed this issue.
