### ISSUE TITLE
[BUG]: Cannot place bound books into golden sacrificial bowls

### ISSUE THREAD

**Issue by raflowers** [klikli-dev/occultism#904]
### Bug Description

On version 1.71.1 in the DW20 pack I can no longer place bound books into the golden sacrificial bowls. I can still place them and other items into the normal sacrificial bowls. I've been doing pentacles all morning with no problem and it suddenly stopped working within the same game session. I've tried leaving world and restarting the game entirely, breaking and replacing the golden sacrificial bowl, and trying different bowls.

### Logs and Crash Reports

I'm not experiencing a full game crash, just missing functionality.

### Bug Reproduction

1. Place Golden Sacrificial Bowl on ground
2. Right click bowl with Book of Binding: Djinni (Bound) (I also tried with Foliot)

### Expected Behavior

The Book of Binding should go onto the Golden Sacrificial Bowl and allow the ritual to begin

### Minecraft Version

1.19.2

### Mod Version

1.71.1

### Modpack

Other

**Comment by klikli-dev** [comment]
@raflowers please join discord and open a support post there and post the info requested by the post guidelines. The golden bowl interactions have not been changed in at least months if not years, so either a) it's a case of certain ritual recipes not working (which we can verify with the screenshots) in which case the golden bowl will not recognize the books as valid ingredients or b) other mods interfering with the block interaction
