### ISSUE TITLE
Demon's Dream Fruit right click familiar healing not working with Beholder.

### ISSUE THREAD

**Issue by Ciege666** [klikli-dev/occultism#905]
**Describe the bug**
Title.

**To Reproduce**
1. Right click with fruit in hand, offhand, empty offhand, empty main hand
2. Familiar nap time?

**Expected behavior**
Should restore the familiars health.

**System (please complete the following information):**
- Modonomicon Version: 1.30.0
- OS: Win 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: 
Architectury 
Cloth
Configured
Curious
GeckoLib
Modonomicon
Occultism
Placebo
REI Compat
REI
Smart Brain Lib
Theurgy
Toast Control

**Additional context**
https://discord.com/channels/688406873392676924/1088663810728017940

**Comment by klikli-dev** [comment]
thanks for the report! Seems there was a bug affecting familiar interactions with items
