### ISSUE TITLE
Suggestion: Display Familiar type and what it provides in the Familiar Ring tooltip

### ISSUE THREAD

**Issue by DmitryScaletta** [klikli-dev/occultism#907]
Display Familiar type in the Familiar Ring tooltip, not only it's name.
It's difficult to determine what familiar inside the ring if you have many of them.
![image](https://user-images.githubusercontent.com/5096735/228571119-4c19395f-c773-4611-9952-707d3ca6a0d1.png)

**Comment by klikli-dev** [comment]
Suggestion by Ciege: Give each type a distinct color

**Comment by klikli-dev** [comment]
Suggestion by Ciege: Enchantment sparkle when familiar is active
