### ISSUE TITLE
Suggestion: Make Miners to work correctly with the Unusing enchant from EvilCraft

### ISSUE THREAD

**Issue by DmitryScaletta** [klikli-dev/occultism#909]
**Describe the solution you'd like**
When a Miner enchanted with Unusing (`evilcraft:unusing`) falls below 6 remaining durability, it just stops working inside a Dimensional Mineshaft.

It allows to repair it in the future using blood from EvilCraft. 
But during the repair it can became cursed and break faster (Curse of Breaking), so it's not a cheaty mechanic.

**Comment by klikli-dev** [comment]
@DmitryScaletta thanks for bringing this up, it slipped under my radar so far!
Am I understanding it right that below 6 durability IF it has that enchantment the miner should just be ignored (not dropped out, not consumed, just pause the mineshaft)?

**Comment by DmitryScaletta** [comment]
> Am I understanding it right that below 6 durability IF it has that enchantment the miner should just be ignored (not dropped out, not consumed, just pause the mineshaft)?

Yes, that's right.
