### ISSUE TITLE
Suggestion: Add crusher spirit recipes for modded metals

### ISSUE THREAD

**Issue by CraftSpider** [klikli-dev/occultism#911]
**Is your feature request related to a problem? Please describe.**

I'd like to use this mod more compatibly with others on a modpack, specifically, I'd like if the crusher spirit supported modded ores

**Describe the solution you'd like**

When using with Create, I'd love to be able to give a crusher spirit zinc ore/raw zinc and get zinc dust. Other modded metals such as tin or nickel would also be nice.

**Comment by klikli-dev** [comment]
Usually in minecraft modding that is something modpacks add via datapack or crafttweaker/kubjs, as they know the specific mods and items involved. Usually in modpacks there are more than one possible e.g. zinc dust, but minecraft recipes generally output one specific item - so there would have to be multiple recipes per zinc dust to cover all possible mods. 

However, this is something I have been planning to support in occultism and is already prepared by integrating with AlmostUnified.

I currently do not have time to add the recipes, but the functionality to output a tag instead of an item is there.

**What the community can do to help**
The biggest help would be a list of metals in common mods that are known to have dusts and need to be supported

**Comment by DmitryScaletta** [comment]
> The biggest help would be a list of metals in common mods that are known to have dusts and need to be supported

Maybe this would be useful.
Dusts from AllTheMods 8

<details>
 <summary>Ores</summary>

| Input | Recipe Id | 
| - | - | 
| #forge:ores/emerald | kubejs:occultism/crushing/emerald_dust |
| #forge:ores/uranium | kubejs:occultism/crushing/uranium_dust |
| #forge:ores/azure_silver | kubejs:occultism/crushing/azure_silver_dust |
| #forge:ores/zinc | kubejs:occultism/crushing/zinc_dust |
| #forge:ores/osmium | kubejs:occultism/crushing/osmium_dust |
| #forge:ores/nickel | kubejs:occultism/crushing/nickel_dust |
| #forge:ores/lead | kubejs:occultism/crushing/lead_dust |
| #forge:ores/sulfur | kubejs:occultism/crushing/sulfur_dust |
| #forge:ores/allthemodium | kubejs:occultism/crushing/allthemodium_dust |
| #forge:ores/unobtainium | kubejs:occultism/crushing/unobtainium_dust |
| #forge:ores/coal | kubejs:occultism/crushing/coal_dust |
| #forge:ores/iridium | kubejs:occultism/crushing/iridium_dust |
| #forge:ores/ruby | kubejs:occultism/crushing/ruby_dust |
| #forge:ores/diamond | kubejs:occultism/crushing/diamond_dust |
| #forge:ores/apatite | kubejs:occultism/crushing/apatite_dust |
| #forge:ores/tin | kubejs:occultism/crushing/tin_dust |
| #forge:ores/cinnabar | kubejs:occultism/crushing/cinnabar_dust |
| #forge:ores/peridot | kubejs:occultism/crushing/peridot_dust |
| #forge:ores/crimson_iron | kubejs:occultism/crushing/crimson_iron_dust |
| #forge:ores/platinum | kubejs:occultism/crushing/platinum_dust |
| #forge:ores/fluorite | kubejs:occultism/crushing/fluorite_dust |
| #forge:ores/sapphire | kubejs:occultism/crushing/sapphire_dust |
| #forge:ores/lapis | kubejs:occultism/crushing/lapis_dust |
| #forge:ores/vibranium | kubejs:occultism/crushing/vibranium_dust |

</details>

<details>
 <summary>Raw materials</summary>


| Input | Recipe Id | 
| - | - | 
| #forge:raw_materials/azure_silver | kubejs:occultism/crushing/azure_silver_dust_from_raw_material |
| #forge:raw_materials/uranium | kubejs:occultism/crushing/uranium_dust_from_raw_material |
| #forge:raw_materials/zinc | kubejs:occultism/crushing/zinc_dust_from_raw_material |
| #forge:raw_materials/osmium | kubejs:occultism/crushing/osmium_dust_from_raw_material |
| #forge:raw_materials/nickel | kubejs:occultism/crushing/nickel_dust_from_raw_material |
| #forge:raw_materials/lead | kubejs:occultism/crushing/lead_dust_from_raw_material |
| #forge:raw_materials/allthemodium | kubejs:occultism/crushing/allthemodium_dust_from_raw_material |
| #forge:raw_materials/unobtainium | kubejs:occultism/crushing/unobtainium_dust_from_raw_material |
| #forge:raw_materials/iridium | kubejs:occultism/crushing/iridium_dust_from_raw_material |
| #forge:raw_materials/tin | kubejs:occultism/crushing/tin_dust_from_raw_material |
| #forge:raw_materials/crimson_iron | kubejs:occultism/crushing/crimson_iron_dust_from_raw_material |
| #forge:raw_materials/platinum | kubejs:occultism/crushing/platinum_dust_from_raw_material |
| #forge:raw_materials/vibranium | kubejs:occultism/crushing/vibranium_dust_from_raw_material |

</details>

<details>
 <summary>Ingots</summary>

| Input | Recipe Id | 
| - | - | 
| #forge:ingots/signalum | kubejs:occultism/crushing/signalum_dust_from_ingot |
| #forge:ingots/uranium | kubejs:occultism/crushing/uranium_dust_from_ingot |
| #forge:ingots/graphite | kubejs:occultism/crushing/graphite_dust_from_ingot |
| #forge:ingots/azure_silver | kubejs:occultism/crushing/azure_silver_dust_from_ingot |
| #forge:ingots/zinc | kubejs:occultism/crushing/zinc_dust_from_ingot |
| #forge:ingots/lumium | kubejs:occultism/crushing/lumium_dust_from_ingot |
| #forge:ingots/osmium | kubejs:occultism/crushing/osmium_dust_from_ingot |
| #forge:ingots/nickel | kubejs:occultism/crushing/nickel_dust_from_ingot |
| #forge:ingots/lead | kubejs:occultism/crushing/lead_dust_from_ingot |
| #forge:ingots/allthemodium | kubejs:occultism/crushing/allthemodium_dust_from_ingot |
| #forge:ingots/bronze | kubejs:occultism/crushing/bronze_dust_from_ingot |
| #forge:ingots/cobalt | kubejs:occultism/crushing/cobalt_dust_from_ingot |
| #forge:ingots/unobtainium | kubejs:occultism/crushing/unobtainium_dust_from_ingot |
| #forge:ingots/tungsten | kubejs:occultism/crushing/tungsten_dust_from_ingot |
| #forge:ingots/iridium | kubejs:occultism/crushing/iridium_dust_from_ingot |
| #forge:ingots/steel | kubejs:occultism/crushing/steel_dust_from_ingot |
| #forge:ingots/enderium | kubejs:occultism/crushing/enderium_dust_from_ingot |
| #forge:ingots/electrum | kubejs:occultism/crushing/electrum_dust_from_ingot |
| #forge:ingots/constantan | kubejs:occultism/crushing/constantan_dust_from_ingot |
| #forge:ingots/tin | kubejs:occultism/crushing/tin_dust_from_ingot |
| #forge:ingots/netherite | kubejs:occultism/crushing/netherite_dust_from_ingot |
| #forge:ingots/brass | kubejs:occultism/crushing/brass_dust_from_ingot |
| #forge:ingots/crimson_iron | kubejs:occultism/crushing/crimson_iron_dust_from_ingot |
| #forge:ingots/platinum | kubejs:occultism/crushing/platinum_dust_from_ingot |
| #forge:ingots/invar | kubejs:occultism/crushing/invar_dust_from_ingot |
| #forge:ingots/vibranium | kubejs:occultism/crushing/vibranium_dust_from_ingot |

</details>


Source: https://github.com/AllTheMods/ATM-8/blob/main/kubejs/server_scripts/postUnify/dust.js#L26

**Comment by klikli-dev** [comment]
Excellent, thanks a lot!
That should cover 99.99% of all use cases so I'll make that the goal
