### ISSUE TITLE
occultism-1.19.2-1.70.0 [BUG]: Connection Lost Internal Exception client disconnect when accessing storage

### ISSUE THREAD

**Issue by DWX12** [klikli-dev/occultism#912]
### Bug Description

![2023-04-09_07 20 26](https://user-images.githubusercontent.com/37384543/230780238-0fa93ab2-103f-4619-8fb3-59f28871baae.png)

Playing on a server running the "All The Mods 8" modpack with Forge version 43.2.6 and occultism-1.19.2-1.70.0

Just recently happened, but when I access or open my storage in any way (remote or direct), I get disconnected from the server. My client doesn't crash out nor does the server. I can still join the server, but will disconnect if I try to access my storage.

What I was doing was simply accessing the storage remotely (with the storage area being chunk loaded) and inserting items into it. This last time when this happened, I put an evilcraft containment box into the storage (of which I have others) and received the error.

For what it's worth, my storage has five tier 3 stabilizers, which gives over 4k storage and am using alittle under 4k with room to spare.

Server restarts seem to temporarily resolve the issue, or atleast allow me into my storage.

Thank you for creating such a wonderful mod and hope you'll be able to figure out what is causing the issue.

### Logs and Crash Reports

https://gist.github.com/DWX12/fade67a78faa8e9f70638bf7b03b1b6f

### Bug Reproduction

1. Open storage inventory remotely or directly
2. Disconnect from server with error.

### Expected Behavior

I expected the storage actuator to open without issue.

### Minecraft Version

1.19.2

### Mod Version

1.70.0

### Modpack

ATM

**Comment by klikli-dev** [comment]
Thanks for reporting this!
Could you possibly upload the server savegame somewhere so I can try to reproduce this? 
You can also DM me the link via discord if you don't want it public

I am using some special packet handling logic to handle sending a lot of items, and that is hard to debug in a test environment without all those items in there

**Comment by klikli-dev** [comment]
@DWX12 [release/v1.19.2-1.74.0](https://github.com/klikli-dev/occultism/tree/release/v1.19.2-1.74.0) might fix it - I am changing some of the packet splitting settings to match what refined storage is using. Let me know if that fixes it ( release will be out on CF in some time)

**Comment by DWX12** [comment]
Thanks soo much for the quick reply. I am actually playing on Mischief of Mice's patron server so I don't have access to those files, but will pass this along to the community.

**Comment by klikli-dev** [comment]
Closing this for now, please ping me if it persists / did not get fixed & there is additional info / logs / etc available to take another look.
