### ISSUE TITLE
Enable adding familiar rings to loot tables

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#915]
See also https://github.com/klikli-dev/occultism/issues/907

Motoko in Discord:
> I know apotheosis/placebo does this. For instance, we were callilng apotheosis:affix_entry in e6 to add apotheosis drops to some loot tables: https://github.com/EnigmaticaModpacks/Enigmatica6/blob/01bcfb55a9dbe7290850702c22511429cf9e19cc/kubejs/server_scripts/enigmatica/kubejs/base/loot_tables/apotheosis/tome_tower.js#L133 
So I suppose it'd be a matter of adding a custom function to call your random name generator

**Comment by klikli-dev** [comment]
@MuteTiefling @theboo pinging you, I created an  issue out of our discord conversation.

Will research how to do that once I find a bit of time

**Comment by MuteTiefling** [comment]
Nice, thanks!

**Comment by MuteTiefling** [comment]
Some thoughts on potential default adds to loot tables: 

Shipwrecks: Cthulhu
Small Dungeons: Bat/greedy
Villages: Crow/Parrot depending on location
Desert Temple: Fairy
End Cities: Beholder
Bastion: Devil
