### ISSUE TITLE
[BUG]: When using StrorageRemote, use the button in the backpack to open replicable items.

### ISSUE THREAD

**Issue by lengzu** [klikli-dev/occultism#917]
### Bug Description

When using StrorageRemote, use the button in the backpack to open replicable items.

### Logs and Crash Reports

on

### Bug Reproduction

When using StrorageRemote, use the button in the backpack to open replicable items.

1.StrorageRemote is not in the shortcut bar, but in the backpack.
After 2.StrorageRemote saves the composite bar once, take out the items in the bar composite bar, click on the StrorageRemote item in the backpack, and then open the composite bar again to browse the item.
### Expected Behavior

Fix him.

### Minecraft Version

1.19.2

### Mod Version

1.73.0

### Modpack

Other

**Comment by klikli-dev** [comment]
@lengzu apparently git doesn't show you the notifications after I moved the issue - This was fixed in https://github.com/klikli-dev/occultism/commit/09e92dd467f744dc65738ae14c4872a0c52f4d40, so try to update to 1.19.2-1.75.0 and let me know if it still exists :)
