### ISSUE TITLE
[BUG]: Leaves are a missing texture

### ISSUE THREAD

**Issue by TheSicko** [klikli-dev/occultism#922]
### Bug Description

When I place down the Occultism Oak Leaves block or grow the Occultism sapling the leaf texture is the black and pink missing texture. 

### Logs and Crash Reports

Null

### Screenshots and/or Videos

![2023-05-09_23 08 26](https://github.com/klikli-dev/occultism/assets/133077677/6d6c7f6f-f313-474b-b887-b7535ebefcc1)
![2023-05-09_23 07 39](https://github.com/klikli-dev/occultism/assets/133077677/f77b3a84-e40f-42fb-abdc-7eddcbb6a431)

### Bug Reproduction

1. Place a sapling
2. Grow sapling
3. see issue

### Expected Behavior

I created a 1.19.2 modpack with a variety of mods and it might be possible that this has created some conflicts. I haven't gotten around to testing it out yet.

### Minecraft Version

1.19.2

### Mod Version

 occultism-1.19.2-1.78.0.jar

### Modpack

Other

**Comment by klikli-dev** [comment]
@TheSicko can you try to run occultism in a minimal pack with only the occultism dependencies?

We had https://github.com/klikli-dev/occultism/issues/903 where it only occured with other mods, but we never found out which other mod causes it.

Forge Discord recommends a binary search to find which mod might interfere (it is important to, of course, leave occultism in for this to work):

> The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
>
> This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
>
> The procedure is simple:
>   1. Remove half of the existing things, and put them aside.
>   2. Run the program / game.
>   3. Does the issue still exist?
>     If YES: Repeat from step 1 with the current things.
>     IF NO: Swap out the current things with the ones set aside, and repeat from step 1.
>   4. Repeat this process until the problematic thing/s have been found.

**Comment by TheSicko** [comment]
So I found out that the Better Foliage Renewed mod was causing the issue. Works perfectly after being removed. [https://www.curseforge.com/minecraft/mc-mods/better-foliage-renewed](url)

**Comment by klikli-dev** [comment]
Thank you for investigating! If you decide to open an issue with them feel free to point them here to discuss in case they need any Occultism side changes to make it work.

I suspect, however, the easiest solution would be for them to add occultism to their ignore list (if that exists), as the leaves are special to handle the two visual modes (hidden vs third eye)
