### ISSUE TITLE
[Suggestion] Config option to disable silver ore (1.19.2)

### ISSUE THREAD

**Issue by ghost** [klikli-dev/occultism#923]
**Is your feature request related to a problem? Please describe.**
Hi, I'm making/working on my own modpack and I'm already using other mod's silver ore in gen because I already did full ingame support in multiple machines and recipe changes to silver ore/ingot etc. from different mod.

**Describe the solution you'd like**
I would really like to have config option to simply disable silver ore from gen.

**Comment by klikli-dev** [comment]
Just like all modern ore gen and vanilla ore gen, occultism ore gen can be turned off using worldgen datapack JSONs. 
You can find default jsons for occultism worldgen are found here: https://github.com/klikli-dev/occultism/tree/version/1.19.2/src/generated/resources/data/occultism/worldgen 

The JSONs that add these features to the world are here: https://github.com/klikli-dev/occultism/tree/version/1.19.2/src/generated/resources/data/occultism/forge/biome_modifier 

With the https://forge.gemwire.uk/wiki/Biome_Modifiers#None modifier you can disable them
