### ISSUE TITLE
[BUG]: Crash with PVI and Crusher Spirit

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#925]
### Bug Description

Unsure if this is a PVI issue or an occultism issue, but figured you would be able to talk to the pvi dev if it's on their end! Crash report linked in the issue. First crash that I know of with PVI that had an occultism mob as the source.

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/368

### Logs and Crash Reports

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/368

### Bug Reproduction

Unsure how to reliably reproduce

### Expected Behavior

Shouldn't crash

### Minecraft Version

1.19.2

### Mod Version

1.77.4

### Modpack

Enigmatica

**Comment by klikli-dev** [comment]
Closing this here as it seems to be a bug with https://github.com/ldtteam/PerViamInvenire, according to the creators.
They identified the issue and I expect it will be fixed soon :)
