### ISSUE TITLE
Typo in Soul Gem craft

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#926]
https://github.com/klikli-dev/occultism/blob/2d63fea63087ca5fa315eda93f83fbd9ea2de8ce/src/main/java/com/github/klikli_dev/occultism/datagen/lang/ENUSProvider.java#L594

should be `"ritual.occultism.craft_soul_gem.finished": "Successfully bound djinni into soul gem.",`

**Comment by klikli-dev** [comment]
Excellent find haha

closed in 
734cb33efb340b0188634fde32f0b2a43f2c98f7
fd40a3c12c965f94f3e24d91b0fcb16b95a60588
059ba7436d906f99e4aa3628dbbdd16916096004
