### ISSUE TITLE
Dragon eyes render above its head

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#931]
**Describe the bug**
Dragon's eyes (?) render above its head

**To Reproduce**
1. Summon dragon from spawn egg

**Expected behavior**
non floaty eyes :D

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/9543430/2bbda8ac-aae4-4da7-ac8b-b8cfa246cb79)

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.80.1.jar
- OS: Windows 11
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Enigmatica 9

**Additional context**

**Comment by MuteTiefling** [comment]
Also happening out of the seat
![image](https://github.com/klikli-dev/occultism/assets/9543430/23aea9c1-b9f8-4742-83e1-eca5b560003d)

**Comment by klikli-dev** [comment]
uhhhhh

**Comment by klikli-dev** [comment]
fixed! 
The eyes were double broken, not rendered in the right place, and with the wrong texture haha
