### ISSUE TITLE
Infused, and Iesnium pickaxes added to the forge:tools/pickaxes on 1.19.2 plus

### ISSUE THREAD

**Issue by ModernGamingWorld** [klikli-dev/occultism#932]
**Is your feature request related to a problem? Please describe.**
Currently your Pickaxes are not being included in the forge:tools/pickaxes tag means any mods calling that tag can use your pickaxes in their recipes cause your pickaxes are not setup by default to use said tag

**Describe the solution you'd like**
Them added to the forge:tools/pickaxes tag

**Additional context**

**Comment by klikli-dev** [comment]
Thanks!

closed in e985ca6e3221698b37d35702dd1c6faefd9f4bf5
