### ISSUE TITLE
Ritual chalk not working 

### ISSUE THREAD

**Issue by Fruitcak3s** [klikli-dev/occultism#933]
**Describe the bug**
-when placing chalk symbols next to each other the other chalk symbol is destroyed. 

**To Reproduce**
1.Right click floor with chalk
2.right click next to recently placed chalk

**Expected behavior**
-Chalk symbols to be placed next to eachother 
**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.20-1.80.1.jar
- OS: [e.g. Windows] windows
- Minecraft Version: 1.20
- Modpack Link and Version, or list of mods: 
-custom made modpack 
**Additional context**

**Comment by klikli-dev** [comment]
Fixed in https://github.com/klikli-dev/occultism/releases/tag/release%2Fv1.20-1.80.3 - I recommend to update to latest occultism - 1.20.1 versions should work for 1.20 and come with a bunch of fixes
