### ISSUE TITLE
Tallow doesn't drop when killing with a butcher knife

### ISSUE THREAD

**Issue by mosharky** [klikli-dev/occultism#934]
**Describe the bug**
When killing a horse or cow (at least, haven't tested others) with a butcher's knife, tallow won't drop at all

**To Reproduce**
1. Kill a cow or horse

**Expected behavior**
Tallow to drop

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.80.8
- OS: Windows
- Minecraft Version: 1.20
- Modpack Link and Version, or list of mods: https://gist.github.com/mosharky/0860ebea76385b21dfeeaf51e5e4013a

**Additional context**
I don't personally have the time to test it myself, this was just something observed by a player on my server

**Comment by klikli-dev** [comment]
@mosharky This is a forge bug, currently loot modifiers do not apply to entities.
When forge fixes it, it will start working again automatically for all mods :) 

See also https://github.com/MinecraftForge/MinecraftForge/issues/9551
