### ISSUE TITLE
[suggestion] extended datapack usability with rituals

### ISSUE THREAD

**Issue by Shibva** [klikli-dev/occultism#938]
**Is your feature request related to a problem? Please describe.**
This was a thought I had as I am learning to do things with datapacks and had an idea that I'm not sure exist in the ritual crafting system 

**Describe what you'd like**
1. The ability for an output to be air but when viewed through the recipe system JEI/REI shows a display item: disco out for "inform" items to be displayed, but when looking at able display information within its tooltip; two and three will expand on why.

2. A new item that is unattainable: the information icon; it's parents will be like a circle with an i at the center. The purpose of this icon can be used for the display feature above. Both number one and number two will be used for the third idea.

3. /function integration: whenever a recipe is crafted whatever function is called, will be executed upon the rituals completion. This would use the "function":"" syntax that can be used in advancements to avoid confusion and is NOT mutually exclusive to recipe output (the function can be called with an item output [and none assuming air is a valid output]). location of the function will occur at the gilded sacrificial bowl (allows for "~ ~ ~" to be used at the center of the ritual)

**Additional context**
By implementing all thee of these things the following could be done with ritual recipes:
- Custom "events" can be executed through the use of /function system.
- Custom rituals that souly call a function and return nothing (outputs air) can have a display item be only seen in JEI/REI with NBT data to display custom info and a info icon item to illustrate such without the use of another item to act as such.

This will make the rituals even more configurable as functions can allow for much more to be done with rituals beyond crafting.

Examples: a custom ritual that when completed will call a function that will use /loot to inject a mineshafts loot table into the central sacrificial bowl and show when viewed in JEI a info icon item that contains nbt data describing what the ritual does.

## If at all you have any questions regarding what I mean the please ask

**Comment by klikli-dev** [comment]
@Shibva that is a really good idea - but as far as I see we already have it!
There is the ritual type "execute_command" with the "command" field to do that.

As info item it uses the "ritual dummy", those can have tooltips and will not be given to the player, but shown as "virtual" output in JEI so players can hover over and see the info

**Comment by Shibva** [comment]
ah; sorry its been a long while since I last messed wtih this mod. My bad
