### ISSUE TITLE
Advancements don't appear to be working

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#940]
**Describe the bug**
Summoned a Familiar, but got no advancement. 

**To Reproduce**
1. Summon Bat familiar (or anything) from a ritual
2. Receive no advancement

**Expected behavior**
root advancement to summon a familiar should trigger

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.19.2-1.80.11.jar
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: limited testing instance of only JEI and Occultism

**Additional context**

**Comment by klikli-dev** [comment]
yup, turns out the familiar rituals did not call the general ritual finish logic which handles that
