### ISSUE TITLE
Modonomicon/]: BookErrorManager.error

### ISSUE THREAD

**Issue by battousan** [klikli-dev/occultism#942]
**Describe your problem**
A clear and concise description of what you need help with. Include log files or examples to illustrate what is going on.

What is your Minecraft version? 1.19.2
What is your Forge version? 43.2.8
What is your modpack and modpack version? BNM Adventure beta date 6/16/2023
What is your exact Mod version (file name)? 
What is your issue? Getting the following error on the server: 26.06 14:05:24 [Server] main/WARN [co.kl.mo.Modonomicon/]: BookErrorManager.error() called for book: occultism:dictionary_of_spirits with error: BookErrorInfo{ 
26.06 14:05:24 [Server] INFO errorMessage='Failed to load entry 'occultism:dictionary_of_spirits/entries/getting_started/theurgy_divination_rod'', 
26.06 14:05:24 [Server] INFO context='Page Index: 0', 
26.06 14:05:24 [Server] INFO exception='com.google.gson.JsonSyntaxException: Unknown item 'theurgy:divination_rod_t1''
26.06 14:05:24 [Server] INFO }

**Comment by klikli-dev** [comment]
@battousan does that lead to any follow up error? 
As in, the book not opening?

Because if theurgy is not installed that error should be OK (there is one entry that only shows up with theurgy present), unless it causes further issues down the road

**Comment by battousan** [comment]
can i add the mod with out corrupting the map ? Sorry still a bit knew to mod creating and management.

**Comment by klikli-dev** [comment]
generally, when adding mods *always* make a backup of the map.

But yes, the mod should not do anything with your map. 
Occultism has some world gen, but that will simply only run on newly created chunks and not affect old ones.
The above error also does not affect your map or savegame in any way.

**Comment by battousan** [comment]
ok thanks, i just tried to create the book and nothing comes up. i will add it on my end on the next mod version update. Any suggestion pls feel free to let me know, and thanks for the mod,

**Comment by klikli-dev** [comment]
@battousan just to clarify, "nothing comes up" as in, no error in the book, right? Or is the book empty :) 

Suggestions: We have a discord that has lots of people to help with in-game questions, so it is worth joining. 
It might also be interesting to add the mod theurgy, it currently only has content that extends occultism (namely, better divination rods), but the first content update will drop soon
