### ISSUE TITLE
Show all crusher tiers in crusher recipes

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#944]
**Is your feature request related to a problem? Please describe.**
Along the left of any Crushing recipe it shows the 'machine' used to process it. It would be nice if it showed all tiers of crusher instead of just the Marid

**Describe the solution you'd like**
Show all tiers of Crusher in the tab on the left of crusher recipes

**Additional context**
Ignore the fact that things are renamed here. The tab on the left is what I'm talking about. 
![image](https://github.com/klikli-dev/occultism/assets/9543430/3bc1d9de-29ca-4fae-b63e-982c78bd9437)

For example, the Furnace shows other valid furnaces in JEI
![image](https://github.com/klikli-dev/occultism/assets/9543430/3c687b21-215c-4637-aba0-57bb8f6b2158)

**Comment by klikli-dev** [comment]
Closed in f0bc7dc997c3add52f113528eae304aad505b6db
