### ISSUE TITLE
Tallow not dropping in ATM9 v0.0.22

### ISSUE THREAD

**Issue by Boredering** [klikli-dev/occultism#945]
**Describe the bug**
Tallow isn't dropping when killing animals with the butcher knife

**To Reproduce**
1. Kill animal with butcher knife
2. No tallow drops after like 30 kills with looting butcher knife

**Expected behavior**
Mob's drop tallow when killed with a butcher knife

**System (please complete the following information):**
- Occultism Version: 1.80.12
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

**Comment by klikli-dev** [comment]
This is a forge Bug, latest version of forge might have fixed it, see also #934

You can use vanilla candles instead of occultism candles to progress
