### ISSUE TITLE
[1.19.x] modrinth support

### ISSUE THREAD

**Issue by ColonelGerdauf** [klikli-dev/occultism#946]
**Is your feature request related to a problem? Please describe.**
Although this mod is available for 1.20.x, the page in Modrinth lacks support for 1.19.x, in particular 1.19.2.

**Describe the solution you'd like**
It would be convenient for the version supports between Modrinth and Curseforge to be on par or near par. 

**Additional context**
This is a factor of convenience for players to do faster mod updates via launchers thanks to its more efficient API versus Curseforge.

**Comment by klikli-dev** [comment]
That is a valid request, but currently I don't have the time to update the workflows on 1.19.2, as I would also have to update Modonomicon and Theurgy in order to ensure the dependencies are available.
That said, if anyone wants to update the github actions I will run a release

**Comment by ColonelGerdauf** [comment]
I have submitted pull requests of the needed actions for Occultism specifically. They may not be 100% functional, but the edits are intended for Modrinth inclusion.

I will get on the dependencies.

**Comment by ColonelGerdauf** [comment]
And accomplished. I have pull requests for Modonomicon and Theurgy.

**Comment by klikli-dev** [comment]
That is absolutely fantastic, thank you. I will try to review them ASAP

**Comment by klikli-dev** [comment]
Looks good! I closed some of the lower version PRs as they would not work as is and as the versions have not been supported in a long while ( and I do not want to trigger a new wave of support requests from users that see activity), but merged the others.

Thanks a lot!
