### ISSUE TITLE
crashes when trying to summon crusher

### ISSUE THREAD

**Issue by cicatrize04** [klikli-dev/occultism#956]
hello,

im having trouble stopping my game crashing when trying to summon a crusher. i have performed other rituals before without any issues until today where it has started crashing right before the end of that summoning. is there something you can recommend?

**Comment by klikli-dev** [comment]
@cicatrize04 please provide the crash log, and the details as requested by the bug report template, specifically you rexact mod version and your modpack or mod list

**Comment by klikli-dev** [comment]
Actually it looks like this might be a duplicate of #955 and the next version of occultism will fix it.
If it still remains in the next occultism version, please ping me or open a new ticket!
