### ISSUE TITLE
Divination Rod causing weird stutter 

### ISSUE THREAD

**Issue by sharkweekthings** [klikli-dev/occultism#957]
**Describe the bug**

**To Reproduce**
When I click and hold an Occultism Divination Rod while moving forward the game lags/stutters out pretty hard until it fires off the pink dot. 

each of the Theurgy ones do not do this. I can walk forward stutter free while "charging" the rod, and fire off the pink dot.

**Expected behavior**
I imagine it should be more like the Theurgy one / where it's smooth and non stuttery

**Screenshots**

**System (please complete the following information):**
- Occultism Version:  occultism-1.19.2-1.81.2 / theurgy-1.19.2-1.3.6
- OS: [e.g. Windows]
- Minecraft Version: 1.19.2 43.2.14
- [Modpack Link and Version, or list of mods: https://docs.google.com/spreadsheets/d/1zrDSeeMsgEhPI0ngClYJWVOliY-F9xeMzvCL3jhTKCU/edit?usp=sharing

**Additional context**

**Comment by klikli-dev** [comment]
@sharkweekthings that's a config option!
In the occultism client config file there is "divinationRodScanRange", if you set that to 96 it will behave like the theurgy rod.
The stuttering happens because occultism by default uses a higher scan range (129), because groves are more rare than most ores.
