### ISSUE TITLE
[Suggestion] Polymorph storage support

### ISSUE THREAD

**Issue by Vallice** [klikli-dev/occultism#958]
Polymorph is a mod that lets you change the endproduct, when there is the same crafting recepies multiple times,
 however this function doesn´t work in the dimensional storage crafting grid. Only checked it on 1.19.2.

**Comment by klikli-dev** [comment]
@Vallice as I understand it that is something polymorph adds on their end at least the issue comments there indicate that.
You can open an issue there and link back to this one in case I need to do something

**Comment by klikli-dev** [comment]
Closing this on my end
