### ISSUE TITLE
Divination rod highlight missing

### ISSUE THREAD

**Issue by ClaymooreEOC** [klikli-dev/occultism#960]
**Describe the bug**
When using the Divination rod to search for otherworld wood and iesnium ore the white box highlight is missing making the ores impossible to find.
The problem is currently both in ATM9 in MC 1.20.1 and FTB Unstable MC 1.20.1 modpacks that i have seen.

**To Reproduce**
Set divination rod to target.
Click to activate
Look around.

**Expected behavior**
After having scanned with the rod a block should be highlighted.

**Screenshots**
Unable to screenshot something missing.

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.81.1.jar
- OS: Windows 10
- Minecraft Version: 1.20.1
- Modpack : https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
https://www.feed-the-beast.com/modpacks/110-ftb-unstable-120-forge?tab=about

**Additional context**
-

**Comment by klikli-dev** [comment]
@ClaymooreEOC I just tested this in ATM 9 and it works - I have an nvidia card though.
Some AMD users need to go to occultism-client.toml (in the config folder) and set `useAlternativeDivinationRodRenderer = true`

To test it search jei for "oak wood" and find the oak wood that does not look like oak wood (= its the occultism variant) and place it down. Then attune the rod to either a real oak tree or to the one you just placed and use the rod - it should highlight the just placed wood. 

Note that iesnium ore only spawns in the nether.

**Comment by ClaymooreEOC** [comment]
Thank you!
Problem solved <3
I just hope i remember this in the future.
I have had similar problems in earlier versions as well since occultism is
one of my absolute favorite mods and i love playing it :)

**Comment by klikli-dev** [comment]
Awesome, I'm glad that worked for you, and super glad you enjoy the mod! :)
