### ISSUE TITLE
Avaiability for the Fabric Modloader

### ISSUE THREAD

**Issue by sowelipililimute** [klikli-dev/occultism#961]
Title is somewhat self-explanatory; it would be nice to see Occultism compatible with Fabric.

**Comment by klikli-dev** [comment]
@pontaoski I agree in principle that this would be a great thing, but after recently having ported Modonomicon (a much less complex mod when it comes to how much modloader related code it needs) I now know that it is unlikely that I will ever port occultism, as a lot of it relies on forge provided functionality that is either not present in fabric, or different enough to require to maintain two codebases at once.

IF someone comes along and wants to port I will assist and make sure it goes smoothly, but I cannot do it
