### ISSUE TITLE
Unable to craft recipes that require XP in Occultism Dimensional Storage

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#964]
**Describe the bug**
Unable to craft recipes that require XP in Occultism Dimensional Storage

**To Reproduce**
Attempt to craft Apotheosis' Hellshelf in the Dimensional Storage

**Expected behavior**
The craft should complete

**Screenshots**
In Occultism
![image](https://github.com/klikli-dev/occultism/assets/9543430/8a5ff07b-9e83-4727-994e-8f5c31d7437b)

In Ars storage lectern
![image](https://github.com/klikli-dev/occultism/assets/9543430/2800e404-4963-4737-84b9-3a55692e2b55)

**System (please complete the following information):**
- Occultism Version: 
occultism-1.19.2-1.84.0.jar
- OS: Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: https://www.curseforge.com/minecraft/modpacks/enigmatica9expert 1.11.2

**Additional context**

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/643

**Comment by klikli-dev** [comment]
I did not know that existed! 
Will look into it

**Comment by GaeaKat** [comment]
Hi there! I downloaded Enigmatica 9 Expert - E9E version 1.11.2 AND current version, I was unable to reproduce this on either one.

The recipe itself works fine, and it doesnt use XP to craft

**Comment by MuteTiefling** [comment]
No longer able to reproduce this either. I've closed up our issue.

**Comment by klikli-dev** [comment]
Thanks for confirming, and thank you all for the investigation!
