### ISSUE TITLE
Update the Deer Familiar

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#966]
**Is your feature request related to a problem? Please describe.**
I believe @theboo is the one that mentioned this first. The Deer familiar is not very good at its particular task. It grants a Jump Height bonus, however this is already covered by the Drikwing quite spectacularly. The Deer, on the other hand, only gives enough Jump to clear a fence.

**Describe the solution you'd like**
It would be nice if the Deer covered a different niche entirely. Something other familiars aren't covering. For example, Step Height. I think a moderate run speed and 1 block step height would be nicer to have for this. Giving it a unique bonus among familiars and making it a more interesting choice to use.

**Comment by klikli-dev** [comment]
Closed in 061d53e2623fca51d1ee099b2416c82c1670e22e and 8336322637628d785b5c1a0df3ed2c7b8db4268b
