### ISSUE TITLE
Mysterious Spirit Deaths and reducing the impact

### ISSUE THREAD

**Issue by Ciege666** [klikli-dev/occultism#967]
**Is your feature request related to a problem? Please describe.**
There is nothing more annoying than your work not mattering. It's one thing for it to be destroyed by a creeper explosion you could have stopped, but coming back to all your spirits just being gone results in a huge resource waste and massive frustration of not even being sure what happened.

**Describe the solution you'd like**
All familiars should have a spirit shard or token they drop, as if their physical form has been shattered and needs to be recharged. Rather than a long craft through rituals I would suggest just allowing the player to drop the "spirit fragment" in the Occultism spirit fire to recharge the spirit and return it to normal spawning it in the world as if nothing happened.

**Additional context**
I wouldn't add any healing to the spirits from the fire as I think with the fruit there is plenty of healing for spirits. Also this would kinda help answer the question of when people have disappearing familiars.

**Comment by klikli-dev** [comment]
Closed in favor of https://github.com/klikli-dev/occultism-feature-tracker/issues/13
