### ISSUE TITLE
Opening Book not working in Server

### ISSUE THREAD

**Issue by windy664** [klikli-dev/occultism#970]
### Issue with Opening Book in Game

**Describe the bug**  

**To Reproduce**  
1. Right click to open book
2. not working

**Expected behavior**  
I hope I can open the book normally, after my testing, it works in single player games, but multiplayer games don't work properly.

**Screenshots**  
![Z$J(_BTA_HJW7R%D$QCI9AV](https://github.com/klikli-dev/occultism/assets/81475218/62d185cd-8717-4149-90fa-630fc75520b2)

**System (please complete the following information):**  
- Occultism Version: ]occultism-1.20.1-1.87.0.
- OS: [e.g. Windows 10]
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://share.weiyun.com/4zy2LK7J
- [1.20.1]风铃物语v7.5.zip

**Additional context**

**Comment by klikli-dev** [comment]
@windy664 I cannot reproduce this if I use latest occultism on client and server. 
Is it possible that serverside there is an older version of occultism? The link "the_hermetica/getting_started/divination_rod" is only present in older versions of occultism and is what causes the crash. 
Alternatively, is it possible that there is a datapack or kubejs or similar that overwrites occultism's book? If so then that datapack might be outdated

**Comment by windy664** [comment]
> @windy664 I cannot reproduce this if I use latest occultism on client and server. Is it possible that serverside there is an older version of occultism? The link "the_hermetica/getting_started/divination_rod" is only present in older versions of occultism and is what causes the crash. Alternatively, is it possible that there is a datapack or kubejs or similar that overwrites occultism's book? If so then that datapack might be outdated

I updated from the old version to the latest today and that's it

**Comment by klikli-dev** [comment]
So on the latest version you get this error?
That is extremely odd - the link you shared, the modpack, is there any way to downlaod that without an account? 
Maybe putting it on wetransfer or similar would be an option?

**Comment by windy664** [comment]
> So on the latest version you get this error? That is extremely odd - the link you shared, the modpack, is there any way to downlaod that without an account? Maybe putting it on wetransfer or similar would be an option?

how to use wetransfer ? 
what the mean "email to "
is it need your email?
![image](https://github.com/klikli-dev/occultism/assets/81475218/ec55f15f-9525-459f-b1a1-5cff6709ef19)

**Comment by klikli-dev** [comment]
Oh sorry I forgot it needed a target email - you can use klikli@outlook.at

**Comment by windy664** [comment]
> Oh sorry I forgot it needed a target email - you can use [klikli@outlook.at](mailto:klikli@outlook.at)

我研究了下 是可以直接发link的
my server pack：
https://we.tl/t-FbUJbVOJu9 
my client pack：
https://we.tl/t-fEwk1z4ci7

**Comment by klikli-dev** [comment]
Thank you!
My first finding is that on the client pack occultism is outdated (1.81.6). If you update that it likely will work.
If you have remaining errors then please let me know

**Comment by windy664** [comment]
> Thank you! My first finding is that on the client pack occultism is outdated (1.81.6). If you update that it likely will work. If you have remaining errors then please let me know

emmmm .......
The client pack I sent you is an old version, but it needs to be started to update my integration package.
Because I am too lazy to make a complete compressed package, can you try to start it first?
![image](https://github.com/klikli-dev/occultism/assets/81475218/5de512b2-ab35-4016-82ae-f60806ff5b34)
![image](https://github.com/klikli-dev/occultism/assets/81475218/ee0e3c9f-df0d-4ff9-aff2-64b94cdc88f8)
![image](https://github.com/klikli-dev/occultism/assets/81475218/6d3391fc-83a7-41c9-a9b5-d2f851fb853e)
![image](https://github.com/klikli-dev/occultism/assets/81475218/02922321-35a1-4c1b-89d6-ba473f2ecee9)
start minecraft
Modpacks will automatically check for updates on startup

**Comment by klikli-dev** [comment]
Sorry I rather not run that executable, multiple antivirus flag it as a trojan. Most likely that is a false positive but I'm not taking any risks

**Comment by windy664** [comment]
> Sorry I rather not run that executable, multiple antivirus flag it as a trojan. Most likely that is a false positive but I'm not taking any risks

![image](https://github.com/klikli-dev/occultism/assets/81475218/0b34d502-3612-4b63-afff-6461f59b87fa)
This is the module package check and update procedure

**Comment by windy664** [comment]
So...what should I do？
![image](https://github.com/klikli-dev/occultism/assets/81475218/a6afaea2-3979-4329-ba93-50002239612e)
I using the least on server

**Comment by klikli-dev** [comment]
So you have latest on server and on client now? 
That would be the most important thing to verify 

Other than that it would be interesting to see if this issue also happens with just occultism + dependencies (jei, theurgy and the required dependencies)

**Comment by windy664** [comment]
> So you have latest on server and on client now? That would be the most important thing to verify
> 
> Other than that it would be interesting to see if this issue also happens with just occultism + dependencies (jei, theurgy and the required dependencies)

my clinet mods list
[JEI物品管理器]jei-1.20.1-forge-15.2.0.27.jar
[农夫乐事]FarmersDelight-1.20.1-1.2.3.jar
[农夫乐事][料理乐事]cuisinedelight-1.1.8.jar
[农夫乐事][末地乐事]ends_delight-1.20.1-1.0.1.jar
[农夫乐事][海洋乐事]oceansdelight-1.0.2-1.20.jar
[农夫乐事][玉米乐事] corn_delight-1.0.3-1.20.1.jar
[前置]architectury-9.0.8-forge.jar
[前置]cloth-config-11.0.99-forge.jar
[前置]supermartijn642corelib-1.1.9-forge-mc1.20.jar
[前置][优化]cupboard-1.20.1-1.9.jar
[前置][创造核心]CreativeCore_FORGE_v2.10.34_mc1.20.1.jar
[前置][动态联合]CyclopsCore-1.20.1-1.18.10.jar
[前置][化学]chemlib-1.20.1-2.0.17.jar
[前置][合成扩展]Cucumber-1.20.1-7.0.0.jar
[前置][妖怪之山通用库] mysterious_mountain_lib-1.2.7-1.20.jar
[前置][帕特抽手册]Patchouli-1.20.1-82-FORGE-SNAPSHOT.jar
[前置][循环]flib-1.20.1-0.0.11.jar
[前置][懒人厨房]balm-forge-1.20-7.0.7.jar
[前置][手册]modonomicon-1.20.1-forge-1.39.0.jar
[前置][柠檬核心]lemon_core-1.20.1-1.0.31.jar
[前置][模型]geckolib-forge-1.20.1-4.2.2.jar
[前置][炼金化学]alchemylib-1.20.1-1.0.29.jar
[前置][生物群系]TerraBlender-forge-1.20.1-3.0.0.169.jar
[前置][神秘主义]theurgy-1.20.1-1.6.4.jar
[前置][神秘主义][聪明大脑库]SmartBrainLib-fabric-1.20-1.11.jar
[前置][葡园酒香]doapi-1.2.6-forge.jar
[前置][铁魔法]caelus-forge-3.1.0+1.20.jar
[前置][铁魔法]player-animation-lib-forge-1.0.2-rc1+1.20.jar
[前置][集成动力]CommonCapabilities-1.20.1-2.9.0.jar
[前置][饰品栏]curios-forge-5.2.0+1.20.1.jar
[前置][饰品栏]curios-forge-5.2.0-beta.3+1.20.1.jar.old
[动态联合]IntegratedDynamics-1.20.1-1.18.0.jar
[动态联合][集成动力学]IntegratedCrafting-1.20.1-1.1.4.jar
[卡哇伊]KawaiiDishes_1.10.2-1.20.1.jar
[原琴]genshinstrument-1.20+1.20.1-3.3.jar
[合成扩展]ExtendedCrafting-1.20.1-6.0.2.jar
[合成表]CraftTweaker-forge-1.20.1-14.0.13.jar.old
[合成表]CraftTweaker-forge-1.20.1-14.0.14.jar
[多态合成] polymorph-forge-0.49.0+1.20.1.jar
[大力能源]Powah-5.0.1.jar
[天空村庄] SkyVillages-1.0.2-1.20.1-forge-release.jar
[循环]Cyclic-1.20.1-1.12.4.jar
[懒人厨房] cookingforblockheads-forge-1.20-16.0.0.jar
[方块小镇]yuushya-1.20.1-forge-2.0.0.jar
[是，史蒂夫模型] yesstevemodel-1.20-release-1.1.5-hotfix-2.jar
[更多实用工具]scalar_utils-1.20.1-5.4.10.jar
[更多生物群系]BiomesOPlenty-1.20.1-18.0.0.597.jar
[更多磁盘] ExtraDisks-1.20.1-3.0.0.jar
[更多箱子]ironchest-1.20.1-14.4.4.jar
[更多结构]Structory_1.20.1_v1.3.2.jar
[末影接口]EnderIO-1.20.1-6.0.18-alpha.jar
[机械动力] create-1.20.1-0.5.1.d.jar
[植物魔法]Botania-1.20.1-441-FORGE-SNAPSHOT.jar
[汉堡包]burgermod-2.9.4-1.20.1.jar
[炼金化学]alchemistry-1.20.1-2.3.3.jar
[现代化修复]modernfix-forge-5.7.2+mc1.20.1.jar
[神秘学]occultism-1.20.1-1.87.0.jar
[管道]pipez-1.20.1-1.1.5.jar
[精致存储] refinedstorage-1.12.2.jar
[精致存储附属] refinedstorageaddons-0.10.0.jar
[网络发包修复]connectivity-1.20.1-4.5.jar
[自然罗盘]NaturesCompass-1.20.1-1.11.2-forge.jar
[葡园酒香] letsdo-vinery-forge-1.4.2.jar
[豆腐工艺]TofuCraftReload-1.20.1-5.5.0.1.jar.old
[豆腐工艺]TofuCraftReload-1.20.1-5.5.1.2.jar
[赛🐎娘]umapyoi-0.2.15-1.20.jar
[选择][前置][一键背包整理]libIPN-forge-1.20-3.0.2.jar
[选择][机械动力渲染优化]oculus-flywheel-compat-1.20.1-0.2.0.jar
[选装[世界地图]XaerosWorldMap_1.34.0_Forge_1.20.jar
[选装][FPS减速器] FpsReducer2-forge-1.20-2.5.jar
[选装][Iris]oculus-mc1.20-1.6.4.jar
[选装][一键背包整理Next] InventoryProfilesNext-forge-1.20-1.10.6.jar
[选装][万用皮肤补丁] CustomSkinLoader_ForgeActive-14.17.jar
[选装][世界地图]XaerosWorldMap_1.33.1_Forge_1.20.jar.old
[选装][前置][一键整理]kotlinforforge-4.4.0-all.jar
[选装][动态光源]dynamiclightsreforged-1.20.1_v1.6.0.jar
[选装][夜间模式无处不在] DarkModeEverywhere-1.20.1-1.2.2.jar
[选装][小地图]Xaeros_Minimap_23.6.3_Forge_1.20.jar.old
[选装][小地图]Xaeros_Minimap_23.7.0_Forge_1.20.jar
[选装][截图到剪贴板] screenshot-to-clipboard-1.0.9-forge.jar
[选装][更好的FPS]betterfpsdist-1.20.1-3.8.jar
[选装][点歌][forge-1.20]AllMusic-2.6.8.jar
[选装][玉]Jade-1.20.1-forge-11.5.1.jar
[选装][玉][附加]JadeAddons-1.20.1-forge-5.2.0.jar
[选装][现代化UI]ModernUI-1.20.1-3.8.1.4-universal.jar
[选装][苹果皮] appleskin-forge-mc1.20.1-2.5.0.jar
[选装][视距]farsight-1.20.1-3.3.jar
[选装][通用拼音搜索] jecharacters-1.20.1-4.4.1.jar
[选装][铷] rubidium-0.6.5.jar
[选装][镁／铷：动态光源] dynamiclightsreforged-1.20.1_v1.5.0.jar.old
[选装][鼠标手势] MouseTweaks-forge-mc1.20-2.25.jar
[通用机械]Mekanism-1.20.1-10.3.9.homebaked-all.jar
[通量网络] FluxNetworks-1.20.1-7.2.0.14.jar
[铁氧体磁芯] ferritecore-6.0.0-forge.jar
[铁魔法]irons_spellbooks-1.20.1-1.2.1.jar
[飞车奇匠] automobility-0.4.2+1.20.1-forge.jar
[魔法使]mahoutsukai-1.20.1-v1.34.54.jar

server mod list

[JEI物品管理器]jei-1.20.1-forge-15.2.0.27.jar
[农夫乐事]FarmersDelight-1.20.1-1.2.3.jar
[农夫乐事][料理乐事]cuisinedelight-1.1.8.jar
[农夫乐事][末地乐事]ends_delight-1.20.1-1.0.1.jar
[农夫乐事][海洋乐事]oceansdelight-1.0.2-1.20.jar
[农夫乐事][玉米乐事] corn_delight-1.0.3-1.20.1.jar
[前置]architectury-9.0.8-forge.jar
[前置]cloth-config-11.0.99-forge.jar
[前置]supermartijn642corelib-1.1.9-forge-mc1.20.jar
[前置][优化]cupboard-1.20.1-1.9.jar
[前置][创造核心]CreativeCore_FORGE_v2.10.34_mc1.20.1.jar
[前置][动态联合]CyclopsCore-1.20.1-1.18.10.jar
[前置][化学]chemlib-1.20.1-2.0.17.jar
[前置][合成扩展]Cucumber-1.20.1-7.0.0.jar
[前置][妖怪之山通用库] mysterious_mountain_lib-1.2.7-1.20.jar
[前置][帕特抽手册]Patchouli-1.20.1-82-FORGE-SNAPSHOT.jar
[前置][循环]flib-1.20.1-0.0.11.jar
[前置][懒人厨房]balm-forge-1.20-7.0.7.jar
[前置][手册]modonomicon-1.20.1-forge-1.39.0.jar
[前置][柠檬核心]lemon_core-1.20.1-1.0.31.jar
[前置][模型]geckolib-forge-1.20.1-4.2.2.jar
[前置][炼金化学]alchemylib-1.20.1-1.0.29.jar
[前置][生物群系]TerraBlender-forge-1.20.1-3.0.0.169.jar
[前置][神秘主义]theurgy-1.20.1-1.6.4.jar
[前置][神秘主义][聪明大脑库]SmartBrainLib-fabric-1.20-1.11.jar
[前置][葡园酒香]doapi-1.2.6-forge.jar
[前置][铁魔法]caelus-forge-3.1.0+1.20.jar
[前置][铁魔法]player-animation-lib-forge-1.0.2-rc1+1.20.jar
[前置][集成动力]CommonCapabilities-1.20.1-2.9.0.jar
[前置][饰品栏]curios-forge-5.2.0+1.20.1.jar
[动态联合]IntegratedDynamics-1.20.1-1.18.0.jar
[动态联合][集成动力学]IntegratedCrafting-1.20.1-1.1.4.jar
[卡哇伊]KawaiiDishes_1.10.2-1.20.1.jar
[原琴]genshinstrument-1.20+1.20.1-3.3.jar
[合成扩展]ExtendedCrafting-1.20.1-6.0.2.jar
[合成表]CraftTweaker-forge-1.20.1-14.0.14.jar
[多态合成] polymorph-forge-0.49.0+1.20.1.jar
[大力能源]Powah-5.0.1.jar
[天空村庄] SkyVillages-1.0.2-1.20.1-forge-release.jar
[循环]Cyclic-1.20.1-1.12.4.jar
[懒人厨房] cookingforblockheads-forge-1.20-16.0.0.jar
[方块小镇]yuushya-1.20.1-forge-2.0.0.jar
[是，史蒂夫模型] yesstevemodel-1.20-release-1.1.5-hotfix-2.jar
[更多实用工具]scalar_utils-1.20.1-5.4.10.jar
[更多生物群系]BiomesOPlenty-1.20.1-18.0.0.597.jar
[更多磁盘] ExtraDisks-1.20.1-3.0.0.jar
[更多箱子]ironchest-1.20.1-14.4.4.jar
[更多结构]Structory_1.20.1_v1.3.2.jar
[服务端]canary-mc1.20.1-0.2.7.jar1
[服务端]does_potato_tick-1.20-3.6.0.jar1
[服务端]spark-1.10.43-forge.jar
[服务端][前置]Placebo-1.20.1-8.3.2.jar
[服务端][机械动力扳手修复]windy-fixes-0.1.0.jar
[服务端][配方缓存修复]FastSuite-1.20.1-5.0.0.jar1
[末影接口]EnderIO-1.20.1-6.0.18-alpha.jar
[机械动力] create-1.20.1-0.5.1.d.jar
[植物魔法]Botania-1.20.1-441-FORGE-SNAPSHOT.jar
[汉堡包]burgermod-2.9.4-1.20.1.jar
[炼金化学]alchemistry-1.20.1-2.3.3.jar
[现代化修复]modernfix-forge-5.7.2+mc1.20.1.jar
[神秘学]occultism-1.20.1-1.87.0.jar
[管道]pipez-1.20.1-1.1.5.jar
[精致存储] refinedstorage-1.12.2.jar
[精致存储附属] refinedstorageaddons-0.10.0.jar
[网络发包修复]connectivity-1.20.1-4.5.jar
[自然罗盘]NaturesCompass-1.20.1-1.11.2-forge.jar
[葡园酒香] letsdo-vinery-forge-1.4.2.jar
[豆腐工艺]TofuCraftReload-1.20.1-5.5.1.2.jar
[赛🐎娘]umapyoi-0.2.15-1.20.jar
[通用机械]Mekanism-1.20.1-10.3.9.homebaked-all.jar
[通量网络] FluxNetworks-1.20.1-7.2.0.14.jar
[铁氧体磁芯] ferritecore-6.0.0-forge.jar
[铁魔法]irons_spellbooks-1.20.1-1.2.1.jar
[飞车奇匠] automobility-0.4.2+1.20.1-forge.jar
[魔法使]mahoutsukai-1.20.1-v1.34.54.jar

**Comment by klikli-dev** [comment]
Ok that looks good - although it really makes me wonder where that error comes from.
Where did you download the occultism.jar from? Curseforge? Github?

**Comment by windy664** [comment]
> 

 Curseforge

it works in single player games, but multiplayer games don't work properly.




新发现：

![image](https://github.com/klikli-dev/occultism/assets/81475218/b51500d7-f0ca-48e2-8c11-6d3f9a8ed88a)

If the language is set to English, it is normal


If the language is set to Chinese[简体中文], it is not normal

Theurgy is the same situation


emmmm.....

It's very random, set to English sometimes is not normal
![image](https://github.com/klikli-dev/occultism/assets/81475218/afe76750-326e-497b-ae2e-1851b2fb56f0)

**Comment by klikli-dev** [comment]
Ohhh you know that was an extremely good find! 
I think the chinese translation is outdated and most likely the error then happens in english due to some caching issues in modonomicon. That is something I can look into, thank you!
