### ISSUE TITLE
Storage Stabilizer. 

### ISSUE THREAD

**Issue by aaron72886** [klikli-dev/occultism#975]
**Describe the bug**
The layout of the Storage setup is wrong. Two of the stabilizers are facing the wrong direction, halving the storage. 

**To Reproduce**
Open the dictionary, go to the  section on storage stabilizer setup and then click the eye button. right click to place on the ground. Does not show complete with the stabilizers facing the correct direction. 

**System (please complete the following information):**
- Occultism Version: 1.19.2-1.6.9
- OS: [e.g. Windows] Windows 10
- Minecraft Version: Java
- Modpack Link and Version, or list of mods: https://www.feed-the-beast.com/modpacks/114-ftb-presents-abepack?tab=mods

**Additional context**
Love the mod. Has been quite fun to play. I realize that the dictionary does say that the stabilizers should face the actuator.

**Comment by klikli-dev** [comment]
Fixed a few versions ago
