### ISSUE TITLE
Djinni is not dwelling on this plane of existence

### ISSUE THREAD

**Issue by SeeMeEat** [klikli-dev/occultism#977]
Whenever i give a djinni machine operator a job, when its done, it just says the spirit bound on the book is not dwelling on this plane of existence

**To Reproduce**
1. Order Djinni to cook in furnace using storage accessor
2. when finished, i have to manually take the items and the djinni is gone

II was expecting for the djinni to be back and my items automatically transported to my storage

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/146575717/e3508003-2193-4aca-916c-ab96d1f35b32)

**System (please complete the following information):**
- Occultism Version:  1.88.0
- OS: Windows
- Minecraft Version: 1.19.2
- FTB Presents AbePack 1.1.1

**Comment by klikli-dev** [comment]
@SeeMeEat can you reproduce this reliably if you spawn a new spirit and try again?

This message just means that the spirit cannot be found by the mod, that means he was either killed or removed by another mod. 
Occultism does not have a builtin mechanism for the machine manager spirits to die (no essence decay), but the essence decay may be enabled by the modpack, or something else may have killed him (mobs, other mods functions, or even bugged into a block and suffocted [thanks MC pathfinding!])

Please try again and see if he survives, and maybe follow him to see if you can see what killed him

**Comment by klikli-dev** [comment]
Closed as stale
