### ISSUE TITLE
[1.18.2] Crash on world creation with Project: Red - Exploration

### ISSUE THREAD

**Issue by jdawg3636** [klikli-dev/occultism#978]
**Describe the bug**
The mod crashes when creating a new world with Project Red: Exploration installed. This is a likely duplicate of a pre-existing issue on Project: Red's GitHub: https://github.com/MrTJP/ProjectRed/issues/1792

**To Reproduce**
1. Install Project Red and Occultism
2. Attempt to create a world with the following seed (it probably crashes for many/all seeds, but I've confirmed on this one): `-8514774603063900555`

**Expected behavior**
The game will crash with an error about feature cycles.

**Screenshots**
Not applicable; it's just a crash.

**System (please complete the following information):**
- Occultism Version: occultism-1.18.2-1.84.0.jar
- OS: Windows 10
- Minecraft Version: 1.18.2 (Forge 
- Modpack Link and Version, or list of mods: 
 - CBMultipart-1.18.2-3.1.0.137-universal.jar (https://www.curseforge.com/minecraft/mc-mods/cb-multipart)
 - CodeChickenLib-1.18.2-4.1.4.488-universal.jar (https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8)
 - curios-forge-1.18.2-5.0.9.1.jar (https://www.curseforge.com/minecraft/mc-mods/curios)
 - geckolib-forge-1.18-3.0.57.jar (https://www.curseforge.com/minecraft/mc-mods/geckolib)
 - modonomicon-1.18.2-1.33.1.jar (https://www.curseforge.com/minecraft/mc-mods/modonomicon)
 - occultism-1.18.2-1.84.0.jar (https://www.curseforge.com/minecraft/mc-mods/occultism)
 - ProjectRed-1.18.2-4.16.0-beta-17-core.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-core)
 - ProjectRed-1.18.2-4.16.0-beta-17-expansion.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-expansion)
 - ProjectRed-1.18.2-4.16.0-beta-17-exploration.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-exploration)
 - ProjectRed-1.18.2-4.16.0-beta-17-illumination.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-illumination)
 - ProjectRed-1.18.2-4.16.0-beta-17-integration.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-integration)
 - ProjectRed-1.18.2-4.16.0-beta-17-transmission.jar (https://www.curseforge.com/minecraft/mc-mods/project-red-transmission)
 - SmartBrainLib-forge-1.18.2-1.9.jar (https://www.curseforge.com/minecraft/mc-mods/smartbrainlib)

**Additional context**
- Here is the crash report (minimal environment, NOT the same as the large modpack cited in the original issue): https://paste.gg/p/anonymous/025a8d3f924c430fb4c02920ee47d516
- See the original issue on Project: Red's GitHub for more information and context: https://github.com/MrTJP/ProjectRed/issues/1792

**Comment by klikli-dev** [comment]
Fixed by ProjectRed
