### ISSUE TITLE
Familiar Ring disconnects other players when held

### ISSUE THREAD

**Issue by UnRealDinnerbone** [klikli-dev/occultism#979]
**Describe the bug**
Holding Familiar ring disconnects other players nearby

**To Reproduce**
1. Swap to Familiar ring while other players are nearby 
2. Others Players get disconnected

**Expected behavior**
Other Players not to get disconnected it 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.88.0
- OS: [e.g. Windows] Windows
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: 

**Additional context**
[Server log when item is held.](https://pste.me/@Gb4pTu5SGaw)

**Comment by klikli-dev** [comment]
This has been reported once before, but I have not been able to reproduce it. It seems to only happen if some (yet unknown) other mod is present.

Does this reproduce for you with just occultism + dependencies?

**Comment by klikli-dev** [comment]
Closed as stale
