### ISSUE TITLE
Stop the Oak Grove from spawning underwater

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#980]
**Is your feature request related to a problem? Please describe.**
I keep seeing the oak trees from Occultism spawning in rivers and oceans, they also keep bisecting other underwater structures. Could you make a blacklist so it does not spawn on ocean and river biomes? 

**Describe the solution you'd like**
Just make a biome blacklist so that the oak grove stop spawning underwater. 

**Additional context**
![image](https://github.com/klikli-dev/occultism/assets/44974827/5dbc283b-b26e-48de-8d0e-5562898cdd67)

**Comment by Dragnier** [comment]
I've seen so many of these in the ocean...
