### ISSUE TITLE
For the Divination Rod, mention config changes in the book if it doesnt work

### ISSUE THREAD

**Issue by BenOHedges** [klikli-dev/occultism#981]
When using the divination rod, the highlighted blocks never appeared but upon finding a reddit post, someone accidentally found out going through the TOML file there is a different renderer method you can enable. (Both reddit guy and i are on AMD machines, thinking thats the issue)

This knowledge didnt exist anywhere from my initial asking around fromwhat i could tell, so it be good to add a note in the Divination Rod section of the book, "if you cant see the rendering, goto the TOML file and change the rendering mode and restart your client" something along those lines.

**Comment by Draco9826** [comment]
Did it work for you? how do I go to the TOML file? it´s not working, I need help, please!

**Comment by BenOHedges** [comment]
Open your Occultism client config at "modpack-instance"/config/occultism-client.toml

Change useAlternativeDivinationRodRenderer from false to true

**Comment by ghost** [comment]
Same issue for me on an AMD GPU. Fixed by editing the Toml. Some better signposting or a check on the brand of GPU being used would be very nice.

**Comment by B3RT1C** [comment]
Im using AMD and worked just fine
