### ISSUE TITLE
Occultism Storage Block Crash

### ISSUE THREAD

**Issue by EzReading** [klikli-dev/occultism#982]
**Describe the bug**
I placed the dimensional storage block, the completed version of it, but the moment I right clicked the ground to place it, my game crashed. 

**To Reproduce**
1. Place Dimensional Storage Actuator
2. crash

**Expected behavior**
I expected the storage block to open

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 
- OS: Windows
- Minecraft Version: 1.18.2
- Modpack Link: https://www.curseforge.com/minecraft/modpacks/power-of-friendship-by-brohaho            
- Version: friends UNITE. 
[Crash Report.txt](https://github.com/klikli-dev/occultism/files/12896013/Crash.Report.txt)

**Additional context**
This is one of my first modpacks, so any help is greatly appreciated. 
[Crash Report.txt](https://github.com/klikli-dev/occultism/files/12896013/Crash.Report.txt)

**Comment by klikli-dev** [comment]
@EzReading it looks like occultism and geckolib are on incompatible versions. You can try to downgrade or upgrade geckolib and I will look into it on my end, maybe they made a breaking change that I missed

**Comment by klikli-dev** [comment]
@EzReading looking at it, you are using Geckolib 3.0.40 , Occultism currently uses at minimum 3.0.57, I dimly remember there was a breaking change earlier. So please update to latest geckolib and it should work
