### ISSUE TITLE
Did it work for you? how do I go to the TOML file? the divination rod highlight to get isneum not working, I need help, please!

### ISSUE THREAD

**Issue by Draco9826** [klikli-dev/occultism#983]
Did it work for you? how do I go to the TOML file? the divination rod highlight to get isneum not working, I need help, please!

_Originally posted by @Draco9826 in https://github.com/klikli-dev/occultism/issues/981#issuecomment-1769067016_

**Comment by klikli-dev** [comment]
Just like any other config - open your minecraft instance, go to the "config" folder and find "occultism-client.toml", then edit it with a text editor such as notepad or notepad++.

**Comment by Draco9826** [comment]
It worked, thank you!
