### ISSUE TITLE
[1.20.1] v1.88.1 Requires SmartBrainLib downgrade

### ISSUE THREAD

**Issue by MokahTGS** [klikli-dev/occultism#984]
**Describe the bug**
v1.88.1 Requires a downgrade of SmartBrainLib to function.

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.88.1
- OS: [e.g. Windows] Win10
- Minecraft Version: 1.20.1

**Comment by klikli-dev** [comment]
This is a consequence of breaking changes in forge affecting smartbrainlib. 
Occultism targets forge 47.1.3 which is the last version that is compatible with neoforge, which will be what occultism will target exclusively going forward to 1.20.2 and further. 

As I understand it using the lower version of SBL is not a regression of features
