### ISSUE TITLE
[Feature request] Allow for Crushers to process Raw Ore Blocks

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#988]
It's a bit frustrating that we need to process the raw ores 1 by 1, even at higher levels. 
I think it would be nice if the higher-level crushers could process the Raw Block.

Adding that recipe I think would be easy, and an incentive to upgrade to the other levels of crushers (besides the ore duplication.)

**Comment by Reaviik** [comment]
Additionally add a block of raw Iésnio

**Comment by klikli-dev** [comment]
I had no idea raw blocks existed haha
That sounds like a good idea - btw you can already add this on your own via datapack, but I can look into adding it by default
