### ISSUE TITLE
Marid Crusher Interact

### ISSUE THREAD

**Issue by Reaviik** [klikli-dev/occultism#990]
**Is your feature request related to a problem? Please describe.**
Dropping items on the ground can be a problem, although it works very well, it ends up involving redstone systems and dropped items cause lag, especially on servers.

**Describe the solution you'd like**
My suggestion is to have the Marids interact with the Bowl's or have a new similar block where we can place the items and they would go to work there

**Additional context**
I don't know for sure if it's possible to do this with the storage actuator because I didn't find anything in the guide book.

**Comment by klikli-dev** [comment]
While not fully excluding dropped blocks you can automate this by using a transporter to insert directly into the marid, and then a janitor to pick it up. For a fully block-based solution that supports pipes and such please try the occultism - ars noveau compat plugin https://www.curseforge.com/minecraft/mc-mods/ars-ocultas
