### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by DonorKrovi** [klikli-dev/occultism#992]
**Describe the bug**
https://streamable.com/cqc2wb

**To Reproduce**
1. Video ^
2. Neruina prevented the server from crashing, error below

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.89.1
- OS: [e.g. Windows] Unbuntu 20
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 

**Additional context**
https://mclo.gs/BIefOWi

**Comment by Tslat** [comment]
You're using the wrong SBL file.

There's two forge versions for 1.20.1 - one for Neoforge & Forge 47.1.3, and one for Forge 47.1.4 and above

I even put a big disclaimer on it and everything

![image](https://github.com/klikli-dev/occultism/assets/7098525/fadea7c8-1fe9-4edf-94b4-1038fbc575f8)
