### ISSUE TITLE
More Familiars

### ISSUE THREAD

**Issue by lunafox447** [klikli-dev/occultism#993]
Hi I'm new to occultism I'm playing in 1.16.4 I've noticed there are only 2 familiars available is there a way i can get more?

**Comment by klikli-dev** [comment]
I honestly don't remember, but it is possible that 1.16 only had two.
To get all features of occultism make sure to use the recommended latest MC version of forge/neoforge, which currently is 1.20.2, although even 1.18+ has a lot more familiars
