### ISSUE TITLE
Divination rod highlights already harvested Iesnium ore spot instead of finding new one

### ISSUE THREAD

**Issue by Dragnier** [klikli-dev/occultism#995]
**Describe the bug**
Per the title, I'm using the Divination rod and it keep highlighting an already harvested spot instead of finding new ore or stating none in range.

**To Reproduce**
1. Scan for Iesnium ore and find some
2. Harvest the Iesnium
3. Re-scan for Iesnium ore
4. See the highlight in the same place where you just harvested instead of a new place or no highlight and a message of none in range

**Expected behavior**
I expected to either see a new highlight or no highlight with a message in chat about none in range.

**System (please complete the following information):**
- Occultism Version: 1.89.1
- OS: Windows 11
- Minecraft Version: 1.20.1

**Comment by Dragnier** [comment]
Further, the one spot it highlights is right near my portal / initial nether spawn. I even changed the config to highlight ALL found ore instead of the closest one. It even fails to highlight Iesnium that does exist in the world and is closer; instead only highlighting the original one near my portal that is no longer there.

**Comment by Dragnier** [comment]
Here's a [quick video showing the problem](https://youtu.be/u4Zq8YJw608).  At the end of the video, the single highlight shown is the original one found near my initial nether spawn portal that I already harvested. I even tried placing another block there and harvesting that... no luck.

**Comment by klikli-dev** [comment]
This is intentional behaviour - if you click the rod only briefly it shows the last found spot without performing a new scan and without consuming durability. If you press and hold it performs a new scan and consumes durability.

This way you do not need to do a full scan just to show the result again after the effect is gone.
