### ISSUE TITLE
Dimensional storage actuator item drops strangely when mined

### ISSUE THREAD

**Issue by B1ackN0va** [klikli-dev/occultism#996]
**Describe the bug**
When the dimensional storage actuator is mined, the item dropped flies out really strangely. Sometimes the actuator flies out too fast, and other times it drops from the corner of the block it was mined on.

**To Reproduce**
1. Place dimensional actuator block
2. Mine it

**Expected behavior**
The dimensional actuator block would drop in the block it was mined in like normal blocks

**Screenshots**
![image](https://github.com/klikli-dev/occultism/assets/76802534/96237326-f298-41fe-b5f6-9b500c8f6a49)

**System (please complete the following information):**
- Occultism Version: 1.19.2 1.88.0
- OS: Windows
- Minecraft Version:
- Modpack Link and Version, or list of mods: 
https://www.curseforge.com/minecraft/modpacks/thecosmereproject-devserver
**Additional context**
When on a vanilla save with just occultism, the storage actuator dropped from the edge of the block it was on and dropped away from the block.

**Comment by klikli-dev** [comment]
Uhh I don't think that is something modders can control tbh 
There is no setting or anything, I think that is just determined by the MC physics and the shape of the block

**Comment by klikli-dev** [comment]
I cannot seem to reproduce this - or rather I tried with a dirt block and with the actuator and both dropped down the edge
